(()=>{'use strict';const D=window.ATLAS,j=document.documentElement.lang==='ja',t=(en,ja)=>j?ja:en,$=id=>document.getElementById(id),q=new URLSearchParams(location.search),chips=D.chips;
const valid=n=>chips.some(c=>c.name===n),cn=(n,f)=>valid(n)?n:f,range=(v,d,min,max)=>Number.isFinite(+v)&&v!==null?Math.max(min,Math.min(max,+v)):d;
let selected=cn(q.get('chip'),'M5'),block=D.concepts.some(c=>c.id===q.get('block'))?q.get('block'):'CPU';
const fmt=n=>Number(n).toLocaleString(j?'ja-JP':'en-US',{maximumFractionDigits:1});
function linkState(){const u=new URL(location.href);u.searchParams.set('chip',selected);u.searchParams.set('block',block);['workload','compare-a','compare-b','memory-chip','params','bits','reserve','serial','workers'].forEach(id=>u.searchParams.set(id,$(id).value));history.replaceState(null,'',u);document.querySelectorAll('a.language-switch,a.ig-language').forEach(a=>{const v=new URL(a.href);v.search=u.search;v.hash=u.hash;a.href=v.pathname+v.search+v.hash;});}
const csource=c=>[c.source,...(c.gen===3?[14]:[]),...(c.name==='M3 Ultra'||c.name==='M4 Max'?[15]:[])].map(i=>`<a class="ref" href="#source-${i}">[${i}]</a>`).join('');
const get=n=>chips.find(c=>c.name===n);
function squares(n,type){return `<div class="cores" aria-hidden="true">${Array.from({length:n},()=>`<i class="core ${type}"></i>`).join('')}</div>`;}
function family(){let out=`<div class="family-labels"><span>${t('Base','標準')}</span><span>Pro</span><span>Max</span><span>Ultra</span></div>`;for(let g=1;g<=6;g++){out+='<div class="family-row">';['Base','Pro','Max','Ultra'].forEach(tier=>{const c=chips.find(c=>c.gen===g&&c.tier===tier);out+=c?`<button data-chip="${c.name}" aria-label="${c.name}" aria-pressed="${c.name===selected}">${tier==='Base'?c.name:'M'+g+' '+tier}</button>`:`<span class="empty" aria-label="${t('No verified announcement','発表未確認')}: M${g} ${tier}">—</span>`;});out+='</div>';} $('chip-grid').innerHTML=out;document.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{selected=b.dataset.chip;renderChip();linkState();});}
const workloadNotes={overview:['Select any block to inspect its role. Core tiles are counts, not area or speed measurements.','ブロックを選ぶと役割を確認できます。コアの四角は個数であり、面積や速度ではありません。'],code:['Compilation mainly exercises CPU and memory; storage and dependencies can also limit it. Highlighting is qualitative, not measured utilization.','コンパイルは主にCPUとメモリを使い、ストレージや依存関係も制約になります。強調表示は定性的で、実測使用率ではありません。'],graphics:['The CPU prepares work, the GPU renders, and both access memory. Hardware ray tracing requires an M3-or-later GPU and supporting software.','CPUが処理を準備し、GPUが描画し、双方がメモリにアクセスします。ハードウェアレイトレーシングはM3以降のGPUと対応ソフトが必要です。'],ai:['A GPU inference path uses GPU and memory with CPU orchestration. M5/M6 add GPU Neural Accelerators; the separate Neural Engine is not automatically involved.','GPUでの推論はCPUの制御下でGPUとメモリを使います。M5/M6にはGPU Neural Acceleratorがありますが、別のNeural Engineが自動的に関与するわけではありません。'],ml:['Core ML may dispatch supported operations to CPU, GPU or Neural Engine. Highlighted blocks are possible participants, not a guarantee that every block runs every model.','Core MLは対応演算をCPU、GPU、Neural Engineへ配分できます。強調部分は候補であり、各モデルがすべてを使う保証ではありません。'],video:['Supported codecs use media engines; effects may use the GPU and timeline control the CPU. The actual route depends on codec and application.','対応コーデックはメディアエンジン、エフェクトはGPU、タイムライン制御はCPUなどを使います。実際の経路はコーデックとアプリによります。']};
function renderChip(){const c=get(selected);family();$('chip-name').textContent=c.name;const task=$('workload').value;const active={overview:D.concepts.map(c=>c.id),code:['CPU','memory','fabric','security'],graphics:['CPU','GPU','memory','fabric'],ai:['CPU','GPU','memory','fabric'],ml:['CPU','GPU','neural','memory','fabric'],video:['CPU','GPU','media','memory','fabric','security']}[task];
const btn=(id,body,cls='')=>`<button data-block="${id}" class="${cls} ${active.includes(id)?'':'dim'}" aria-pressed="${id===block}">${body}</button>`;
const cluster=(n,type,title)=>n?`<div class="cluster"><div class="cluster-label">${title} × ${n}</div>${squares(n,type)}</div>`:'';
$('chip-diagram').innerHTML=btn('CPU',`<span class="block-heading">CPU · ${c.cpu}</span>${cluster(c.s,'s',t('Super','スーパー'))}${cluster(c.p,'',t(c.gen===5&&c.tier==='Base'?'Performance¹':'Performance',c.gen===5&&c.tier==='Base'?'高性能¹':'高性能'))}${cluster(c.e,'e',t('Efficiency','高効率'))}`)+btn('GPU',`<span class="block-heading">GPU · ${c.gpu}</span>${squares(c.gpu,'g'+(c.gen>=5?' ai':''))}<span class="block-sub">${c.gen>=5?t('Neural Accelerator / core','各コアにNeural Accelerator'):c.gen>=3?t('Hardware ray tracing','ハードウェアRT'):t('Graphics + compute','描画・計算')}</span>`)+btn('fabric',`<span>${t('Shared interconnect','共通の内部接続')}</span><span aria-hidden="true">↔</span>`,'fabric-block')+btn('neural',`<span class="block-heading">Neural Engine · ${c.neural}</span>${squares(c.neural,'n')}<span class="block-sub">${c.name==='M6'?t('2 × 16-core engines','16コア × 2基'):t('Dedicated ML hardware','機械学習専用回路')}</span>`)+btn('media',`<span class="block-heading">${t('Media engines','メディアエンジン')}</span><span class="block-sub">H.264 · HEVC<br>${c.name==='M1'?t('No dedicated ProRes','ProRes専用回路なし'):'ProRes'}${c.gen>=3?' · AV1 '+t('decode','デコード'):''}</span>`)+btn('memory',`<span class="block-heading">${t('Unified memory','ユニファイドメモリ')} · ${t('up to','最大')} ${c.mem} GB</span><span class="block-sub">${c.bw?fmt(c.bw)+' GB/s':t('Exact bandwidth not in cited release','引用資料に正確な帯域幅なし')}</span><div class="memory-lines" aria-hidden="true">${'<i></i>'.repeat(16)}</div>`,'memory-block')+btn('security',`<span class="block-heading">${t('Security · I/O · display','セキュリティ・I/O・表示')}</span>`,'memory-block');
document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>{block=b.dataset.block;renderChip();linkState();});
const names=c.dies===1?[c.name]:c.gen===5?(c.dies===4?['Max A · 1','Max A · 2','Max B · 1','Max B · 2']:['1','2']):['Max A','Max B'];
$('topology').innerHTML=`<div class="die-row">${names.map(n=>`<span class="die">${t('Die','ダイ')} ${n}</span>`).join('<span class="die-link" aria-hidden="true">↔</span>')}</div><p class="topology-label">${t('Package topology','パッケージ構成')}: ${c.dies} ${t(c.dies===1?'die':'dies','ダイ')} ${c.dies>1?'· '+(c.gen===5&&c.tier!=='Ultra'?'Fusion Architecture':'UltraFusion'):''} · ${t('schematic','模式図')}</p>`;
$('workload-note').textContent=workloadNotes[task][j?1:0];const co=D.concepts.find(x=>x.id===block);$('block-title').textContent=co[j?'ja':'en'];$('block-desc').textContent=co[j?'text_ja':'text_en'];$('chip-facts').innerHTML=[[t('Announced','発表'),c.date],[t('CPU cores (max)','CPUコア（最大）'),c.cpu],[t('GPU cores (max)','GPUコア（最大）'),c.gpu],[t('Process generation','プロセス世代'),(c.gen<3?'5':c.gen<6?'3':'2')+' nm']].map(([k,v])=>`<div class="fact"><span>${k}</span><b>${v}</b></div>`).join('');window.dispatchEvent(new CustomEvent('atlas:chip',{detail:c}));$('chip-source').innerHTML=csource(c)+(c.name==='M5'?`<p class="small">${t('¹ Uses the 2025 launch terminology. Apple later calls its highest-performance core a “super core”.','¹ 2025年発表時の名称です。Appleは後に最上位コアを「スーパーコア」と呼んでいます。')}</p>`:'');}
function options(id,def){$(id).innerHTML=chips.map(c=>`<option>${c.name}</option>`).join('');$(id).value=cn(q.get(id),def);}
const metrics=[['cpu',t('CPU cores · maximum','CPUコア数・最大'),''],['gpu',t('GPU cores · maximum','GPUコア数・最大'),''],['mem',t('Unified memory · GB, historical maximum','ユニファイドメモリ・GB、歴史上の最大値'),' GB'],['bw',t('Memory bandwidth · GB/s, maximum','メモリ帯域幅・GB/s、最大'),'']];
function compare(){const a=get($('compare-a').value),b=get($('compare-b').value);$('comparison').innerHTML=metrics.map(([key,label,unit])=>{const mx=Math.max(a[key]||0,b[key]||0);return `<div class="metric"><h3>${label}</h3>${[a,b].map((c,i)=>`<div class="bar-row"><span>${c.name}</span><div class="bar-track"><div class="bar ${i?'second':''}" style="width:${c[key]===null?0:c[key]/mx*100}%"></div></div><span class="bar-number">${c[key]===null?'—':fmt(c[key])+unit}</span></div>`).join('')}<p class="delta">${a[key]&&b[key]?`${b.name} / ${a.name}: ${(b[key]/a[key]).toFixed(2)}× ${t('by this specification','（この仕様の比）')}`:t('Exact comparison unavailable in cited data.','引用データから正確な比較はできません。')}</p></div>`;}).join('');}
function catalogue(){$('catalogue').innerHTML=`<table><caption>${t('Maximum published configurations; GB and GB/s are decimal.','公表最大構成。GBとGB/sは十進単位。')}</caption><thead><tr>${[t('Chip','チップ'),t('Announced','発表'),'CPU','GPU',t('Memory GB','メモリ GB'),'GB/s',t('Neural cores','Neuralコア'),t('Source','出典')].map(s=>`<th scope="col">${s}</th>`).join('')}</tr></thead><tbody>${chips.map(c=>`<tr><th scope="row">${c.name}</th><td>${c.date}</td><td>${c.cpu}</td><td>${c.gpu}</td><td>${c.mem}</td><td>${c.bw??'—'}</td><td>${c.neural}</td><td>${csource(c)}</td></tr>`).join('')}</tbody></table>`;}
function memory(){const c=get($('memory-chip').value),p=+$('params').value,b=+$('bits').value,r=+$('reserve').value,w=p*b/8,need=w+r,fits=need<=c.mem;$('params-value').textContent=p;$('reserve-value').textContent=r;$('memory-result').innerHTML=`<div class="result-number">${fmt(w)} GB</div><div class="result-note">${t('Weights alone','重みのみ')} · ${fmt(need)} GB ${t('including reserve','（予約領域を含む）')}</div><div class="capacity ${fits?'':'capacity-over'}" role="img" aria-label="${fmt(need)} / ${c.mem} GB"><div class="weights" style="width:${Math.min(100,w/c.mem*100)}%"></div><div class="reserve" style="width:${Math.min(100,r/c.mem*100)}%"></div></div><div class="legend"><span>${t('Weights','重み')}</span><span>${t('Reserved','予約済み')}</span></div><strong>${fits?t('Within the historical capacity ceiling','歴史上の容量上限の範囲内'):t('Exceeds the capacity ceiling','容量上限を超えています')}</strong><p class="result-note">${c.mem} GB ${t('chip ceiling, not necessarily installed RAM.','はチップの上限で、搭載RAMとは限りません。')}</p><p class="result-note">${fits?(c.bw?`${(c.bw/w).toFixed(1)} ${t('tokens/s: bandwidth-only ceiling in the simplified weight-streaming model. Not a benchmark.','トークン/秒：重みを読む単純モデルでの帯域幅上限。ベンチマークではありません。')}`:t('No bandwidth ceiling calculated: M1’s exact value is not in our cited launch source.','帯域幅上限は計算しません。M1の引用発表資料に正確な値がありません。')):t('No in-memory speed estimate: the model does not fit under these assumptions.','この仮定では収まらないため、メモリ内での速度は計算しません。')}</p>`;}
function amdahl(){let s=+$('serial').value/100,n=+$('workers').value;const speed=x=>1/(s+(1-s)/x);$('serial-value').textContent=fmt(s*100);$('workers-value').textContent=n;$('amdahl-result').innerHTML=`<div class="result-number">${speed(n).toFixed(2)}×</div><div class="result-note">${t('Ideal speedup versus one worker','1個に対する理想的な高速化')} · ${t('serial limit','直列部分による上限')} ${s===0?'∞':(1/s).toFixed(2)+'×'}</div>`;$('amdahl-chart').innerHTML=[1,2,4,8,16,32,80].map(x=>`<div class="amd-row"><span>${x}×</span><div class="bar-track"><div class="bar" style="width:${speed(x)/speed(80)*100}%"></div></div><b>${speed(x).toFixed(2)}×</b></div>`).join('');}
options('compare-a','M1 Max');options('compare-b','M5');options('memory-chip','M5');
['params','reserve','serial','workers'].forEach(id=>{const e=$(id);e.value=range(q.get(id),+e.value,+e.min,+e.max);});if(['4','8','16'].includes(q.get('bits')))$('bits').value=q.get('bits');if(workloadNotes[q.get('workload')])$('workload').value=q.get('workload');
$('workload').onchange=()=>{renderChip();linkState();};['compare-a','compare-b'].forEach(id=>$(id).onchange=()=>{compare();linkState();});['memory-chip','params','bits','reserve'].forEach(id=>$(id).oninput=()=>{memory();linkState();});['serial','workers'].forEach(id=>$(id).oninput=()=>{amdahl();linkState();});$('swap').onclick=()=>{let a=$('compare-a').value;$('compare-a').value=$('compare-b').value;$('compare-b').value=a;compare();linkState();};$('surprise').onclick=()=>{$('compare-a').value='M2 Pro';$('compare-b').value='M3 Pro';compare();linkState();};renderChip();compare();catalogue();memory();amdahl();document.querySelectorAll("[data-formula]").forEach(e=>{if(window.katex)katex.render(e.dataset.formula==="memory"?String.raw`W=\frac{Pq}{8},\quad W+R\le C`:String.raw`S(N)=\frac{1}{s+(1-s)/N}`,e,{throwOnError:false});});linkState();window.addEventListener('hashchange',linkState);
})();
