(()=>{'use strict';const D=window.ATLAS,j=document.documentElement.lang==='ja',t=(a,b)=>j?b:a,$=id=>document.getElementById(id),url=new URL(location.href);let chip=D.chips.find(c=>c.name===$('chip-name').textContent),view=url.searchParams.get('view')||'soc',picked='package',zoom=+(url.searchParams.get('zoom')||80),step=0;
const views={soc:t('Full topology','全体のトポロジー'),package:t('Die connections','ダイ間接続'),cpu:t('Inside a CPU core','CPUコア内部'),gpu:t('Inside a GPU core','GPUコア内部'),memory:t('Memory hierarchy','メモリ階層'),media:t('Video pipeline','動画の処理経路'),reference:t('Apple imagery','Appleの画像')};if(!views[view])view='soc';zoom=Math.min(150,Math.max(70,Number.isFinite(zoom)?zoom:80));
$('topology-lab').innerHTML=`<div class="topo-toolbar"><label for="topo-chip">${t('Explore a chip','チップを選択')}<select id="topo-chip">${D.chips.map(c=>`<option>${c.name}</option>`).join('')}</select></label><label for="topo-view">${t('Depth of view','表示する階層')}<select id="topo-view">${Object.entries(views).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label for="topo-zoom">${t('Diagram zoom','図の倍率')} <output id="topo-zoom-value"></output><input id="topo-zoom" type="range" min="70" max="150" step="10" value="${zoom}"></label><button id="topo-expand">${t('Expand','拡大表示')}</button></div><p class="topo-help">${t('Select a block to inspect it. On a phone, slide the diagram sideways; zoom keeps small structures legible.','ブロックを選ぶと詳細を表示します。スマートフォンでは図を横にスクロールできます。拡大して小さな構造も確認できます。')}</p><div class="topo-stage" id="topo-stage" tabindex="0" role="region" aria-label="${t('Scrollable detailed topology diagram','スクロールできる詳細トポロジー図')}"></div><div class="topo-stepper"><button id="topo-prev">${t('Previous step','前の段階')}</button><button id="topo-next">${t('Follow the data','データを追う')}</button><span id="topo-step-note" aria-live="polite"></span></div><div class="topo-inspector" aria-live="polite"><div><p class="eyebrow">${t('INSIDE THE ARCHITECTURE','アーキテクチャの詳細')}</p><h3 id="topo-picked"></h3><p id="topo-description"></p><div id="topo-refs"></div></div><div class="topo-evidence"><p id="topo-evidence"></p><div id="topo-choices"></div></div></div>`;
const C={bg:'#091322',panel:'#112139',cpu:'#264673',gpu:'#463768',memory:'#194e51',neural:'#255c55',io:'#363f50',cache:'#314657',edge:'#91b4c9',text:'#edf4ff',muted:'#abc0d4',hot:'#ffce7e'};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');let nodes=[];
function text(x,y,s,size=20,color=C.text){return `<text x="${x}" y="${y}" fill="${color}" font-size="${size}">${esc(s)}</text>`;}
function rect(id,x,y,w,h,label,sub='',color=C.panel){nodes.push(id);return `<g data-topo-node="${id}" role="button" tabindex="0" aria-label="${esc(label+' '+sub)}" class="topo-node ${picked===id?'is-selected':''}"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="7" fill="${color}" stroke="${picked===id?C.hot:'#698297'}" stroke-width="${picked===id?3:1}"/>${text(x+14,y+29,label,20)}${sub?text(x+14,y+54,sub,16,C.muted):''}</g>`;}
function edge(x1,y1,x2,y2,hot=false){return `<path d="M${x1} ${y1} L${x2} ${y2}" fill="none" stroke="${hot?C.hot:'#6d91aa'}" stroke-width="${hot?4:2}" marker-end="url(#arrow)"/>`;}
function tiles(x,y,n,cols=12,w=25,h=27,type='cpu'){let s='';for(let i=0;i<n;i++){let xx=x+(i%cols)*(w+5),yy=y+Math.floor(i/cols)*(h+5);s+=`<g aria-hidden="true"><rect x="${xx}" y="${yy}" width="${w}" height="${h}" rx="2" fill="${type==='gpu'?'#9f84cf':type==='s'?'#dca763':type==='e'?'#6c839e':'#76a6d5'}"/>`;s+=`<path d="M${xx+4} ${yy+h-7}h${w-8}" stroke="#152d44" stroke-width="3"/>`;if(type==='gpu'&&chip.gen>=5)s+=`<rect x="${xx+w-7}" y="${yy+3}" width="4" height="6" fill="#83f4d2"/>`;s+='</g>';}return s;}
function begin(title,sub){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1140 830" width="${1140*zoom/100}" height="${830*zoom/100}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><desc>${esc(sub)}</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 1L8 5L0 9" fill="none" stroke="#91b4c9" stroke-width="1.3"/></marker><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#36536c" stroke-width=".3"/></pattern></defs><rect width="1140" height="830" fill="${C.bg}"/><rect width="1140" height="830" fill="url(#grid)"/>${text(30,42,title,28)}${text(30,73,sub,17,C.muted)}`;}
function soc(){let s=begin(chip.name+' / '+t('functional top-down layout','機能を俯瞰する配置図'),t('Published counts. Illustrative locations, grouping and areas. Whole-package resources.','公表コア数。位置・グループ・面積は模式的。パッケージ全体の資源。'));s+=`<rect x="24" y="92" width="1090" height="615" rx="12" fill="none" stroke="#65849c" stroke-dasharray="7 5"/>`;
s+=rect('cpu-cache',42,112,400,338,t('CPU complex','CPUブロック'),t('Core classes; not physical clusters','コア種別。実際のクラスタ配置ではない'),C.cpu);let yy=194;for(const [n,kind,label] of [[chip.s,'s',t('Super','スーパー')],[chip.p,'cpu',t('Performance','高性能')],[chip.e,'e',t('Efficiency','高効率')]]){if(n){s+=text(58,yy,label+' × '+n,18);s+=tiles(58,yy+10,n,12,25,22,kind);yy+=n>12?92:62;}}
s+=rect('cpu-cache',55,403,374,35,'L1 / L2 '+t('cache hierarchy','キャッシュ階層'),'',C.cache);
s+=rect('gpu-command',464,112,630,64,t('GPU front end / command + geometry','GPUフロントエンド・コマンド・ジオメトリ'),'',C.gpu);
s+=rect('gpu-shader',464,190,630,207,t('GPU shader cores','GPUシェーダーコア')+' × '+chip.gpu,t(chip.gen>=5?'Small green marks: GPU Neural Accelerators':'Tiles count cores, not ALUs or physical area',chip.gen>=5?'緑の印：GPU内Neural Accelerator':'タイルはコア数。ALU数や実面積ではない'),C.gpu);
s+=tiles(480,256,chip.gpu,20,24,23,'gpu');s+=rect('gpu-cache',464,409,630,41,t('GPU last-level cache (LLC)','GPU最終レベルキャッシュ（LLC）'),'',C.cache);
s+=edge(240,450,240,483);s+=edge(780,450,780,483);s+=rect('fabric-deep',42,483,1052,51,t('Shared fabric / coherence and memory access (logical paths)','共通接続・整合性・メモリアクセス（論理経路）'),'',C.cache);
s+=edge(160,534,160,562);s+=edge(453,534,453,562);s+=edge(745,534,745,562);s+=edge(980,534,980,562);
s+=rect('neural-deep',42,562,264,111,'Neural Engine · '+chip.neural,chip.name==='M6'?'2 × 16':t('Separate ML engine','独立したMLエンジン'),C.neural);s+=tiles(58,626,chip.neural,16,10,12,'e');s+=rect('media-deep',322,562,260,111,t('Media engines','メディアエンジン'),'H.264 / HEVC'+(chip.name==='M1'?'':' / ProRes'),C.io);s+=rect('io-deep',598,562,260,111,t('Display / ISP / security','表示・ISP・セキュリティ'),t('Controllers and Secure Enclave','コントローラ・Secure Enclave'),C.io);s+=rect('fabric-deep',874,562,220,111,t('Memory control','メモリ制御'),t('Not a channel count','チャネル数の図ではない'),C.memory);
s+=edge(984,673,984,737);s+=rect('dram',42,737,1052,69,t('Shared DRAM outside the logic dies','ロジックダイ外の共通DRAM'),`${chip.mem} GB ${t('historical maximum','歴史上の最大値')} · ${chip.bw?chip.bw+' GB/s':t('bandwidth not specified here','帯域幅未記載')} · ${chip.dies} ${t('logic die(s)','ロジックダイ')}`,C.memory);return s+'</svg>';}
function cpu(){let s=begin(chip.name+' / '+(chip.gen===1?t('Firestorm performance core','Firestorm高性能コア'):t('inside a CPU core','CPUコア内部')),t('Generic out-of-order dataflow. Unit counts and pipeline widths are not generalized across generations.','一般的なアウトオブオーダーの流れ。実行器数や幅を世代間で同一視しない。'));
s+=rect('cpu-front',45,112,310,91,t('Branch prediction + fetch','分岐予測・フェッチ'),t('Choose the next instructions','次の命令を選択'),C.cpu);s+=rect('cpu-cache',45,230,310,82,t('L1 instruction cache','L1命令キャッシュ'),t('Instruction working set','使用する命令を保持'),C.cache);s+=edge(200,203,200,230);s+=edge(355,270,413,270);s+=rect('cpu-front',413,112,305,200,t('Decode / internal operations','デコード・内部命令'),(chip.gen===1?t('Measured: 8 µops/cycle [20]','測定：8 µop/周期 [20]'):t('Instruction → one or more µops','命令 → 1つ以上のµop')),C.cpu);s+=edge(355,157,413,157);s+=rect('cpu-exec',770,112,322,200,t('Rename + dispatch','リネーム・ディスパッチ'),t('Track dependencies','依存関係を管理'),C.cpu);s+=edge(718,209,770,209);s+=edge(930,312,930,355);
s+=rect('cpu-exec',45,355,1047,78,t('Schedulers / ready operations','スケジューラ・実行可能な演算'),t('Independent work can issue while a dependency waits','依存待ちの間も独立した演算を発行'),C.cache);
const xs=[45,310,575,840];const labs=[t('Integer + branch','整数・分岐'),t('Vector / floating point','ベクトル・浮動小数点'),t('Load / store','ロード・ストア'),t('Registers + completion','レジスタ・完了管理')];xs.forEach((x,i)=>{s+=edge(x+122,433,x+122,473);s+=rect('cpu-exec',x,473,252,101,labs[i],chip.gen===1?([t('6 integer units [20]','整数実行器6基 [20]'),t('4 SIMD/FP units [20]','SIMD/FP実行器4基 [20]'),t('4 load/store units [20]','ロード・ストア実行器4基 [20]'),t('Retire in program order','プログラム順にリタイア')][i]):t('Functional grouping','機能ごとの分類'),i===2?C.memory:C.cpu);});s+=edge(700,574,700,620);s+=rect('cpu-cache',45,620,510,73,t('L1 data cache','L1データキャッシュ'),t('Fast local data access','近くのデータへアクセス'),C.cache);s+=rect('cpu-cache',575,620,517,73,t('Cluster L2 / further hierarchy','クラスタL2・より遠い階層'),t('Sizes and cluster boundaries not inferred','容量やクラスタ境界は推定しない'),C.cache);s+=edge(555,655,575,655);s+=edge(827,693,827,734);s+=rect('fabric-deep',45,734,1047,66,t('System fabric → memory controllers → shared DRAM','システム接続 → メモリコントローラ → 共通DRAM'),t('A cache hit can avoid part of this longer route','キャッシュヒットなら長い経路の一部を省略できる'),C.memory);return s+'</svg>';}
function gpu(){let s=begin(chip.name+' / '+t('inside a GPU shader core','GPUシェーダーコア内部'),t('Functional microarchitecture. The repeated pipelines are categories, not a disclosed unit count.','機能マイクロアーキテクチャ。演算経路の分類であり、公表実行器数の図ではない。'));
s+=rect('gpu-command',45,113,1050,77,t('Command processing / geometry / rasterization','コマンド処理・ジオメトリ・ラスタライズ'),chip.gen>=3?t('Hardware mesh shading available','ハードウェアメッシュシェーディング対応'):t('Earlier graphics architecture','以前のグラフィックス世代'),C.gpu);s+=edge(550,190,550,220);
s+=rect('gpu-shader',45,220,510,93,t('SIMDgroup pool + scheduler','SIMDgroup群・スケジューラ'),t('Choose ready work to hide latency','実行可能な処理を選び、待ち時間を隠す'),C.gpu);s+=rect('gpu-local',578,220,517,93,t('Register / local storage','レジスタ・局所記憶領域'),chip.gen>=3?t('Dynamic Caching generation','Dynamic Caching世代'):t('Earlier allocation model','以前の割り当て方式'),C.cache);
s+=edge(300,313,300,349);s+=rect('gpu-shader',45,349,246,110,t('FP32 / FP16 math','FP32・FP16演算'),t('Floating point','浮動小数点'),C.gpu);s+=rect('gpu-shader',312,349,244,110,t('Integer math','整数演算'),t('Arithmetic + logic','算術・論理'),C.gpu);s+=rect('gpu-local',578,349,248,110,t('Memory pipelines','メモリ演算経路'),t('Buffers / loads / stores','バッファ・読込・書込'),C.cache);s+=rect('texture',847,349,248,110,t('Texture unit','テクスチャ回路'),t('Sampling + filtering','サンプリング・フィルタ'),C.gpu);
s+=rect('gpu-local',45,490,510,109,t('Threadgroup + tile working storage','スレッドグループ・タイル領域'),t('Cooperative work and local render data','協調処理と局所的な描画データ'),C.cache);s+=rect('rt',578,490,248,109,t('Ray intersections','レイ交差判定'),chip.gen>=3?t('Hardware: present','専用回路：あり'):t('Dedicated HW: absent','専用回路：なし'),chip.gen>=3?C.gpu:C.io);s+=rect('gpu-ai',847,490,248,109,t('Neural Accelerator','Neural Accelerator'),chip.gen>=5?t('Inside each GPU core','各GPUコア内に搭載'):t('Not in this generation','この世代には非搭載'),chip.gen>=5?C.neural:C.io);
s+=edge(300,599,300,634);s+=edge(700,599,700,634);s+=rect('gpu-cache',45,634,1050,65,t('GPU cache hierarchy / last-level cache','GPUキャッシュ階層・最終レベルキャッシュ'),t('Reduces the traffic that reaches system memory','システムメモリへ到達する転送を減らす'),C.cache);s+=edge(550,699,550,735);s+=rect('dram',45,735,1050,66,t('System fabric / memory controllers / unified DRAM','システム接続・メモリ制御・ユニファイドDRAM'),t('Shared with CPU and other engines','CPUやほかのエンジンと共用'),C.memory);return s+'</svg>';}
function pack(){let s=begin(chip.name+' / '+t('die connectivity','ダイの接続関係'),t('Connectivity and grouping, not die shape, orientation or physical area.','接続とグループ関係を示す。ダイ形状、向き、実面積は示さない。'));
if(chip.dies===1){s+=rect('package',260,200,620,350,t('One logic die','1つのロジックダイ'),t('CPU · GPU · Neural Engine · media · controllers','CPU・GPU・Neural Engine・メディア・制御'),C.cpu);s+=tiles(292,292,chip.cpu,12,30,30);s+=tiles(292,388,chip.gpu,16,25,25,'gpu');s+=edge(570,550,570,695);}
else if(chip.dies===2){s+=rect('fusion',55,220,450,310,chip.gen===5?t('Constituent die A','構成ダイA'):'M'+chip.gen+' Max · A',t('Shared system resources','共通のシステム資源'),C.cpu);s+=rect('fusion',635,220,450,310,chip.gen===5?t('Constituent die B','構成ダイB'):'M'+chip.gen+' Max · B',t('Resource placement not asserted','資源の実配置は示していない'),C.gpu);s+=edge(505,360,635,360,true);s+=text(355,190,chip.gen===5?'Fusion Architecture':'UltraFusion',28);s+=text(340,588,chip.gen===5?t('Two dies combine into one SoC','2ダイを1つのSoCへ統合'):t('Two Max dies; software sees one system','2つのMaxダイ。ソフトからは1システム'),20);s+=edge(280,530,280,695);s+=edge(860,530,860,695);}
else{for(let k=0;k<2;k++){let x=45+k*550;s+=`<rect x="${x}" y="160" width="500" height="430" rx="12" fill="none" stroke="#b69bde" stroke-width="2"/>`;s+=text(x+20,195,'M5 Max · '+(k?'B':'A'),25);s+=rect('fusion',x+25,220,450,125,t('Constituent die','構成ダイ')+' '+(k*2+1),t('Internal blocks not physically assigned','内部ブロックの物理配置は割り当てない'),C.cpu);s+=edge(x+250,345,x+250,394,true);s+=rect('fusion',x+25,394,450,125,t('Constituent die','構成ダイ')+' '+(k*2+2),'Fusion Architecture',C.gpu);}s+=edge(545,565,595,565,true);s+=text(415,635,'UltraFusion > 4.4 TB/s',22);s+=edge(295,590,295,695);s+=edge(845,590,845,695);}
s+=rect('dram',45,695,1050,100,t('Unified memory pool','ユニファイドメモリ・プール'),`${chip.mem} GB · ${chip.bw?chip.bw+' GB/s':t('bandwidth unspecified','帯域幅未記載')} · `+t('DRAM bandwidth is different from die-to-die bandwidth','DRAM帯域幅とダイ間帯域幅は別'),C.memory);return s+'</svg>';}
function mem(){let s=begin(chip.name+' / '+t('the memory hierarchy','メモリ階層'),t('Logical paths. A hit stops a request earlier; a miss travels farther. No latency scale is implied.','論理経路。ヒットなら手前で完了し、ミスなら先へ進む。遅延の縮尺ではない。'));s+=rect('cpu-exec',45,115,480,72,t('CPU registers / execution','CPUレジスタ・実行'),t('Values used by instructions','命令が使う値'),C.cpu);s+=rect('gpu-shader',615,115,480,72,t('GPU shader work','GPUシェーダー処理'),t('Many simultaneous threads','多数のスレッドを同時実行'),C.gpu);s+=edge(285,187,285,224,step===1);s+=edge(855,187,855,224,step===1);s+=rect('cpu-cache',45,224,480,88,t('CPU L1 caches','CPU L1キャッシュ'),t('Instruction + data working sets','命令とデータのワーキングセット'),C.cache);s+=rect('gpu-local',615,224,480,88,t('GPU on-chip working storage','GPU内ワーキング領域'),t('Registers / threadgroup / tile','レジスタ・スレッドグループ・タイル'),C.cache);s+=edge(285,312,285,351,step===2);s+=edge(855,312,855,351,step===2);s+=rect('cpu-cache',45,351,480,76,t('CPU cluster L2','CPUクラスタL2'),t('Grouping depends on architecture','構成はアーキテクチャに依存'),C.cache);s+=rect('gpu-cache',615,351,480,76,t('GPU cache hierarchy / LLC','GPUキャッシュ階層・LLC'),t('A separate hierarchy','CPU側とは別の階層'),C.cache);s+=edge(285,427,285,475,step===3);s+=edge(855,427,855,475,step===3);s+=rect('fabric-deep',45,475,1050,91,t('System connections / memory controllers','システム接続・メモリコントローラ'),t('Other engines are clients too; aggregate bandwidth is shared','ほかのエンジンも利用する。総帯域幅は共用される'),C.memory);s+=edge(570,566,570,614,step===4);s+=rect('dram',45,614,1050,95,t('Unified DRAM','共通DRAM'),`${chip.mem} GB · ${chip.bw?chip.bw+' GB/s':t('exact bandwidth not in cited release','引用資料に正確な帯域幅なし')}`,C.memory);s+=text(45,763,t('Cache hit ≠ DRAM access. Shared memory ≠ infinite bandwidth.','キャッシュヒット ≠ DRAMアクセス。共通メモリ ≠ 無限の帯域幅。'),22);return s+'</svg>';}
function media(){let s=begin(chip.name+' / '+t('a frame through the system','フレームが通る経路'),t('Codec-dependent functional pipeline; software can choose other routes.','コーデック依存の機能経路。ソフトウェアによって別経路も使う。'));const steps=[['io-deep',t('1. Compressed input','1. 圧縮された入力'),t('Storage / network','ストレージ・ネットワーク')],['media-deep',t('2. Decode','2. デコード'),'H.264 / HEVC'+(chip.gen>=3?' / AV1':'')],['dram',t('3. Frame buffers','3. フレームバッファ'),t('Shared memory','共通メモリ')],['gpu-shader',t('4. Effects / compositing','4. エフェクト・合成'),t('GPU kernels + CPU orchestration','GPU演算・CPU制御')],['media-deep',t('5. Encode','5. エンコード'),t('Supported output codec','対応する出力コーデック')],['io-deep',t('6. Display or store','6. 表示または保存'),t('Scanout / file output','画面出力・ファイル出力')]];for(let i=0;i<6;i++){const x=i%3*365+30,y=Math.floor(i/3)*265+140;s+=rect(...[steps[i][0],x,y,345,185,steps[i][1],steps[i][2],i===2?C.memory:i===3?C.gpu:C.io]);if(i%3<2)s+=edge(x+345,y+95,x+365,y+95,step===i+1);}s+=`<path d="M 1067 325 V370 H195 V405" fill="none" stroke="${C.edge}" stroke-width="2" marker-end="url(#arrow)"/>`;s+=rect('fabric-deep',30,660,1075,115,t('The shared system connects every stage','共通システムがすべての段階を接続'),t('Decode, effects, encode and display have different bottlenecks.','デコード・エフェクト・エンコード・表示では制約が異なる。'),C.cache);return s+'</svg>';}
function inspect(){const item=D.topology.find(n=>n.id===picked)||D.topology[0];$('topo-picked').textContent=item[j?'ja':'en'];$('topo-description').textContent=item[j?'text_ja':'text_en'];$('topo-refs').innerHTML=item.refs.map(i=>`<a href="#source-${i}" class="ref">[${i}] ${D.sources[i-1].title}</a>`).join(' ');$('topo-evidence').textContent=t('Evidence boundary: named functions and published counts are sourced. Positions, areas, wire paths and unspecified cache/pipeline dimensions are illustrative. Independent M1 CPU measurements are not generalized to M2–M6.','根拠の範囲：機能名と公表個数は資料に基づきます。位置・面積・配線・未公開のキャッシュやパイプライン寸法は模式的です。M1の独立測定をM2〜M6へ一般化しません。');$('topo-choices').innerHTML=[...new Set(nodes)].map(id=>{const n=D.topology.find(n=>n.id===id);return `<button data-topo-pick="${id}" aria-pressed="${picked===id}">${n[j?'ja':'en']}</button>`;}).join('');document.querySelectorAll('[data-topo-pick]').forEach(b=>b.onclick=()=>{picked=b.dataset.topoPick;draw();});}
function remember(){const u=new URL(location.href);u.searchParams.set('view',view);u.searchParams.set('zoom',zoom);history.replaceState(null,'',u);document.querySelectorAll('.language-switch,.ig-language').forEach(a=>{let v=new URL(a.href);v.search=u.search;v.hash=u.hash;a.href=v.pathname+v.search+v.hash;});}
const paths={soc:['cpu-cache','fabric-deep','dram','gpu-shader','gpu-cache'],package:['package','fusion','dram'],cpu:['cpu-front','cpu-exec','cpu-cache','fabric-deep'],gpu:['gpu-command','gpu-shader','gpu-local','texture','gpu-cache','dram'],memory:['cpu-exec','cpu-cache','gpu-cache','fabric-deep','dram'],media:['io-deep','media-deep','dram','gpu-shader','media-deep','io-deep']};
function draw(){nodes=[];$('topo-chip').value=chip.name;$('topo-view').value=view;$('topo-zoom-value').textContent=zoom+'%';const stage=$('topo-stage');if(view==='reference'){stage.innerHTML=`<div class="source-gallery">${[['apple-m1','M1',1],['apple-m1-pro','M1 Pro',2],['apple-m2','M2',4]].map(([f,n,r])=>`<figure><img src="/apple-silicon/images/${f}.jpg" alt="${n} · ${t('Apple-published package artwork','Apple公表のパッケージ画像')}" loading="lazy"><figcaption>${n} · <a href="#source-${r}">Apple Newsroom [${r}]</a><br>${t('Published package illustration, not a reverse-engineered annotated floorplan. © Apple.','公表されたパッケージ図。解析済みの注釈付き実配置図ではありません。© Apple。')}</figcaption></figure>`).join('')}</div>`;nodes=['package'];picked='package';}else{stage.innerHTML=({soc,package:pack,cpu,gpu,memory:mem,media}[view])();stage.querySelectorAll('[data-topo-node]').forEach(n=>{const choose=()=>{picked=n.dataset.topoNode;draw();};n.onclick=choose;n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};});}inspect();$('topo-prev').disabled=view==='reference';$('topo-next').disabled=view==='reference';$('topo-step-note').textContent=view==='reference'?t('Original source imagery','一次資料の画像'):t('Step through a conceptual route; it is not a cycle-accurate simulation.','概念的な経路をたどります。サイクル精度のシミュレーションではありません。');remember();}
$('topo-chip').onchange=()=>{const b=document.querySelector(`[data-chip="${$('topo-chip').value}"]`);b.click();};window.addEventListener('atlas:chip',e=>{chip=e.detail;draw();});$('topo-view').onchange=()=>{view=$('topo-view').value;step=0;picked=(paths[view]||['package'])[0];draw();};$('topo-zoom').oninput=()=>{zoom=+$('topo-zoom').value;draw();};$('topo-expand').onclick=()=>{const expanded=$('topology-lab').classList.toggle('topo-expanded');$('topo-expand').textContent=expanded?t('Close expanded view','拡大表示を閉じる'):t('Expand','拡大表示');$('topo-expand').setAttribute('aria-expanded',String(expanded));};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('topology-lab').classList.remove('topo-expanded');$('topo-expand').textContent=t('Expand','拡大表示');}});function route(delta){const p=paths[view];if(!p)return;step=(step+delta+p.length)%p.length;picked=p[step];draw();$('topo-step-note').textContent=`${step+1} / ${p.length} · `+D.topology.find(n=>n.id===picked)[j?'ja':'en'];}$('topo-prev').onclick=()=>route(-1);$('topo-next').onclick=()=>route(1);draw();
})();
