const ja=document.documentElement.lang==='ja';
const t=(en,jp)=>ja?jp:en;
const $=id=>document.getElementById(id);
const fmt=x=>x.toFixed(5);
const NS='http://www.w3.org/2000/svg';
let mathTimer;
function typeset(){clearTimeout(mathTimer);mathTimer=setTimeout(()=>{if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise().catch(console.error)},100)}
function mathText(id,txt){const node=$(id);if(window.MathJax?.typesetClear)window.MathJax.typesetClear([node]);node.textContent=txt;}

function el(tag,attrs={},parent){const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(parent)parent.append(e);return e}
function label(svg,x,y,s,anchor='middle'){const e=el('text',{x,y,'text-anchor':anchor},svg);e.textContent=s;return e}
function frame(id,max=1){const svg=$(id),w=Math.max(270,svg.clientWidth),h=svg.clientHeight;svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const X=x=>48+x*(w-66),Y=y=>h-40-y/max*(h-67);for(const q of [0,.5,1]){el('line',{x1:X(0),y1:Y(q*max),x2:X(1),y2:Y(q*max),stroke:'#d7e0e7'},svg);label(svg,38,Y(q*max)+4,Number((q*max).toFixed(2)),'end');label(svg,X(q),h-20,q)}label(svg,12,18,'f(x)','start');label(svg,w-8,h-5,'x','end');el('path',{d:`M${X(0)} ${Y(max)}V${Y(0)}H${X(1)}`,fill:'none',stroke:'#647b8e'},svg);return{svg,X,Y}}
function curve(ctx,f,color='#122c42'){const {svg,X,Y}=ctx;el('path',{d:Array.from({length:401},(_,i)=>`${i?'L':'M'}${X(i/400)},${Y(f(i/400))}`).join(' '),fill:'none',stroke:color,'stroke-width':2.5},svg)}
function rect(c,a,b,h,color,opacity=.22){el('rect',{x:c.X(a),y:c.Y(h),width:Math.max(0,c.X(b)-c.X(a)),height:Math.max(0,c.Y(0)-c.Y(h)),fill:color,'fill-opacity':opacity,stroke:color,'stroke-width':.65},c.svg)}
function ranges(kind,a,b){return kind==='square'?[[Math.sqrt(a),Math.sqrt(b)]]:[[a/2,b/2],[1-b/2,1-a/2]]}
function calculate(kind,n,sample){const f=kind==='square'?x=>x*x:x=>1-Math.abs(2*x-1);let r=0,l=0;const bands=[];for(let k=0;k<n;k++){r+=f((k+sample)/n)/n;const a=k/n,b=(k+1)/n,parts=ranges(kind,a,b),measure=parts.reduce((s,[u,v])=>s+v-u,0);l+=a*measure;bands.push({a,b,parts,measure})}return{r,l,bands,f,exact:kind==='square'?1/3:1/2}}
function stateURL(){const u=new URL(location.href);u.searchParams.set('function',$('function').value);u.searchParams.set('level',$('resolution').value);u.searchParams.set('sample',$('sample').value);u.searchParams.set('band',$('band').value);u.searchParams.set('sequence',$('sequence').value);u.searchParams.set('n',$('sequence-n').value);history.replaceState(null,'',u);const link=$('language');link.href=link.dataset.target+u.search+u.hash}
function draw(){const n=2**Number($('resolution').value),kind=$('function').value,sample=Number($('sample').value);$('count').textContent=n;$('band').max=n-1;$('band').value=Math.min(Number($('band').value),n-1);const k=Number($('band').value),d=calculate(kind,n,sample);$('band-count').textContent=`${k+1} / ${n}`;const R=frame('riemann'),L=frame('lebesgue');for(let i=0;i<n;i++){const h=d.f((i+sample)/n);rect(R,i/n,(i+1)/n,h,'#17669b');el('circle',{cx:R.X((i+sample)/n),cy:R.Y(h),r:2.5,fill:'#17669b'},R.svg);for(const[a,b]of d.bands[i].parts)rect(L,a,b,d.bands[i].a,'#ae4516',i===k?.65:.12)}curve(R,d.f);curve(L,d.f);const band=d.bands[k];el('rect',{x:L.X(0),y:L.Y(band.b),width:L.X(1)-L.X(0),height:L.Y(band.a)-L.Y(band.b),fill:'#ae4516','fill-opacity':.08},L.svg);for(const[a,b]of band.parts)el('line',{x1:L.X(a),x2:L.X(b),y1:L.Y(0)+5,y2:L.Y(0)+5,stroke:'#ae4516','stroke-width':5},L.svg);$('r-value').textContent=fmt(d.r);$('l-value').textContent=fmt(d.l);$('r-error').textContent=fmt(Math.abs(d.r-d.exact));$('l-bound').textContent=fmt(d.l+1/n);mathText('exact',kind==='square'?String.raw`\(\frac13\approx0.33333\)`:String.raw`\(\frac12=0.50000\)`);mathText('band-detail',t('Selected value band: ','選択した値の帯：')+String.raw`\(${fmt(band.a)}\le f(x) ${k===n-1?'\\le':'<'} ${fmt(band.b)}\). `+t('Preimage length: ','逆像の全長：')+String.raw`\(\mu(E)=${fmt(band.measure)}\). `+t('Contribution: ','寄与：')+String.raw`\(${fmt(band.a)}\times${fmt(band.measure)}=${fmt(band.a*band.measure)}\). `+(kind==='tent'?t('Add the lengths of both pieces.','２つの区間の長さを足します。'):''));typeset();stateURL();window.integrationResult={...d,n}}
function sequence(){typeset();stateURL();const n=Number($('sequence-n').value),spike=$('sequence').value==='spike';$('sequence-count').textContent=n;const c=frame('sequence-chart',spike?n:1);if(spike){rect(c,0,1/n,n,'#ae4516',.3);el('circle',{cx:c.X(0),cy:c.Y(0),r:3,fill:'#122c42'},c.svg)}else curve(c,x=>x**n);mathText('sequence-result',spike?String.raw`\(${n}\times\frac1{${n}}=1\). `+t('Pointwise limit: 0 everywhere.','各点での極限は常に 0。'):String.raw`\(\int_0^1x^{${n}}\,dx=\frac1{${n}+1}=${fmt(1/(n+1))}\). `+t('Limit: 0 for x < 1, and 1 at x = 1.','極限は x < 1 で 0、x = 1 で 1。'));$('sequence-note').textContent=spike?t('The vertical axis rescales with n. There is no single integrable dominating function: the area stays 1 although the pointwise limit integrates to 0.','縦軸は n に合わせて変化します。全項を上から抑える可積分関数は存在しません。各点での極限の積分は 0 ですが、面積は 1 のままです。'):t('Every curve is bounded by the integrable function g = 1 on [0,1]. Dominated convergence justifies taking the limit inside the integral.','すべての曲線は [0,1] 上の可積分関数 g = 1 以下です。優収束定理により、極限と積分を交換できます。')}
const params=new URLSearchParams(location.search);for(const[id,key,values]of [['function','function',['square','tent']],['sample','sample',['0','0.5','1']],['sequence','sequence',['bounded','spike']]])if(values.includes(params.get(key)))$(id).value=params.get(key);for(const[id,key,min,max]of [['resolution','level',1,6],['band','band',0,63],['sequence-n','n',1,40]]){const v=Number(params.get(key));if(params.has(key)&&Number.isInteger(v)&&v>=min&&v<=max)$(id).value=v}
for(const [id,en,jp] of [['resolution','Refinement level','細分化の段階'],['band','Selected value band','選択した値の帯'],['sequence-n','Sequence index','関数列の番号']])$(id).setAttribute('aria-label',t(en,jp));
for(const id of ['function','sample','resolution','band'])$(id).addEventListener('input',draw);for(const id of ['sequence','sequence-n'])$(id).addEventListener('input',sequence);new ResizeObserver(()=>{draw();sequence()}).observe($('riemann'));window.addEventListener('hashchange',stateURL);draw();sequence();window.addEventListener('load',typeset);window.integrationMath={calculate,ranges};
