import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {HDRLoader} from 'three/addons/loaders/HDRLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {makeModels} from './models.js';
import {createPhotoreal, loadGainMapHDR} from './photoreal.js';
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const setText=(s,t)=>{const e=$(s);if(e)e.textContent=t};
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={lang:new URL(location.href).searchParams.get('lang')==='ja'?'ja':'en',stage:0,year:'2022',photo:false,cutaway:true,selection:'all',explode:0,mismatch:0,frequency:100,listener:0,phase:.125,playing:false};
document.documentElement.lang=state.lang;
const copy={en:{tabs:['01 The six drivers','02 Quiet structure','03 Moving air','04 A wider stage'],kickers:['01 / ANATOMY','02 / FORCE CANCELLATION','03 / LOW FREQUENCIES','04 / SPATIAL CUES'],titles:['A speaker system hiding in a display.','Opposing forces. Useful sound.','Long waves, small sources.','Where does the sound seem to be?'],
 text:['Two tall acoustic chambers follow the sides of the 2022 display. At each lower corner sit a woofer module, drawn holding an opposed pair, and a tweeter. Use the part buttons to isolate each family; the labels say where each shape comes from.','Watch a conceptual opposed woofer pair in slow motion. Their reactions act in opposite directions on the support. Add a mismatch to see a residual force emerge.','Change frequency to compare wavelength with the 62.3 cm display width. The arcs show wavefront spacing at a slowed physical time; they are not a measured sound-pressure field.','Each speaker reaches both ears. Move the listener to change all four paths. The readout shows the travel-time difference between the ears for the left source.'],
 notes:['The enclosure follows Apple’s published dimensions; interior parts are fitted to iFixit’s 2022 teardown photograph. Depths, the inside of the woofer modules and the outlet route are inferred. The 2026 interior is not reconstructed.','This separated pair is an inspection model, not the measured internal mechanism. Motion is exaggerated. Arrows and graph share one cycle: blue is woofer A, orange woofer B; the thick curve and the grey arrow at the top are the residual on the support.','Sound speed: 343 m/s. Wave spacing follows λ = c/f. At low frequency, fewer wavefronts fit in the view. This says nothing about the display’s measured output at that frequency.','Ideal point sources 0.48 m apart; ears 0.18 m apart; forward distance 0.75 m. No head shadow, reflections or Apple spatial filters are simulated.'],
 all:'All parts',woofers:'Woofer pairs',tweeters:'Tweeters',isolated:'Speakers only',electronics:'Electronics',fans:'Cooling fans',explode:'Separate assemblies',year:'Product evidence',mismatch:'Force mismatch',frequency:'Frequency',listener:'Listener sideways',front:'Front',side:'Side',reset:'Reset view',detail:'Speaker detail',exterior:'Exterior',cutaway:'Cutaway',play:'Play motion',pause:'Pause',cycle:'Cycle',hint:'Drag to orbit · Pinch or ± to zoom · Alt + wheel to zoom',source:'Compare with the 2022 teardown',
 sourceNote:'Modelled 3D reconstruction: outlines and positions follow iFixit’s 2022 photograph, which the page can overlay on the model; depths and hidden mechanics are inferred.',readout:['physical drivers: 4 woofers + 2 tweeters','peak residual / one driver’s reference force','wavelength in air','left-source arrival difference between ears'],
 yearNote:{'2022':'2022: original six-driver system; A13 Bionic. [1, 6]','2026':'2026: updated six-driver system; Apple claims 30% deeper bass. The geometry shown remains the 2022 reconstruction. [2, 3]'},tags:['2022 / PANEL REMOVED','OPPOSED PAIR / CONCEPT MODEL','WAVE SPACING / SLOWED TIME','TOP VIEW / GEOMETRY MODEL'],exteriorTag:'2022 / EXTERIOR',explodedTag:'2022 / SEPARATED FOR INSPECTION',
 sound:'Hear stereo panning',stop:'Stop sound',soundNote:'Three short tones: left, center, right. Ordinary stereo only, through your current output. Begin at a comfortable volume. This is not Atmos or a recording of the display.',downloads:'Take the explanation with you.',downloadText:'An illustrated, seven-page guide in each language, plus a combined bilingual edition. The same evidence and model boundaries as the page.',sources:'Sources & model boundaries',checked:'Sources checked 13 September 2026. The 3D model is an original reconstruction from published references; no Apple CAD or acoustic measurements were available.',fallback:'3D is unavailable here. Use the interactive controls and numerical readouts below, or read the illustrated PDF.',footer:'Independent educational model · Sources checked 13 September 2026',
 photoOn:'Teardown photo overlay: on',photoOff:'Overlay the teardown photo',legendTitle:'Where each label comes from',legend:{spec:'Apple specification',photo:'Fitted to the teardown photo',inferred:'Inferred or teaching model'},
 sel:{woofers:['Four woofers in two opposed pairs.','Apple confirms four force-cancelling woofers. Each lower module is drawn holding two drivers back to back; the photograph shows only the module face, so that internal layout is inferred. The tall chamber above each module is highlighted with it.'],tweeters:['Two tweeters at the outer corners.','The narrow silver parts at the outer lower corners sit behind a metal mesh. Apple assigns the tweeters the mid and high frequencies. Their internal motor and acoustic passages are not reconstructed.'],fans:['Those large circles are cooling fans.','The two large circular parts higher in the enclosure are blower fans, not bass drivers. The speaker assemblies occupy the side chambers and lower corners. The internal power supply also needs cooling. [7, 8]'],electronics:['Power and processing share the enclosure.','The split power supply and lower-right logic board follow their photographed positions. Their top surfaces carry the photograph’s circuit detail; component heights are estimated. This is not a complete circuit reconstruction.'],isolated:['Only the sound system.','Electronics, fans and cables are hidden, leaving the two side chambers, the two woofer modules and the two tweeters.']},
 explodeNote:' Separation is a nonphysical inspection state; the ghosted woofer modules reveal the inferred opposed drivers.',
 call:{enclosure:['Aluminium enclosure','62.3 × 36.2 cm · Apple specification','spec'],glass:['Glass over the 27-inch 5K panel','Apple specification','spec'],edges:['Perforated top and bottom edges','Product photographs','photo'],stand:['Tilt stand, one bent plate','47.8 cm high, 16.8 cm deep · Apple; plate gauge estimated','spec'],wooferL:['Woofer pair, left','Size and position: teardown photo · opposed layout inside: inferred','photo'],wooferR:['Woofer pair, right','Size and position: teardown photo · opposed layout inside: inferred','photo'],tweeterL:['Tweeter, left','Behind a metal mesh · teardown photo','photo'],tweeterR:['Tweeter, right','Behind a metal mesh · teardown photo','photo'],chamber:['Side acoustic chamber','Outline: teardown photo · depth and role: inferred','photo'],outlet:['Outlet through the bottom edge','Route inferred; not visible in the photograph','inferred'],fan:['Cooling fan, not a speaker','Teardown photo','photo'],psu:['Power supply board','Outline and surface: teardown photo','photo'],logic:['Logic board with A13 Bionic','Chip: Apple · outline: teardown photo','photo'],driverA:['Woofer A','Teaching model, motion exaggerated','inferred'],driverB:['Woofer B','Teaching model, motion exaggerated','inferred'],net:['Residual force on the support','A + B; zero when matched','inferred'],srcL:['Left speaker','Ideal point source','inferred'],srcR:['Right speaker','Ideal point source','inferred'],listener:['Listener','Ears 0.18 m apart','inferred']}},
ja:{tabs:['01 6基のドライバー','02 筐体の揺れを減らす','03 空気を動かす','04 広がりを感じる'],kickers:['01 / 内部の構成','02 / 力の相殺','03 / 低い周波数','04 / 空間の手がかり'],titles:['ディスプレイの中の音響システム。','逆向きの反力で、揺れを減らす。','長い波を、小さな音源から。','どこから聞こえると感じる？'],
 text:['2022年版では、背の高い音響室が左右の縁に沿って延びています。下部の左右の隅には、対向するウーファーのペアを収めたモジュールとツイーターがあります。部品ボタンで各グループを抜き出せます。ラベルは各形状の根拠を示します。','概念的な対向ウーファーのペアをスロー表示します。支持部にかかる反力は逆向きです。不一致を加え、残留する力を見てください。','周波数を変え、波長と画面幅62.3 cmを比べます。弧の間隔は時間を遅くした波長を示し、実測の音圧分布ではありません。','各スピーカーの音は両耳に届きます。聴く位置を動かすと4本の経路が変わります。数値は左音源から両耳への到達時間差です。'],
 notes:['外形は Apple の公表寸法、内部の部品は iFixit の2022年の分解写真に合わせています。奥行き、ウーファーモジュールの内部、音の出口の経路は推定です。2026年の内部は未再構成です。','間隔を広げたペアは原理の観察用で、実機の内部機構を測定したものではありません。動きは誇張しています。矢印とグラフは同じ周期で動きます。青がウーファーA、橙がウーファーB、太い曲線と上部の灰色の矢印が支持部に残る力です。','音速343 m/s、波の間隔は λ = c/f です。低周波ほど画面内に入る波面が少なくなります。その周波数で実機がどれほどの音を出すかは示しません。','点音源間0.48 m、耳の間0.18 m、正面距離0.75 mの理想モデル。頭による遮蔽、反射、Apple の空間フィルターは計算していません。'],
 all:'全体',woofers:'ウーファー',tweeters:'ツイーター',isolated:'スピーカーのみ',electronics:'電子回路',fans:'冷却ファン',explode:'ユニットを分離',year:'製品の根拠',mismatch:'反力の不一致',frequency:'周波数',listener:'聴く位置の左右移動',front:'正面',side:'側面',reset:'視点を戻す',detail:'スピーカー拡大',exterior:'外観',cutaway:'内部を見る',play:'動きを再生',pause:'停止',cycle:'周期',hint:'ドラッグで回転 · ピンチ / ± で拡大 · Alt + ホイールで拡大',source:'2022年の分解写真と比べる',
 sourceNote:'モデル化した3D再構成：輪郭と位置は iFixit の2022年の写真（モデルに重ねて表示できます）に合わせ、奥行きと隠れた機構は推定です。',readout:['物理ドライバー：ウーファー4基＋ツイーター2基','残留力のピーク / 1基の基準反力','空気中の波長','左音源から両耳への到達時間差'],
 yearNote:{'2022':'2022年：初代の6ドライバー構成。A13 Bionic。[1, 6]','2026':'2026年：更新された6ドライバー構成。Apple は低音が30%深くなったと説明。表示形状は2022年版です。[2, 3]'},tags:['2022年 / 画面を取り外した状態','対向ペア / 概念モデル','波の間隔 / スロー表示','上面図 / 幾何モデル'],exteriorTag:'2022年 / 外観',explodedTag:'2022年 / 分離した観察状態',
 sound:'ステレオパンを聴く',stop:'音を止める',soundNote:'左・中央・右の短い音。現在の出力機器から通常のステレオで再生します。無理のない音量で始めてください。Atmos や実機の録音ではありません。',downloads:'図解を持ち帰る。',downloadText:'各言語7ページの図解ガイドと、日英合本版。ページと同じ根拠とモデル上の限界を収録しています。',sources:'出典とモデルの範囲',checked:'出典確認：2026年9月13日。公開資料を参考に独自に再構成した3Dモデルです。Apple のCADや音響測定値は使用していません。',fallback:'この環境では3Dを表示できません。下の操作と数値表示、または図解PDFをご利用ください。',footer:'独立した教育用モデル · 出典確認：2026年9月13日',
 photoOn:'分解写真の重ね表示：オン',photoOff:'分解写真を重ねる',legendTitle:'ラベルの根拠',legend:{spec:'Apple の公表仕様',photo:'分解写真に合わせた形状',inferred:'推定・教材モデル'},
 sel:{woofers:['2組のペアで、ウーファーは4基。','Apple は力を相殺する4基のウーファーを公表しています。下部の各モジュールに2基のドライバーを背中合わせに描いています。写真に写るのはモジュールの表面だけなので、内部の配置は推定です。各モジュールの上の背の高い音響室も一緒に強調します。'],tweeters:['外側の隅に、2基のツイーター。','下部の外側の隅にある細い銀色の部品は、金属メッシュの奥にあります。Apple の説明では、ツイーターは中高域を担当します。内部の磁気回路や音響経路は再構成していません。'],fans:['大きな丸い部品は、冷却ファン。','筐体上部の大きな円形部品は、低音用スピーカーではなくブロワーファンです。スピーカーは側面の音響室と下部の隅にあります。内部の電源回路も冷却が必要です。[7, 8]'],electronics:['電源と処理回路も、筐体の中に。','左右に分かれた電源基板と右下のロジックボードを、分解写真の配置に沿って示します。基板の表面には写真の回路の細部を使い、部品の高さは推定しています。回路全体の再構成ではありません。'],isolated:['音響システムだけを見る。','電子回路、ファン、ケーブルを隠し、左右の音響室、2つのウーファーモジュール、2基のツイーターだけを残します。']},
 explodeNote:' 分離表示は実動作ではありません。半透明のウーファーモジュールの中に、推定した対向ドライバーを示します。',
 call:{enclosure:['アルミニウムの筐体','62.3 × 36.2 cm · Apple の仕様','spec'],glass:['27インチ5Kパネルを覆うガラス','Apple の仕様','spec'],edges:['上下の縁に並ぶ細かな穴','製品写真','photo'],stand:['傾き調整スタンド（1枚の曲げ板）','高さ47.8 cm・奥行き16.8 cm · Apple。板厚は推定','spec'],wooferL:['ウーファーのペア（左）','大きさと位置：分解写真 · 内部の対向配置：推定','photo'],wooferR:['ウーファーのペア（右）','大きさと位置：分解写真 · 内部の対向配置：推定','photo'],tweeterL:['ツイーター（左）','金属メッシュの奥 · 分解写真','photo'],tweeterR:['ツイーター（右）','金属メッシュの奥 · 分解写真','photo'],chamber:['側面の音響室','輪郭：分解写真 · 奥行きと役割：推定','photo'],outlet:['下縁から出る音','経路は推定。写真には写っていません','inferred'],fan:['冷却ファン（スピーカーではない）','分解写真','photo'],psu:['電源基板','輪郭と表面：分解写真','photo'],logic:['A13 Bionic を載せたロジックボード','チップ：Apple · 輪郭：分解写真','photo'],driverA:['ウーファーA','教材モデル、動きは誇張','inferred'],driverB:['ウーファーB','教材モデル、動きは誇張','inferred'],net:['支持部に残る力','A + B。一致していれば0','inferred'],srcL:['左スピーカー','理想的な点音源','inferred'],srcR:['右スピーカー','理想的な点音源','inferred'],listener:['聴く人','両耳の間隔0.18 m','inferred']}}};

const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(28,1,.05,120);let renderer,orbit,models,raf,contextLost=false,env,pr,gtao,flight,accRaf=0;
const host=$('#scene'),layer=$('#callout-layer'),list=$('#callout-list');
const dark=()=>document.documentElement.dataset.theme==='dark'||(!document.documentElement.dataset.theme&&matchMedia('(prefers-color-scheme: dark)').matches);
function backdrop(){const c=document.createElement('canvas');c.width=4;c.height=256;const x=c.getContext('2d');const g=x.createLinearGradient(0,0,0,256);const d=dark();g.addColorStop(0,d?'#2a2825':'#f7f5f1');g.addColorStop(.62,d?'#1c1a18':'#ebe7e0');g.addColorStop(1,d?'#141311':'#ddd8cf');x.fillStyle=g;x.fillRect(0,0,4,256);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;scene.background?.dispose?.();scene.background=t}
// Live frames while anything moves; when still, the image converges to supersampled AA,
// reflections in the display glass and aluminium, and depth of field on the speaker close-up.
function draw(){if(!renderer||contextLost)return;models.update(state);pr.gtaoAllowed=state.stage!==1&&!models.isGhosted()&&!(state.stage===0&&state.cutaway&&state.photo);if(pr.render()&&!accRaf)accRaf=requestAnimationFrame(()=>{accRaf=0;draw()});layoutCallouts()}
const presets={0:{reset:[[3.6,1.5,15.8],[0,.25,0]],front:[[0,.35,16.2],[0,.25,0]],side:[[14.5,1.4,4.6],[0,.2,0]],detail:[[3.95,-.2,3.9],[2.5,-.66,0]]},1:{reset:[[4.4,2.0,5.3],[0,.05,0]],front:[[0,.2,5.6],[0,0,0]],side:[[5.8,1,1.4],[0,0,0]],detail:[[2.7,1.1,3.2],[0,0,0]]},2:{reset:[[8.5,10,19.5],[0,-1,2.5]],front:[[0,4,21],[0,-.8,2]],side:[[19,6,7],[0,-1,2]],detail:[[8.5,10,19.5],[0,-1,2.5]]},3:{reset:[[0,22,5.2],[0,0,4.8]],front:[[0,22,5.2],[0,0,4.8]],side:[[11,8,13],[0,0,4]],detail:[[0,22,5.2],[0,0,4.8]]}};
function cameraPreset(kind='reset',animate=true){
 if(!orbit)return;const [p,t]=presets[state.stage][kind];pr?.setDof(kind==='detail'&&state.stage===0?{focus:new THREE.Vector3(...t),aperture:.06}:null);const narrow=host.clientWidth<620;const k=narrow&&state.stage!==3?1.06:1;const pos=new THREE.Vector3(...p).sub(new THREE.Vector3(...t)).multiplyScalar(k).add(new THREE.Vector3(...t));
 orbit.minDistance=state.stage===1?2.5:3;orbit.maxDistance=30;
 cancelAnimationFrame(flight);if(!animate||reduced.matches){camera.position.copy(pos);orbit.target.set(...t);orbit.update();draw();return}
 const p0=camera.position.clone(),t0=orbit.target.clone(),t1=new THREE.Vector3(...t),start=performance.now();
 const step=now=>{const u=Math.min(1,(now-start)/650),e=u<.5?2*u*u:1-Math.pow(-2*u+2,2)/2;camera.position.lerpVectors(p0,pos,e);orbit.target.lerpVectors(t0,t1,e);orbit.update();draw();if(u<1)flight=requestAnimationFrame(step)};flight=requestAnimationFrame(step)}
function showFallback(){const f=$('#fallback');if(!f)return;f.hidden=false;f.innerHTML=`<svg viewBox="0 0 540 250" role="img" aria-label="${state.lang==='ja'?'左右の音響室と下部のドライバー':'Side chambers and lower driver assemblies'}"><rect x="28" y="15" width="484" height="204" rx="8" fill="#b9c1c7" stroke="#627581"/><path d="M40 25h55v25h22v62H91v95H40z M500 25h-55v25h-22v62h26v95h51z" fill="#28323a"/><g fill="#427a91"><rect x="67" y="164" width="17" height="35" rx="4"/><rect x="456" y="164" width="17" height="35" rx="4"/></g><g fill="#b6804d"><rect x="46" y="165" width="13" height="34"/><rect x="481" y="165" width="13" height="34"/></g><text x="270" y="115" text-anchor="middle" font-family="sans-serif" font-size="20" fill="#273c48">2022 · 4 + 2</text></svg><p>${copy[state.lang].fallback}</p>`;all('.camera-controls button').forEach(b=>b.disabled=true)}
try{
 renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,host.clientWidth<620?1.5:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NeutralToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);
 renderer.domElement.addEventListener('wheel',e=>{if(!e.altKey)e.stopImmediatePropagation()},{capture:true,passive:true});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;stopMotion();showFallback()});renderer.domElement.addEventListener('webglcontextrestored',()=>location.reload());
 const pm=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();env=pm.fromScene(room,.04);scene.environment=env.texture;room.dispose();
 new HDRLoader().load('/assets/hdri/photo_studio_01_1k.hdr',hdr=>{const t=pm.fromEquirectangular(hdr).texture;hdr.dispose();env.dispose();env={texture:t,dispose:()=>t.dispose()};scene.environment=t;scene.environmentIntensity=.95;scene.environmentRotation.set(0,-.6,0);pm.dispose();draw();
   // then the 2k studio light, for crisp strip-light reflections in the glass and aluminium
   if(host.clientWidth>=620)loadGainMapHDR(renderer,'/assets/textures/studio-hdri-2k/photo_studio_01','/assets/textures/studio-hdri-2k/photo_studio_01-gain').then(src=>{const p2=new THREE.PMREMGenerator(renderer);const t2=p2.fromEquirectangular(src.texture).texture;src.dispose();p2.dispose();env.dispose();env={texture:t2,dispose:()=>t2.dispose()};scene.environment=t2;window.__labEnv2k=true;draw()}).catch(e=>console.warn(e))},undefined,()=>pm.dispose());
 scene.add(new THREE.HemisphereLight('#ffffff','#8b8478',.35));const key=new THREE.DirectionalLight('#ffffff',1.5);key.position.set(3.5,10,6.5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-6,right:6,top:6,bottom:-6,near:1,far:30});key.shadow.radius=6;key.shadow.bias=-.0003;key.shadow.normalBias=.02;scene.add(key);
 backdrop();
 const photoTex=new THREE.TextureLoader().load('./assets/ifixit-studio-display-2022-interior.jpg',()=>draw());photoTex.colorSpace=THREE.SRGBColorSpace;photoTex.anisotropy=8;
 models=makeModels(scene,photoTex);
  gtao=new GTAOPass(scene,camera,1,1);gtao.blendIntensity=.9;gtao.updateGtaoMaterial({radius:.3,distanceExponent:1.4,thickness:1,scale:1,samples:16,distanceFallOff:1});gtao.updatePdMaterial({lumaPhi:10,depthPhi:2,normalPhi:3,radius:5,rings:2,samples:16});pr=createPhotoreal({renderer,scene,camera,gtao,phone:host.clientWidth<620||matchMedia('(pointer: coarse)').matches,ssr:{maxDistance:4,thickness:.3,intensity:1}});
 orbit=new OrbitControls(camera,renderer.domElement);orbit.enablePan=false;orbit.enableDamping=false;orbit.minPolarAngle=.01;orbit.maxPolarAngle=Math.PI*.6;orbit.addEventListener('change',draw);orbit.addEventListener('start',()=>{stopMotion();cancelAnimationFrame(flight)});
 new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();pr.setSize(w,h);draw()}).observe(host);
 cameraPreset('reset',false);
 new MutationObserver(()=>{backdrop();draw()}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
}catch(e){console.warn('3D unavailable:',e.message);renderer=null;showFallback()}
/* Callouts: projected anchors, labels stacked in side columns with elbow leaders; numbered markers on narrow screens. */
function chainVisible(o){for(let n=o;n;n=n.parent)if(!n.visible)return false;return true}
function layoutCallouts(){if(!layer||!models)return;const t=copy[state.lang],w=host.clientWidth,h=host.clientHeight,narrow=w<620;
 const items=models.callouts.filter(c=>c.when(state)&&chainVisible(c.obj)).map(c=>{c.obj.updateWorldMatrix(true,false);const wp=c.obj.localToWorld(c.pos.clone());if((c.normal||(state.stage===0&&state.cutaway))&&camera.position.clone().sub(wp).dot(c.normal||new THREE.Vector3(0,0,1))<0)return {ok:false};const p=wp.project(camera);return {c,x:(p.x*.5+.5)*w,y:(-p.y*.5+.5)*h,ok:p.z<1&&Math.abs(p.x)<1.05&&Math.abs(p.y)<1.05,txt:t.call[c.key]}}).filter(i=>i.ok);
 const top=58,bottom=h-(narrow?96:112),lw=Math.min(200,w*.24),gap=narrow?0:8;let html='',svg='';const main=[models.product,models.force,null,models.spatial][state.stage];let bl=w*.2,br=w*.8;if(main){const bx=new THREE.Box3();main.traverseVisible(o=>{if(o.isMesh&&o.geometry.type!=='PlaneGeometry'){o.geometry.boundingBox||o.geometry.computeBoundingBox();bx.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld))}});if(!bx.isEmpty()){bl=w;br=0;for(let i=0;i<8;i++){const v=new THREE.Vector3(i&1?bx.max.x:bx.min.x,i&2?bx.max.y:bx.min.y,i&4?bx.max.z:bx.min.z).project(camera);const sx=(v.x*.5+.5)*w;bl=Math.min(bl,sx);br=Math.max(br,sx)}}}
 if(narrow){const placed=[];items.forEach((it,i)=>{let x=it.x,y=it.y;for(let k=0;k<6&&placed.some(p=>Math.hypot(p[0]-x,p[1]-y)<23);k++){x+=x<w/2?-15:15;y-=17}placed.push([x,y]);if(x!==it.x||y!==it.y)svg+=`<polyline points="${it.x},${it.y} ${x},${y}"/>`;html+=`<span class="callout-dot prov-${it.txt[2]}" style="left:${x}px;top:${y}px">${i+1}</span>`});
  if(list){list.hidden=!items.length;list.innerHTML=items.map((it,i)=>`<li><b><i class="prov-${it.txt[2]}">${i+1}</i>${it.txt[0]}</b><span>${it.txt[1]}</span></li>`).join('')}}
 else{if(list)list.hidden=true;for(const side of[0,1]){const col=items.filter(it=>side?it.x>=w/2:it.x<w/2).sort((a,b)=>a.y-b.y);const hgt=50;let y=top;const ys=col.map(it=>{y=Math.max(Math.min(Math.max(it.y-hgt/2,top),bottom-hgt),y);const r=y;y+=hgt+gap;return r});
  for(let i=ys.length-1,lim=bottom-hgt;i>=0;i--){ys[i]=Math.min(ys[i],lim);lim=ys[i]-hgt-gap}
  col.forEach((it,i)=>{const lx=side?Math.min(w-lw-12,Math.max(br+26,w*.5+40)):Math.max(12,Math.min(bl-lw-26,w*.5-lw-40)),ly=ys[i],ex=side?lx:lx+lw,ey=ly+hgt/2,mx=side?Math.min(it.x+24,ex-10):Math.max(it.x-24,ex+10);
   html+=`<div class="callout prov-${it.txt[2]}" style="left:${lx}px;top:${ly}px;width:${lw}px"><b>${it.txt[0]}</b><span>${it.txt[1]}</span></div>`;
   svg+=`<polyline points="${it.x},${it.y} ${mx},${ey} ${ex},${ey}"/><circle cx="${it.x}" cy="${it.y}" r="3.5"/>`})}}
 layer.innerHTML=`<svg class="callout-lines" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${svg}</svg>`+html}
let content;try{const r=await fetch('./content.json');if(!r.ok)throw Error(r.status);content=await r.json()}catch(e){console.error('Explanation could not load',e)}
function range(id,label,min,max,value,step,unit=''){return `<div class="control"><label for="${id}">${label}<output id="${id}-value">${value}${unit}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`}
function legend(t){return `<div class="prov-legend" aria-label="${t.legendTitle}"><p>${t.legendTitle}</p>${['spec','photo','inferred'].map(k=>`<span class="prov-${k}"><i></i>${t.legend[k]}</span>`).join('')}</div>`}
// The site header links to the other language; this page serves both from one URL.
function shellLanguage(){const ja=state.lang==='ja';all('.ig-language').forEach(a=>{a.textContent=ja?'English':'日本語';a.lang=ja?'en':'ja';a.hreflang=ja?'en':'ja';a.href=ja?'/studio-display-sound/':'/studio-display-sound/?lang=ja'});const crumb=$('#ig-breadcrumb [aria-current="page"]');if(crumb)crumb.textContent=ja?'Studio Display：薄い筐体から、広がる音':'Studio Display · Sound in a thin space';const b=$('.ig-brand');if(b)b.href=ja?'/ja/':'/';const crumbs=all('#ig-breadcrumb a');if(crumbs[0]){crumbs[0].textContent=ja?'ホーム':'Home';crumbs[0].href=ja?'/ja/':'/'}if(crumbs[1]){crumbs[1].textContent=ja?'操作できる解説':'Interactive explainers';crumbs[1].href=ja?'/ja/#interactive':'/#interactive'}const menu=$('#ig-header .ig-menu');if(menu)menu.textContent=ja?'メニュー':'Menu';const skip=$('.ig-skip');if(skip)skip.textContent=ja?'本文へ移動':'Skip to content'}
function updateUI(rebuild=true){const t=copy[state.lang],ja=state.lang==='ja';document.documentElement.lang=state.lang;document.body.classList.toggle('ja',ja);document.title=ja?'Studio Display：薄い筐体から、広がる音。 | Isegoria':'Studio Display · Sound in a thin space | Isegoria';shellLanguage();
 $('#scene')?.setAttribute('aria-label',ja?'Studio Display の内部を示す3Dモデル':'Interactive 3D model of Studio Display speaker chambers');$('#explore')?.setAttribute('aria-label',ja?'音のしくみを探索する':'Explore how the sound works');$('#zoom-in')?.setAttribute('aria-label',ja?'拡大':'Zoom in');$('#zoom-out')?.setAttribute('aria-label',ja?'縮小':'Zoom out');
 const lib=$('#library');if(lib){lib.textContent=ja?'ライブラリー':'Library';lib.href=ja?'../ja/library.html':'../library.html'}
 setText('#eyebrow',ja?'APPLE STUDIO DISPLAY / 音のしくみ':'APPLE STUDIO DISPLAY / ACOUSTICS');const title=$('#title');if(title)title.innerHTML=ja?'薄い筐体から、<br><em>広がる音。</em>':'Sound in a <br><em>thin space.</em>';setText('#intro',content?.[state.lang].intro||t.text[0]);setText('#scope',ja?'2022・2026年版 · 英語 / 日本語 · 独立した解説':'2022 + 2026 models · English / 日本語 · Independent explanation');
 all('[data-stage]').forEach((b,i)=>{b.textContent=t.tabs[i];b.setAttribute('aria-pressed',String(i===state.stage))});setText('#chapter-number',t.kickers[state.stage]);setText('#chapter-title',t.titles[state.stage]);setText('#chapter-text',t.text[state.stage]);setText('#chapter-note',t.notes[state.stage]+(state.stage===0&&state.explode>0?t.explodeNote:''));
 if(state.stage===0&&t.sel[state.selection]){setText('#chapter-title',t.sel[state.selection][0]);setText('#chapter-text',t.sel[state.selection][1])}
 setText('#scene-tag',state.stage===0?(state.explode>0&&state.cutaway?t.explodedTag:state.cutaway?t.tags[0]:t.exteriorTag):t.tags[state.stage]);setText('#scene-count',state.stage===0?'4 W + 2 T':state.stage===1?'F₁ + F₂ = Fnet':state.stage===2?'λ = c / f':'Δt = Δr / c');setText('#scene-hint',t.hint);
 for(const id of['front','side','reset','detail'])setText('#'+id,t[id]);const cut=$('#cutaway');if(cut){cut.textContent=state.cutaway?t.exterior:t.cutaway;cut.setAttribute('aria-pressed',String(!state.cutaway));cut.hidden=state.stage!==0}const det=$('#detail');if(det)det.hidden=state.stage===3||state.stage===2;
 const play=$('#play');if(play){play.textContent=state.playing?t.pause:t.play;play.setAttribute('aria-pressed',String(state.playing))}setText('#phase-label',t.cycle);const ph=$('#phase');if(ph){ph.setAttribute('aria-label',t.cycle);ph.value=state.phase*1000}const pb=$('.playback');if(pb)pb.hidden=state.stage===0||state.stage===3;setText('#footer-note',t.footer);
 if(rebuild){let c='';if(state.stage===0)c=`<div class="component-controls">${['all','woofers','tweeters','isolated','fans','electronics'].map(k=>`<button data-select="${k}" aria-pressed="${state.selection===k}">${t[k]}</button>`).join('')}</div>${range('explode',t.explode,0,100,Math.round(state.explode*100),1,'%')}<button id="surface-detail" aria-pressed="${state.photo}">${state.photo?t.photoOn:t.photoOff}</button>${legend(t)}<div class="control"><label for="year">${t.year}</label><select id="year"><option value="2022" ${state.year==='2022'?'selected':''}>2022</option><option value="2026" ${state.year==='2026'?'selected':''}>2026</option></select><p class="note" id="year-note">${t.yearNote[state.year]}</p></div><a class="reference-link" href="https://www.ifixit.com/News/58242/studio-display-teardown-is-this-secretly-an-imac" target="_blank" rel="noopener">${t.source} ↗</a>`;
  if(state.stage===1)c=range('mismatch',t.mismatch,0,100,state.mismatch,1,'%')+'<svg id="force-graph" viewBox="0 0 300 86" role="img" aria-label="'+(ja?'正規化した反力と合力の1周期':'One cycle of normalized reaction forces and their sum')+'"></svg>';
  if(state.stage===2)c=range('frequency',t.frequency,50,2000,state.frequency,10,' Hz');
  if(state.stage===3)c=range('listener',t.listener,-.45,.45,state.listener,.01,' m')+`<div class="sound-demo"><button id="sound">${audioContext?t.stop:t.sound}</button><p>${t.soundNote}</p></div>`;
  const sc=$('#stage-controls');if(sc)sc.innerHTML=c;
  const sd=$('#surface-detail');if(sd)sd.onclick=()=>{state.photo=!state.photo;state.cutaway=true;updateUI();if(state.photo)cameraPreset('front');else draw()};
  all('[data-select]').forEach(b=>b.onclick=()=>{state.selection=b.dataset.select;state.cutaway=true;updateUI();draw()});
  const ex=$('#explode');if(ex)ex.oninput=e=>{state.explode=Number(e.target.value)/100;setText('#explode-value',e.target.value+'%');state.cutaway=true;updateUI(false);draw()};
  const yr=$('#year');if(yr)yr.onchange=e=>{state.year=e.target.value;setText('#year-note',t.yearNote[state.year])};
  for(const id of['mismatch','frequency','listener']){const el=$('#'+id);if(el)el.oninput=e=>{state[id]=Number(e.target.value);setText('#'+id+'-value',e.target.value+(id==='mismatch'?'%':id==='frequency'?' Hz':' m'));updateNumbers();draw()}}
  const so=$('#sound');if(so)so.onclick=toggleAudio;
 }
 updateNumbers();if(!renderer||contextLost)showFallback();
}
function updateNumbers(){const t=copy[state.lang];let number='4 + 2',extra='';if(state.stage===1){number=(state.mismatch/100).toFixed(2)+' F₀';updateForceGraph()}
 if(state.stage===2){const w=343/state.frequency;number=w.toFixed(w<1?3:2)+' m';extra=` · ${(w/.623).toFixed(2)} × ${state.lang==='ja'?'画面幅':'display width'}`}
 if(state.stage===3){const leftEar=state.listener-.09,rightEar=state.listener+.09;const a=Math.hypot(leftEar+.24,.75),b=Math.hypot(rightEar+.24,.75);number=(Math.abs(b-a)/343*1e6).toFixed(0)+' μs';extra=state.lang==='ja'?' · 絶対値':' · absolute value'}
 const r=$('#readout');if(r)r.innerHTML=`<strong>${number}</strong><span>${t.readout[state.stage]}${extra}</span>`;
}
function updateForceGraph(){const svg=$('#force-graph');if(!svg)return;function d(amp){let s='';for(let i=0;i<=120;i++)s+=(i?'L':'M')+(10+i/120*280).toFixed(2)+','+(43-Math.sin(i/120*Math.PI*2)*amp*31).toFixed(2);return s}svg.innerHTML=`<path d="M10 43H290" class="fg-axis" fill="none"/><path d="${d(1)}" class="fg-a" stroke-width="1.6" fill="none"/><path d="${d(-(1-state.mismatch/100))}" class="fg-b" stroke-width="1.6" fill="none"/><path d="${d(state.mismatch/100)}" class="fg-sum" stroke-width="2.6" fill="none"/><path d="M${10+state.phase*280} 8V78" class="fg-axis" stroke-dasharray="3 3"/><text x="10" y="84" font-size="10" class="fg-a-t">A</text><text x="30" y="84" font-size="10" class="fg-b-t">B</text><text x="51" y="84" font-size="10" class="fg-sum-t">${state.lang==='ja'?'合力':'SUM'}</text>`}
let audioContext=null,audioTimer;
async function toggleAudio(){if(audioContext){stopAudio();return}try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Web Audio unavailable');audioContext=new AC();await audioContext.resume();const now=audioContext.currentTime;for(let i=0;i<3;i++){const osc=audioContext.createOscillator(),gain=audioContext.createGain(),pan=audioContext.createStereoPanner();osc.frequency.value=440;pan.pan.value=i-1;gain.gain.setValueAtTime(0,now+i);gain.gain.linearRampToValueAtTime(.035,now+i+.035);gain.gain.setValueAtTime(.035,now+i+.55);gain.gain.linearRampToValueAtTime(0,now+i+.7);osc.connect(gain).connect(pan).connect(audioContext.destination);osc.start(now+i);osc.stop(now+i+.75)}setText('#sound',copy[state.lang].stop);audioTimer=setTimeout(stopAudio,3000)}catch(e){stopAudio();setText('#sound',state.lang==='ja'?'音声を再生できません':'Audio unavailable')}}
function stopAudio(){clearTimeout(audioTimer);if(audioContext){void audioContext.close();audioContext=null}setText('#sound',copy[state.lang].sound)}
function stopMotion(){state.playing=false;cancelAnimationFrame(raf);const p=$('#play');if(p){p.textContent=copy[state.lang].play;p.setAttribute('aria-pressed','false')}}
function startMotion(){state.playing=true;const p=$('#play');if(p){p.textContent=copy[state.lang].pause;p.setAttribute('aria-pressed','true')}let last=performance.now();function tick(t){if(!state.playing)return;state.phase=(state.phase+Math.min(.05,(t-last)/1000)/2.5)%1;last=t;const ph=$('#phase');if(ph)ph.value=Math.round(state.phase*1000);if(state.stage===1)updateForceGraph();draw();raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick)}
function selectStage(i){stopMotion();stopAudio();state.stage=i;state.phase=.125;updateUI();cameraPreset();draw()}
all('[data-stage]').forEach(b=>b.onclick=()=>selectStage(Number(b.dataset.stage)));
for(const id of['front','side','reset','detail']){const b=$('#'+id);if(b)b.onclick=()=>{if(id==='detail'&&state.stage===0){state.selection='isolated';state.cutaway=true;updateUI()}cameraPreset(id)}}
const cutBtn=$('#cutaway');if(cutBtn)cutBtn.onclick=()=>{state.cutaway=!state.cutaway;updateUI();draw()};
const zoom=f=>{if(!orbit)return;cancelAnimationFrame(flight);const delta=camera.position.clone().sub(orbit.target);delta.multiplyScalar(f);delta.clampLength(orbit.minDistance,orbit.maxDistance);camera.position.copy(orbit.target).add(delta);orbit.update();draw()};
const zi=$('#zoom-in'),zo=$('#zoom-out');if(zi)zi.onclick=()=>zoom(.82);if(zo)zo.onclick=()=>zoom(1.22);
const playBtn=$('#play');if(playBtn)playBtn.onclick=()=>state.playing?stopMotion():startMotion();const phase=$('#phase');if(phase)phase.oninput=e=>{stopMotion();state.phase=Number(e.target.value)/1000;updateNumbers();draw()};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMotion();stopAudio()}});reduced.addEventListener('change',()=>{if(reduced.matches)stopMotion()});
function citations(s){return s.replace(/\[([0-9, ]+)\]/g,(_,nums)=>'['+nums.split(',').map(n=>`<a href="#source-${n.trim()}">${n.trim()}</a>`).join(', ')+']')}
function renderReading(){if(!content)return;const c=content[state.lang],t=copy[state.lang];const r=$('#reading');if(!r)return;r.innerHTML=c.pages.map((p,i)=>`<section class="reading-section" id="chapter-${i+1}"><p class="eyebrow">${p.kicker}</p><div class="section-grid"><div><h2>${p.title}</h2><p class="lead">${p.deck}</p>${p.equation?`<div class="equation">${p.equation}<small>${p.equationNote}</small></div>`:''}${i===1?comparisonTable():''}${i===0?`<div class="boundary"><p>${t.sourceNote} <a href="https://www.ifixit.com/News/58242/studio-display-teardown-is-this-secretly-an-imac">iFixit (2022)</a> · <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">CC BY-NC-SA 3.0</a> · <a href="ATTRIBUTION.md">${state.lang==='ja'?'画像の利用と変更点':'Image use & modifications'}</a></p></div>`:''}</div><div>${p.blocks.map(b=>`<h3>${b.h}</h3><p>${citations(b.p)}</p>`).join('')}</div></div></section>`).join('')+`<section class="reading-section"><p class="eyebrow">PDF / ENGLISH + 日本語</p><h2>${t.downloads}</h2><p>${t.downloadText}</p><div class="download-row"><a href="studio-display-sound-en.pdf">English PDF</a><a href="studio-display-sound-ja.pdf" lang="ja">日本語 PDF</a><a href="studio-display-sound-bilingual.pdf">${state.lang==='ja'?'日英合本 PDF':'Bilingual PDF'}</a></div></section><section class="reading-section" id="sources"><h2>${t.sources}</h2><p>${t.checked}</p><ol class="sources">${content.sources.map(s=>`<li id="source-${s.id}"><a href="${s.url}">${state.lang==='ja'?s.ja:s.title}</a><span>${state.lang==='ja'?s.noteJa:s.note}</span></li>`).join('')}</ol></section>`}
function comparisonTable(){return state.lang==='en'?'<table class="comparison"><thead><tr><th>Documented feature</th><th>2022</th><th>2026</th></tr></thead><tbody><tr><td>Woofers / tweeters</td><td>4 / 2</td><td>4 / 2</td></tr><tr><td>Force cancellation</td><td>Yes</td><td>Yes</td></tr><tr><td>Atmos spatial audio</td><td>Yes</td><td>Yes</td></tr><tr><td>Bass statement</td><td>Reference generation</td><td>30% deeper, per Apple</td></tr><tr><td>Geometry shown here</td><td>Reference-informed</td><td>Not reconstructed</td></tr></tbody></table>':'<table class="comparison"><thead><tr><th>公表された機能</th><th>2022年</th><th>2026年</th></tr></thead><tbody><tr><td>ウーファー / ツイーター</td><td>4 / 2</td><td>4 / 2</td></tr><tr><td>力の相殺</td><td>対応</td><td>対応</td></tr><tr><td>Atmos 空間オーディオ</td><td>対応</td><td>対応</td></tr><tr><td>低音の説明</td><td>比較の基準</td><td>30%深い（Apple）</td></tr><tr><td>本教材の形状</td><td>公開資料を参照</td><td>未再構成</td></tr></tbody></table>'}
updateUI();renderReading();draw();
const lifecycle=new AbortController();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_sound_exploration',title:'Explore Studio Display acoustics',description:'Select a teaching chapter and adjust its displayed physical parameters. Does not start audio.',inputSchema:{type:'object',properties:{stage:{type:'integer',minimum:0,maximum:3},frequency:{type:'number',minimum:50,maximum:2000},mismatch:{type:'number',minimum:0,maximum:100},listener:{type:'number',minimum:-.45,maximum:.45}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object')throw Error('Expected parameters');const bounds={stage:[0,3],frequency:[50,2000],mismatch:[0,100],listener:[-.45,.45]};for(const[k,v]of Object.entries(input)){if(!bounds[k]||!Number.isFinite(v)||v<bounds[k][0]||v>bounds[k][1]||(k==='stage'&&!Number.isInteger(v)))throw Error('Invalid parameter '+k)}Object.assign(state,input);selectStage(state.stage);return{stage:state.stage,frequency:state.frequency,mismatch:state.mismatch,listener:state.listener,readout:$('#readout')?.textContent}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
window.addEventListener('pagehide',()=>{stopMotion();stopAudio();lifecycle.abort();orbit?.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of(Array.isArray(o.material)?o.material:[o.material])){m.map?.dispose();m.dispose()}}});env?.dispose();pr?.dispose?.();renderer?.dispose()},{once:true});
