'use strict';
const $=id=>document.getElementById(id),T=window.LAB_TEXT,ja=document.documentElement.lang==='ja';
// The shared site header can replace the original lesson language link.
function syncLanguage(hash=location.hash){document.querySelectorAll('#language,.ig-language').forEach(a=>{const u=new URL(a.href,location.href);u.search=location.search;u.hash=hash;a.href=u.href;});}
syncLanguage();
document.querySelectorAll('main nav a').forEach(a=>a.addEventListener('click',()=>syncLanguage(a.hash)));
window.addEventListener('hashchange',()=>syncLanguage());
let seed=Array(101).fill(0);seed[50]=1;let rule=90;
function drawEca(){const count=+$('rows').value,c=$('eca'),ctx=c.getContext('2d');c.height=count*10;let row=seed.slice();ctx.fillStyle='#0b110d';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#d7fc70';for(let y=0;y<count;y++){row.forEach((v,x)=>{if(v)ctx.fillRect(x*10,y*10,10,10);});row=CA.elementary(row,rule,$('edge').value==='wrap');}$('rows-value').value=count;c.setAttribute('aria-label',ja?`規則${rule}、${count}世代の時空間図`:`Rule ${rule}, space-time diagram of ${count} generations`);}
function ruleUI(){ $('rule').value=rule;$('rule-table').replaceChildren();for(let k=7;k>=0;k--){const b=document.createElement('button'),v=(rule>>k)&1,input=k.toString(2).padStart(3,'0');b.className='rule-tile';b.setAttribute('aria-pressed',String(!!v));b.setAttribute('aria-label',ja?`入力 ${input}、出力 ${v}。押して反転`:`Input ${input}, output ${v}. Press to flip`);b.innerHTML=`<span class="mini" aria-hidden="true">${input.split('').map(x=>`<i class="${x==='1'?'on':''}"></i>`).join('')}</span><span class="small">${input}</span><span class="out">${v}</span>`;b.onclick=()=>{rule^=1<<k;ruleUI();$('rule-table').children[7-k].focus();};$('rule-table').append(b);}$('binary').textContent=`${rule.toString(2).padStart(8,'0')}₂ = ${rule}₁₀`;document.querySelectorAll('[data-rule]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.rule===rule)));drawEca();}
$('rule').onchange=()=>{if(!$('rule').checkValidity()||$('rule').value===''){$('rule').reportValidity();$('rule').value=rule;return;}rule=+$('rule').value;ruleUI();};document.querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>{rule=+b.dataset.rule;ruleUI();});$('seed').onchange=()=>{seed=Array.from({length:101},(_,i)=>$('seed').value==='single'?+(i===50):+(Math.random()<.5));drawEca();};$('edge').onchange=drawEca;$('rows').oninput=drawEca;ruleUI();
const members=[1,0,1,0,0,1];function setUI(){ $('set-cells').replaceChildren();members.forEach((v,i)=>{let b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-pressed',String(!!v));b.setAttribute('aria-label',`${i+1}: ${v? '∈':'∉'} A`);b.onclick=()=>{members[i]^=1;setUI();$('set-cells').children[i].focus();};$('set-cells').append(b);});$('set-result').textContent=`A = {${members.flatMap((v,i)=>v?[i+1]:[]).join(', ')}}; |A| = ${members.reduce((a,b)=>a+b,0)}`;}setUI();let l=1,r=0;function logicUI(){ $('left').textContent=`${T.left}: ${l}`;$('right').textContent=`${T.right}: ${r}`;$('left').setAttribute('aria-pressed',!!l);$('right').setAttribute('aria-pressed',!!r);$('logic-result').textContent=`${l} XOR ${r} = ${l^r}`;}$('left').onclick=()=>{l^=1;logicUI();};$('right').onclick=()=>{r^=1;logicUI();};logicUI();function counting(){const k=+$('k').value,n=2**k;$('count-result').textContent=ja?`k = ${k} → 入力 ${n} 通り → 規則 ${(2**n).toLocaleString()} 通り`:`k = ${k} → ${n} input patterns → ${(2**n).toLocaleString()} rules`;}$('k').oninput=counting;counting();
const W=32,H=20;let board=Array(W*H).fill(0),generation=0,timer=null,initial=[];
function drawLife(){const c=$('life-board'),ctx=c.getContext('2d');ctx.fillStyle='#0b110d';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++){ctx.fillStyle=board[y*W+x]?'#d7fc70':'#1c2a21';ctx.fillRect(x*30+1,y*30+1,28,28);}$('life-stats').textContent=`${T.generation} ${generation} · ${T.population} ${board.reduce((a,b)=>a+b,0)}`;c.setAttribute('aria-label',$('life-stats').textContent);}
function pause(){clearInterval(timer);timer=null;$('play').textContent=T.play;$('play').setAttribute('aria-pressed','false');}
function step(){board=CA.life(board,W,H,$('life-edge').value==='wrap');generation++;drawLife();}
function reset(newSeed=true){pause();generation=0;if(newSeed){board=Array(W*H).fill(0);let p=$('preset').value;const patterns={glider:[[1,0],[2,1],[0,2],[1,2],[2,2]],blinker:[[0,1],[1,1],[2,1]],block:[[0,0],[1,0],[0,1],[1,1]]};if(p==='soup')board=board.map(()=>+(Math.random()<.28));else patterns[p].forEach(([x,y])=>board[(y+8)*W+x+14]=1);initial=board.slice();}else board=initial.slice();drawLife();}
$('play').onclick=()=>{if(timer){pause();return;}$('play').textContent=T.pause;$('play').setAttribute('aria-pressed','true');timer=setInterval(step,1000/+$('speed').value);};$('step').onclick=()=>{pause();step();};$('reset').onclick=()=>reset(false);$('preset').onchange=()=>reset();$('life-edge').onchange=()=>reset();$('speed').oninput=()=>{if(timer){pause();$('play').click();}};$('clear').onclick=()=>{pause();board.fill(0);generation=0;drawLife();};
function toggle(x,y){pause();board[y*W+x]^=1;drawLife();$('edit-row').value=y+1;$('edit-col').value=x+1;$('edit-status').textContent=`${T.row} ${y+1}, ${T.col} ${x+1}: ${board[y*W+x]?T.alive:T.dead}`;}
$('life-board').onclick=e=>{const rect=e.currentTarget.getBoundingClientRect();toggle(Math.min(W-1,Math.floor((e.clientX-rect.left)/rect.width*W)),Math.min(H-1,Math.floor((e.clientY-rect.top)/rect.height*H)));};$('toggle').onclick=()=>{for(const id of ['edit-row','edit-col']){if(!$(id).checkValidity()||!$(id).value){$(id).reportValidity();return;}}toggle(+$('edit-col').value-1,+$('edit-row').value-1);};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});reset();
const nb=[0,1,0,1,0,1,0,0,0];function inspect(){ $('neighbour-grid').replaceChildren();nb.forEach((v,i)=>{const b=document.createElement('button');b.textContent=v;b.setAttribute('aria-pressed',String(!!v));b.setAttribute('aria-label',`${i===4?(ja?'中央':'Centre'):`${T.row} ${Math.floor(i/3)+1}, ${T.col} ${i%3+1}`}: ${v}`);b.onclick=()=>{nb[i]^=1;inspect();$('neighbour-grid').children[i].focus();};$('neighbour-grid').append(b);});const n=nb.reduce((a,b)=>a+b,0)-nb[4],next=+(n===3||(nb[4]&&n===2));$('inspect-result').textContent=`${T.neighbours}: ${n} · ${T.next}: ${next} (${next?T.alive:T.dead})`;}inspect();
