# Scheduled addition: hyperbolic geometry (exec'd by build.py after batch-six.py).
add_expansion('hyperbolic-geometry','Hyperbolic geometry: where parallels multiply','双曲幾何：平行線が増える世界','Distance in the Poincaré disc, triangles whose angles fall short of π, and tilings no flat plane can hold.','ポアンカレ円板の距離、角の和が π に届かない三角形、平面には収まらないタイリングを扱います。','geometry','Complex numbers and differential geometry','複素数と微分幾何','Cannon, Floyd, Kenyon, Parry · Hyperbolic Geometry (Flavors of Geometry, MSRI)','https://library.slmath.org/books/Book31/files/cannon.pdf',[
L('poincare-distance','1. Distance, lines, and many parallels','1. 距離と直線、そしてたくさんの平行線',
 r'In the Poincaré disc, lines are arcs of circles that meet the rim at right angles, and the rim itself is infinitely far away. Drag P and Q: the dots are equally spaced in hyperbolic length and crowd towards the edge. Then drag R off the line. Through R pass two limiting parallels and infinitely many other lines that never meet PQ, so Euclid’s parallel postulate fails.',
 r'ポアンカレ円板では、直線は縁と直角に交わる円弧で、縁そのものは無限に遠くにあります。P と Q をドラッグしてください。点は双曲的な長さで等間隔に並び、縁に向かって詰まっていきます。次に R を直線の外へドラッグしてください。R を通る極限平行線が二本あり、さらに PQ と決して交わらない直線が無数にあります。ユークリッドの平行線公準は成り立ちません。',
 r'd(z,w)=\operatorname{arcosh}\Bigl(1+\frac{2|z-w|^2}{(1-|z|^2)(1-|w|^2)}\Bigr),\qquad \Pi(d)=2\arctan e^{-d}',
 r'From the centre, a point at Euclidean radius \(r\) lies at hyperbolic distance \(2\operatorname{artanh}r=\ln\frac{1+r}{1-r}\). At \(r=0.9\) that is \(\ln 19\approx2.94\), and the rim is infinitely far.',
 r'中心から見て、ユークリッド半径 \(r\) の点までの双曲距離は \(2\operatorname{artanh}r=\ln\frac{1+r}{1-r}\) です。\(r=0.9\) では \(\ln 19\approx2.94\) で、縁までは無限の距離です。',
 r'The disc shows angles faithfully but not lengths: arcs near the rim look short but are long. Because the model is conformal, the angle \(\Pi\) can be read straight off the picture.',
 r'この円板は角度を正しく表しますが、長さは表しません。縁の近くの弧は短く見えても実際は長いのです。モデルが等角的なので、角 \(\Pi\) は図からそのまま読み取れます。',
 'What happens to Π(d) when R is very close to the line?','R が直線にごく近いとき、Π(d) はどうなりますか？',
 r'It tends to 90°, and the two limiting parallels merge into the single Euclidean parallel. Small regions of the hyperbolic plane look Euclidean.',
 r'90° に近づき、二本の極限平行線はユークリッドのただ一本の平行線に重なります。双曲平面の小さな領域はユークリッド的に見えます。',
 [p('px','P: x','P：x',-0.9,0.9,0.01,-0.55),p('py','P: y','P：y',-0.9,0.9,0.01,-0.3),p('qx','Q: x','Q：x',-0.9,0.9,0.01,0.6),p('qy','Q: y','Q：y',-0.9,0.9,0.01,-0.25),p('rx','R: x','R：x',-0.9,0.9,0.01,0.05),p('ry','R: y','R：y',-0.9,0.9,0.01,0.45)]),
L('hyperbolic-triangle','2. Triangles: the angle sum falls short','2. 三角形：角の和が足りない',
 r'Drag the vertices of a geodesic triangle. Its angles always add to less than π, and the shortfall is exactly its area: the Gauss–Bonnet theorem for a surface of constant curvature −1. Press Play to grow the triangle from a point. Tiny triangles are almost Euclidean; the defect appears as the triangle gets large.',
 r'測地三角形の頂点をドラッグしてください。角の和はいつも π より小さく、その不足分はちょうど面積に等しくなります。曲率が一定値 −1 の曲面に対するガウス・ボネの定理です。再生を押すと、三角形が点から成長します。ごく小さな三角形はほぼユークリッド的で、大きくなるにつれて欠損が現れます。',
 r'\alpha+\beta+\gamma=\pi-\operatorname{Area}(\triangle),\qquad dA=\frac{4\,dx\,dy}{(1-x^2-y^2)^2}',
 r'A triangle whose three vertices sit on the rim (an ideal triangle) has three zero angles, so its area is exactly \(\pi\), the largest any hyperbolic triangle can have.',
 r'三つの頂点がすべて縁にある三角形（理想三角形）は三つの角がすべて 0 なので、面積はちょうど \(\pi\) です。これはどの双曲三角形の面積よりも大きな値です。',
 r'Area means hyperbolic area, not the Euclidean area of the shaded region on the screen. With curvature \(-K\) the rule becomes \(\alpha+\beta+\gamma=\pi-K\cdot\operatorname{Area}\).',
 r'ここでの面積は双曲的な面積で、画面上の塗られた部分のユークリッド面積ではありません。曲率が \(-K\) なら、規則は \(\alpha+\beta+\gamma=\pi-K\cdot\operatorname{Area}\) になります。',
 'Can two hyperbolic triangles have the same angles but different sizes?','角が同じで大きさの違う双曲三角形はありますか？',
 r'No. The angles fix the area, and in fact fix the triangle up to an isometry: there are no similar triangles of different sizes.',
 r'ありません。角が面積を決め、さらに三角形を等長変換を除いて決めてしまいます。大きさだけが違う相似な三角形は存在しません。',
 [p('ax','A: x','A：x',-0.9,0.9,0.01,-0.62),p('ay','A: y','A：y',-0.9,0.9,0.01,-0.4),p('bx','B: x','B：x',-0.9,0.9,0.01,0.7),p('by','B: y','B：y',-0.9,0.9,0.01,-0.3),p('cx','C: x','C：x',-0.9,0.9,0.01,0.0),p('cy','C: y','C：y',-0.9,0.9,0.01,0.72)]),
L('hyperbolic-tiling','3. Regular tilings {p, q}','3. 正則タイリング {p, q}',
 r'Choose p and q. The tiling {p, q} uses regular p-gons, q of them at every corner. On a flat plane only {3, 6}, {4, 4} and {6, 3} work; in the hyperbolic plane every pair with 1/p + 1/q < 1/2 does. The picture is built by reflecting every point into one triangle with angles π/p, π/2 and π/q. Drag the gold centre to move the whole tiling by an isometry of the disc.',
 r'p と q を選んでください。タイリング {p, q} は正 p 角形を使い、各頂点に q 枚が集まります。平面では {3, 6}、{4, 4}、{6, 3} しかありませんが、双曲平面では 1/p + 1/q < 1/2 を満たすどの組でも可能です。図は、すべての点を角が π/p、π/2、π/q の一つの三角形へ鏡映で折り返して描いています。金色の中心をドラッグすると、円板の等長変換でタイリング全体が動きます。',
 r'\frac1p+\frac1q<\frac12,\qquad \operatorname{Area}(p\text{-gon})=(p-2)\pi-\frac{2\pi p}{q},\qquad z\mapsto\frac{z+a}{1+\bar a z}',
 r'For \(\{7,3\}\): heptagons with 120° corners, three at each vertex. Each has area \(5\pi-\tfrac{14\pi}{3}=\tfrac{\pi}{3}\).',
 r'\(\{7,3\}\) では、角が 120° の七角形が各頂点に三枚集まります。一枚の面積は \(5\pi-\tfrac{14\pi}{3}=\tfrac{\pi}{3}\) です。',
 r'The two tones mark mirror-image triangles, not separate tiles: each tile is made of \(2p\) of them. Near the rim the tiles blur together because they are smaller than a pixel in this picture, not because they change.',
 r'二つの濃淡は鏡像の三角形を示すもので、別々のタイルではありません。一枚のタイルは \(2p\) 個の三角形からできています。縁の近くでタイルがぼやけるのは、この図で一画素より小さくなるからで、タイル自体が変わるからではありません。',
 'Why can’t {7, 3} tile the flat plane?','{7, 3} が平面を敷き詰められないのはなぜですか？',
 r'A flat regular heptagon has corners of \(900^\circ/7\approx128.6^\circ\), and three of them add up to more than 360°. Only negative curvature lets a polygon’s corners shrink to 120°.',
 r'平面の正七角形の角は \(900^\circ/7\approx128.6^\circ\) で、三つ合わせると 360° を超えます。多角形の角を 120° まで小さくできるのは負の曲率だけです。',
 [p('p','Polygon sides p','多角形の辺の数 p',3,10,1,7),p('q','Tiles at each corner q','各頂点のタイル数 q',3,10,1,3),p('ax','Centre: x','中心：x',-0.9,0.9,0.01,0),p('ay','Centre: y','中心：y',-0.9,0.9,0.01,0)])])
