# Scheduled addition: rigid-body dynamics (exec'd by build.py after batch-six.py).
add_expansion('rigid-body-dynamics','Rigid-body dynamics: spinning, tumbling, precessing','剛体力学：回転・転倒・歳差','The tennis-racket flip, the gyroscope that refuses to fall, and the inertia tensor behind both.','テニスラケットの反転、倒れないジャイロ、そしてその両方を支える慣性テンソルを扱います。','physics','Classical mechanics and linear algebra','古典力学と線形代数','David Tong · Classical Dynamics, Chapter 3: The Motion of Rigid Bodies','https://www.damtp.cam.ac.uk/user/tong/dynamics/three.pdf',[
L('tennis-racket','1. The tennis-racket theorem','1. テニスラケットの定理',
 r'A box with three different moments of inertia spins with no torque acting on it. About the long axis or the short axis the spin is stable. About the middle axis the smallest disturbance grows, and the body flips over again and again, as the cosmonaut Vladimir Dzhanibekov saw with a wing nut in orbit in 1985. Conservation of energy and of angular momentum forces the angular-momentum point to move along the curves where an ellipsoid meets a sphere.',
 r'三つの慣性モーメントがすべて異なる箱が、トルクを受けずに回転します。長軸か短軸のまわりの回転は安定です。中間の軸のまわりでは、ほんのわずかな乱れが成長し、物体は何度も裏返ります。1985 年に宇宙飛行士ウラジーミル・ジャニベコフが軌道上で蝶ナットに見た現象です。エネルギーと角運動量の保存により、角運動量の点は楕円体と球面が交わる曲線に沿って動くしかありません。',
 r'I_1\dot\omega_1=(I_2-I_3)\,\omega_2\omega_3,\quad I_2\dot\omega_2=(I_3-I_1)\,\omega_3\omega_1,\quad I_3\dot\omega_3=(I_1-I_2)\,\omega_1\omega_2',
 r'Linearising about the middle axis at spin rate \(\omega\) gives growth like \(e^{\lambda t}\) with \(\lambda=\omega\sqrt{(I_2-I_1)(I_3-I_2)/(I_1I_3)}\). For this box \(I_1:I_2:I_3\approx0.363:0.780:1.083\), so \(\lambda\approx0.567\,\omega\).',
 r'回転の速さ \(\omega\) で中間の軸のまわりに線形化すると、\(\lambda=\omega\sqrt{(I_2-I_1)(I_3-I_2)/(I_1I_3)}\) として \(e^{\lambda t}\) のように成長します。この箱では \(I_1:I_2:I_3\approx0.363:0.780:1.083\) なので、\(\lambda\approx0.567\,\omega\) です。',
 r'No torque causes the flip: energy and angular momentum are conserved throughout, and the readout shows the numerical drift. With internal friction a real body ends up spinning about its largest axis, which is not modelled here.',
 r'反転を起こすトルクはありません。エネルギーと角運動量は常に保存され、読み取り欄に数値誤差によるずれを示しています。内部に摩擦があると実際の物体は最大の軸のまわりの回転に落ち着きますが、ここではそれを扱っていません。',
 'Why can a small disturbance about the long axis never grow large?','長軸のまわりの小さな乱れが決して大きくならないのはなぜですか？',
 r'Near that axis the polhodes are small closed loops. Conservation of energy and of \(|\mathbf L|\) confines the motion to one of them, so the angular momentum can only circle nearby.',
 r'その軸の近くのポールホードは小さな閉曲線です。エネルギーと \(|\mathbf L|\) の保存により運動はそのうちの一つに閉じ込められるので、角運動量は近くを回ることしかできません。',
 [c('axis','Spin axis','回転軸',0,2,1,1,[['Long (I₁)','長軸（I₁）'],['Middle (I₂)','中間（I₂）'],['Short (I₃)','短軸（I₃）']]),p('eps','Initial nudge ε','最初のずれ ε',0.001,0.2,0.001,0.01),p('time','Duration','継続時間',20,120,1,60)]),
L('gyroscope','2. The gyroscope: precession and nutation','2. ジャイロ：歳差と章動',
 r'A heavy wheel spins on an axle whose end rests on a pivot. Gravity pulls the wheel down, yet the axle swings sideways instead: the torque changes the direction of the angular momentum, not its size. Released from rest, the tip bobs as it goes round (nutation) and draws cusps. Launched at the right sideways speed, it precesses perfectly steadily.',
 r'重い車輪が軸のまわりに回り、軸の端は支点に載っています。重力は車輪を下へ引きますが、軸は代わりに横へ回ります。トルクが変えるのは角運動量の向きで、大きさではないからです。静止状態から放すと、先端は回りながら上下に揺れ（章動）、カスプを描きます。ちょうどよい横向きの速さで送り出すと、完全に一定の歳差運動をします。',
 r'I_1\ddot\theta=I_1\dot\phi^2\sin\theta\cos\theta-I_3\omega_3\dot\phi\sin\theta+mgl\sin\theta,\qquad \dot\phi=\frac{p_\phi-I_3\omega_3\cos\theta}{I_1\sin^2\theta}',
 r'For a fast top the mean precession rate is \(\Omega\approx mgl/(I_3\omega_3)\), so doubling the spin halves the precession. With \(I_3=0.8\), \(mgl=4\) and \(\omega_3=10\) this is 0.5 radians per unit time.',
 r'速いこまの平均の歳差角速度は \(\Omega\approx mgl/(I_3\omega_3)\) なので、自転を二倍にすると歳差は半分になります。\(I_3=0.8\)、\(mgl=4\)、\(\omega_3=10\) では単位時間あたり 0.5 ラジアンです。',
 r'Here \(\theta\) is measured from the upward vertical and the pivot is frictionless, with \(I_1=1\). Friction at a real pivot slowly drains the spin, so the precession speeds up as the wheel slows.',
 r'ここで \(\theta\) は上向きの鉛直から測り、支点に摩擦はなく、\(I_1=1\) としています。実際の支点では摩擦が自転をゆっくり奪うので、車輪が遅くなるにつれて歳差は速くなります。',
 'Where does the tip stop moving completely?','先端が完全に止まるのはどこですか？',
 r'At the top of each cusp when the wheel is released from rest. There \(\dot\theta=0\), and \(\dot\phi=0\) because \(p_\phi-I_3\omega_3\cos\theta\) vanishes exactly when \(\theta\) is back at its starting value.',
 r'静止状態から放したときの各カスプの頂点です。そこでは \(\dot\theta=0\) であり、\(\theta\) が最初の値に戻ったときにちょうど \(p_\phi-I_3\omega_3\cos\theta\) が 0 になるので \(\dot\phi=0\) でもあります。',
 [p('spin','Spin ω₃','自転 ω₃',4,30,0.5,10),p('tilt','Starting tilt from vertical (degrees)','鉛直からの最初の傾き（度）',20,110,1,60),c('start','Start','始め方',0,2,1,0,[['From rest','静止から'],['Steady push','定常の押し'],['Push backwards','逆向きの押し']]),p('time','Duration','継続時間',2,30,0.5,13)]),
L('inertia-tensor','3. The inertia tensor and principal axes','3. 慣性テンソルと主軸',
 r'Drag four point masses in a plane. The moment of inertia about an axis through the reference point depends on the axis direction only through a symmetric matrix, so I(θ) is a sinusoid in 2θ. Its extremes, always 90° apart, are the principal axes, and the momental ellipse shows them at a glance. Switch the reference point to the origin to see the parallel-axis theorem at work.',
 r'平面上の四つの質点をドラッグしてください。基準点を通る軸のまわりの慣性モーメントは、軸の向きに対称行列を通してしか依存しないので、I(θ) は 2θ の正弦波になります。いつも 90° 離れたその最大と最小が主軸で、慣性楕円を見れば一目でわかります。基準点を原点に切り替えると、平行軸の定理がはたらく様子が見られます。',
 r'I(\theta)=\sum_i m_i r_{\perp,i}^2=\mathbf u^{\mathsf T}\mathbf I\,\mathbf u,\qquad \mathbf I=\sum_i m_i\begin{pmatrix}y_i^2&-x_iy_i\\-x_iy_i&x_i^2\end{pmatrix},\qquad I_z=I_{xx}+I_{yy}',
 r'Unit masses at \((\pm1,0)\) and \((0,\pm2)\) give \(I_{xx}=8\), \(I_{yy}=2\) and \(I_{xy}=0\): the coordinate axes are already principal, and \(I_z=10\).',
 r'\((\pm1,0)\) と \((0,\pm2)\) に単位質量を置くと、\(I_{xx}=8\)、\(I_{yy}=2\)、\(I_{xy}=0\) です。座標軸がすでに主軸で、\(I_z=10\) です。',
 r'The rule \(I_z=I_{xx}+I_{yy}\) holds only for a flat body. A solid body needs the full \(3\times3\) tensor, which, being symmetric, also has three perpendicular principal axes.',
 r'\(I_z=I_{xx}+I_{yy}\) が成り立つのは平らな物体だけです。立体には \(3\times3\) のテンソル全体が必要ですが、それも対称なので、互いに垂直な三本の主軸をもちます。',
 'Why are the principal axes always perpendicular?','主軸がいつも互いに垂直なのはなぜですか？',
 r'The inertia tensor is a real symmetric matrix, and eigenvectors of a real symmetric matrix belonging to different eigenvalues are orthogonal.',
 r'慣性テンソルは実対称行列であり、実対称行列の異なる固有値に属する固有ベクトルは直交するからです。',
 [p('mass','Mass of the orange point','橙の質点の質量',0.2,5,0.1,2.5),p('angle','Axis angle θ (degrees)','軸の角度 θ（度）',0,180,1,75),c('about','Reference point','基準点',0,1,1,0,[['Centre of mass','重心'],['Origin','原点']])])])
