# Scheduled addition: elliptic curves (exec'd by build.py after batch-six.py).
extra_sources['lattice-torus']=('NIST DLMF §23.6 · Relations to theta functions','https://dlmf.nist.gov/23.6')
add_expansion('elliptic-curves','Elliptic curves: geometry that adds','楕円曲線：足し算ができる幾何','A cubic curve whose points form a group: the chord-and-tangent law, curves over finite fields, and the torus hidden behind every curve.','点が群をなす三次曲線：弦と接線による加法、有限体上の曲線、そしてどの曲線の背後にも隠れているトーラスを扱います。','foundations','Group theory, modular arithmetic and complex numbers','群論・合同算術・複素数','Andrew Sutherland · Elliptic Curves (MIT OpenCourseWare 18.783)','https://ocw.mit.edu/courses/18-783-elliptic-curves-spring-2021/',[
L('chord-tangent','1. Adding points with a ruler','1. 定規で点を足す',
 r'A line through two points of a cubic curve meets it in exactly one more point, counted with multiplicity. Reflect that third point in the x axis and call the result P + Q. Drag P and Q along the curve, and switch to 2P to use the tangent instead. In the (a, b) plane, cross the cusp-shaped discriminant curve and watch the curve split into two pieces or merge into one.',
 r'三次曲線上の二点を通る直線は、重複度を込めてちょうどもう一点で曲線と交わります。その三つ目の点を x 軸で折り返したものを P + Q と呼びます。P と Q を曲線に沿ってドラッグし、2P に切り替えると代わりに接線を使います。(a, b) 平面で尖点状の判別式曲線を横切ると、曲線が二つに分かれたり一つにまとまったりします。',
 r'\lambda=\frac{y_Q-y_P}{x_Q-x_P}\ \Bigl(\text{or }\tfrac{3x_P^2+a}{2y_P}\text{ if }P=Q\Bigr),\qquad x_{P+Q}=\lambda^2-x_P-x_Q,\qquad y_{P+Q}=\lambda(x_P-x_{P+Q})-y_P',
 r'On \(y^2=x^3-2x+1\), take \(P=(0,1)\) and \(Q=(1,0)\). Then \(\lambda=-1\), \(x_{P+Q}=1-0-1=0\) and \(y_{P+Q}=-1\cdot(0-0)-1=-1\), so \(P+Q=(0,-1)=-P\). This is consistent: \(Q\) has order 2, and the line through \(P\) and \(Q\) passes through \(-(P+Q)=(0,1)=P\) as a tangent point.',
 r'\(y^2=x^3-2x+1\) で \(P=(0,1)\)、\(Q=(1,0)\) とします。\(\lambda=-1\)、\(x_{P+Q}=1-0-1=0\)、\(y_{P+Q}=-1\cdot(0-0)-1=-1\) なので \(P+Q=(0,-1)=-P\) です。これは整合的です。\(Q\) の位数は 2 で、\(P\) と \(Q\) を通る直線は \(P\) で曲線に接しています。',
 r'The identity is the point at infinity O, where every vertical line meets the curve. Associativity is not obvious from the picture: it is a theorem (it follows from the Cayley–Bacharach theorem on cubics), which the checks behind this page verify numerically.',
 r'単位元は無限遠点 O で、すべての垂直な直線がそこで曲線と交わります。結合法則は図からは明らかではなく、三次曲線に関するケイリー・バカラックの定理から従う定理です。',
 'When is 2P = O?','2P = O になるのはいつですか？',
 r'Exactly when the tangent at P is vertical, that is when \(y_P=0\). Those points are the real roots of \(x^3+ax+b\), so there are one or three of them besides O.',
 r'P での接線が垂直になるとき、つまり \(y_P=0\) のときです。そのような点は \(x^3+ax+b\) の実根なので、O 以外に一つか三つあります。',
 [p('a','Coefficient a','係数 a',-3,2,0.05,-2),p('b','Coefficient b','係数 b',-2,3,0.05,1),p('px','P: x coordinate','P の x 座標',-3,3.4,0.01,-1.2),c('ps','P: branch','P の枝',0,1,1,0,[['upper','上'],['lower','下']]),p('qx','Q: x coordinate','Q の x 座標',-3,3.4,0.01,2.3),c('qs','Q: branch','Q の枝',0,1,1,1,[['upper','上'],['lower','下']]),c('op','Operation','演算',0,1,1,0,[['P + Q','P + Q'],['2P','2P']])]),
L('curves-mod-p','2. The same curve over a finite field','2. 有限体上の同じ曲線',
 r'Replace the real numbers by the integers mod p. The curve becomes a finite scatter of points with the same symmetry y ↔ −y, and the same formulas still add them. Hasse proved that the number of points never strays from p + 1 by more than 2√p. The histogram counts every curve for this p; the walk of G, 2G, 3G, … shows why undoing multiplication is hard.',
 r'実数を p を法とする整数に置き換えます。曲線は y ↔ −y の対称性を保った有限個の点の散らばりになり、同じ公式で点を足せます。ハッセは、点の個数が p + 1 から 2√p より大きくずれないことを証明しました。ヒストグラムはこの p のすべての曲線を数えたものです。G, 2G, 3G, … の歩みは、掛け算を逆にたどるのがなぜ難しいかを示します。',
 r'\#E(\mathbb F_p)=p+1+\sum_{x=0}^{p-1}\Bigl(\frac{x^3+ax+b}{p}\Bigr),\qquad \bigl|\,p+1-\#E(\mathbb F_p)\,\bigr|\le 2\sqrt p',
 r'For \(y^2=x^3+x\) with \(p\equiv3\pmod 4\), the substitution \(x\mapsto-x\) flips the sign of every Legendre symbol, so the sum is 0 and \(\#E=p+1\) exactly. Try \(a=1,\ b=0\) with \(p=23\): there are 24 points.',
 r'\(p\equiv3\pmod 4\) のときの \(y^2=x^3+x\) では、置き換え \(x\mapsto-x\) がすべてのルジャンドル記号の符号を反転させるので和は 0 になり、ちょうど \(\#E=p+1\) です。\(p=23\) で \(a=1,\ b=0\) を試すと、点は 24 個です。',
 r'The semicircle drawn over the histogram is a limit: Birch showed in 1968 that, over all curves mod p, the moments of the normalised trace approach those of the semicircle as p grows. For small p the match is rough.',
 r'ヒストグラムに重ねた半円は極限の形です。バーチは 1968 年に、p を法とするすべての曲線にわたって、正規化したトレースのモーメントが p の増大とともに半円のモーメントに近づくことを示しました。p が小さいうちは一致は粗いものです。',
 'Why must the order of G divide #E?','G の位数が #E を割り切らなければならないのはなぜですか？',
 r'The multiples of G form a subgroup of the group of points, and by Lagrange’s theorem the size of a subgroup divides the size of the group.',
 r'G の倍数全体は点の群の部分群をなし、ラグランジュの定理により部分群の大きさは群の大きさを割り切るからです。',
 [c('pk','Prime p','素数 p',0,7,1,4,[['7','7'],['13','13'],['23','23'],['31','31'],['47','47'],['61','61'],['83','83'],['97','97']]),p('a','Coefficient a (mod p)','係数 a（p を法とする）',0,96,1,2),p('b','Coefficient b (mod p)','係数 b（p を法とする）',0,96,1,3)]),
L('lattice-torus','3. Every complex curve is a torus','3. 複素曲線はどれもトーラス',
 r'Over the complex numbers an elliptic curve is a doughnut: the plane rolled up along a lattice of periods. The Weierstrass function ℘ repeats over the lattice and sends a point z of the torus to (℘(z), ℘′(z)) on the curve. Drag u and v along the two lines where ℘ is real. Adding u and v on the torus, which is just adding complex numbers, lands exactly where the chord through P and Q predicts.',
 r'複素数の上では楕円曲線はドーナツ、つまり周期の格子に沿って平面を丸めたものです。ワイエルシュトラスの関数 ℘ は格子ごとに繰り返し、トーラスの点 z を曲線上の点 (℘(z), ℘′(z)) に写します。℘ が実数になる二本の線に沿って u と v をドラッグしてください。トーラス上で u と v を足すこと、つまり複素数を足すだけのことが、P と Q を通る弦の予言する点にちょうど一致します。',
 r'\wp(z)=\frac1{z^2}+\sum_{\omega\in\Lambda\setminus0}\Bigl(\frac1{(z-\omega)^2}-\frac1{\omega^2}\Bigr),\qquad \wp^{\prime}(z)^2=4\wp(z)^3-g_2\wp(z)-g_3',
 r'For the square lattice \(\tau=i\), symmetry under \(z\mapsto iz\) forces \(g_3=0\), and \(g_2=\tfrac{4\pi^4}{3}E_4(i)\approx189.07\). The curve is \(y^2=4x^3-189.07\,x\), symmetric about \(x=0\).',
 r'正方格子 \(\tau=i\) では \(z\mapsto iz\) に関する対称性から \(g_3=0\) となり、\(g_2=\tfrac{4\pi^4}{3}E_4(i)\approx189.07\) です。曲線は \(x=0\) について対称な \(y^2=4x^3-189.07\,x\) です。',
 r'Only rectangular lattices are shown, so that \(g_2\) and \(g_3\) are real and the curve can be drawn in the real plane. The colouring is a picture of the complex function ℘; the curve on the right shows only its real points.',
 r'\(g_2\) と \(g_3\) が実数になって曲線を実平面に描けるように、長方形の格子だけを扱っています。色づけは複素関数 ℘ の図で、右の曲線はその実数点だけを表します。',
 'Why does ℘ have a double pole at each lattice point but no other poles?','℘ が各格子点に二位の極を持ち、それ以外に極を持たないのはなぜですか？',
 r'Each term \(1/(z-\omega)^2\) has its only pole at \(\omega\), and the subtracted constants make the sum converge. A doubly periodic function with a single simple pole per period is impossible, since the residues in a period must sum to zero, so a double pole is the simplest possibility.',
 r'各項 \(1/(z-\omega)^2\) の極は \(\omega\) だけで、引いた定数が和を収束させます。一周期に単純極を一つだけ持つ二重周期関数は、一周期の留数の和が 0 でなければならないので存在せず、二位の極が最も簡単な可能性です。',
 [p('t','Lattice shape: τ = t i','格子の形：τ = t i',0.7,2,0.01,1.25),p('ux','u: real part','u の実部',-0.5,0.5,0.005,0.35),c('ul','u: line','u の線',0,1,1,0,[['Im z = 0','Im z = 0'],['Im z = t/2','Im z = t/2']]),p('vx','v: real part','v の実部',-0.5,0.5,0.005,0.12),c('vl','v: line','v の線',0,1,1,1,[['Im z = 0','Im z = 0'],['Im z = t/2','Im z = t/2']])])])
