# Scheduled addition: atomic physics (exec'd by build.py after batch-six.py).
extra_sources['spectral-lines']=('NIST · Handbook of Basic Atomic Spectroscopic Data: hydrogen','https://physics.nist.gov/PhysRefData/Handbook/Tables/hydrogentable2.htm')
extra_sources['zeeman']=('Daniel A. Steck · Sodium D Line Data','https://steck.us/alkalidata/sodiumnumbers.pdf')
add_expansion('atomic-physics','Atomic physics: orbitals and spectra','原子物理：軌道とスペクトル','The shapes of the hydrogen orbitals, the spectral series they produce, and how a magnetic field splits the sodium D lines.','水素原子の軌道の形、そこから生じるスペクトル系列、そして磁場がナトリウムの D 線を分裂させる仕組みを扱います。','physics','Quantum mechanics','量子力学','David Tong · Topics in Quantum Mechanics (Cambridge lecture notes)','https://www.damtp.cam.ac.uk/user/tong/topicsinqm.html',[
L('hydrogen-orbitals','1. The shapes of the orbitals','1. 軌道の形',
 r'Each stationary state of hydrogen is a radial function times an angular one. Choose n, l and m and look at a slice through the atom. The nodes, where ψ changes sign, come in two kinds: spheres from the radial factor and cones or planes from the angular factor. On the right, r²R² gives the probability of finding the electron at distance r; the dashed curves are the other l values with the same n.',
 r'水素原子の定常状態はどれも、動径関数と角度関数の積です。n、l、m を選び、原子を切った断面を見てください。ψ の符号が変わる節には二種類あります。動径因子からくる球面と、角度因子からくる円錐面や平面です。右の r²R² は電子を距離 r に見いだす確率を表し、点線は同じ n で l が異なるものです。',
 r'\psi_{nlm}=R_{nl}(r)\,Y_{lm}(\theta,\phi),\qquad R_{nl}\propto e^{-r/n}\Bigl(\frac{2r}{n}\Bigr)^{l}L^{(2l+1)}_{n-l-1}\Bigl(\frac{2r}{n}\Bigr),\qquad \langle r\rangle=\frac{3n^2-l(l+1)}{2}\,a_0',
 r'For \(3d_{z^2}\), \(Y\propto3\cos^2\theta-1\) vanishes where \(\cos^2\theta=1/3\), that is at \(\theta\approx54.7^\circ\): the two nodal cones. With \(n=3,\ l=2\) there is no radial node, and \(\langle r\rangle=(27-6)/2=10.5\,a_0\).',
 r'\(3d_{z^2}\) では \(Y\propto3\cos^2\theta-1\) が \(\cos^2\theta=1/3\)、つまり \(\theta\approx54.7^\circ\) で 0 になり、これが二つの節の円錐です。\(n=3,\ l=2\) では動径方向の節はなく、\(\langle r\rangle=(27-6)/2=10.5\,a_0\) です。',
 r'The pictures use real orbitals (\(p_x\), \(d_{xy}\) and so on), which are combinations of \(+m\) and \(-m\); they are not eigenstates of \(L_z\) when \(m\neq0\). Colour intensity grows like \(|\psi|^{0.55}\) so that faint outer lobes stay visible.',
 r'図は実数の軌道（\(p_x\)、\(d_{xy}\) など）で、\(+m\) と \(-m\) の組み合わせです。\(m\neq0\) のとき \(L_z\) の固有状態ではありません。外側の淡い部分も見えるように、色の濃さは \(|\psi|^{0.55}\) に比例させています。',
 'Why does the 2s orbital have a node but 2p does not have a radial one?','2s 軌道には節があるのに 2p には動径方向の節がないのはなぜですか？',
 r'Both have \(n-1=1\) node in total. For 2s (\(l=0\)) it must be radial, a sphere; for 2p (\(l=1\)) it is the angular nodal plane, which leaves none for the radial factor.',
 r'どちらも節は合計 \(n-1=1\) 個です。2s（\(l=0\)）ではそれは動径方向の球面でなければならず、2p（\(l=1\)）では角度方向の節面なので、動径因子には節が残りません。',
 [p('n','Principal number n','主量子数 n',1,5,1,4),p('l','Angular momentum l','方位量子数 l',0,4,1,2),p('m','Magnetic number m','磁気量子数 m',-4,4,1,0),p('phi','Slice azimuth φ₀ (degrees)','断面の方位角 φ₀（度）',0,180,1,0)]),
L('spectral-lines','2. Spectral series','2. スペクトル系列',
 r'When the electron drops from level n to a lower level, it emits one photon carrying the energy difference. Transitions that end on the same level form a series: Lyman in the ultraviolet, Balmer partly in the visible, Paschen and beyond in the infrared. Choose a series and an upper level, and press play to watch the electron fall.',
 r'電子が準位 n からより低い準位に落ちると、エネルギー差を運ぶ光子を一つ放出します。同じ準位で終わる遷移が一つの系列をなします。ライマン系列は紫外、バルマー系列は一部が可視、パッシェン系列より先は赤外です。系列と上の準位を選び、再生を押して電子が落ちる様子を見てください。',
 r'E_n=-\frac{13.598\ \text{eV}}{n^2},\qquad \frac1\lambda=R_{\mathrm H}\Bigl(\frac1{n_\ell^2}-\frac1{n_u^2}\Bigr),\qquad R_{\mathrm H}=1.09678\times10^{7}\ \text{m}^{-1}',
 r'Hα is the Balmer transition \(3\to2\): \(E=13.598\,(1/4-1/9)=1.889\ \text{eV}\), so \(\lambda=1239.84/1.889\approx656.5\ \text{nm}\) in vacuum, the red line that colours emission nebulae.',
 r'Hα はバルマー系列の遷移 \(3\to2\) です。\(E=13.598\,(1/4-1/9)=1.889\ \text{eV}\) なので、真空中で \(\lambda=1239.84/1.889\approx656.5\ \text{nm}\) となります。散光星雲を赤く染める線です。',
 r'These are Bohr levels with the reduced-mass Rydberg constant. Fine structure and the Lamb shift move the lines by about one part in \(10^5\), far too little to see here. Wavelengths are vacuum values; in air they are about 0.03% shorter.',
 r'これは換算質量を用いたリュードベリ定数によるボーアの準位です。微細構造とラムシフトは線を \(10^5\) 分の 1 程度しか動かさず、ここでは見えません。波長は真空中の値で、空気中では約 0.03% 短くなります。',
 'Why do the lines of a series crowd together at one end?','系列の線が片方の端に詰まるのはなぜですか？',
 r'Because \(1/n_u^2\to0\) as \(n_u\) grows, the photon energies approach the ionisation energy of the lower level from below. The limit wavelength is \(n_\ell^2/R_{\mathrm H}\).',
 r'\(n_u\) が大きくなると \(1/n_u^2\to0\) なので、光子のエネルギーは下の準位の電離エネルギーに下から近づきます。極限の波長は \(n_\ell^2/R_{\mathrm H}\) です。',
 [c('nl','Lower level (series)','下の準位（系列）',1,5,1,2,[['Lyman 1','ライマン 1'],['Balmer 2','バルマー 2'],['Paschen 3','パッシェン 3'],['Brackett 4','ブラケット 4'],['Pfund 5','プント 5']]),p('nu','Upper level n','上の準位 n',2,12,1,3)]),
L('zeeman','3. A magnetic field splits the lines','3. 磁場が線を分裂させる',
 r'The yellow sodium doublet comes from 3p → 3s. In a magnetic field each level splits into sublevels m_J, shifted by g_J m_J μ_B B, and photons can only change m_J by 0 or ±1. Because the Landé factor g_J is different in the upper and lower levels, the D1 line splits into four components and D2 into six. Drag the field and see each component move in proportion to B.',
 r'ナトリウムの黄色い二重線は 3p → 3s の遷移から生じます。磁場の中では各準位が副準位 m_J に分裂して g_J m_J μ_B B だけずれ、光子は m_J を 0 か ±1 だけしか変えられません。ランデ因子 g_J が上と下の準位で異なるので、D1 線は 4 成分に、D2 線は 6 成分に分裂します。磁場をドラッグし、各成分が B に比例して動く様子を見てください。',
 r'\Delta E=\bigl(g_u m_u-g_\ell m_\ell\bigr)\mu_B B,\qquad g_J=1+\frac{J(J+1)+S(S+1)-L(L+1)}{2J(J+1)},\qquad \Delta m=0,\pm1',
 r'For \(^2P_{3/2}\): \(g_J=1+\frac{15/4+3/4-2}{15/2}=\tfrac43\); for \(^2S_{1/2}\): \(g_J=2\). The D2 component \(m_u=\tfrac32\to m_\ell=\tfrac12\) shifts by \(\tfrac43\cdot\tfrac32-2\cdot\tfrac12=1\) unit of \(\mu_B B\), about 16 pm at 1 T.',
 r'\(^2P_{3/2}\) では \(g_J=1+\frac{15/4+3/4-2}{15/2}=\tfrac43\)、\(^2S_{1/2}\) では \(g_J=2\) です。D2 線の成分 \(m_u=\tfrac32\to m_\ell=\tfrac12\) は \(\tfrac43\cdot\tfrac32-2\cdot\tfrac12=1\) 単位の \(\mu_B B\) だけずれ、1 T でおよそ 16 pm です。',
 r'The electron g factor is taken as exactly 2 and hyperfine structure is ignored. Line thickness shows the squared 3j symbol, the relative strength of each transition; the brightness actually seen also depends on the viewing direction and polarisation.',
 r'電子の g 因子はちょうど 2 とし、超微細構造は無視しています。線の太さは各遷移の相対的な強さである 3j 記号の二乗を表します。実際に見える明るさは観測方向と偏光にも依存します。',
 'What would happen in a field of 100 T?','100 T の磁場では何が起こりますか？',
 r'The Zeeman shift would exceed the 2.1 meV fine-structure splitting, so L and S decouple and the pattern goes over to the Paschen–Back effect, where the shifts are \((m_L+2m_S)\mu_B B\).',
 r'ゼーマンのずれが 2.1 meV の微細構造分裂を上回るので、L と S の結合がほどけ、ずれが \((m_L+2m_S)\mu_B B\) となるパッシェン・バック効果に移ります。',
 [p('B','Magnetic field B (tesla)','磁場 B（テスラ）',0,2,0.01,1),c('line','Line','スペクトル線',0,2,1,1,[['D1','D1'],['D2','D2'],['both','両方']]),c('pol','Components','成分',0,2,1,0,[['all','すべて'],['π only','π のみ'],['σ only','σ のみ']])])])
