import {tr} from './i18n.js';
import {initPhysics} from './physics.js';
const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={mode:'heating',part:'indoor',cutaway:false,playing:!reduced.matches,load:3.5,efficiency:4,hours:6,days:120,tariff:.3,capital:2500,compareEff:2.5};
let sceneAPI=null,physicsAPI=null;
const limits={load:[.5,10],efficiency:[1,6],hours:[0,24],days:[0,366],tariff:[0,2],capital:[0,30000],compareEff:[1,8]};
const money=n=>'A$'+Math.abs(n).toLocaleString('en-AU',{maximumFractionDigits:0});
function calculate(s=state){const demand=s.load*s.hours*s.days;const baseline=s.mode==='heating'?1:s.compareEff;const split=demand/s.efficiency;const alternative=demand/baseline;const saving=(alternative-split)*s.tariff;return {demand,split,alternative,saving,splitCost:split*s.tariff,alternativeCost:alternative*s.tariff,reduction:(1-baseline/s.efficiency)*100,payback:s.capital===0?0:saving>0?s.capital/saving:null};}
function partText(){const heat=state.mode==='heating';return {
indoor:['The indoor heat exchanger',heat?'The indoor coil is the condenser: hot refrigerant releases heat and condenses. A fan recirculates room air over the coil and sends warmed air back into the room.':'The indoor coil is the evaporator: cold refrigerant absorbs room heat and evaporates. Moisture may condense on the coil and drain away. The fan returns cooler air to the room.'],
outdoor:['The outdoor heat exchanger',heat?'The outdoor coil is the evaporator. Refrigerant can absorb heat when it is colder than the outside air. The fan helps air cross the coil; the air leaving it is cooler.':'The outdoor coil is the condenser. It rejects both the heat removed from the room and the energy added by the compressor. The air leaving this unit is warmer.'],
pipes:['A closed refrigerant circuit','Two sealed refrigerant lines link the coils. They carry refrigerant, not air. Each line is wrapped in foam insulation; copper shows only at the flare joints and service valves.'],
compressor:['Pressure makes heat transfer possible','The compressor raises vapour pressure and temperature; it always compresses in the same direction. A reversing valve reroutes the circuit between seasons. An expansion device drops pressure before the evaporator. Internal placement here is schematic.']
}[state.part];}
function update(){const heat=state.mode==='heating',r=calculate();$('heating').setAttribute('aria-pressed',heat);$('cooling').setAttribute('aria-pressed',!heat);$('season').textContent=heat?'WINTER / HEATING':'SUMMER / COOLING';$('mode-title').textContent=heat?'Bring outside heat in.':'Move room heat outside.';$('mode-copy').textContent=heat?'Even cold outdoor air contains thermal energy. Refrigerant absorbs some of it, then the compressor raises its pressure and temperature so the indoor coil can warm the room.':'The indoor coil absorbs heat from the room. The compressor and outdoor coil release that heat outdoors, along with the electrical energy used to run the system.';
const electric=state.load/state.efficiency;const source=heat?state.load-electric:state.load;const result=heat?state.load:state.load+electric;$('source-label').textContent=heat?'Heat from outside':'Heat from room';$('delivery-label').textContent=heat?'Heat into room':'Heat to outdoors';for(const [id,value]of [['source-energy',source],['electric-energy',electric],['delivery-energy',result]])$(id).innerHTML=value.toFixed(2)+' <small>kW</small>';
$('eff-label').textContent=heat?'Split-system COP':'Split cooling efficiency (W/W)';$('eff-note').textContent=heat?'Useful heat ÷ electricity. Use an average appropriate to the season, not a best-case rating.':'Heat removed ÷ electricity, in W/W (not US Btu/Wh EER). Use a realistic average over operation.';document.querySelector('.mode-word').textContent=heat?'heating':'cooling';$('load-out').textContent=state.load.toFixed(1)+' kW';$('efficiency-out').textContent=state.efficiency.toFixed(1)+(heat?'':' W/W');$('compare-eff-wrap').hidden=heat;$('cooling-note').hidden=heat;
$('compare-label').textContent=heat?'HEATING / VERSUS ELECTRIC RESISTANCE':'COOLING / VERSUS ANOTHER AIR CONDITIONER';$('alternative-label').textContent=heat?'Resistance heater':'Alternative air conditioner';$('annual-saving').textContent=money(r.saving);$('saving-label').textContent=r.saving>=0?'less electricity cost per year':'more electricity cost per year';$('split-cost').textContent=money(r.splitCost)+'/year';$('alternative-cost').textContent=money(r.alternativeCost)+'/year';$('split-kwh').textContent=Math.round(r.split).toLocaleString('en-AU')+' kWh electricity / year';$('alternative-kwh').textContent=Math.round(r.alternative).toLocaleString('en-AU')+' kWh electricity / year';const max=Math.max(r.split,r.alternative,1);$('split-bar').style.width=r.split/max*100+'%';$('alternative-bar').style.width=r.alternative/max*100+'%';$('reduction').textContent=Math.abs(r.reduction).toFixed(0)+'%';$('reduction-label').textContent=r.reduction>=0?'less electricity':'more electricity';$('payback').textContent=r.payback===null?'No payback':r.payback===0?'No extra cost':r.payback>99?'>99 years':r.payback.toFixed(1)+' years';$('hourly').textContent='A$'+(electric*state.tariff).toFixed(2);$('cost-formula').textContent=`${state.load.toFixed(1)} kW × ${state.hours} h/day × ${state.days} days ÷ ${state.efficiency.toFixed(1)} × A$${state.tariff.toFixed(2)}/kWh = ${money(r.splitCost)}/year.`;
const p=partText();$('part-title').textContent=p[0];$('part-copy').textContent=p[1];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.part===state.part));$('cutaway').setAttribute('aria-pressed',state.cutaway);$('cutaway').textContent=state.cutaway?'Close covers':'Show inside';$('play').textContent=state.playing?'Pause flow':'Play flow';$('play').setAttribute('aria-pressed',state.playing);sceneAPI?.sync();physicsAPI?.sync();return r;}
function setMode(mode){state.mode=mode;update();}
$('heating').onclick=()=>setMode('heating');$('cooling').onclick=()=>setMode('cooling');$('cutaway').onclick=()=>{state.cutaway=!state.cutaway;update();};$('play').onclick=()=>{state.playing=!state.playing;update();};$('reset').onclick=()=>{state.part='indoor';state.cutaway=false;sceneAPI?.reset();update();};
document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{state.part=b.dataset.part;if(state.part==='compressor')state.cutaway=true;update();sceneAPI?.focus(state.part);});
for(const key of Object.keys(limits)){const el=$(key==='compareEff'?'compare-eff':key);el.addEventListener('input',()=>{if(el.value===''||!el.checkValidity())return;const value=Number(el.value);if(Number.isFinite(value)){state[key]=value;update();}});el.addEventListener('change',()=>{el.value=state[key];});}
$('reset-costs').onclick=()=>{Object.assign(state,{load:3.5,efficiency:4,hours:6,days:120,tariff:.3,capital:2500,compareEff:2.5});for(const k of Object.keys(limits))$(k==='compareEff'?'compare-eff':k).value=state[k];update();};
reduced.addEventListener('change',()=>{if(reduced.matches){state.playing=false;update();}});update();
async function initScene(){const {createSplitScene}=await import('./scene3d.js');const host=$('scene');sceneAPI=createSplitScene({host,state,tr,onPart(part){state.part=part;if(part==='compressor')state.cutaway=true;update();sceneAPI?.focus(part);},onLost(){$('fallback').hidden=false;host.hidden=true;state.playing=false;update();}});}
physicsAPI=initPhysics({getState:()=>state,setMode,showPart(part){state.part=part;state.cutaway=true;update();sceneAPI?.focus(part);}});
initScene().catch(error=>{console.error('3D unavailable',error);$('fallback').hidden=false;$('scene').hidden=true;$('cutaway').disabled=true;$('play').disabled=true;$('reset').disabled=true;});
// Optional page-scoped tool, using exactly the visible calculator state.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_energy_comparison',title:'Configure energy comparison',description:'Set heating or cooling and calculator inputs, update visible results, and return annual electricity, cost and simple payback.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['heating','cooling']},...Object.fromEntries(Object.entries(limits).map(([k,[min,max]])=>[k,{type:'number',minimum:min,maximum:max}]))},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('An object is required');for(const[k,v]of Object.entries(input)){if(k==='mode'){if(!['heating','cooling'].includes(v))throw new Error('Invalid mode');}else if(!limits[k]||typeof v!=='number'||!Number.isFinite(v)||v<limits[k][0]||v>limits[k][1]||(k==='days'&&!Number.isInteger(v)))throw new Error('Invalid '+k);}Object.assign(state,input);for(const k of Object.keys(limits))$(k==='compareEff'?'compare-eff':k).value=state[k];return {mode:state.mode,...update()};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
