import {tr} from './i18n.js';
import {initPhysics} from './physics.js';
const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={mode:'heating',part:'indoor',cutaway:false,playing:!reduced.matches,load:3.5,efficiency:4,hours:6,days:120,tariff:.3,capital:2500,compareEff:2.5};
let sceneAPI=null,physicsAPI=null;
const limits={load:[.5,10],efficiency:[1,6],hours:[0,24],days:[0,366],tariff:[0,2],capital:[0,30000],compareEff:[1,8]};
const money=n=>'A$'+Math.abs(n).toLocaleString('en-AU',{maximumFractionDigits:0});
function calculate(s=state){const demand=s.load*s.hours*s.days;const baseline=s.mode==='heating'?1:s.compareEff;const split=demand/s.efficiency;const alternative=demand/baseline;const saving=(alternative-split)*s.tariff;return {demand,split,alternative,saving,splitCost:split*s.tariff,alternativeCost:alternative*s.tariff,reduction:(1-baseline/s.efficiency)*100,payback:s.capital===0?0:saving>0?s.capital/saving:null};}
function partText(){const heat=state.mode==='heating';return {
indoor:['The indoor heat exchanger',heat?'The indoor coil is the condenser: hot refrigerant releases heat and condenses. A fan recirculates room air over the coil and sends warmed air back into the room.':'The indoor coil is the evaporator: cold refrigerant absorbs room heat and evaporates. Moisture may condense on the coil and drain away. The fan returns cooler air to the room.'],
outdoor:['The outdoor heat exchanger',heat?'The outdoor coil is the evaporator. Refrigerant can absorb heat when it is colder than the outside air. The fan helps air cross the coil; the air leaving it is cooler.':'The outdoor coil is the condenser. It rejects both the heat removed from the room and the energy added by the compressor. The air leaving this unit is warmer.'],
pipes:['A closed refrigerant circuit','Two sealed refrigerant lines link the coils. They carry refrigerant, not air. Exposed copper here is an inspection aid; real installations insulate refrigerant lines as specified by the manufacturer.'],
compressor:['Pressure makes heat transfer possible','The compressor raises vapour pressure and temperature; it always compresses in the same direction. A reversing valve reroutes the circuit between seasons. An expansion device drops pressure before the evaporator. Internal placement here is schematic.']
}[state.part];}
function update(){const heat=state.mode==='heating',r=calculate();$('heating').setAttribute('aria-pressed',heat);$('cooling').setAttribute('aria-pressed',!heat);$('season').textContent=heat?'WINTER / HEATING':'SUMMER / COOLING';$('mode-title').textContent=heat?'Bring outside heat in.':'Move room heat outside.';$('mode-copy').textContent=heat?'Even cold outdoor air contains thermal energy. Refrigerant absorbs some of it, then the compressor raises its pressure and temperature so the indoor coil can warm the room.':'The indoor coil absorbs heat from the room. The compressor and outdoor coil release that heat outdoors, along with the electrical energy used to run the system.';
const electric=state.load/state.efficiency;const source=heat?state.load-electric:state.load;const result=heat?state.load:state.load+electric;$('source-label').textContent=heat?'Heat from outside':'Heat from room';$('delivery-label').textContent=heat?'Heat into room':'Heat to outdoors';for(const [id,value]of [['source-energy',source],['electric-energy',electric],['delivery-energy',result]])$(id).innerHTML=value.toFixed(2)+' <small>kW</small>';
$('eff-label').textContent=heat?'Split-system COP':'Split cooling efficiency (W/W)';$('eff-note').textContent=heat?'Useful heat ÷ electricity. Use an average appropriate to the season, not a best-case rating.':'Heat removed ÷ electricity, in W/W (not US Btu/Wh EER). Use a realistic average over operation.';document.querySelector('.mode-word').textContent=heat?'heating':'cooling';$('load-out').textContent=state.load.toFixed(1)+' kW';$('efficiency-out').textContent=state.efficiency.toFixed(1)+(heat?'':' W/W');$('compare-eff-wrap').hidden=heat;$('cooling-note').hidden=heat;
$('compare-label').textContent=heat?'HEATING / VERSUS ELECTRIC RESISTANCE':'COOLING / VERSUS ANOTHER AIR CONDITIONER';$('alternative-label').textContent=heat?'Resistance heater':'Alternative air conditioner';$('annual-saving').textContent=money(r.saving);$('saving-label').textContent=r.saving>=0?'less electricity cost per year':'more electricity cost per year';$('split-cost').textContent=money(r.splitCost)+'/year';$('alternative-cost').textContent=money(r.alternativeCost)+'/year';$('split-kwh').textContent=Math.round(r.split).toLocaleString('en-AU')+' kWh electricity / year';$('alternative-kwh').textContent=Math.round(r.alternative).toLocaleString('en-AU')+' kWh electricity / year';const max=Math.max(r.split,r.alternative,1);$('split-bar').style.width=r.split/max*100+'%';$('alternative-bar').style.width=r.alternative/max*100+'%';$('reduction').textContent=Math.abs(r.reduction).toFixed(0)+'%';$('reduction-label').textContent=r.reduction>=0?'less electricity':'more electricity';$('payback').textContent=r.payback===null?'No payback':r.payback===0?'No extra cost':r.payback>99?'>99 years':r.payback.toFixed(1)+' years';$('hourly').textContent='A$'+(electric*state.tariff).toFixed(2);$('cost-formula').textContent=`${state.load.toFixed(1)} kW × ${state.hours} h/day × ${state.days} days ÷ ${state.efficiency.toFixed(1)} × A$${state.tariff.toFixed(2)}/kWh = ${money(r.splitCost)}/year.`;
const p=partText();$('part-title').textContent=p[0];$('part-copy').textContent=p[1];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.part===state.part));$('cutaway').setAttribute('aria-pressed',state.cutaway);$('cutaway').textContent=state.cutaway?'Close covers':'Show inside';$('play').textContent=state.playing?'Pause flow':'Play flow';$('play').setAttribute('aria-pressed',state.playing);sceneAPI?.sync();physicsAPI?.sync();return r;}
function setMode(mode){state.mode=mode;update();}
$('heating').onclick=()=>setMode('heating');$('cooling').onclick=()=>setMode('cooling');$('cutaway').onclick=()=>{state.cutaway=!state.cutaway;update();};$('play').onclick=()=>{state.playing=!state.playing;update();};$('reset').onclick=()=>{state.part='indoor';state.cutaway=false;sceneAPI?.reset();update();};
document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{state.part=b.dataset.part;if(state.part==='compressor')state.cutaway=true;update();sceneAPI?.focus(state.part);});
for(const key of Object.keys(limits)){const el=$(key==='compareEff'?'compare-eff':key);el.addEventListener('input',()=>{if(el.value===''||!el.checkValidity())return;const value=Number(el.value);if(Number.isFinite(value)){state[key]=value;update();}});el.addEventListener('change',()=>{el.value=state[key];});}
$('reset-costs').onclick=()=>{Object.assign(state,{load:3.5,efficiency:4,hours:6,days:120,tariff:.3,capital:2500,compareEff:2.5});for(const k of Object.keys(limits))$(k==='compareEff'?'compare-eff':k).value=state[k];update();};
reduced.addEventListener('change',()=>{if(reduced.matches){state.playing=false;update();}});update();
async function initScene(){const THREE=await import('three');const {OrbitControls}=await import('./vendor/OrbitControls.js');const {RoundedBoxGeometry}=await import('./vendor/RoundedBoxGeometry.js');
const host=$('scene');const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0xe8eff3,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D split-system model; use component buttons for explanations and Reset view to restore the camera');renderer.domElement.tabIndex=0;
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xe8eff3,17,30);const camera=new THREE.PerspectiveCamera(36,1,.1,60);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=16;controls.maxPolarAngle=Math.PI*.49;controls.minPolarAngle=.25;controls.target.set(0,1.45,0);controls.zoomSpeed=.65;
scene.add(new THREE.HemisphereLight(0xe7f4ff,0x788999,2.4));const key=new THREE.DirectionalLight(0xfff7e9,3.2);key.position.set(-3,9,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-7,right:7,top:7,bottom:-7});key.shadow.normalBias=.03;scene.add(key);const fill=new THREE.DirectionalLight(0xbad8ee,1.3);fill.position.set(5,4,-4);scene.add(fill);
const mat=(color,roughness=.6,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const white=mat(0xf0f3f4,.35),edge=mat(0xc6d2d9),dark=mat(0x263845),metal=mat(0x8ba3b0,.35,.7),copper=mat(0xba764a,.34,.68),hot=mat(0xd47246,.5,.3),cold=mat(0x338fad,.5,.3);const model=new THREE.Group();scene.add(model);const covers=[];const coils=[];const fans=[];const targets={indoor:new THREE.Vector3(-1.9,2.65,.2),outdoor:new THREE.Vector3(2.2,.8,0),pipes:new THREE.Vector3(.5,1.9,-.05),compressor:new THREE.Vector3(2.85,.72,0)};
function box(w,h,d,m,x,y,z,round=.03,parent=model){const mesh=new THREE.Mesh(round?new RoundedBoxGeometry(w,h,d,3,round):new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function cylinder(r,h,m,x,y,z,parent=model){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o;}
function tube(points,m,r=.025){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)),false,'catmullrom',.1);const o=new THREE.Mesh(new THREE.TubeGeometry(curve,50,r,8,false),m);model.add(o);o.castShadow=true;return o;}
function label(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=88;const ctx=c.getContext('2d');ctx.fillStyle='#e8eff3';ctx.fillRect(0,0,512,88);ctx.fillStyle='#35576c';ctx.font='600 32px sans-serif';ctx.textAlign='center';ctx.fillText(tr(text),256,55);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;window.addEventListener('explainer-languagechange',()=>{ctx.fillStyle='#e8eff3';ctx.fillRect(0,0,512,88);ctx.fillStyle='#35576c';ctx.fillText(tr(text),256,55);tex.needsUpdate=true;dirty=true;wake();});const spr=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true}));spr.position.set(x,y,z);spr.scale.set(2.5,.43,1);scene.add(spr);return spr;}
box(7.5,.15,3.6,mat(0xcbd9e2),0,-.13,0,.08);box(3.6,3.6,.12,mat(0xd9e2e6),-1.9,1.7,-.49,.025);for(let x=-3.55;x<-.2;x+=.55)box(.009,3.4,.01,mat(0xc2d1da),x,1.7,-.42,0);
// Indoor unit: rounded shallow shell, separate front, open outlet, coil and louvres.
box(2.65,.80,.62,edge,-1.9,2.65,-.04,.14);box(2.47,.55,.12,dark,-1.9,2.69,.26,.06);const indoorCoil=box(2.3,.42,.13,hot,-1.9,2.76,.35,.025);coils.push(indoorCoil);for(let i=0;i<50;i++)box(.012,.41,.17,metal,-3.02+i*.045,2.76,.355,.002);const front=box(2.65,.60,.14,white,-1.9,2.77,.44,.085);covers.push(front);box(2.38,.12,.17,dark,-1.9,2.36,.31,.03);for(let i=0;i<12;i++)box(.014,.12,.15,edge,-2.98+i*.195,2.36,.40,.004);const flap=box(2.4,.035,.23,white,-1.9,2.31,.45,.015);flap.rotation.x=-.22;box(.1,.025,.007,mat(0x74b9a0),-1,2.63,.516,.002);
// Outdoor chassis, heat-exchanger fins, service compartment and guarded axial fan.
box(2.02,1.40,.07,edge,2.12,.79,-.53,.025);box(.07,1.40,.88,edge,1.14,.79,-.12,.025);box(.07,1.40,.88,edge,3.10,.79,-.12,.025);box(2.02,.08,.88,edge,2.12,.12,-.12,.025);const outdoorCoil=box(1.78,1.22,.15,cold,2.10,.83,-.61,.02);coils.push(outdoorCoil);for(let i=0;i<44;i++)box(.018,1.2,.12,metal,1.23+i*.04,.83,-.68,.002);for(const x of [1.44,2.8])box(.25,.16,1.01,dark,x,.03,-.12,.02);box(1.35,1.34,.04,dark,1.83,.80,.35,.01);const fan=new THREE.Group();fan.position.set(1.82,.83,.40);model.add(fan);fans.push(fan);for(let i=0;i<5;i++){const blade=box(.22,.43,.05,mat(0x52646e),0,.20,0,.09,fan);const pivot=new THREE.Group();fan.remove(blade);pivot.add(blade);pivot.rotation.z=i*Math.PI*2/5;fan.add(pivot);}const hub=cylinder(.13,.1,edge,1.82,.83,.49);hub.rotation.x=Math.PI/2;
for(let i=0;i<9;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.10+i*.049,.009,6,64),edge);ring.position.set(1.82,.83,.51);model.add(ring);}for(let i=0;i<12;i++){const angle=i*Math.PI/6;const bar=box(.012,1.01,.014,edge,1.82,.83,.52,.003);bar.rotation.z=angle;}
const service=box(.50,1.36,.08,white,2.85,.80,.42,.03);covers.push(service);box(2.08,.12,1.02,white,2.12,1.51,-.12,.03);for(let i=0;i<7;i++)box(.3,.018,.012,edge,2.85,1.26-i*.06,.466,.003);for(const x of [1.15,3.08])for(const y of [.16,1.41]){const screw=cylinder(.017,.014,metal,x,y,.452);screw.rotation.x=Math.PI/2;}
const compressor=cylinder(.17,.64,dark,2.85,.55,.11);cylinder(.19,.07,metal,2.85,.23,.11);const valve=cylinder(.07,.32,copper,2.76,1.09,.08);valve.rotation.z=Math.PI/2;box(.16,.12,.13,dark,2.82,1.19,.09,.012);const expansion=box(.12,.16,.14,copper,2.6,.4,.1,.025);
const pipes=[];pipes.push(tube([[-.57,2.58,-.12],[-.30,2.57,-.12],[-.03,2.4,-.12],[.05,1.82,-.12],[.34,1.65,-.12],[2.78,1.65,-.12],[3.22,1.4,-.12],[3.24,.75,-.12],[2.85,.85,.10]],copper,.038));pipes.push(tube([[-.58,2.36,-.12],[-.34,2.33,-.12],[-.23,2.04,-.12],[-.15,1.58,-.12],[.2,1.43,-.12],[2.5,1.43,-.12],[2.6,.4,.1]],copper,.025));tube([[2.85,.88,.1],[2.88,1.05,.1],[2.6,1.1,.1]],copper,.026);
label('INDOORS',-1.9,3.75,0);label('OUTDOORS',2.12,2.13,.2);
const arrows=[];const indoorFlowMat=mat(0xcd633b,.45),outdoorFlowMat=mat(0x2687aa,.45);function arrow(x,z,material,inside){const g=new THREE.Group();const shaft=cylinder(.012,.43,material,0,0,0,g);shaft.rotation.x=Math.PI/2;const head=new THREE.Mesh(new THREE.ConeGeometry(.055,.14,12),material);head.rotation.x=Math.PI/2;head.position.z=.27;g.add(head);g.userData={x,z,inside};g.position.set(x,inside?2.1:.80,z);scene.add(g);arrows.push(g);}
for(let i=0;i<4;i++){arrow(-2.7+i*.53,.7+i*.1,indoorFlowMat,true);arrow(1.3+i*.32,.8+i*.13,outdoorFlowMat,false);}
let flowTime=0,last=0,raf=0,visible=true,dirty=true;const render=()=>{renderer.render(scene,camera);};function reset(){camera.position.set(8,5.3,11);controls.target.set(0,1.65,0);controls.update();dirty=true;wake();}function sync(){const heat=state.mode==='heating';indoorCoil.material=heat?hot:cold;outdoorCoil.material=heat?cold:hot;indoorFlowMat.color.set(heat?0xcd633b:0x2687aa);outdoorFlowMat.color.set(heat?0x2687aa:0xcd633b);covers.forEach(c=>c.visible=!state.cutaway);for(const p of pipes)p.material=state.part==='pipes'?hot:copper;compressor.material=state.part==='compressor'?hot:dark;dirty=true;wake();}
function focus(part){if(part==='compressor'){controls.target.set(1.7,1,.1);camera.position.set(5,3.2,6.5);}else if(part==='indoor'){controls.target.set(-1.1,2,.1);camera.position.set(4,4,9);}else reset();controls.update();dirty=true;wake();}
function frame(now){raf=0;if(!visible||document.hidden)return;const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(state.playing){flowTime+=dt;fans.forEach(f=>f.rotation.z-=dt*3);dirty=true;}arrows.forEach((a,i)=>{const t=(flowTime*.35+i*.21)%1;a.position.z=a.userData.z+t*.75;a.position.y=a.userData.inside?2.17-t*.6:.80;a.scale.setScalar(.65+Math.sin(t*Math.PI)*.35);});if(dirty){render();dirty=false;}if(state.playing)raf=requestAnimationFrame(frame);}
function wake(){if(!raf&&visible&&!document.hidden){last=0;raf=requestAnimationFrame(frame);}}controls.addEventListener('change',()=>{dirty=true;wake();});const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();dirty=true;wake();}});resize.observe(host);const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){dirty=true;wake();}},{threshold:0});observer.observe(host);document.addEventListener('visibilitychange',wake);renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();$('fallback').hidden=false;host.hidden=true;state.playing=false;update();});renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home'){e.preventDefault();reset();}});sceneAPI={sync,reset,focus};reset();sync();}
physicsAPI=initPhysics({getState:()=>state,setMode,showPart(part){state.part=part;state.cutaway=true;update();sceneAPI?.focus(part);}});
initScene().catch(error=>{console.error('3D unavailable',error);$('fallback').hidden=false;$('scene').hidden=true;$('cutaway').disabled=true;$('play').disabled=true;$('reset').disabled=true;});
// Optional page-scoped tool, using exactly the visible calculator state.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_energy_comparison',title:'Configure energy comparison',description:'Set heating or cooling and calculator inputs, update visible results, and return annual electricity, cost and simple payback.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['heating','cooling']},...Object.fromEntries(Object.entries(limits).map(([k,[min,max]])=>[k,{type:'number',minimum:min,maximum:max}]))},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('An object is required');for(const[k,v]of Object.entries(input)){if(k==='mode'){if(!['heating','cooling'].includes(v))throw new Error('Invalid mode');}else if(!limits[k]||typeof v!=='number'||!Number.isFinite(v)||v<limits[k][0]||v>limits[k][1]||(k==='days'&&!Number.isInteger(v)))throw new Error('Invalid '+k);}Object.assign(state,input);for(const k of Object.keys(limits))$(k==='compareEff'?'compare-eff':k).value=state[k];return {mode:state.mode,...update()};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
