import {tr} from './i18n.js';
import {thermoData} from './thermo-data.js';

export function cycleValues(te,tc,mode,load){
  const row=thermoData.rows[`${te},${tc}`];
  if(!row)throw new RangeError('Unsupported saturation temperatures');
  const [pl,ph,h1,h2,h3,t2,x4]=row;
  const work=h2-h1,absorbed=h1-h3,rejected=h2-h3;
  const useful=mode==='heating'?rejected:absorbed;
  return {te,tc,pl,ph,h1,h2,h3,h4:h3,t1:te+5,t2,t3:tc-3,t4:te,x4,work,absorbed,rejected,cop:useful/work,mass:load/useful,power:load*work/useful,ratio:ph/pl,carnot:(mode==='heating'?tc+273.15:te+273.15)/(tc-te)};
}

export function chamberGeometry(degrees,segments=120){
  const theta=degrees*Math.PI/180,R=1.25,r=.82,e=R-r,cx=e*Math.cos(theta),cy=e*Math.sin(theta);
  const inner=a=>e*Math.cos(a-theta)+Math.sqrt(Math.max(0,r*r-e*e*Math.sin(a-theta)**2));
  const points=(a,b)=>{const p=[];for(let i=0;i<=segments;i++){const t=a+(b-a)*i/segments;p.push([R*Math.cos(t),R*Math.sin(t)]);}for(let i=segments;i>=0;i--){const t=a+(b-a)*i/segments,q=inner(t);p.push([q*Math.cos(t),q*Math.sin(t)]);}return p;};
  const suction=points(0,theta),compression=points(theta,Math.PI*2);
  const area=p=>Math.abs(p.reduce((v,a,i)=>{const b=p[(i+1)%p.length];return v+a[0]*b[1]-b[0]*a[1];},0))/2;
  return {cx,cy,tip:inner(0),suction,compression,suctionArea:area(suction),compressionArea:area(compression),total:Math.PI*(R*R-r*r)};
}

export function initPhysics({getState,setMode,showPart}){
  const section=document.createElement('section');section.id='engineering';section.className='engineering';
  section.innerHTML=`<div class="section-heading"><div><p class="eyebrow">02 / INSIDE THE ENGINEERING</p><h2>Follow the refrigerant.<br>See what changes.</h2></div><p>Pressure sets the boiling temperature. Phase change carries heat. A compressor supplies the work that keeps the cycle going.</p></div>
  <div class="engineering-toolbar"><div class="mechanism-tabs" role="tablist" aria-label="Engineering mechanisms"><button role="tab" id="tab-cycle" aria-controls="panel-cycle" aria-selected="true">Refrigerant cycle</button><button role="tab" id="tab-rotary" aria-controls="panel-rotary" aria-selected="false" tabindex="-1">Inside the compressor</button><button role="tab" id="tab-reverse" aria-controls="panel-reverse" aria-selected="false" tabindex="-1">Reversing & defrost</button></div><div class="segmented"><button id="engineering-heat" aria-pressed="true">☀ Heating</button><button id="engineering-cool" aria-pressed="false">❄ Cooling</button></div></div>
  <div id="panel-cycle" role="tabpanel" aria-labelledby="tab-cycle"><div class="cycle-grid"><div class="cycle-left"><div class="mini-heading"><h3>A closed loop, four processes</h3><span id="cycle-role-note"></span></div><div id="cycle-diagram" class="diagram-surface"></div><div class="cycle-steps" aria-label="Choose a process"><button data-cycle-step="0" aria-pressed="true">1 → 2 · Compress</button><button data-cycle-step="1" aria-pressed="false">2 → 3 · Condense</button><button data-cycle-step="2" aria-pressed="false">3 → 4 · Expand</button><button data-cycle-step="3" aria-pressed="false">4 → 1 · Evaporate</button></div><div class="process-detail" aria-live="polite"><p class="eyebrow" id="process-tag"></p><h3 id="process-title"></h3><p id="process-copy"></p><p class="process-equation" id="process-equation"></p></div><button id="locate-process" class="text-button">Locate this part in the system ↑</button></div>
  <div class="cycle-right"><div class="mini-heading"><h3>Pressure–enthalpy diagram</h3><span>R32 · absolute pressure</span></div><div id="ph-chart" class="ph-chart"></div><p class="caption">The shaded dome is liquid + vapour. Left of it is liquid; right is vapour. Straight links join calculated states; they are not resolved compressor trajectories. Coil pressure drops are neglected.</p><div class="state-table-wrap"><table class="state-table"><thead><tr><th>State</th><th>Pressure<br><small>bar abs</small></th><th>Temperature<br><small>°C</small></th><th>Enthalpy<br><small>kJ/kg</small></th></tr></thead><tbody id="state-rows"></tbody></table></div></div></div>
  <div class="temperature-lab"><div><p class="eyebrow">TRY A LARGER TEMPERATURE LIFT</p><h3>Make the cold coil colder.</h3><p>Lower the evaporation temperature while holding condensation fixed. The pressure ratio and work per kilogram rise; the cycle COP falls.</p><p class="caption">These are refrigerant saturation temperatures, not outdoor temperature or the thermostat setting. Air must be warmer than the evaporating refrigerant and cooler than the condensing refrigerant for the intended heat transfer.</p></div><div class="temperature-controls"><label for="evap-temp">Evaporation temperature <output id="evap-out">0 °C</output></label><input id="evap-temp" type="range" min="-15" max="15" step="5" value="0"><label for="cond-temp">Condensation temperature <output id="cond-out">40 °C</output></label><input id="cond-temp" type="range" min="30" max="55" step="5" value="40"><div class="cycle-metrics" aria-live="polite"><div><strong id="cycle-cop"></strong><span id="cycle-cop-label">heating cycle COP</span></div><div><strong id="pressure-ratio"></strong><span>pressure ratio</span></div><div><strong id="shaft-power"></strong><span id="shaft-label">compressor work</span></div></div><p class="caption" id="mass-rate"></p></div></div>
  <details class="model-details"><summary>What the cycle model includes — and what it leaves out</summary><p>Properties are calculated with CoolProp 8.0.0 (HEOS R32), using 5 K suction superheat, 3 K liquid subcooling and 70% compressor isentropic efficiency. Expansion is adiabatic throttling at constant enthalpy; heat exchangers have no pressure loss. The table has 42 exact temperature pairs, with no interpolation.</p><p>The cycle COP is useful refrigerant heat divided by compressor work, excluding motor losses, fans, controls, piping losses, cycling and defrost. It is not a product rating or seasonal COP. The running-cost calculator retains your separate efficiency assumption. Its useful load is shared with this model to convert kJ/kg into kW.</p><p id="carnot-note"></p><p>Enthalpy is a flowing fluid’s energy measure including pressure–volume work. Differences in enthalpy matter here; the reference zero is conventional. Refrigerant names do not prescribe safe servicing procedures.</p></details>
  <div class="physics-notes"><article><h3>Superheat protects the compressor</h3><p>After boiling finishes, further heating raises vapour above its saturation temperature. This model adds 5 K; it does not send liquid to the compressor.</p></article><article><h3>Subcooling preserves a liquid supply</h3><p>After condensation, further cooling lowers liquid below its saturation temperature. Here it is 3 K cooler before the expansion device.</p></article><article><h3>Fins make air-side heat transfer practical</h3><p>Fins increase area; fans move air across them. Roughly, heat flow grows with UA × temperature difference: U captures thermal resistance and A is exchange area. More resistance demands a larger temperature gap for the same heat flow.</p></article></div></div>
  <div id="panel-rotary" role="tabpanel" aria-labelledby="tab-rotary" hidden><div class="rotary-grid"><div class="rotary-surface"><div class="mini-heading"><span>ROLLING-PISTON COMPRESSOR</span><span>Open inspection view</span></div><div id="rotary-scene" aria-label="3D rolling-piston compressor cutaway"></div><div id="rotary-fallback" hidden>3D is unavailable. The shaft moves an eccentric roller against a sliding vane, growing a suction pocket while shrinking a compression pocket.</div><div class="rotary-controls"><label for="rotary-angle">Shaft angle <output id="rotary-angle-out">160°</output></label><input id="rotary-angle" type="range" min="1" max="359" step="1" value="160"><div class="rotary-play-row"><button id="rotary-play" aria-pressed="false">Play one revolution</button><span id="rotary-volume"></span></div><p class="caption" id="rotary-phase"></p></div><div class="rotary-view-buttons"><button id="rotary-overhead">Top view</button><button id="rotary-perspective">Angled view</button><button id="rotary-reset">Reset view</button></div></div><div class="rotary-copy"><p class="eyebrow">ROTATION → SMALLER VOLUME → COMPRESSION</p><h3>A moving seal makes two pockets.</h3><p>The eccentric shaft moves the roller around the cylinder. A sliding vane separates the growing suction pocket from the shrinking compression pocket. Oil films seal the tiny clearances.</p><div class="pocket-legend"><span><i class="suction-swatch"></i>Suction pocket · filling</span><span><i class="compression-swatch"></i>Compression pocket · shrinking</span></div><h4>Why does the vapour get hot?</h4><p>Work done on trapped vapour increases its energy. The discharge reed opens once chamber pressure exceeds discharge pressure. Compression continues to push gas out; pressure does not grow without limit.</p><h4>What the model shows</h4><p class="caption">Single-cylinder teaching geometry based on a rolling-piston mechanism, not a particular product. The top plate is removed; the motor and outer shell are omitted. Pocket colours identify geometry, not computed pressure. Scrubbing is slow inspection motion, not operating RPM. Port timing, clearances, oil, leakage and reed dynamics are not simulated. Some split systems instead use scroll or other compressors.</p><p class="caption">An inverter varies motor speed to change refrigerant throughput. Capacity and efficiency still depend on pressure ratio, flow and losses; doubling speed does not guarantee twice the COP.</p></div></div></div>
  <div id="panel-reverse" role="tabpanel" aria-labelledby="tab-reverse" hidden><div class="reverse-grid"><div><div class="mini-heading"><h3>The four-way valve</h3><span>Functional connection map</span></div><div id="valve-diagram"></div><p class="caption">Two separate passages reroute discharge and suction. This map shows connections, not the physical shape of the valve spool.</p><div class="defrost-controls"><button id="defrost-toggle" aria-pressed="false">Show a defrost interval</button><span id="defrost-state">Normal operation</span></div></div><div class="reverse-copy" aria-live="polite"><p class="eyebrow" id="reverse-tag"></p><h3 id="reverse-title"></h3><p id="reverse-path"></p><div class="coil-role-list"><div><span>Indoor coil</span><strong id="reverse-indoor"></strong></div><div><span>Outdoor coil</span><strong id="reverse-outdoor"></strong></div></div><p id="reverse-detail"></p><h4>The expansion device still belongs before the evaporator.</h4><p>Reverse-cycle systems use suitable bidirectional metering or arrangements of metering and check valves. The four-way valve alone does not perform expansion.</p><p class="caption" id="defrost-note">The compressor always draws vapour into suction and pushes it out through discharge. The coil connections change; the compressor does not run backwards.</p></div></div></div>`;
  document.getElementById('costs').before(section);
  const $=id=>section.querySelector('#'+id);const local={te:0,tc:40,step:0,tab:'cycle',angle:160,playing:false,defrost:false};let rotary=null;
  const fmt=(n,d=1)=>n.toFixed(d);const ns='http://www.w3.org/2000/svg';
  const svgEl=(tag,attrs={},text='')=>{const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;};
  function svgRoot(host,height,label){const width=Math.max(280,host.clientWidth);host.replaceChildren();const svg=svgEl('svg',{viewBox:`0 0 ${width} ${height}`,width:'100%',height,role:'img','aria-label':label});host.append(svg);return {svg,w:width};}
  function text(svg,x,y,value,cls='',anchor='middle'){svg.append(svgEl('text',{x,y,class:cls,'text-anchor':anchor},value));}
  function arrow(svg,x1,y1,x2,y2,color,active=false){svg.append(svgEl('path',{d:`M${x1},${y1} L${x2},${y2}`,fill:'none',stroke:color,'stroke-width':active?4:2.5}));const a=Math.atan2(y2-y1,x2-x1),x=(x1+x2)/2,y=(y1+y2)/2;svg.append(svgEl('path',{d:`M${x-8*Math.cos(a-.5)},${y-8*Math.sin(a-.5)} L${x},${y} L${x-8*Math.cos(a+.5)},${y-8*Math.sin(a+.5)}`,fill:'none',stroke:color,'stroke-width':2.5}));}
  const colours=['#c3582c','#bd7a39','#247f89','#2279a0'];
  function cycleDiagram(v){const heat=getState().mode==='heating';const {svg,w}=svgRoot($('cycle-diagram'),300,'Closed refrigerant loop. Vapour is compressed, condensed to liquid, throttled to a mixture, then evaporated back to vapour.');const left=w*.245,right=w*.755,top=75,bottom=228,bw=Math.min(150,w*.43),bh=66;
    arrow(svg,left+bw/2,top,right-bw/2,top,colours[0],local.step===0);arrow(svg,right,top+bh/2,right,bottom-bh/2,colours[1],local.step===1);arrow(svg,right-bw/2,bottom,left+bw/2,bottom,colours[2],local.step===2);arrow(svg,left,bottom-bh/2,left,top+bh/2,colours[3],local.step===3);
    const nodes=[[left,top,'Compressor','Vapour → vapour'],[right,top,'Condenser',heat?'Indoor coil':'Outdoor coil'],[right,bottom,'Expansion device','Liquid → mixture'],[left,bottom,'Evaporator',heat?'Outdoor coil':'Indoor coil']];
    nodes.forEach(([x,y,title,sub],i)=>{svg.append(svgEl('rect',{x:x-bw/2,y:y-bh/2,width:bw,height:bh,rx:8,fill:local.step===i?'#183e52':'#f0f5f8',stroke:local.step===i?'#183e52':'#ccd9e1'}));text(svg,x,y-4,title,local.step===i?'node-title selected':'node-title');text(svg,x,y+17,sub,local.step===i?'node-sub selected':'node-sub');});
    text(svg,w/2,17,'2 · HIGH-PRESSURE VAPOUR','state-label');text(svg,w/2,292,'4 · LOW-PRESSURE MIXTURE','state-label');text(svg,w/2,143,`${fmt(v.ph)} bar high side`,'diagram-pressure');text(svg,w/2,166,`${fmt(v.pl)} bar low side`,'diagram-pressure');
  }
  function phChart(v){const {svg,w}=svgRoot($('ph-chart'),300,`R32 pressure versus specific enthalpy. Low pressure ${fmt(v.pl)} bar, high pressure ${fmt(v.ph)} bar. Selected process ${local.step+1}.`);const L=54,R=w-19,T=18,B=247;const hs=thermoData.dome.flatMap(d=>[d[2],d[3]]).concat([v.h1,v.h2,v.h3]);const hmin=Math.floor((Math.min(...hs)-15)/50)*50,hmax=Math.ceil((Math.max(...hs)+15)/50)*50;const ps=thermoData.dome.map(d=>d[1]).concat([v.pl,v.ph]);const pmin=Math.min(...ps)*.9,pmax=Math.max(...ps)*1.08;const x=h=>L+(h-hmin)/(hmax-hmin)*(R-L),y=p=>B-(Math.log(p)-Math.log(pmin))/(Math.log(pmax)-Math.log(pmin))*(B-T);
    svg.append(svgEl('rect',{x:L,y:T,width:R-L,height:B-T,fill:'none',stroke:'#d4dfe5'}));
    for(const p of [2,5,10,20,50])if(p>pmin&&p<pmax){svg.append(svgEl('line',{x1:L,y1:y(p),x2:R,y2:y(p),stroke:'#e0e8ed'}));text(svg,L-8,y(p)+4,p,'tick','end');}
    const ticks=w<420?3:5;for(let i=0;i<ticks;i++){const h=hmin+(hmax-hmin)*i/(ticks-1);text(svg,x(h),B+20,Math.round(h),'tick',i===0?'start':i===ticks-1?'end':'middle');}
    text(svg,(L+R)/2,294,'Specific enthalpy h (kJ/kg)','axis-title');const yl=svgEl('text',{transform:`translate(14 ${(T+B)/2}) rotate(-90)`,'text-anchor':'middle',class:'axis-title'},'Pressure (bar abs · log scale)');svg.append(yl);
    const dome=thermoData.dome;const path=dome.map((d,i)=>`${i?'L':'M'}${x(d[2])},${y(d[1])}`).join(' ')+dome.slice().reverse().map(d=>` L${x(d[3])},${y(d[1])}`).join(' ')+' Z';svg.append(svgEl('path',{d:path,fill:'#c7dbe64d',stroke:'#98b5c4','stroke-width':1}));
    const points=[[v.h1,v.pl],[v.h2,v.ph],[v.h3,v.ph],[v.h4,v.pl]];points.forEach((p,i)=>{const q=points[(i+1)%4];arrow(svg,x(p[0]),y(p[1]),x(q[0]),y(q[1]),colours[i],local.step===i);});
    points.forEach(([h,p],i)=>{svg.append(svgEl('circle',{cx:x(h),cy:y(p),r:11,fill:'#fff',stroke:colours[i],'stroke-width':2}));text(svg,x(h),y(p)+4,String(i+1),'state-number');});
  }
  function renderCycle(){const shared=getState(),heat=shared.mode==='heating';const v=cycleValues(local.te,local.tc,shared.mode,shared.load);$('cycle-role-note').textContent=heat?'Useful heat: condenser':'Useful cooling: evaporator';
    const steps=[['WORK IN','Compress the vapour.','The compressor raises pressure and enthalpy. The outlet is hot, superheated vapour. Motor work makes the refrigerant hot enough to reject heat at the condenser.',`w = h₂ − h₁ = ${fmt(v.work)} kJ/kg`],['HEAT OUT',`Condense in the ${heat?'indoor':'outdoor'} coil.`,'The refrigerant first cools to saturation, then releases heat while condensing. This model cools the resulting liquid another 3 K before it leaves.',`qₕ = h₂ − h₃ = ${fmt(v.rejected)} kJ/kg`],['PRESSURE DROP','Throttle; do not extract work.',`Pressure drops through a restriction. Some liquid flashes into vapour; the two-phase mixture settles at the lower saturation temperature. Here ${fmt(v.x4*100)}% of its mass is vapour.`, `h₄ = h₃ = ${fmt(v.h3)} kJ/kg`],['HEAT IN',`Boil in the ${heat?'outdoor':'indoor'} coil.`,'The cold mixture absorbs heat as liquid evaporates. At roughly constant pressure, phase change carries energy without a large temperature rise. After evaporation, the vapour gains 5 K of superheat.',`q꜀ = h₁ − h₄ = ${fmt(v.absorbed)} kJ/kg`]];const step=steps[local.step];$('process-tag').textContent=step[0];$('process-title').textContent=step[1];$('process-copy').textContent=step[2];$('process-equation').textContent=step[3];section.querySelectorAll('[data-cycle-step]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.cycleStep===local.step));
    $('state-rows').innerHTML=[[1,v.pl,v.t1,v.h1,'Superheated vapour'],[2,v.ph,v.t2,v.h2,'Superheated vapour'],[3,v.ph,v.t3,v.h3,'Subcooled liquid'],[4,v.pl,v.t4,v.h4,'Liquid + vapour']].map(([n,p,t,h,phase])=>`<tr class="${n===local.step+1?'active-state':''}"><th>${n}<span>${phase}</span></th><td>${fmt(p)}</td><td>${fmt(t)}</td><td>${fmt(h)}</td></tr>`).join('');
    $('evap-out').textContent=local.te+' °C';$('cond-out').textContent=local.tc+' °C';$('cycle-cop').textContent=fmt(v.cop,2);$('cycle-cop-label').textContent=(heat?'heating':'cooling')+' cycle COP';$('pressure-ratio').textContent=fmt(v.ratio,2)+' : 1';$('shaft-power').textContent=fmt(v.power,2)+' kW';$('shaft-label').textContent='compressor work rate';$('mass-rate').textContent=`At the calculator’s ${fmt(shared.load)} kW useful ${heat?'heating':'cooling'} load: ${fmt(v.mass*1000,1)} g/s refrigerant. These are steady-cycle values, not mains electricity or annual consumption.`;
    $('carnot-note').textContent=`For an ideal reversed Carnot cycle between these saturation temperatures, COP${heat?'ₕ':'꜀'} = ${heat?'Tₕ':'T꜀'} / (Tₕ − T꜀) = ${fmt(v.carnot,2)}, with temperatures in kelvin. This is an ideal reference at a ${local.tc-local.te} K lift, not an installed-system prediction. Our superheated/subcooled cycle exchanges heat over a range of temperatures.`;
    if(local.tab==='cycle'){cycleDiagram(v);phChart(v);}return v;
  }
  function valveDiagram(){const shared=getState(),heat=shared.mode==='heating'&&!local.defrost;const {svg,w}=svgRoot($('valve-diagram'),340,heat?'Valve connects compressor discharge to indoor coil and outdoor coil to suction.':'Valve connects compressor discharge to outdoor coil and indoor coil to suction.');const cx=w/2,cy=166,rx=Math.min(130,w*.29),ry=90;
    svg.append(svgEl('rect',{x:cx-rx,y:cy-ry,width:2*rx,height:2*ry,rx:18,fill:'#eef4f7',stroke:'#b8cdd9'}));const hotPath=heat?`M${cx},${cy-ry} Q${cx},${cy} ${cx-rx},${cy}`:`M${cx},${cy-ry} Q${cx},${cy} ${cx+rx},${cy}`;const coldPath=heat?`M${cx+rx},${cy} Q${cx},${cy} ${cx},${cy+ry}`:`M${cx-rx},${cy} Q${cx},${cy} ${cx},${cy+ry}`;
    svg.append(svgEl('path',{d:hotPath,fill:'none',stroke:colours[0],'stroke-width':9}));svg.append(svgEl('path',{d:coldPath,fill:'none',stroke:colours[3],'stroke-width':9}));text(svg,cx,23,'FROM COMPRESSOR DISCHARGE','valve-label');text(svg,cx,43,'Hot, high-pressure vapour','node-sub');arrow(svg,cx,51,cx,cy-ry,colours[0]);arrow(svg,cx,cy+ry,cx,292,colours[3]);text(svg,cx,314,'TO COMPRESSOR SUCTION','valve-label');text(svg,cx,335,'Low-pressure vapour','node-sub');text(svg,cx-rx,cy-20,'INDOOR','valve-label');text(svg,cx+rx,cy-20,'OUTDOOR','valve-label');arrow(svg,heat?cx-rx:cx-rx-25,cy,heat?cx-rx-25:cx-rx,cy,heat?colours[0]:colours[3]);arrow(svg,heat?cx+rx+25:cx+rx,cy,heat?cx+rx:cx+rx+25,cy,heat?colours[3]:colours[0]);
  }
  function renderReverse(){const shared=getState();if(shared.mode==='cooling')local.defrost=false;const heat=shared.mode==='heating'&&!local.defrost;$('reverse-tag').textContent=local.defrost?'TEMPORARY DEFROST':heat?'HEATING CONNECTIONS':'COOLING CONNECTIONS';$('reverse-title').textContent=local.defrost?'Send hot refrigerant to the frosted coil.':'Swap the coils, keep compression direction.';$('reverse-path').textContent=heat?'Discharge → indoor condenser → expansion device → outdoor evaporator → suction.':'Discharge → outdoor condenser → expansion device → indoor evaporator → suction.';$('reverse-indoor').textContent=heat?'Condenser · releases heat':'Evaporator · absorbs heat';$('reverse-outdoor').textContent=heat?'Evaporator · absorbs heat':'Condenser · releases heat';$('reverse-detail').textContent=local.defrost?'In reverse-cycle defrost, hot refrigerant warms the outdoor coil to melt frost. Outdoor fan operation is typically stopped; indoor airflow may stop to avoid a cold draught. Normal heating resumes after defrost. Exact controls vary by product.':'The high-pressure discharge goes to whichever coil must reject heat. The return from the other coil goes to compressor suction. Refrigerant still passes through compression, condensation, expansion and evaporation.';$('defrost-toggle').disabled=shared.mode==='cooling';$('defrost-toggle').textContent=local.defrost?'Return to normal heating':'Show a defrost interval';$('defrost-toggle').setAttribute('aria-pressed',local.defrost);$('defrost-state').textContent=local.defrost?'Defrost illustration':shared.mode==='cooling'?'Defrost applies during heating':'Normal operation';$('defrost-note').textContent=local.defrost?'This interval is a functional illustration. The overview and annual calculator remain in normal heating; defrost frequency and energy penalty are not estimated.':'The compressor always draws vapour into suction and pushes it out through discharge. The coil connections change; the compressor does not run backwards.';if(local.tab==='reverse')valveDiagram();}
  function sync(){const heat=getState().mode==='heating';$('engineering-heat').setAttribute('aria-pressed',heat);$('engineering-cool').setAttribute('aria-pressed',!heat);renderCycle();renderReverse();}
  function switchTab(tab){local.tab=tab;local.playing=false;for(const name of ['cycle','rotary','reverse']){$('tab-'+name).setAttribute('aria-selected',name===tab);$('tab-'+name).tabIndex=name===tab?0:-1;$('panel-'+name).hidden=name!==tab;}if(tab==='rotary'&&!rotary){rotary={pending:true};initRotary($,local,()=>rotaryUI()).then(api=>{rotary=api;api.sync();}).catch(error=>{$('rotary-fallback').hidden=false;$('rotary-scene').hidden=true;$('rotary-play').disabled=true;console.error(error);});}rotaryUI();rotary?.sync?.();sync();}
  section.querySelectorAll('[role=tab]').forEach((button,i)=>{button.onclick=()=>switchTab(button.id.slice(4));button.onkeydown=e=>{const names=['cycle','rotary','reverse'];let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();switchTab(names[next]);$('tab-'+names[next]).focus();}};});
  $('engineering-heat').onclick=()=>setMode('heating');$('engineering-cool').onclick=()=>setMode('cooling');section.querySelectorAll('[data-cycle-step]').forEach(b=>b.onclick=()=>{local.step=+b.dataset.cycleStep;renderCycle();});
  $('locate-process').onclick=()=>{const heat=getState().mode==='heating';showPart(local.step===0||local.step===2?'compressor':local.step===1?(heat?'indoor':'outdoor'):(heat?'outdoor':'indoor'));document.querySelector('.lab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
  $('evap-temp').oninput=e=>{local.te=+e.target.value;renderCycle();};$('cond-temp').oninput=e=>{local.tc=+e.target.value;renderCycle();};$('defrost-toggle').onclick=()=>{local.defrost=!local.defrost;renderReverse();};
  function rotaryUI(){const geo=chamberGeometry(local.angle);$('rotary-angle-out').textContent=Math.round(local.angle)+'°';$('rotary-angle').value=Math.round(local.angle);$('rotary-play').textContent=local.playing?'Pause revolution':'Play one revolution';$('rotary-play').setAttribute('aria-pressed',local.playing);$('rotary-volume').textContent=fmt(100*geo.compressionArea/geo.total,0)+'% of swept volume in compression pocket';$('rotary-phase').textContent=local.angle<90?'Early in the revolution: the suction pocket opens and fills. The other pocket contains vapour from the preceding revolution.':local.angle<240?'The vane tracks the eccentric roller. Suction volume grows while the trapped pocket becomes smaller.':'Late in the revolution: the remaining compression pocket is small. In a working unit, discharge begins when its pressure overcomes the outlet pressure.';}
  $('rotary-angle').oninput=e=>{local.playing=false;local.angle=+e.target.value;rotaryUI();rotary?.sync?.();};$('rotary-play').onclick=()=>{if(!local.playing&&local.angle>=358)local.angle=1;local.playing=!local.playing;rotaryUI();rotary?.sync?.();};for(const [id,view]of [['rotary-overhead','top'],['rotary-perspective','angle'],['rotary-reset','angle']])$(id).onclick=()=>rotary?.view?.(view);
  const resize=new ResizeObserver(()=>{if(local.tab==='cycle'){const s=getState(),v=cycleValues(local.te,local.tc,s.mode,s.load);cycleDiagram(v);phChart(v);}else if(local.tab==='reverse')valveDiagram();});resize.observe(section);sync();rotaryUI();
  // Expose the same controls to supported agent-enabled browsers.
  if(document.modelContext?.registerTool){const abort=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'explore_refrigerant_physics',title:'Explore refrigerant physics',description:'Select the mechanism, process, R32 saturation temperatures, or compressor angle and return the cycle calculation shown on the page.',inputSchema:{type:'object',properties:{tab:{enum:['cycle','rotary','reverse']},step:{type:'integer',minimum:0,maximum:3},evaporationC:{type:'integer',enum:[-15,-10,-5,0,5,10,15]},condensationC:{type:'integer',enum:[30,35,40,45,50,55]},shaftAngle:{type:'integer',minimum:1,maximum:359}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Object required');for(const[k,v]of Object.entries(input)){if(k==='tab'){if(!['cycle','rotary','reverse'].includes(v))throw new Error('Invalid tab');}else if(k==='step'){if(!Number.isInteger(v)||v<0||v>3)throw new Error('Invalid step');}else if(k==='shaftAngle'){if(!Number.isInteger(v)||v<1||v>359)throw new Error('Invalid angle');}else if(k==='evaporationC'){if(![-15,-10,-5,0,5,10,15].includes(v))throw new Error('Invalid evaporation temperature');}else if(k==='condensationC'){if(![30,35,40,45,50,55].includes(v))throw new Error('Invalid condensation temperature');}else throw new Error('Unknown field');}if(input.step!==undefined)local.step=input.step;if(input.evaporationC!==undefined)local.te=input.evaporationC;if(input.condensationC!==undefined)local.tc=input.condensationC;if(input.shaftAngle!==undefined){local.angle=input.shaftAngle;local.playing=false;}$('evap-temp').value=local.te;$('cond-temp').value=local.tc;if(input.tab)switchTab(input.tab);rotaryUI();rotary?.sync?.();return {tab:local.tab,step:local.step,shaftAngle:local.angle,...renderCycle()};}},{signal:abort.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>abort.abort(),{once:true});}
  return {sync};
}

async function initRotary($,local,onFrame){
  const THREE=await import('three');const {OrbitControls}=await import('./vendor/OrbitControls.js');const host=$('rotary-scene');
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0xe8eff3);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Rolling-piston compressor: roller, vane and coloured suction and compression pockets. Use angle slider for keyboard inspection.');
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.05,30);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=4.5;controls.maxDistance=10;controls.minPolarAngle=.01;controls.maxPolarAngle=Math.PI*.46;controls.target.set(.15,0,0);scene.add(new THREE.HemisphereLight(0xeaf7ff,0x758a96,2.5));const light=new THREE.DirectionalLight(0xfff3e3,3);light.position.set(3,7,5);scene.add(light);const fill=new THREE.DirectionalLight(0xc8e7ff,1.5);fill.position.set(-4,2,-2);scene.add(fill);
  const material=(c,metalness=.5,roughness=.35)=>new THREE.MeshStandardMaterial({color:c,metalness,roughness});const steel=material(0x8095a4),aluminium=material(0xc8d4da,.65,.3),brass=material(0xb38546,.55,.3),dark=material(0x293c49),suction=material(0x63bdde,.05,.6),compression=material(0xe99459,.05,.6);const meshes=[];
  function add(geometry,mat,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,mat);m.position.set(x,y,z);scene.add(m);meshes.push(m);return m;}
  function ring(ro,ri,height,mat){const shape=new THREE.Shape();shape.absarc(0,0,ro,0,Math.PI*2,false);const hole=new THREE.Path();hole.absarc(0,0,ri,0,Math.PI*2,true);shape.holes.push(hole);const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false,curveSegments:96});g.rotateX(-Math.PI/2);return add(g,mat,0,-height/2,0);}
  add(new THREE.CylinderGeometry(1.64,1.64,.16,96),dark,0,-.38,0);ring(1.52,1.25,.58,aluminium);
  for(let i=0;i<6;i++){const a=i*Math.PI/3;add(new THREE.CylinderGeometry(.07,.07,.075,6),dark,1.39*Math.cos(a),.325,1.39*Math.sin(a));}
  const roller=ring(.82,.62,.58,steel);const eccentric=add(new THREE.CylinderGeometry(.617,.617,.64,64),brass);const shaft=add(new THREE.CylinderGeometry(.15,.15,.86,40),dark,0,.03,0);const vane=add(new THREE.BoxGeometry(1,.67,.08),brass);add(new THREE.BoxGeometry(.57,.4,.30),steel,1.66,-.04,0);
  const suctionPort=add(new THREE.CylinderGeometry(.09,.09,.67,24),suction,1.57,.05,-.28);suctionPort.rotation.z=Math.PI/2;const dischargePort=add(new THREE.CylinderGeometry(.075,.075,.57,24),compression,1.57,.05,.28);dischargePort.rotation.z=Math.PI/2;
  // Geometric pockets are triangulated from exactly the same circle/vane state as the roller.
  const gasGeo=()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(120*6*3),3));return g;};const gasIn=add(gasGeo(),suction,0,.292,0),gasOut=add(gasGeo(),compression,0,.295,0);gasIn.material.side=gasOut.material.side=THREE.DoubleSide;
  function fillPocket(mesh,points){const n=points.length/2-1,a=mesh.geometry.attributes.position.array;let offset=0;for(let i=0;i<n;i++){const outerA=points[i],outerB=points[i+1],innerA=points[points.length-1-i],innerB=points[points.length-2-i];for(const p of [outerA,outerB,innerA,outerB,innerB,innerA]){a[offset++]=p[0];a[offset++]=0;a[offset++]=-p[1];}}mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingSphere();}
  function label(value,x,y,z){const c=document.createElement('canvas');c.width=384;c.height=72;const ctx=c.getContext('2d');ctx.fillStyle='#e8eff3';ctx.fillRect(0,0,384,72);ctx.fillStyle='#24475b';ctx.font='500 38px sans-serif';ctx.textAlign='center';ctx.fillText(tr(value),192,46);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;window.addEventListener('explainer-languagechange',()=>{ctx.fillStyle='#e8eff3';ctx.fillRect(0,0,384,72);ctx.fillStyle='#24475b';ctx.fillText(tr(value),192,46);texture.needsUpdate=true;dirty=true;wake();});const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));sprite.position.set(x,y,z);sprite.scale.set(1.35,.253,1);scene.add(sprite);}
  label('SUCTION IN',2.02,.48,-.65);label('DISCHARGE OUT',2.02,.48,.75);label('SLIDING VANE',2.02,.6,.04);label('SHAFT & ECCENTRIC',-.3,.75,-.75);
  let dirty=true,raf=0,last=0,visible=false;function view(kind){camera.position.set(...(kind==='top'?[.55,7.2,.1]:[3.6,4.5,4.75]));controls.target.set(.55,0,0);controls.update();dirty=true;wake();}
  function sync(){const geo=chamberGeometry(local.angle);roller.position.x=geo.cx;roller.position.z=-geo.cy;eccentric.position.x=geo.cx;eccentric.position.z=-geo.cy;const len=1.9-geo.tip;vane.scale.x=len;vane.position.set(geo.tip+len/2,0,0);fillPocket(gasIn,geo.suction);fillPocket(gasOut,geo.compression);dirty=true;wake();}
  function frame(now){raf=0;if(document.hidden||!visible||local.tab!=='rotary')return;const dt=last?Math.min((now-last)/1000,.06):0;last=now;if(local.playing){local.angle=Math.min(359,local.angle+dt*42);if(local.angle>=359)local.playing=false;sync();onFrame();}if(dirty){renderer.render(scene,camera);dirty=false;}if(local.playing&&!raf)raf=requestAnimationFrame(frame);}
  function wake(){if(!raf&&visible&&!document.hidden&&local.tab==='rotary'){raf=requestAnimationFrame(frame);}}
  controls.addEventListener('change',()=>{dirty=true;wake();});new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();dirty=true;last=0;wake();}}).observe(host);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;last=0;if(visible){dirty=true;wake();}},{threshold:0}).observe(host);document.addEventListener('visibilitychange',()=>{last=0;wake();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){local.playing=false;onFrame();}});view('angle');sync();return {sync,view};
}
