'use strict';
const $=id=>document.getElementById(id);const ja=new URLSearchParams(location.search).get('lang')==='ja';const t=a=>Array.isArray(a)?a[ja?1:0]:a;
let subject=0,lab=0,state={};
const defaults={topology:[{x:.5,r:.2,kind:'open'},{space:'chain',subset:2}],metric:[{p:'2',r:1,x:.7,y:.7},{ambient:'R',N:5,eps:.15}],real:[{a:1,eps:.5,delta:.2},{family:'power',n:5,b:1}],complex:[{map:'square',r:1,theta:45},{a:.3,r:1,direction:'ccw'}],functional:[{n:3},{n:3,operator:'D'}]};
const math=(s,display=false)=>katex.renderToString(s,{displayMode:display,throwOnError:true,output:'htmlAndMathml'});
const num=x=>Math.abs(x)<1e-9?'0':x.toFixed(3).replace(/\.?0+$/,'');
function control(id,label,min,max,step){return `<label for="${id}">${t(label)}<output id="${id}-value">${state[id]}</output><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${state[id]}"></label>`}
function select(id,label,options){return `<label for="${id}">${t(label)}<select id="${id}">${options.map(o=>`<option value="${o[0]}" ${state[id]===o[0]?'selected':''}>${t(o[1])}</option>`).join('')}</select></label>`}
function svg(body,title,view='0 0 660 310'){return `<svg viewBox="${view}" role="img" aria-label="${title}"><title>${title}</title>${body}</svg>`}
const line=(x1,y1,x2,y2,color='#d5dfe9',dash='',width=1.5)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
const txt=(x,y,s,anchor='middle',cls='')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" class="${cls}">${s}</text>`;
const circle=(x,y,r,color,fill=color)=>`<circle cx="${x}" cy="${y}" r="${r}" stroke="${color}" stroke-width="2" fill="${fill}"/>`;
const path=(pts,color='#1261b0',width=2,dash='')=>`<path d="${pts.map((p,i)=>(i?'L':'M')+p.map(v=>Number(v).toFixed(3)).join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
const sample=(f,a,b,n=300)=>Array.from({length:n+1},(_,i)=>f(a+(b-a)*i/n));
function axes(xmin,xmax,ymin,ymax){let X=x=>65+(x-xmin)/(xmax-xmin)*540,Y=y=>265-(y-ymin)/(ymax-ymin)*225;let b='';for(let i=0;i<=4;i++){let x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;b+=line(X(x),40,X(x),265)+line(65,Y(y),605,Y(y))+txt(X(x),291,num(x))+txt(54,Y(y)+4,num(y),'end');}if(ymin<=0&&ymax>=0)b+=line(65,Y(0),605,Y(0),'#8798ab');if(xmin<=0&&xmax>=0)b+=line(X(0),40,X(0),265,'#8798ab');return {X,Y,b};}
function setName(mask){return mask===0?'\\varnothing':mask===7?'X':'\\{'+['a','b','c'].filter((_,i)=>mask&(1<<i)).join(',')+'\\}'}
function finite(space,A){const opens=space==='discrete'?[0,1,2,3,4,5,6,7]:space==='indiscrete'?[0,7]:[0,1,3,7];const interior=opens.filter(U=>(U&A)===U).reduce((v,U)=>v|U,0);const closure=opens.map(U=>7^U).filter(F=>(F&A)===A).reduce((v,F)=>v&F,7);return {opens,interior,closure,boundary:closure&~interior,open:opens.includes(A),closed:opens.includes(7^A)}}
function configure(){const id=LESSONS[subject].id;let c='';if(id==='topology')c=lab===0?control('x',['Point x','点 x'],0,1,.01)+control('r',['Radius r','半径 r'],.01,.4,.01)+select('kind',['Set in ℝ','ℝ の部分集合'],[['open','(0,1)'],['closed','[0,1]']]):select('space',['Open-set structure','開集合の構造'],[['chain',['Chain','鎖状']],['discrete',['Discrete','離散']],['indiscrete',['Indiscrete','密着']]])+`<div><p class="control-label">${t(['Points in A','A に入れる点'])}</p><div class="set-buttons">${['a','b','c'].map((v,i)=>`<button data-point="${i}" aria-pressed="${!!(state.subset&(1<<i))}">${v}</button>`).join('')}</div></div>`;
if(id==='metric')c=lab===0?select('p',['Metric','距離'],[['1',['Taxicab (ℓ¹)','マンハッタン (ℓ¹)']],['2',['Euclidean (ℓ²)','ユークリッド (ℓ²)']],['inf',['Maximum (ℓ∞)','最大値 (ℓ∞)']]])+control('r',['Ball radius r','球の半径 r'],.2,1.5,.05)+control('x',['Probe x','調べる点 x'],-1.5,1.5,.05)+control('y',['Probe y','調べる点 y'],-1.5,1.5,.05):select('ambient',['Ambient space','全体空間'],[['R','ℝ'],['punctured','(0,1]']])+control('N',['Tail starts at N','末尾の開始 N'],1,30,1)+control('eps',['Tolerance ε','許容誤差 ε'],.02,.5,.01);
if(id==='real')c=lab===0?control('a',['Center a','中心 a'],-1.5,1.5,.1)+control('eps',['Output tolerance ε','出力の許容誤差 ε'],.05,1.5,.05)+control('delta',['Input radius δ','入力の半径 δ'],.01,.8,.01):select('family',['Sequence of functions','関数列'],[['power','fₙ(x) = xⁿ'],['linear','fₙ(x) = x/n']])+control('n',['Term n','項 n'],1,60,1)+control('b',['Right endpoint b','右端 b'],.2,1,.01);
if(id==='complex')c=lab===0?select('map',['Complex map','複素写像'],[['square','f(z) = z²'],['exp','f(z) = exp(z)'],['conj',['f(z) = conjugate(z)','f(z) = 共役(z)']]])+control('r',['Magnitude |z|','絶対値 |z|'],0,1.4,.05)+control('theta',['Argument θ (degrees)','偏角 θ（度）'],-180,180,5):control('a',['Pole a on real axis','実軸上の極 a'],-2,2,.05)+control('r',['Contour radius R','積分路の半径 R'],.25,1.5,.05)+select('direction',['Orientation','向き'],[['ccw',['Counterclockwise','反時計回り']],['cw',['Clockwise','時計回り']]]);
if(id==='functional')c=lab===0?control('n',['Sine modes N','正弦波の項数 N'],0,20,1):control('n',['Frequency n','周波数 n'],1,30,1)+select('operator',['Operator T','作用素 T'],[['D',['Differentiate','微分']],['I',['Identity','恒等']]]);
$('controls').innerHTML=c; $('controls').querySelectorAll('input[type=range]').forEach(el=>{const min=+el.min,step=+el.step;el.value=String(min+Math.round((+el.value-min)/step)*step);state[el.id]=+el.value;$(el.id+'-value').textContent=el.value;}); $('controls').querySelectorAll('select').forEach(el=>state[el.id]=el.value);if(id==='topology'&&lab===1)state.subset=(state.subset|0)&7;$('controls').querySelectorAll('input,select').forEach(el=>el.oninput=()=>{state[el.id]=el.type==='range'?+el.value:el.value;if($(el.id+'-value'))$(el.id+'-value').textContent=el.value;draw()});$('controls').querySelectorAll('[data-point]').forEach(el=>el.onclick=()=>{state.subset^=1<<+el.dataset.point;el.setAttribute('aria-pressed',String(!!(state.subset&(1<<+el.dataset.point))));draw()});}
function draw(){const id=LESSONS[subject].id;let b='',read='';
if(id==='topology'&&lab===0){const {x,r,kind}=state,px=v=>170+v*320,inside=x-r>=-1e-12&&x+r<=1+1e-12; b=line(30,170,630,170,'#8798ab')+line(px(0),170,px(1),170,'#1261b0','',4)+`<rect x="${px(x-r)}" y="115" width="${r*640}" height="110" fill="#1261b0" opacity=".10"/>`+line(px(x-r),115,px(x-r),225,'#1261b0','5 4')+line(px(x+r),115,px(x+r),225,'#1261b0','5 4')+circle(px(0),170,6,'#1261b0',kind==='closed'?'#1261b0':'white')+circle(px(1),170,6,'#1261b0',kind==='closed'?'#1261b0':'white')+circle(px(x),170,5,'#ae481b')+txt(px(0),201,'0')+txt(px(1),201,'1')+txt(px(x),92,`x = ${x.toFixed(2)}`)+txt(330,265,t(['Shaded interval: neighborhood of x','色付きの区間：x の近傍']));read=t([inside?'The neighborhood fits inside the set.':'The neighborhood extends outside the set.',inside?'近傍は集合内に収まります。':'近傍は集合の外へはみ出します。'])+' '+math(`r=${num(r)},\\quad \\min(x,1-x)=${num(Math.min(x,1-x))}`);if(x===0||x===1)read+=' '+t([kind==='open'?'This endpoint is not a member of (0,1).':'This endpoint belongs to [0,1], but has no positive radius that fits.',kind==='open'?'この端点は (0,1) に属しません。':'この端点は [0,1] に属しますが、正の半径の近傍は収まりません。']);}
if(id==='topology'&&lab===1){const f=finite(state.space,state.subset);b=txt(330,40,t(['Same points. Different open sets.','同じ点、異なる開集合。']),'middle','large');['a','b','c'].forEach((v,i)=>{b+=circle(170+i*160,120,29,'#1261b0',state.subset&(1<<i)?'#dbeeff':'white')+txt(170+i*160,126,v,'middle','large')+txt(170+i*160,185,t([state.subset&(1<<i)?'in A':'not in A',state.subset&(1<<i)?'A に属する':'A に属さない']));});b+=txt(330,244,t(['Select points above to change A','上のボタンで A の点を選択']));read=math(`A=${setName(state.subset)},\\quad \\operatorname{int}A=${setName(f.interior)},\\quad \\overline A=${setName(f.closure)}`)+'<br>'+math(`\\partial A=${setName(f.boundary)}`)+' · '+t([`A is ${f.open?'open':'not open'} and ${f.closed?'closed':'not closed'}.`, `A は${f.open?'開集合です':'開集合ではありません'}。${f.closed?'閉集合です':'閉集合ではありません'}。`]);$('plot-note').innerHTML=math(`\\tau=\\{${f.opens.map(setName).join(',')}\\}`)+'<br>'+t(LESSONS[subject].notes[lab]);}
if(id==='metric'&&lab===0){const {p,r,x,y}=state,S=72,X=v=>330+S*v,Y=v=>155-S*v;for(let i=-2;i<=2;i++)b+=line(X(i),Y(-1.8),X(i),Y(1.8))+line(X(-2),Y(i),X(2),Y(i));b+=line(160,Y(0),505,Y(0),'#8798ab')+line(X(0),25,X(0),288,'#8798ab')+txt(505,145,'x')+txt(343,27,'y');const points=sample(th=>{const u=Math.cos(th),v=Math.sin(th),scale=r/(p==='1'?Math.abs(u)+Math.abs(v):p==='inf'?Math.max(Math.abs(u),Math.abs(v)):1);return [X(u*scale),Y(v*scale)]},0,2*Math.PI);b+=`<path d="${points.map((v,i)=>(i?'L':'M')+v.join(',')).join(' ')}Z" fill="#e8f2ff" stroke="#1261b0" stroke-width="2" stroke-dasharray="6 4"/>`+line(X(0),Y(0),X(x),Y(y),'#ae481b')+circle(X(x),Y(y),5,'#ae481b')+circle(X(0),Y(0),3,'#122036')+txt(330,302,t(['One coordinate unit = one grid spacing','格子の間隔は座標の1単位']));const d=p==='1'?Math.abs(x)+Math.abs(y):p==='inf'?Math.max(Math.abs(x),Math.abs(y)):Math.hypot(x,y);read=math(`d(0,q)=${num(d)},\\quad r=${num(r)}`)+' · '+t([d<r-1e-10?'Inside the open ball.':Math.abs(d-r)<1e-10?'On the boundary — excluded.':'Outside the open ball.',d<r-1e-10?'開球の内部です。':Math.abs(d-r)<1e-10?'境界上なので含まれません。':'開球の外部です。']);}
if(id==='metric'&&lab===1){const {N,eps,ambient}=state,{X,Y,b:grid}=axes(1,40,0,1.05);b=grid;for(let k=1;k<=40;k++)b+=circle(X(k),Y(1/k),k>=N?4:3,k>=N?'#1261b0':'#aab9c9');b+=line(65,Y(eps),605,Y(eps),'#ae481b','6 4')+line(X(N),40,X(N),265,'#1261b0','4 4')+txt(575,31,'xₙ = 1/n')+txt(610,Y(eps)-8,'ε','end')+txt(620,286,'n');read=math(`\\sup_{m,n\\ge ${N}}|x_m-x_n|=\\frac1{${N}}=${num(1/N)}`)+'<br>'+t([1/N<=eps+1e-10?'Every tail-pair distance is below ε.':'Increase N to make every tail-pair distance below ε.',1/N<=eps+1e-10?'末尾のどの二項の距離も ε 未満です。':'末尾のすべての距離を ε 未満にするには N を増やしましょう。'])+' '+t([ambient==='R'?'Limit 0 belongs to ℝ: convergent.':'Limit 0 is missing from (0,1]: Cauchy, but not convergent here.',ambient==='R'?'極限0は ℝ に属するので収束します。':'(0,1] に0はないので、この空間ではコーシー列でも収束しません。']);}
if(id==='real'&&lab===0){const {a,eps,delta}=state,ymax=Math.max((Math.abs(a)+1)**2,a*a+eps)+.2,{X,Y,b:grid}=axes(a-1,a+1,-.4,ymax);b=grid+`<rect x="65" y="${Y(a*a+eps)}" width="540" height="${Y(a*a-eps)-Y(a*a+eps)}" fill="#ffddc9" opacity=".55"/><rect x="${X(a-delta)}" y="40" width="${X(a+delta)-X(a-delta)}" height="225" fill="#dbeeff" opacity=".7"/>`;b+=path(sample(x=>[X(x),Y(x*x)],a-1,a+1),'#8098b0',2)+path(sample(x=>[X(x),Y(x*x)],a-delta,a+delta),'#1261b0',4)+circle(X(a),Y(a*a),5,'#ae481b')+txt(580,29,'f(x) = x²')+txt(620,286,'x');const bound=2*Math.abs(a)*delta+delta*delta;read=math(`\\sup_{0<|x-a|<\\delta}|x^2-a^2|=${num(bound)}`)+' · '+t([bound<=eps+1e-10?'The ε–δ promise holds.':'This δ is too large.',bound<=eps+1e-10?'ε–δ の条件を満たします。':'この δ は大きすぎます。'])+'<br>'+t(['A sufficient choice: ','十分な選び方：'])+math(`\\delta=\\min\\left(1,\\frac{\\varepsilon}{2|a|+1}\\right)=${num(Math.min(1,eps/(2*Math.abs(a)+1)))}`);}
if(id==='real'&&lab===1){const {family,n,b:end}=state,{X,Y,b:grid}=axes(0,1,0,1.05);b=grid+`<rect x="${X(end)}" y="40" width="${X(1)-X(end)}" height="225" fill="#e6e9ed" opacity=".6"/>`+path(sample(x=>[X(x),Y(family==='power'?x**n:x/n)],0,end),'#1261b0',3)+line(X(0),Y(0),X(end),Y(0),'#ae481b','7 4',3)+txt(587,28,family==='power'?`n = ${n}, fₙ = xⁿ`:`n = ${n}, fₙ = x/n`)+txt(620,286,'x');const edge=family==='power'&&end===1;if(edge)b+=circle(X(1),Y(0),5,'#ae481b','white')+circle(X(1),Y(1),5,'#ae481b');const error=family==='linear'?end/n:edge?1:end**n;read=math(`\\|f_{${n}}-f\\|_\\infty=${error<.001&&error>0?error.toExponential(2).replace('e-',String.raw`\times10^{-`)+'}':num(error)}`)+' · '+t([edge?'Not uniform on [0,1]: the supremum stays 1.':'Uniform convergence on this fixed interval as n → ∞.',edge?'[0,1] では上限が1のままなので、一様収束ではありません。':'この固定した区間では n → ∞ で一様収束します。']);}
if(id==='complex'&&lab===0){const {map,r,theta}=state,z=[r*Math.cos(theta*Math.PI/180),r*Math.sin(theta*Math.PI/180)];const F=([x,y])=>map==='square'?[x*x-y*y,2*x*y]:map==='exp'?[Math.exp(x)*Math.cos(y),Math.exp(x)*Math.sin(y)]:[x,-y],w=F(z),out=map==='exp'?4.5:map==='square'?2.4:1.6;
const plane=(isOut)=>{const limit=isOut?out:1.6,X=x=>165+x/limit*112,Y=y=>168-y/limit*112;let g=txt(165,25,isOut?t(['Output w = f(z)','出力 w = f(z)']):t(['Input z','入力 z']),'middle','large')+line(30,168,302,168,'#8798ab')+line(165,36,165,301,'#8798ab')+txt(300,157,'Re')+txt(179,47,'Im');for(let a=-1;a<=1.001;a+=.25){for(let type=0;type<2;type++){g+=path(sample(v=>{let p=type?[v,a]:[a,v];if(isOut)p=F(p);return [X(p[0]),Y(p[1])]},-1,1,100),type?'#ae481b':'#1261b0',1.3,type?'4 3':'');}}const q=isOut?w:z;g+=line(X(0),Y(0),X(q[0]),Y(q[1]),'#122036','',2)+circle(X(q[0]),Y(q[1]),5,'#122036')+txt(X(1),185,'1');return svg(g,isOut?'Output complex plane':'Input complex plane','0 0 330 325')};$('plot').innerHTML='<div class="plot-pair">'+plane(false)+plane(true)+'</div>';read=math(`z=${num(z[0])}${z[1]<-1e-9?'-':'+'}${num(Math.abs(z[1]))}i,\\quad f(z)=${num(w[0])}${w[1]<-1e-9?'-':'+'}${num(Math.abs(w[1]))}i`);read+='<br>'+t([map==='conj'?'Conjugation reverses orientation and is nowhere holomorphic.':map==='square'&&r===0?'At 0 the derivative vanishes; this is a branch point.':'Nonzero complex derivative: locally a rotation and scaling.',map==='conj'?'共役は向きを反転し、どの点でも正則ではありません。':map==='square'&&r===0?'0では導関数が0となります。分岐点です。':'0でない複素導関数は、局所的に回転と拡大縮小を表します。']);}
if(id==='complex'&&lab===1){const {a,r,direction}=state,S=66,X=x=>330+x*S,Y=y=>155-y*S,on=Math.abs(Math.abs(a)-r)<1e-9,inside=Math.abs(a)<r-1e-9,sign=direction==='ccw'?1:-1;b=line(135,155,525,155,'#8798ab')+line(330,30,330,280,'#8798ab')+circle(330,155,r*S,'#1261b0','#eaf3ff')+txt(535,146,'Re')+txt(344,33,'Im')+line(X(a)-6,149,X(a)+6,161,'#ae481b','',3)+line(X(a)-6,161,X(a)+6,149,'#ae481b','',3)+txt(X(a),185,`a = ${num(a)}`)+txt(330,301,t([direction==='ccw'?'Counterclockwise (+)':'Clockwise (−)',direction==='ccw'?'反時計回り (+)':'時計回り (−)']));const y=Y(r);b+=line(320,y,340,y,'#1261b0','',3)+(sign===1?path([[327,y-5],[320,y],[327,y+5]],'#1261b0',3):path([[333,y-5],[340,y],[333,y+5]],'#1261b0',3));read=on?t(['Pole on contour: the ordinary integral is undefined.','極が経路上にあります。通常の積分は定義されません。']):math(`\\oint_{|z|=${num(r)}}\\frac{dz}{z-(${num(a)})}=${inside?(sign===1?'2\\pi i':'-2\\pi i'):'0'}`)+' · '+t([inside?'The pole is enclosed.':'The pole is outside.',inside?'極は内部にあります。':'極は外部にあります。']);}
if(id==='functional'&&lab===0){const N=state.n,{X,Y,b:grid}=axes(-Math.PI,Math.PI,-4,4);b=grid+path(sample(x=>[X(x),Y(x)],-Math.PI,Math.PI),'#1261b0',3);const sum=x=>Array.from({length:N},(_,i)=>2*(-1)**i/(i+1)*Math.sin((i+1)*x)).reduce((a,v)=>a+v,0);b+=path(sample(x=>[X(x),Y(sum(x))],-Math.PI,Math.PI,600),'#ae481b',2.5,'7 4')+txt(620,286,'x')+txt(145,28,'f(x) = x')+txt(525,28,`N = ${N}`);const error=Math.sqrt(2*Math.PI**3/3-4*Math.PI*Array.from({length:N},(_,i)=>1/(i+1)**2).reduce((a,v)=>a+v,0));read=math(`\\|f-P_{${N}}f\\|_2=${num(error)}`)+' · '+t(['The projection minimizes L² error in the selected sine subspace.','選んだ正弦波の部分空間で、射影は L² 誤差を最小にします。']);}
if(id==='functional'&&lab===1){const {n,operator}=state,{X,Y,b:grid}=axes(-Math.PI,Math.PI,-1.2,1.2);b=grid+path(sample(x=>[X(x),Y(Math.sin(n*x)/n)],-Math.PI,Math.PI,1000),'#1261b0',2.5)+path(sample(x=>[X(x),Y(operator==='D'?Math.cos(n*x):Math.sin(n*x)/n)],-Math.PI,Math.PI,1000),'#ae481b',2,'7 4')+txt(620,286,'x')+txt(175,28,t(['Blue solid: input','青実線：入力']))+txt(495,28,t(['Orange dashed: output','橙破線：出力']));read=math(`\\|f_n\\|_2=\\frac{\\sqrt\\pi}{${n}}=${num(Math.sqrt(Math.PI)/n)},\\quad \\|Tf_n\\|_2=${num(operator==='D'?Math.sqrt(Math.PI):Math.sqrt(Math.PI)/n)}`)+'<br>'+t(['Amplification: ','増幅率：'])+math(`\\frac{\\|Tf_n\\|_2}{\\|f_n\\|_2}=${operator==='D'?n:1}`)+' · '+t([operator==='D'?'This ratio grows without bound as n increases.':'Identity keeps the input unchanged.',operator==='D'?'n とともに、この比は限りなく増えます。':'恒等作用素では入力は変わりません。']);}
if(!(id==='complex'&&lab===0))$('plot').innerHTML=svg(b,t(LESSONS[subject].labs[lab]));$('readout').innerHTML=read;typesetProse($('readout'));typesetProse($('plot-note'));updateLanguage();}
const formulas=[String.raw`\begin{gathered}f:(X,\tau_X)\to(Y,\tau_Y)\text{ continuous}\\\Updownarrow\\\forall V\in\tau_Y:\ f^{-1}(V)\in\tau_X\end{gathered}`,String.raw`B_r^d(x)=\{y\in X:d(x,y)<r\}`,String.raw`\begin{gathered}\forall\varepsilon>0\;\exists\delta>0\;\forall x:\\0<|x-a|<\delta\\\implies |f(x)-L|<\varepsilon\end{gathered}`,String.raw`\begin{gathered}u_x=v_y,\quad u_y=-v_x\\z=re^{i\theta}\implies z^2=r^2e^{2i\theta}\end{gathered}`,String.raw`\begin{gathered}\langle f,g\rangle=\int_{-\pi}^{\pi}f(x)\overline{g(x)}\,dx\\\|f\|_2=\sqrt{\langle f,f\rangle}\end{gathered}`];
function render(){const s=LESSONS[subject];document.documentElement.lang=ja?'ja':'en';document.title=`${t(s.name)} · Analysis Atlas`;$('subjects').innerHTML=LESSONS.map((v,i)=>`<a href="#${v.id}" ${i===subject?'aria-current="page"':''}><span>0${i+1}</span>${t(v.name)}</a>`).join('');$('intro').innerHTML=`<p class="eyebrow">0${subject+1} / 05 · ${t(s.name)}</p><h1>${t(s.title)}</h1><p class="deck">${t(s.deck)}</p><p class="bridge">${t(s.bridge)}</p>`;$('lab-tabs').innerHTML=s.labs.map((v,i)=>`<button data-lab="${i}" aria-pressed="${lab===i}">${t(v)}</button>`).join('');document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{const target='#'+s.id+(+b.dataset.lab?'/2':'');if(location.hash===target)return;location.hash=target});$('lab-title').textContent=t(s.labs[lab]);$('lab-prompt').textContent=t(s.prompts[lab]);$('plot-note').textContent=t(s.notes[lab]);configure();draw();$('lab-kicker').textContent=t(['Experiment','実験']);$('route-label').textContent=t(['Five connected subjects','つながる五つの分野']);$('route-note').textContent=t(['Start with sets and functions. Familiarity with calculus and vectors helps in the later lessons.','集合と写像から始めます。後半では微積分とベクトルの知識が役立ちます。']);const formula=formulas[subject];$('reading').innerHTML=`<div class="reading-grid"><div class="definition"><h2>${t(['The precise idea','厳密な定義'])}</h2><p>${t(s.definition)}</p><div class="formula">${math(formula,true)}</div><p>${t(s.explain)}</p></div><div><h2>${t(['Work through an example','具体例で考える'])}</h2><p>${t(s.worked)}</p><h3>${t(s.connections[0])}</h3><p>${t(s.connections[1])}</p><h3>${t(s.connections[2])}</h3><p>${t(s.connections[3])}</p></div></div><section class="exercise"><h3>${t(['Check your understanding','理解を確かめる'])}</h3><p>${t(s.question)}</p><details><summary>${t(['Reveal the reasoning','考え方を表示'])}</summary><p>${t(s.answer)}</p></details></section><div class="sources"><strong>${t(['Further reading','さらに学ぶ'])}</strong>${s.source==='ra'?'<a href="https://www.jirka.org/ra/html/ra.html">Jiří Lebl · Basic Analysis I & II</a>':s.source==='ca'?'<a href="https://www.jirka.org/ca/">Jiří Lebl · Guide to Cultivating Complex Analysis</a>':'<a href="https://ocw.mit.edu/courses/18-102-introduction-to-functional-analysis-spring-2021/resources/lecture-notes/">MIT OpenCourseWare · 18.102, Functional Analysis</a>'}<span>${t(['Original introductory explanations and analytic examples; plots illustrate the statements and do not replace their proofs.','独自の入門解説と解析的な例です。図は命題の理解を助けますが、証明の代わりではありません。'])}</span></div>`;typesetProse($('reading'));typesetProse($('intro'));typesetProse($('lab-prompt'));
$('next').innerHTML=(subject>0?`<a href="#${LESSONS[subject-1].id}">← ${t(LESSONS[subject-1].name)}</a>`:'<span></span>')+(subject<4?`<a href="#${LESSONS[subject+1].id}">${t(LESSONS[subject+1].name)} →</a>`:`<a href="#topology">${t(['Return to topology','位相空間に戻る'])} →</a>`);$('footer').innerHTML=t(['Analysis Atlas · Isegoria · September 2026<br>Ten experiments, five introductory lessons. Basic set notation is assumed; calculus and linear algebra support the later chapters.','Analysis Atlas · Isegoria · 2026年9月<br>五つの入門レッスンと十の実験。基本的な集合の記法を前提とし、後半では微積分と線形代数の知識を使います。<br>日本語版は AI による翻訳です。原文は英語です。']);$('language').textContent=ja?'English':'日本語';updateLanguage();}
function updateLanguage(){const u=new URL(location);u.searchParams.set('lang',ja?'en':'ja');u.searchParams.set('state',JSON.stringify(state));document.querySelectorAll('#language,.ig-language').forEach(link=>{link.href=u.pathname+u.search+u.hash;link.textContent=ja?'English':'日本語';link.hreflang=ja?'en':'ja';link.lang=ja?'en':'ja';});}
function route(){const [id,k]=location.hash.slice(1).split('/');subject=Math.max(0,LESSONS.findIndex(s=>s.id===id));lab=k==='2'?1:0;state={...defaults[LESSONS[subject].id][lab]};if(!window.atlasRouted){try{const saved=JSON.parse(new URLSearchParams(location.search).get('state')||'null');if(saved&&Object.keys(state).every(k=>typeof saved[k]===typeof state[k])){for(const k of Object.keys(state)){if(typeof state[k]==='number'&&Number.isFinite(saved[k])&&Math.abs(saved[k])<=180)state[k]=saved[k];else if(typeof state[k]==='string'&&['open','closed','chain','discrete','indiscrete','1','2','inf','R','punctured','power','linear','square','exp','conj','ccw','cw','D','I'].includes(saved[k]))state[k]=saved[k];}}}catch{}}window.atlasRouted=true;render()};addEventListener('hashchange',route);route();

document.querySelectorAll('.skip,.ig-skip').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();$('lesson').focus();$('lesson').scrollIntoView({block:'start'});}));
const brand=document.querySelector('.brand');if(brand)brand.href=ja?'https://theisegoria.github.io/ja/':'https://theisegoria.github.io/';
