export let language = new URLSearchParams(location.search).get('lang') === 'ja' || (!new URLSearchParams(location.search).has('lang') && /\/ja\//.test(location.pathname)) ? 'ja' : 'en';
const ja={
'SodaStream ART — Inside the fizz':'SodaStream ART — 炭酸のしくみ',
'OBJECT LESSONS':'身近なもののしくみ','EVERYDAY DESIGN, EXPLAINED':'日常のデザインをひもとく','SODASTREAM ART · INTERACTIVE EXPLAINER':'SODASTREAM ART · 触って学ぶ解説','Inside the':'炭酸の','fizz.':'しくみ。','A bottle of water. A pull of a lever.':'水を入れて、レバーをひと押し。','Explore the chemistry behind the fizz ↓':'炭酸を生む化学を探る ↓','Back to library':'ライブラリへ',
'01 / THE WHOLE OBJECT':'01 / 全体を見る','02 / FRONT ELEVATION':'02 / 正面','03 / SIDE PROFILE':'03 / 側面','04 / CYLINDER HOUSING':'04 / 背面とシリンダー','05 / THE CARBONATING LEVER':'05 / 炭酸注入レバー','DRAG TO ROTATE':'ドラッグで回転','Loading the 3D model…':'3Dモデルを読み込み中…','The guided explanation below also works without 3D.':'3D表示がなくても、下の解説を利用できます。','Overview':'全体','Front':'正面','Side':'側面','Rear':'背面','Lever detail':'レバー拡大','Reset ↺':'リセット ↺','Reference-based exterior · illustrative internals':'外形は資料をもとに再現 · 内部は模式図',
'FROM STILL TO SPARKLING':'水から炭酸水へ','Meet ART':'ARTを見る','Fill & lock':'水を入れ装着','Make it fizz':'炭酸を注入','Release & enjoy':'取り外して飲む','01 / THE DESIGN':'01 / デザイン','02 / PREPARE THE BOTTLE':'02 / ボトルの準備','03 / CARBONATE':'03 / 炭酸の注入','04 / RELEASE':'04 / 圧力を逃がす','A little leverage.':'レバーで炭酸をつくる。',
'The side lever makes carbonation a hands-on ritual. The bottle hangs from the Snap-Lock beneath the metal-trimmed head, while a CO₂ cylinder sits inside the rear housing. No electricity required.':'側面のレバーを押すと炭酸を注入できます。ボトルは金属の縁取りがあるヘッド下のスナップロックに支えられ、CO₂シリンダーは背面の筐体に収まります。電源は不要です。',
'Fill. Lift. Lock.':'注ぐ、持ち上げる、装着する。','Fill a compatible bottle with cold, plain water to its fill line. With the bottle rest tilted forward, insert the neck, then push up and back into the Snap-Lock. The bottle should hang above the base.':'対応するボトルに冷たい水だけを水位線まで入れます。ボトルホルダーを手前に傾けて口を差し込み、上に押し上げてから奥へ戻すと装着できます。ボトルの底と台座の間には隙間ができます。',
'Put the lever to work.':'レバーでガスを送り込む。','Push the lever fully down for one second, then release. The official guide suggests three presses for standard fizz or five for strong fizz. Try it here; actual carbonation also depends on water temperature and the cylinder.':'レバーを下まで押し、1秒間保持してから離します。公式ガイドの目安は通常の炭酸で3回、強い炭酸で5回です。ここで操作を試せます。実際の炭酸の強さは水温やシリンダーの状態にも左右されます。',
'Let the pressure go.':'圧力が抜けてから取り外す。','After releasing the lever, gently tilt the bottle fully forward. Wait for the sound of excess gas escaping before removing it. Add flavours only after carbonation, then pour and enjoy.':'レバーを離したら、ボトルをゆっくり手前いっぱいまで傾けます。余分なガスが抜ける音を確認してから取り外してください。フレーバーは炭酸を注入した後に加えます。',
'Reveal the gas path':'ガスの経路を見る','Teaching view: housing fades to show the cylinder and a simplified route to the bottle.':'学習用表示：筐体を透かし、シリンダーとボトルへ向かうガスの模式的な経路を表示します。','ILLUSTRATIVE PRESS COUNT':'デモのレバー操作回数','Press the lever':'レバーを押す','Press the lever ↓':'レバーを押す ↓','Select “Fill & lock” to prepare the bottle.':'「水を入れ装着」でボトルを準備します。','Bottle filled and locked. Continue to make it fizz.':'ボトルの準備ができました。炭酸注入へ進みます。','Pressure released. Flavours go in afterwards.':'圧力が抜けました。フレーバーはこの後に加えます。','Lever down: gas enters the water.':'レバーを押しています。水にガスが入ります。','Five presses: strong fizz guidance. Ready to release.':'5回：強い炭酸の目安です。取り外しへ進めます。','Three presses: standard fizz guidance.':'3回：通常の炭酸の目安です。','Next: Fill & lock →':'次へ：水を入れ装着 →','Next: Make it fizz →':'次へ：炭酸を注入 →','Next: Release & enjoy →':'次へ：取り外して飲む →','Start again ↺':'最初から ↺',
'02 / THE CHEMISTRY LAB':'02 / 炭酸の化学ラボ','What makes water sparkle?':'水がシュワッとするのはなぜ？','Explore the gas you can’t see, the bubbles you can, and the small reaction that makes water acidic.':'見えない溶存ガス、見える気泡、そして水を酸性にする反応を調べます。','Dissolve CO₂':'CO₂を溶かす','Open the bottle':'ボトルを開ける','Make carbonic acid':'炭酸の反応','WATER AT EQUILIBRIUM':'平衡に達した水','MOLECULAR VIEW · NOT TO SCALE':'分子の模式図 · 縮尺は任意','OPEN TO AIR':'空気に開放','TWO DIFFERENT CHEMICAL REACTIONS':'2つの異なる化学反応','ATOM CONNECTIVITY · NOT TO SCALE':'原子の結合を表示 · 縮尺は任意','Higher pressure. More dissolved gas.':'圧力が高いほど、多く溶ける。',
'CO₂ molecules move between gas and water. At equilibrium, increasing CO₂ pressure increases the amount dissolved. Cooling the water also increases its capacity to hold CO₂.':'CO₂分子は気体と水の間を行き来します。平衡状態では、CO₂の分圧を上げるほど溶ける量が増えます。水を冷やすことでも、溶かせるCO₂の量が増えます。',
'Opening changes the balance.':'開けると平衡が変わる。','The liquid initially retains its dissolved CO₂. With much less CO₂ in the surrounding air, the water is supersaturated. Gas can escape at the surface and into growing bubbles, until a new equilibrium is approached.':'開けた直後も、水にはCO₂が溶けたまま残っています。周囲の空気のCO₂分圧は低いため、水は過飽和になります。CO₂は水面から逃げたり、気泡に入って成長させたりしながら、新しい平衡へ近づきます。',
'A small reaction makes an acid.':'一部が反応して酸になる。','Dissolved CO₂ is mostly individual molecules, not tiny bubbles and not all carbonic acid. A small fraction reacts with water; carbonic acid can then transfer a proton to water, increasing hydronium and lowering pH.':'溶けているCO₂の多くは独立した分子です。小さな気泡として存在するわけでも、すべてが炭酸になっているわけでもありません。一部は水と反応し、できた炭酸は水にプロトンを渡します。その結果、オキソニウムイオンが増え、pHが下がります。',
'Dissolved CO₂ molecules':'溶けたCO₂分子','Gas bubbles contain many molecules':'気泡は多数の分子を含む','CO₂ partial pressure':'CO₂の分圧','Water temperature':'水温','Cold · 4 °C':'冷水 · 4 °C','Room temperature · 25 °C':'室温 · 25 °C','Progress toward air equilibrium':'空気との平衡までの進行度','Just opened':'開けた直後','Equilibrated with air':'空気と平衡',
'Scrub the loss of dissolved gas. This is a progress model, not a clock; real degassing depends on nucleation sites, agitation and the vessel.':'スライダーで溶存ガスの減少をたどれます。これは時間ではなく進行度のモデルです。実際の脱気は気泡の核となる場所、かき混ぜ方、容器などに左右されます。',
'Reaction to inspect':'調べる反応','Hydration: form carbonic acid':'水和：炭酸をつくる','Dissociation: transfer a proton':'解離：プロトンを渡す','Most dissolved CO₂ stays as CO₂(aq). A small fraction reacts with water to form carbonic acid. Dissolving and reacting are different processes.':'溶けたCO₂の多くはCO₂(aq)のままです。一部だけが水と反応して炭酸をつくります。「溶けること」と「化学反応すること」は別の過程です。',
'Carbonic acid donates a proton to a water molecule. Bicarbonate and hydronium form. More hydronium means a lower pH; no CO₂ gas bubble is created by this step.':'炭酸が水分子にプロトンを渡すと、炭酸水素イオンとオキソニウムイオンができます。オキソニウムイオンが増えるほどpHは下がります。この反応そのものがCO₂の気泡をつくるわけではありません。',
'Molecule models show atom connectivity; proportions are not species abundances. Actual pH also depends on the water’s minerals and buffering.':'分子モデルは原子の結合関係を表します。表示数は存在比ではありません。実際のpHは水に含まれるミネラルや緩衝作用にも依存します。',
'Dissolved CO₂ at equilibrium':'平衡時の溶存CO₂','Dissolved CO₂ remaining':'残っている溶存CO₂','CO₂ released':'放出されたCO₂','g / kg water':'g / kg（水）',
'Ideal-water equilibrium estimate. These pressure values are model inputs, not ART settings or a conversion from lever presses.':'純水を近似した平衡モデルです。圧力はモデルへの入力値であり、ARTの設定値でも、レバー操作回数を換算した値でもありません。',
'How the chemistry model works':'化学モデルの計算方法','At the same temperature, doubling CO₂ partial pressure doubles the equilibrium concentration.':'同じ温度では、CO₂分圧を2倍にすると平衡濃度も2倍になります。','Just opened: pressure changes before the dissolved gas has time to escape.':'開けた直後：圧力は先に変化しますが、溶存ガスが逃げるには時間が必要です。','Dissolved gas remaining + gas released = the initial dissolved amount.':'残った溶存ガス ＋ 放出したガス ＝ 最初に溶けていた量。','Bubbles are a gas phase. Acidity is an aqueous chemical equilibrium.':'気泡は気体の相。酸性度は水中の化学平衡によって決まります。',
'CO₂ gas above the water':'水面の上のCO₂ガス','Air above the water':'水面の上の空気','Dissolved, individual CO₂ molecules':'水に溶けたCO₂分子','Supersaturated water → air equilibrium':'過飽和の水 → 空気との平衡','Water equilibrated with air':'空気と平衡に達した水','Atom labels: C · carbon   O · oxygen   H · hydrogen':'原子：C · 炭素　O · 酸素　H · 水素',
'← Isegoria library':'← Isegoriaの全コンテンツ','Sources & model notes':'出典とモデルについて','This independent educational model depicts the black SodaStream ART with a Fuse-style bottle. The exterior was rebuilt against manufacturer front, side and open-rear photographs. Nominal height (42.9 cm), base width (17.4 cm), and depth (24.5 cm) follow the manufacturer’s dimension graphic. Local contours remain photo-based; internal gas routing is schematic. No suitably licensed full-product CAD was used. Press count illustrates the manufacturer’s guidance, not a carbonation calculation.':'この独立した学習用モデルは、黒のSodaStream ARTとFuse型ボトルを表しています。メーカーの正面・側面・背面開放時の写真をもとに外形を再構築しました。公称の高さ42.9 cm、台座の幅17.4 cm、奥行き24.5 cmはメーカーの寸法図に基づきます。細部の形状は写真からの再現で、内部のガス経路は模式図です。適切な再配布ライセンスを確認できる製品全体のCADは使用していません。レバー回数はメーカーの操作目安を示すもので、炭酸濃度の計算ではありません。',
'Use compatible, in-date carbonating bottles; carbonate plain water only. Follow your machine’s full manual.':'使用期限内の対応ボトルを使い、炭酸は水だけに注入してください。実機の操作は取扱説明書に従ってください。',
'Manufacturer product reference ↗':'メーカー製品情報 ↗','Official ART operating guide ↗':'ART公式操作ガイド ↗','ART manual ↗':'ART取扱説明書 ↗','Manufacturer dimensions & three-quarter view ↗':'メーカー寸法図と斜め前方の写真 ↗','Manufacturer side reference ↗':'メーカーの側面写真 ↗','Manufacturer open-rear reference ↗':'メーカーの背面内部写真 ↗','EXPLORE THE ORDINARY.':'身近なものを、深く知る。',
'Interactive SodaStream ART model':'SodaStream ARTの操作可能な3Dモデル','Language':'言語','Camera views':'カメラの向き','Guide steps':'操作ガイド','Chemistry chapters':'化学の章','CO₂ partial pressure in bar':'CO₂の分圧（bar）','Water temperature in degrees Celsius':'水温（摂氏）','Reference-based SodaStream ART model. Camera buttons provide keyboard views.':'資料に基づくSodaStream ARTモデル。カメラボタンはキーボードでも操作できます。',
'3D rendering paused. Reload to restore it; the chemistry guide still works.':'3D表示が停止しました。再読み込みで復元できます。化学の解説は引き続き使えます。','3D is unavailable in this browser. The guided steps and interactive chemistry still work.':'このブラウザでは3Dを表示できません。操作ガイドと化学ラボは利用できます。'
};
function translateDynamic(s){
 let m;
 if((m=s.match(/^(\d+) of 5 demonstration presses\. Each press lasts one second\.$/)))return `デモの操作回数：${m[1]} / 5回。1回につき1秒間押します。`;
 if((m=s.match(/^At (.+) °C, capacity is (.+)× the capacity at 25 °C, at the same CO₂ pressure\.$/)))return `同じCO₂分圧では、${m[1]} °Cで溶かせる量は25 °Cの${m[2]}倍です。`;
 if((m=s.match(/^Started at (.+) °C and (.+) bar CO₂: (.+) g dissolved per kg water\.$/)))return `初期条件：${m[1]} °C、CO₂分圧${m[2]} bar。水1 kgあたり${m[3]} gが溶けています。`;
 if((m=s.match(/^Air-equilibrium target: (.+) g\/kg\. “Flat” does not mean absolutely zero CO₂\.$/)))return `空気との平衡値：${m[1]} g/kg。「炭酸が抜けた」状態でもCO₂は完全なゼロではありません。`;
 if((m=s.match(/^WATER AT EQUILIBRIUM\. (.+) grams of dissolved CO₂ per kilogram water at (.+) degrees Celsius\. CO₂ partial pressure (.+) bar\.$/)))return `平衡状態。水温${m[2]} °C、CO₂分圧${m[3]} bar、水1 kgあたりの溶存CO₂は${m[1]} gです。`;
 if((m=s.match(/^OPEN TO AIR\. (.+) grams of dissolved CO₂ per kilogram water at (.+) degrees Celsius\. (.+) percent toward equilibrium with air\.$/)))return `空気に開放。水温${m[2]} °C、水1 kgあたりの溶存CO₂は${m[1]} g、平衡までの進行度は${m[3]}%です。`;
 return s;
}
export function t(value){if(language==='en')return value;const s=value.trim(),translated=ja[s]??translateDynamic(s);return value.slice(0,value.indexOf(s))+translated+value.slice(value.indexOf(s)+s.length);}
const original=new WeakMap(),attrs=new WeakMap();
function localize(node){
 if(node.nodeType===3){if(/^(SCRIPT|STYLE)$/.test(node.parentElement?.tagName))return;let record=original.get(node);if(!record||record.last!==node.nodeValue)record={en:node.nodeValue,last:node.nodeValue};const out=t(record.en);record.last=out;original.set(node,record);if(node.nodeValue!==out)node.nodeValue=out;return;}
 if(node.nodeType!==1)return;
 for(const attr of ['aria-label','alt','title'])if(node.hasAttribute(attr)){let records=attrs.get(node)||{};let record=records[attr];const value=node.getAttribute(attr);if(!record||record.last!==value)record={en:value,last:value};const out=t(record.en);record.last=out;records[attr]=record;attrs.set(node,records);if(value!==out)node.setAttribute(attr,out);}
 for(const child of [...node.childNodes])localize(child);
}
const methods=[...document.querySelectorAll('.chem-method>div>p')],methodsEnglish=methods.map(p=>p.innerHTML);
const methodsJapanese=[
'ヘンリーの法則は <strong>c = k<sub>H</sub>(T) × p<sub>CO₂</sub></strong> です。<a href="https://webbook.nist.gov/cgi/cbook.cgi?ID=C124389&Mask=10" target="_blank" rel="noreferrer">NIST Chemistry WebBook</a> の値として、25 °Cでの k<sub>H</sub> = 0.035 mol/(kg·bar)、温度係数2400 K、CO₂のモル質量44.0095 g/molを用います。温度補正は k<sub>H</sub>(T) = 0.035 exp[2400(1/T − 1/298.15)] で、Tはケルビンです。気体を理想気体として近似し、溶けた分子状CO₂の量を求めます。溶存無機炭素全体の量ではありません。',
'「ボトルを開ける」では、選択した条件の平衡濃度から出発し、c(s) = c<sub>空気</sub> + (c<sub>初期</sub> − c<sub>空気</sub>)(1 − s) に従って空気との平衡へ近づきます。sは変化の進行度であり、経過時間ではありません。よく混ざった空気のCO₂分圧を0.00042 barと仮定し、開口部付近の気体が混ざる過渡過程は計算しません。大気の全圧は約1 barのままです。',
'物理的背景：<a href="https://openstax.org/books/chemistry-2e/pages/11-3-solubility" target="_blank" rel="noreferrer">OpenStaxの気体の溶解度</a>。反応の背景：<a href="https://pubs.acs.org/doi/10.1021/jp909019u" target="_blank" rel="noreferrer">Wangらによる水中のCO₂の水和・脱水反応の研究</a>、<a href="https://acswebcontent.acs.org/ChemistryInContextSuite/applets/OceanAcidification/1_2.html" target="_blank" rel="noreferrer">ACSによる溶存CO₂と炭酸の解説</a>。酸の表示は定性的な反応図であり、pHの計算ではありません。'
];
export function setLanguage(next){language=next==='ja'?'ja':'en';document.documentElement.lang=language;document.querySelector('#library-link').href=language==='ja'?'/ja/library.html':'/library.html';document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===language)));methods.forEach((p,i)=>p.innerHTML=language==='ja'?methodsJapanese[i]:methodsEnglish[i]);localize(document.documentElement);const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);dispatchEvent(new Event('languagechange'));}
const observer=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')localize(record.target);else if(record.type==='attributes')localize(record.target);else for(const node of record.addedNodes)localize(node)}});
observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','alt','title']});
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLanguage(b.dataset.lang));
setLanguage(language);
