'use strict';
const rel=new Set(),xs=[1,2,3,4],key=(a,b)=>a+','+b;
function relationPreset(name){rel.clear();for(const a of xs)for(const b of xs)if(({equivalence:a%2===b%2,order:a<=b,strict:a<b,cycle:b===a%4+1,empty:false,full:true})[name])rel.add(key(a,b));renderRelation()}
function renderRelation(){const has=(a,b)=>rel.has(key(a,b));$('relation-matrix').innerHTML='<table><caption>Row x, column y: is x related to y?</caption><thead><tr><th>x / y</th>'+xs.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+xs.map(a=>'<tr><th>'+a+'</th>'+xs.map(b=>`<td><button data-pair="${a},${b}" aria-label="Pair (${a}, ${b})" aria-pressed="${has(a,b)}">${has(a,b)?'1':'0'}</button></td>`).join('')+'</tr>').join('')+'</tbody></table>';
let ref=xs.find(a=>!has(a,a)),sym,anti,trans;for(const a of xs)for(const b of xs){if(has(a,b)&&!has(b,a)&&!sym)sym=[a,b];if(a!==b&&has(a,b)&&has(b,a)&&!anti)anti=[a,b];for(const c of xs)if(has(a,b)&&has(b,c)&&!has(a,c)&&!trans)trans=[a,b,c]}
const props=[['Reflexive',!ref,'Every x must relate to itself.',ref?`(${ref}, ${ref}) is missing.`:'All diagonal pairs are present.'],['Symmetric',!sym,'If x relates to y, y must relate to x.',sym?`(${sym}) is present; (${sym[1]}, ${sym[0]}) is missing.`:'Every pair has its reverse.'],['Antisymmetric',!anti,'Two-way related elements must be equal.',anti?`${anti[0]} and ${anti[1]} relate both ways but are different.`:'No distinct elements relate both ways.'],['Transitive',!trans,'If x relates to y and y to z, x must relate to z.',trans?`(${trans[0]}, ${trans[1]}) and (${trans[1]}, ${trans[2]}) are present; (${trans[0]}, ${trans[2]}) is missing.`:'Every two-step connection has the direct pair.']];$('relation-properties').innerHTML=props.map(([n,ok,d,w])=>`<div class="property"><strong>${ok?'✓':'✕'} ${n}</strong><span>${d} ${w}</span></div>`).join('')+`<p class="classification">${!ref&&!sym&&!trans?'Equivalence relation. ':''}${!ref&&!anti&&!trans?'Partial order. ':''}${ref||sym||trans?'Not an equivalence relation. ':''}</p>`;}
$('relation-preset').addEventListener('change',e=>relationPreset(e.target.value));$('relation-matrix').addEventListener('click',e=>{const pair=e.target.closest('button')?.dataset.pair;if(!pair)return;rel.has(pair)?rel.delete(pair):rel.add(pair);$('relation-preset').selectedIndex=-1;renderRelation()});
function quotient(){const m=+$('modulus').value;$('quotient-classes').innerHTML=Array.from({length:m},(_,r)=>`<div><h3 data-tex="[${r}]"></h3><p>${Array.from({length:12},(_,n)=>n).filter(n=>n%m===r).join(' · ')}</p><span class="muted">Remainder ${r}</span></div>`).join('');$('quotient-count').textContent=`The integers split into ${m} equivalence classes. Every displayed integer belongs to exactly one class.`;typeset($('quotient-classes'))}$('modulus').addEventListener('change',quotient);
let mapping=['a','b','c','d'];let codomain=['a','b','c','d'];$('function-controls').innerHTML=xs.map((x,i)=>`<label class="field">f(${x}) <select data-input="${i}" aria-label="Output for ${x}">${['a','b','c','d'].map(y=>`<option ${y===mapping[i]?'selected':''}>${y}</option>`).join('')}</select></label>`).join('');function functionRender(){const image=[...new Set(mapping)],collision=mapping.findIndex((y,i)=>mapping.indexOf(y)!==i),missing=codomain.filter(y=>!image.includes(y));$('function-properties').innerHTML=`<div class="property"><strong>${collision<0?'✓':'✕'} Injective (one-to-one)</strong><span>${collision<0?'Distinct inputs have distinct outputs.':`Inputs ${mapping.indexOf(mapping[collision])+1} and ${collision+1} both map to ${mapping[collision]}.`}</span></div><div class="property"><strong>${missing.length?'✕':'✓'} Surjective (onto Y)</strong><span>${missing.length?`No input maps to ${missing.join(', ')}.`:'Every element of the codomain is reached.'}</span></div><p class="classification">${collision<0&&!missing.length?'Bijective: a one-to-one correspondence.':'Not bijective.'} This is always a function: every input has exactly one output.</p>`;
setMath('codomain-formula','Y='+texify(fmt(codomain)));$('function-map').setAttribute('viewBox','0 0 480 '+(codomain.length===5?340:280));$('function-map').innerHTML='<title>Function arrows from inputs 1 through 4 to outputs a through d</title><defs><marker id="arrowhead" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3z" fill="#245bcc"/></marker></defs>'+mapping.map((y,i)=>`<line x1="95" y1="${40+i*64}" x2="377" y2="${40+codomain.indexOf(y)*64}" stroke="#245bcc" stroke-width="2" marker-end="url(#arrowhead)"/>`).join('')+xs.map((x,i)=>`<circle cx="70" cy="${40+i*64}" r="22" fill="#e6efff"/><text x="70" y="${46+i*64}" text-anchor="middle" font-size="18">${x}</text>`).join('')+codomain.map((y,i)=>`<circle cx="410" cy="${40+i*64}" r="22" fill="#e6efff"/><text x="410" y="${46+i*64}" text-anchor="middle" font-size="18">${y}</text>`).join('');setMath('image-result','f(\\{1,2\\})='+texify(fmt([...new Set(mapping.slice(0,2))])));const target=$('preimage-target').value,pre=xs.filter((x,i)=>target!=='empty'&&target.includes(mapping[i]));setMath('preimage-result','f^{-1}(T)='+texify(fmt(pre)));}
$('function-controls').addEventListener('change',e=>{mapping[+e.target.dataset.input]=e.target.value;$('function-preset').selectedIndex=-1;functionRender()});$('preimage-target').addEventListener('change',functionRender);$('function-preset').addEventListener('change',e=>{mapping={bijective:['a','b','c','d'],collision:['a','a','c','d'],constant:['b','b','b','b']}[e.target.value];codomain=['a','b','c','d'];$('codomain-size').value='4';rebuildOutputs();functionRender()});
const bits=Array.from({length:6},(_,i)=>Array.from({length:6},(_,j)=>(i+j*3+Math.floor(i/2))%2));function diagonal(){const anti=bits.map((row,i)=>1-row[i]);$('diagonal').innerHTML='<table><caption>A finite window into a proposed infinite list</caption><thead><tr><th>Row / bit</th>'+bits.map((_,i)=>`<th>${i+1}</th>`).join('')+'<th>…</th></tr></thead><tbody>'+bits.map((row,i)=>`<tr><th>${i+1}</th>`+row.map((b,j)=>`<td><button class="${i===j?'diagonal-bit':''}" data-bit="${i},${j}" aria-label="Row ${i+1}, bit ${j+1}: ${b}${i===j?', diagonal':''}" aria-pressed="${b===1}">${b}</button></td>`).join('')+'<td>…</td></tr>').join('')+'<tr class="anti-row"><th>New</th>'+anti.map(b=>`<td>${b}</td>`).join('')+'<td>…</td></tr></tbody></table>';$('diagonal-result').textContent='Constructed prefix: '+anti.join(' ')+' …';diagonalWitness()}
function diagonalWitness(){const k=+$('diagonal-row').value;setMath('diagonal-witness',`b_{${k}}=${1-bits[k-1][k-1]}\\ne ${bits[k-1][k-1]}=a_{${k}${k}}`)}$('diagonal').addEventListener('click',e=>{const pair=e.target.closest('button')?.dataset.bit;if(!pair)return;const [i,j]=pair.split(',').map(Number);bits[i][j]=1-bits[i][j];diagonal()});$('diagonal-row').addEventListener('change',diagonalWitness);
relationPreset('equivalence');quotient();functionRender();diagonal();typeset();
// Keep rendered mathematics synchronized with local control changes.
document.addEventListener('change',()=>typeset());document.addEventListener('click',()=>typeset());

function rebuildOutputs(){$('function-controls').querySelectorAll('select').forEach((s,i)=>{if(!codomain.includes(mapping[i]))mapping[i]=codomain[0];s.innerHTML=codomain.map(y=>`<option ${y===mapping[i]?'selected':''}>${y}</option>`).join('')})}
$('codomain-size').addEventListener('change',e=>{codomain='abcde'.slice(0,+e.target.value).split('');$('function-preset').selectedIndex=-1;rebuildOutputs();functionRender()});
