'use strict';
const U=[1,2,3,4,5,6,7,8];let A=new Set([1,2,3,4]),B=new Set([3,4,5,6]),op='union';
const $=id=>document.getElementById(id),fmt=xs=>xs.length?'{'+xs.join(', ')+'}':'∅';
const operations={union:{symbol:'A ∪ B',name:'Union',rule:(a,b)=>a||b,explain:'In A or in B, including elements that belong to both. “Or” in mathematics includes both.'},intersection:{symbol:'A ∩ B',name:'Intersection',rule:(a,b)=>a&&b,explain:'In A and in B. Only the shared elements are included.'},difference:{symbol:'A ∖ B',name:'Difference',rule:(a,b)=>a&&!b,explain:'In A but not in B. Reversing A and B can change this result.'},reverse:{symbol:'B ∖ A',name:'Reverse difference',rule:(a,b)=>b&&!a,explain:'In B but not in A. Compare this with A ∖ B.'},complement:{symbol:'Aᶜ',name:'Complement in U',rule:a=>!a,explain:'In the universe U but not in A. Elements of B are included only if they are outside A.'},symmetric:{symbol:'A △ B',name:'Symmetric difference',rule:(a,b)=>a!==b,explain:'In exactly one of A and B. The overlap is excluded.'}};
$('membership').innerHTML='<table><caption class="muted">Tick to include a number in each set</caption><thead><tr><th>Element</th><th>In A</th><th>In B</th></tr></thead><tbody>'+U.map(n=>`<tr><td>${n}</td><td><label><input type="checkbox" data-set="A" data-n="${n}" aria-label="${n} in A"></label></td><td><label><input type="checkbox" data-set="B" data-n="${n}" aria-label="${n} in B"></label></td></tr>`).join('')+'</tbody></table>';
$('membership').addEventListener('change',e=>{const n=Number(e.target.dataset.n),s=e.target.dataset.set==='A'?A:B;e.target.checked?s.add(n):s.delete(n);$('preset').selectedIndex=-1;render()});
$('operations').innerHTML=Object.entries(operations).map(([key,v])=>`<button data-op="${key}" aria-pressed="${key===op}" aria-label="${v.name}: ${v.symbol}">${v.symbol}</button>`).join('');
$('operations').addEventListener('click',e=>{const target=e.target.closest('button');if(!target?.dataset.op)return;op=target.dataset.op;render()});
const presets={overlap:[[1,2,3,4],[3,4,5,6]],disjoint:[[1,2,3],[5,6,7]],subset:[[2,4],[1,2,3,4,5]],equal:[[1,3,5],[1,3,5]],empty:[[],[2,4,6,8]]};
function preset(k){[A,B]=presets[k].map(x=>new Set(x));$('preset').value=k;render()}
$('preset').addEventListener('change',e=>preset(e.target.value));$('try-subset').addEventListener('click',()=>{preset('subset');$('sets').scrollIntoView();$('preset').focus({preventScroll:true})});
function render(){const o=operations[op],result=U.filter(n=>o.rule(A.has(n),B.has(n)));$('operation-label').textContent=o.symbol;$('result-name').textContent=o.name+' · '+result.length+' element'+(result.length===1?'':'s');$('result-set').textContent=o.symbol+' = '+fmt(result);$('result-explanation').textContent=o.explain;$('set-a').textContent='A = '+fmt(U.filter(n=>A.has(n)));$('set-b').textContent='B = '+fmt(U.filter(n=>B.has(n)));document.querySelectorAll('[data-set]').forEach(e=>e.checked=(e.dataset.set==='A'?A:B).has(+e.dataset.n));document.querySelectorAll('[data-op]').forEach(e=>e.setAttribute('aria-pressed',e.dataset.op===op));
const regions=[{id:'a',a:true,b:false,x:193,y:120,w:64},{id:'both',a:true,b:true,x:310,y:100,w:0},{id:'b',a:false,b:true,x:427,y:120,w:64},{id:'neither',a:false,b:false,x:92,y:313,w:60}];let dots='';for(const r of regions){$( 'region-'+r.id).setAttribute('fill',o.rule(r.a,r.b)?'#396295':'#1b344d');const ns=U.filter(n=>A.has(n)===r.a&&B.has(n)===r.b);ns.forEach((n,i)=>{let x,y;if(r.id==='both'){x=r.x+(i%2-.5)*40;y=108+Math.floor(i/2)*38}else if(r.id==='neither'){x=r.x+i*r.w;y=r.y}else{x=r.x+(i%2-.5)*r.w;y=r.y+Math.floor(i/2)*38}const active=result.includes(n);dots+=`<g><circle cx="${x}" cy="${y}" r="17" fill="${active?'#edf5ff':'#203d58'}" stroke="${active?'#edf5ff':'#95b0cb'}"/><text x="${x}" y="${y+8}" text-anchor="middle" fill="${active?'#142940':'#d5e2f0'}" font-size="24">${n}</text></g>`})}$('dots').innerHTML=dots;$('venn-desc').textContent='A = '+fmt([...A])+'. B = '+fmt([...B])+'. '+o.symbol+' = '+fmt(result)+'. Solid circles indicate included numbers.';
const common=U.filter(n=>A.has(n)&&B.has(n)).length,union=U.filter(n=>A.has(n)||B.has(n)).length;$('counting').textContent=`${union} = ${A.size} + ${B.size} − ${common}`;const missing=U.filter(n=>A.has(n)&&!B.has(n));$('subset-symbol').textContent=missing.length?'A ⊈ B':A.size===B.size?'A = B, so A ⊆ B':'A ⊊ B';$('subset-reason').textContent=missing.length?`${fmt(missing)} ${missing.length===1?'contains an element':'contains elements'} of A missing from B. This prevents A from being a subset of B.`:A.size===B.size?'The sets have exactly the same elements. A is a subset of B, but not a proper subset.':A.size===0?'A has no elements, so none can be missing from B. Since B is nonempty, the containment is proper.':'Every element of A is in B, and B has additional elements. The containment is proper.';renderLaw()}
function renderLaw(){const union=$('law').value==='union';const left=U.filter(n=>union?!(A.has(n)||B.has(n)):!(A.has(n)&&B.has(n))),right=U.filter(n=>union?!A.has(n)&&!B.has(n):!A.has(n)||!B.has(n));$('law-words').textContent=union?'Being outside the union means being outside A and outside B.':'Being outside the intersection means being outside A or outside B (possibly both).';$('law-result').textContent=fmt(left)+' = '+fmt(right)}$('law').addEventListener('change',renderLaw);
const S=new Set(['a','b']);$('power-controls').innerHTML=['a','b','c','d'].map(c=>`<button data-element="${c}" aria-label="Toggle ${c} in S" aria-pressed="${S.has(c)}">${c} ∈ S</button>`).join('');function power(){const items=['a','b','c','d'].filter(x=>S.has(x)),subs=Array.from({length:2**items.length},(_,mask)=>items.filter((_,i)=>mask&(1<<i)));$('power-summary').textContent=`S = ${fmt(items)}   ;   |𝒫(S)| = 2^${items.length} = ${subs.length}`;$('power-grid').innerHTML=subs.map(s=>`<span>${fmt(s)}</span>`).join('');$('power-controls').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',S.has(b.dataset.element)))}$('power-controls').addEventListener('click',e=>{const c=e.target.closest('button')?.dataset.element;if(!c)return;S.has(c)?S.delete(c):S.add(c);power()});
for(const [id,items]of [['product-x',['1','2','3']],['product-y',['a','b','c']]]){$(id).innerHTML=items.map((c,i)=>`<label><input type="checkbox" value="${c}" ${i<2?'checked':''}>${c}</label>`).join('');$(id).addEventListener('change',product)}function product(){const xs=[...$('product-x').querySelectorAll(':checked')].map(e=>e.value),ys=[...$('product-y').querySelectorAll(':checked')].map(e=>e.value);$('product-grid').style.gridTemplateColumns=`repeat(${ys.length||1},1fr)`;$('product-grid').innerHTML=xs.length&&ys.length?xs.flatMap(x=>ys.map(y=>`<span>(${x}, ${y})</span>`)).join(''):'<span>∅ · No ordered pairs</span>';$('product-summary').textContent=`X = ${fmt(xs)}, Y = ${fmt(ys)}. |X × Y| = ${xs.length} × ${ys.length} = ${xs.length*ys.length}.`}
const questions=[{q:'Let A = {1, 2, 3} and B = {3, 4}. What is A ∩ B?',options:['{1, 2, 3, 4}','{3}','{1, 2}'],answer:1,why:'Intersection keeps only the elements in both sets. Here, only 3 belongs to both.'},{q:'How many elements does {∅} contain?',options:['0','1','2'],answer:1,why:'Its one element is the empty set. The container {∅} is not itself empty.'},{q:'If S has 3 elements, how many subsets does S have?',options:['3','6','8'],answer:2,why:'Each element can be included or excluded: 2 × 2 × 2 = 8 subsets, including ∅ and S.'},{q:'For U = {1, 2, 3, 4} and A = {2, 4}, what is Aᶜ?',options:['{1, 3}','{2, 4}','All odd integers'],answer:0,why:'Take elements of the specified universe that are outside A. Numbers outside U are not part of this complement.'},{q:'Which statement is always true for any set A?',options:['∅ ∈ A','∅ ⊆ A','A ∈ A'],answer:1,why:'There are no elements of ∅ that could be absent from A. Membership ∅ ∈ A requires ∅ to be an actual element of A.'}];
questions.push({q:'A relation is reflexive, symmetric and transitive. What does it determine?',options:['An equivalence relation and a partition','A total order','Necessarily a function'],answer:0,why:'The equivalence classes partition the underlying set into disjoint nonempty blocks.'},{q:'An injective function maps a four-element set into a five-element set. Is it onto?',options:['Always','Never','Sometimes'],answer:1,why:'Its four distinct outputs reach only four of the five codomain elements.'},{q:'Must a function be bijective for preimages to exist?',options:['Yes','No'],answer:1,why:'A preimage is the set of all inputs landing in a target subset; it is defined whether or not an inverse function exists.'},{q:'What makes the diagonal sequence absent from a proposed infinite list?',options:['It has more digits','It differs from row n at position n for every n','It differs from the first six rows only'],answer:1,why:'The argument applies to every position in the proposed list, not just a finite window.'},{q:'Which property distinguishes the rationals from the reals?',options:['Only the reals are infinite','Only the rationals can be listed in a sequence','Only the rationals are dense in the real line'],answer:1,why:'Both are infinite and dense in the real line, but the rationals are countable and the reals are uncountable.'});
function quizMath(s){return s.replace(/\{[^}]*\}|[A-Z] [∩∪∈⊆] [A-Z]|[A-Z]ᶜ|∅ [∈⊆] [A-Z]/g,m=>'<span class="math">'+m+'</span>')}
$('quiz').innerHTML=questions.map((q,i)=>`<div class="quiz-item"><h3>${i+1}. ${quizMath(q.q)}</h3><div class="quiz-options" role="group" aria-label="Question ${i+1}">${q.options.map((s,j)=>`<button data-question="${i}" data-answer="${j}" aria-label="${s}" aria-pressed="false">${quizMath(s)}</button>`).join('')}</div><p class="feedback" id="feedback-${i}" aria-live="polite"></p></div>`).join('');$('quiz').addEventListener('click',e=>{const target=e.target.closest('button');if(!target?.hasAttribute('data-answer'))return;const i=+target.dataset.question,j=+target.dataset.answer,q=questions[i];target.parentElement.querySelectorAll('button').forEach(b=>{b.setAttribute('aria-pressed',b===target);b.classList.toggle('correct',b===target&&j===q.answer)});$('feedback-'+i).textContent=(j===q.answer?'Correct. ':'Not quite. ')+q.why});render();power();product();
