import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const ja=document.documentElement.lang==='ja', t=(a,b)=>ja?b:a;
const S={view:0,spread:.65,power:1,r:1,g:.45,b:.12,play:!matchMedia('(prefers-reduced-motion: reduce)').matches,phase:0,layer:3};
const layers=[
[t('Substrate + TFT backplane','基板＋TFTバックプレーン'),t('The foundation carries thin-film transistors. In an active-matrix panel, pixel circuits set the current supplied to each subpixel. A storage capacitor holds the programmed drive condition between updates.','基板上の薄膜トランジスタで各サブピクセルの電流を制御します。アクティブマトリクス方式では、保持容量が次の書き込みまで駆動状態を保持します。'),0x587785],
[t('Anode · positive electrode','陽極・正側の電極'),t('Under forward bias, the anode injects holes: missing electrons that behave as positive charge carriers.','順方向に電圧を加えると、陽極から正孔が注入されます。正孔とは電子の抜けた状態で、正の電荷のように移動します。'),0xbacbd3],
[t('Hole transport layers','正孔輸送層'),t('Organic injection and transport layers help holes reach the emission region. Several real layers are grouped here.','有機物の注入層と輸送層が、正孔を発光領域へ導きます。ここでは複数の層をまとめて表示しています。'),0xd7a368],
[t('Emissive layer','発光層'),t('An electron and a hole can form an excited state (an exciton). Radiative relaxation releases a photon; some energy is lost without producing light. The emitter determines the emission spectrum.','電子と正孔は励起状態（励起子）を形成します。光を伴う緩和で光子が放出されますが、光にならず失われるエネルギーもあります。発光材料が光のスペクトルを決めます。'),0x83cfaf],
[t('Electron transport layers','電子輸送層'),t('These organic layers deliver electrons toward the emissive region. Real devices may add blocking layers to confine charge and excitons.','有機層が電子を発光領域へ運びます。実際の素子では、電荷や励起子を閉じ込める阻止層を追加する場合もあります。'),0x82b1dd],
[t('Cathode · negative electrode','陰極・負側の電極'),t('The cathode injects electrons. This top-emission teaching model uses a semitransparent upper electrode so light can leave toward the viewer.','陰極から電子が注入されます。この上面発光の教材モデルでは、上側の半透明電極を通って観察者側へ光が出ます。'),0xc0bbd5],
[t('Encapsulation','封止層'),t('A protective barrier limits exposure to water and oxygen. Cover glass, touch sensors and reflection-control films are omitted from this microscopic stack.','水分や酸素の侵入を抑える保護層です。この微視的な積層図では、カバーガラス、タッチセンサー、反射を抑えるフィルムは省略しています。'),0x89a5b5]
];
const views=[t('01 / Inside the panel','01 / パネルの内部'),t('02 / Charge → light','02 / 電荷から光へ'),t('03 / Build a colour','03 / 色をつくる')];
document.querySelector('#app').innerHTML=`
<header><a class="brand" href="${ja?'/ja/':'/'}">ISEGORIA <span>/ ${t('Display notebook','ディスプレイノート')}</span></a><a id="language" lang="${ja?'en':'ja'}" href="${ja?'../':'ja/'}">${ja?'English':'日本語'}</a></header>
<main><div class="intro"><div><p class="eyebrow">${t('OLED / ORGANIC LIGHT-EMITTING DIODE','OLED / 有機発光ダイオード')}</p><h1>${t('A panel made of light.','画素そのものが、光になる。')}</h1></div><p>${t('No backlight. Each subpixel makes its own light. Explore the layers, follow a charge pair, then mix a colour.','バックライトはありません。各サブピクセルが自ら発光します。層を広げ、電荷の動きを追い、色を混ぜてみましょう。')}</p></div>
<nav class="tabs" aria-label="${t('Explore','探索')}">${views.map((v,i)=>`<button data-view="${i}" aria-pressed="${i===0}">${v}</button>`).join('')}</nav>
<section class="lab"><div class="stage"><div class="stage-top"><span id="scene-title"></span><span>3D · ${t('TEACHING MODEL','教材モデル')}</span></div><div id="canvas-host"></div><div id="fallback" hidden>${t('3D could not start. Use the layer list and explanations to explore the same mechanism.','3Dを起動できませんでした。層の一覧と解説で仕組みをご覧いただけます。')}</div><div class="stage-bottom"><span id="hint">${t('Drag to orbit · pinch / scroll to zoom','ドラッグで回転・ピンチ／スクロールで拡大')}</span><button id="reset">${t('Reset view','視点を戻す')}</button></div></div>
<aside><div id="stack-controls"><label>${t('Separate the layers','層を広げる')}<output id="spread-out">65%</output><input id="spread" type="range" min="0" max="100" value="65"></label><div class="layer-list">${layers.map((l,i)=>`<button data-layer="${i}" aria-pressed="${i===3}"><span style="background:#${l[2].toString(16)}"></span>${l[0]}</button>`).reverse().join('')}</div></div>
<div id="charge-controls" hidden><p class="eyebrow">${t('A SINGLE RECOMBINATION EVENT','一つの再結合過程')}</p><div class="legend"><span>− ${t('Electron','電子')}</span><span>+ ${t('Hole','正孔')}</span><span>~ ${t('Photon','光子')}</span></div><label>${t('Event progress (illustrative)','過程の進行（模式表示）')}<output id="phase-out"></output><input id="phase" type="range" min="0" max="100" value="0"></label><button id="play"></button><p class="note">${t('Motion is slowed and schematic. Holes are not particles orbiting atoms, and not every injected pair produces an escaping photon.','動きは模式的に遅く表示しています。正孔は原子の周りを回る粒子ではなく、注入した全ての対が外へ出る光子になるわけでもありません。')}</p></div>
<div id="pixel-controls" hidden><p class="eyebrow">${t('RELATIVE LINEAR CHANNEL OUTPUT','各色の相対的な線形光出力')}</p>${['r','g','b'].map((k,i)=>`<label>${[t('Red','赤'),t('Green','緑'),t('Blue','青')][i]}<output id="${k}-out"></output><input id="${k}" type="range" min="0" max="100" value="${S[k]*100}" style="accent-color:${['#ff6476','#74dbb0','#77aaff'][i]}"></label>`).join('')}<div class="presets"><button data-rgb="0,0,0">${t('Black','黒')}</button><button data-rgb="1,1,1">${t('White','白')}</button><button data-rgb="1,1,0">${t('Yellow','黄')}</button></div><div class="mix"><div id="swatch"></div><p>${t('Seen from a distance','離れて見た色')}<strong id="hex"></strong></p></div><p class="note">${t('An ideal RGB stripe layout. Real subpixel shapes and arrangements vary. Preview uses sRGB encoding; it is not a calibrated spectrum or power estimate.','理想化したRGBストライプ配列です。実際の形や配置は異なります。色表示はsRGB変換を用いたもので、校正済みのスペクトルや消費電力の推定ではありません。')}</p></div>
<div class="detail" aria-live="polite"><p class="eyebrow" id="detail-kicker"></p><h2 id="detail-title"></h2><p id="detail-body"></p></div>
</aside></section>
<div class="model-note">${t('TOP-EMISSION RGB OLED · Layer thicknesses, gaps, colours and particle sizes are exaggerated. The exploded state is for inspection, not an operating panel.','上面発光RGB OLED · 層の厚さ、間隔、色、粒子の大きさは説明用に誇張しています。分解表示は観察用で、動作中のパネルの状態ではありません。')}</div>
<section class="reading"><div><p class="eyebrow">${t('THE BIG PICTURE','全体像')}</p><h2>${t('Electricity in. Light out.','電気を入れ、光を取り出す。')}</h2><p>${t('OLED means organic light-emitting diode. “Organic” refers to carbon-based semiconductor materials. A forward voltage injects electrons and holes from opposite electrodes; transport layers guide them into a region where excited states can release light. [1, 2]','OLEDは有機発光ダイオードの略です。「有機」は炭素を基盤とする半導体材料を指します。順方向の電圧で両側の電極から電子と正孔を注入し、輸送層がそれらを発光領域へ導きます。そこで生じた励起状態から光が放出されます。[1, 2]')}</p><p>${t('The photon energy is E = hc/λ. Shorter wavelengths carry more energy per photon. Changing current mainly changes light output; changing the emissive material changes the spectrum. A brightness slider does not turn a red emitter into a blue one.','光子のエネルギーは E = hc/λ です。波長が短いほど、一つの光子のエネルギーが大きくなります。主に電流が光量を、発光材料がスペクトルを決めます。明るさを調整しても赤の発光材料が青に変わるわけではありません。')}</p></div><div><p class="eyebrow">${t('FROM ONE DIODE TO A DISPLAY','一つの素子からディスプレイへ')}</p><h2>${t('Millions of independent decisions.','無数の画素を、個別に制御する。')}</h2><p>${t('An AMOLED backplane addresses subpixels and controls their drive current. A pixel programmed off emits essentially no light of its own: OLED does not need to block a shared backlight to make black. Room light can still reflect from the panel. [3]','AMOLEDのバックプレーンはサブピクセルを選択し、駆動電流を制御します。消灯した画素はほぼ自発光しないため、黒を作るのに共通のバックライトを遮る必要がありません。ただし室内光はパネル表面で反射します。[3]')}</p><p>${t('That does not mean a black image makes the whole display consume zero power: driver electronics still operate. Water and oxygen can damage the organic stack, so encapsulation is essential. [4]','黒い画像でもディスプレイ全体の消費電力がゼロになるわけではありません。駆動回路などは動作しています。水分や酸素は有機層を傷めるため、封止が重要です。[4]')}</p></div></section>
<section class="variants"><p class="eyebrow">${t('ONE PRINCIPLE, DIFFERENT COLOUR ARCHITECTURES','発光原理は共通、色の作り方は多様')}</p><h2>${t('Not every OLED is an RGB stack.','すべてのOLEDがRGB発光ではありません。')}</h2><div class="variant-grid"><article><h3>RGB OLED</h3><p>${t('Separate red, green and blue organic emitters produce the primaries directly. This is the architecture illustrated above. [1]','赤・緑・青の有機発光材料で、それぞれの色を直接作ります。上の教材モデルはこの方式です。[1]')}</p></article><article><h3>WOLED</h3><p>${t('A white-emitting OLED stack supplies light to colour filters. Common TV implementations also include an unfiltered white subpixel. White emission can come from multiple emissive units. [5]','白色光を作るOLED積層とカラーフィルターを組み合わせます。一般的なテレビ用では、フィルターを通さない白サブピクセルも使います。複数の発光ユニットで白色光を作る場合があります。[5]')}</p></article><article><h3>QD-OLED</h3><p>${t('Blue OLED emission excites quantum dots that convert some light to red or green; the blue channel transmits blue light. It remains self-emissive at the subpixel level. [6]','青色OLEDの光で量子ドットを励起し、一部を赤や緑に変換します。青の経路は青色光を通します。サブピクセル単位で自発光する方式です。[6]')}</p></article></div></section>
<footer><h2>${t('Sources & model boundaries','出典とモデルの範囲')}</h2><ol><li><a href="https://oled.com/oleds/">Universal Display Corporation — OLED structure</a></li><li><a href="https://news.samsungdisplay.com/4660">Samsung Display — OLED principle & structure</a></li><li><a href="https://global.samsungdisplay.com/30927">Samsung Display — Backplane</a></li><li><a href="https://global.samsungdisplay.com/29626">Samsung Display — Encapsulation</a></li><li><a href="https://www.lgdisplay.com/eng/technology/tandem-woled">LG Display — Tandem WOLED</a></li><li><a href="https://global.samsungdisplay.com/31428">Samsung Display — QD-OLED emission architecture</a></li></ol><p>${t('A conceptual explainer, not a device simulation. No measured layer dimensions, carrier mobility, quantum efficiency, lifetime or luminance are inferred. Circuit details and optical interference are omitted.','概念を理解するための解説であり、素子シミュレーションではありません。層寸法、キャリア移動度、量子効率、寿命、輝度の測定値を示すものではありません。回路の詳細や光の干渉は省略しています。')}</p><p>${t('14 September 2026 · English / Japanese','2026年9月14日 · 英語・日本語')}</p></footer></main>`;
const $=id=>document.getElementById(id);let renderer,scene,camera,controls,group,stack=[],charges,grid;const rgb=new THREE.Color();
try{
renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0c141d,1);$('canvas-host').append(renderer.domElement);renderer.domElement.setAttribute('aria-label',t('Interactive OLED teaching model','操作できるOLED教材モデル'));renderer.domElement.setAttribute('role','img');
scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.1,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=5;controls.maxDistance=21;controls.enablePan=false;scene.add(new THREE.HemisphereLight(0xd8edff,0x283547,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(2,7,5);scene.add(light);group=new THREE.Group();scene.add(group);
const geo=new THREE.BoxGeometry(5,.085,3.05);
layers.forEach((l,i)=>{let mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:l[2],metalness:i===1||i===5?.5:.15,roughness:.4,transparent:i===6,opacity:i===6?.22:1,depthWrite:i!==6}));mesh.userData.layer=i;group.add(mesh);stack.push(mesh);let edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:l[2],transparent:true,opacity:.6}));mesh.add(edges)});
// Lithographic traces and transistor blocks on the backplane.
for(let x=-2.2;x<=2.2;x+=.55){let m=new THREE.Mesh(new THREE.BoxGeometry(.018,.006,2.85),new THREE.MeshBasicMaterial({color:0xc5ae6c}));m.position.set(x,.05,0);stack[0].add(m)}
for(let z=-1.25;z<=1.25;z+=.5){let m=new THREE.Mesh(new THREE.BoxGeometry(4.6,.006,.018),new THREE.MeshBasicMaterial({color:0xc5ae6c}));m.position.set(0,.05,z);stack[0].add(m);for(let x=-2.2;x<2.3;x+=.55){let q=new THREE.Mesh(new THREE.BoxGeometry(.13,.018,.16),new THREE.MeshStandardMaterial({color:0x212f36}));q.position.set(x,.06,z);stack[0].add(q)}}
charges=new THREE.Group();group.add(charges);['electron','hole','photon'].forEach((name,i)=>{let m=new THREE.Mesh(new THREE.SphereGeometry(i===2?.1:.14,20,12),new THREE.MeshBasicMaterial({color:[0x86baff,0xffc48a,0x83ffb6][i]}));m.name=name;const cv=document.createElement('canvas');cv.width=128;cv.height=128;const ctx=cv.getContext('2d');ctx.fillStyle='#ffffff';ctx.font='bold 92px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(['−','+','~'][i],64,64);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv),depthTest:false}));sprite.scale.set(.35,.35,1);sprite.position.y=.28;m.add(sprite);charges.add(m)});
grid=new THREE.Group();group.add(grid);const pixGeo=new THREE.BoxGeometry(.14,.065,.31);for(let row=0;row<8;row++)for(let col=0;col<9;col++)for(let c=0;c<3;c++){const p=new THREE.Mesh(pixGeo,new THREE.MeshBasicMaterial());p.position.set((col-4)*.54+(c-1)*.16,0,(row-3.5)*.36);p.userData.c=c;grid.add(p)}
const base=new THREE.Mesh(new THREE.BoxGeometry(5.2,.15,3.15),new THREE.MeshStandardMaterial({color:0x020305,roughness:.35}));base.position.y=-.13;grid.add(base);
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(S.view!==0||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;let b=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);let hit=ray.intersectObjects(stack,false)[0];if(hit){S.layer=hit.object.userData.layer;update()}});
new ResizeObserver(()=>{let b=$('canvas-host').getBoundingClientRect();renderer.setSize(b.width,b.height);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();render()}).observe($('canvas-host'));
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('fallback').hidden=false;});
}catch(e){$('fallback').hidden=false;console.error(e)}
function reset(){if(!camera)return;camera.position.set(S.view===1?6:7,S.view===2?9:6,S.view===1?8:8);controls.target.set(0,0,0);controls.update();render()}
function render(){if(renderer&&scene)renderer.render(scene,camera)}
function update(){document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.view)===S.view));['stack','charge','pixel'].forEach((v,i)=>$(v+'-controls').hidden=S.view!==i);$('scene-title').textContent=views[S.view];$('spread-out').textContent=Math.round(S.spread*100)+'%';$('phase-out').textContent=Math.round(S.phase*100)+'%';$('play').textContent=S.play?t('Pause','一時停止'):t('Play','再生');$('play').setAttribute('aria-pressed',S.play);document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.layer)===S.layer));
let phase=Math.min(3,Math.floor(S.phase*4));let titles=[t('Inject opposite charges','反対符号の電荷を注入'),t('Transport toward the emissive layer','発光層へ輸送'),t('Form an excited state','励起状態を形成'),t('Release a photon','光子を放出')],bodies=[t('Electrons enter from the cathode above; holes enter from the anode below. − and + mark the two carrier types.','上側の陰極から電子、下側の陽極から正孔が入ります。−と＋はキャリアの種類を示します。'),t('Electric fields and material energy levels govern transport. The straight paths shown here are explanatory, not molecular trajectories.','電場と材料のエネルギー準位が輸送を左右します。直線の経路は説明用で、分子スケールの軌道ではありません。'),t('An electron and a hole form an excited state in the emissive region. The flash marks this state, not a miniature physical explosion.','発光領域で電子と正孔が励起状態を形成します。光る球はこの状態の記号で、物理的な爆発を示していません。'),t('Radiative relaxation emits light. We draw one upward path; actual emission has an angular distribution and some light stays trapped or is absorbed.','光を伴う緩和で発光します。上向きの一経路を描いていますが、実際は角度分布をもち、一部の光は閉じ込められたり吸収されたりします。')];
$('detail-kicker').textContent=S.view===0?t('SELECTED LAYER','選択中の層'):S.view===1?t('CURRENT STAGE','現在の段階'):t('ADDITIVE COLOUR','加法混色');$('detail-title').textContent=S.view===0?layers[S.layer][0]:S.view===1?titles[phase]:t('Three channels. One perceived colour.','三つの色を、一つの色として見る。');$('detail-body').textContent=S.view===0?layers[S.layer][1]:S.view===1?bodies[phase]:t('Red plus green looks yellow. All channels off makes black; balanced channels make a neutral grey or white in this ideal sRGB model.','赤と緑を重ねると黄色に見えます。全て消灯すると黒になります。この理想化したsRGBモデルでは、三色を同じ強さにすると無彩色になります。');
['r','g','b'].forEach(k=>$(k+'-out').textContent=Math.round(S[k]*100)+'%');rgb.setRGB(S.r,S.g,S.b,THREE.LinearSRGBColorSpace);const hex='#'+rgb.getHexString();$('swatch').style.background=hex;$('hex').textContent=hex.toUpperCase();if(!group)return;
stack.forEach((m,i)=>{m.visible=S.view!==2;m.position.y=(i-3)*(.115+(S.view===1?.43:S.spread*.6));m.material.emissive.setHex(S.view===0&&i===S.layer?0x27372f:0);m.material.transparent=i===6||S.view===1;m.material.opacity=S.view===1?(i===3?.26:.12):i===6?.22:1;m.material.depthWrite=S.view!==1&&i!==6;m.material.needsUpdate=true;});charges.visible=S.view===1;grid.visible=S.view===2;grid.children.forEach(m=>{if(m.userData.c!==undefined){let c=m.userData.c;let v=[S.r,S.g,S.b][c];m.material.color.setRGB(c===0?v:0,c===1?v:0,c===2?v:0)}});animateCharges();render()}
function animateCharges(){if(!charges)return;const p=S.phase;const y=stack[5].position.y;charges.children[0].position.set(-.15,Math.max(0,y*(1-p/.58)),0);charges.children[1].position.set(.15,Math.min(0,-y*(1-p/.58)),0);charges.children[0].visible=charges.children[1].visible=p<.62;const photon=charges.children[2];photon.visible=p>=.58;photon.position.set(0,p<.75?0:(p-.75)*13,0);photon.scale.setScalar(p<.75?1+Math.sin((p-.58)/.17*Math.PI)*1.4:1)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=+b.dataset.view;update();reset();save()});document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{S.layer=+b.dataset.layer;update()});$('spread').oninput=e=>{S.spread=+e.target.value/100;update();save()};$('phase').oninput=e=>{S.play=false;S.phase=+e.target.value/100;update()};$('play').onclick=()=>{S.play=!S.play;update()};['r','g','b'].forEach(k=>$(k).oninput=e=>{S[k]=+e.target.value/100;update();save()});document.querySelectorAll('[data-rgb]').forEach(b=>b.onclick=()=>{b.dataset.rgb.split(',').forEach((v,i)=>{let k=['r','g','b'][i];S[k]=+v;$(k).value=+v*100});update();save()});$('reset').onclick=reset;
function save(){let p=new URLSearchParams(location.search);p.set('view',S.view);p.set('rgb',[S.r,S.g,S.b].join(','));p.set('spread',S.spread);history.replaceState(null,'',location.pathname+'?'+p+location.hash);$('language').href=(location.pathname.includes('oled-panel-lab')?(ja?'/oled-panel-lab/':'/ja/oled-panel-lab/'):(ja?'../':'ja/'))+location.search+location.hash}
const params=new URLSearchParams(location.search);if(params.has('view'))S.view=Math.max(0,Math.min(2,Number(params.get('view'))||0));if(params.has('spread')){S.spread=Math.max(0,Math.min(1,Number(params.get('spread'))||0));$('spread').value=S.spread*100}if(params.has('rgb'))params.get('rgb').split(',').slice(0,3).forEach((v,i)=>{let k=['r','g','b'][i];S[k]=Math.max(0,Math.min(1,Number(v)||0));$(k).value=S[k]*100});$('language').href=(location.pathname.includes('oled-panel-lab')?(ja?'/oled-panel-lab/':'/ja/oled-panel-lab/'):(ja?'../':'ja/'))+location.search+location.hash;
controls?.addEventListener('change',render);update();reset();let prev=0,lastPhase=-1;function frame(now){let dt=Math.min((now-prev)/1000,.05);prev=now;if(!document.hidden&&S.view===1&&S.play){S.phase=(S.phase+dt/7)%1;$('phase').value=S.phase*100;$('phase-out').textContent=Math.round(S.phase*100)+'%';let phase=Math.floor(S.phase*4);if(phase!==lastPhase){lastPhase=phase;update()}animateCharges();render()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
