# Six topics added 2026-09-22: Lie groups, Hamiltonian mechanics, stochastic processes,
# solid-state physics, control theory, logic and computability.
# Imported by build.py (exec'd in its namespace so add_expansion, L and p are available).

def c(key,en,ja,lo,hi,step,value,options):return [key,en,ja,lo,hi,step,value,options]

add_expansion('lie-groups','Lie groups and Lie algebras: continuous symmetry','リー群とリー代数：連続的な対称性','Exponentials of rotations, the double cover, and why the bracket measures failure to commute.','回転の指数写像・二重被覆・交換子が非可換性を測る理由を見ます。','geometry','Linear algebra and group theory','線形代数と群論','MIT OpenCourseWare · Introduction to Lie Groups','https://ocw.mit.edu/courses/18-755-introduction-to-lie-groups-fall-2004/',[
L('exp-map','1. The exponential map','1. 指数写像',
 r'A rotation is the exponential of an infinitesimal one. Choose an axis and an angle, then add terms of the power series one at a time. The true rotation moves a point around a circle; each truncated series lands off that circle, and the gap closes as terms are added. Drag in the figure to turn the view.',
 r'回転は無限小回転の指数関数です。軸と角度を選び、べき級数の項を一つずつ加えてください。本当の回転は点を円に沿って動かしますが、打ち切った級数はその円から外れ、項を増やすとずれが縮みます。図をドラッグすると視点を回せます。',
 r'R(\theta)=e^{\theta K}=\sum_{n=0}^{\infty}\frac{(\theta K)^n}{n!}=I+\sin\theta\,K+(1-\cos\theta)\,K^2',
 r'For a unit axis \(\mathbf n\), \(K\mathbf v=\mathbf n\times\mathbf v\) and \(K^3=-K\), so the whole series collapses to Rodrigues’ formula. The trace of \(R\) is \(1+2\cos\theta\).',
 r'単位軸 \(\mathbf n\) について \(K\mathbf v=\mathbf n\times\mathbf v\)、\(K^3=-K\) なので、級数全体がロドリゲスの公式にまとまります。\(R\) のトレースは \(1+2\cos\theta\) です。',
 r'A truncated series is not a rotation: it stretches lengths, so \(R^{\mathsf T}R\neq I\). Only the full sum lies in the group.',
 r'打ち切った級数は回転ではありません。長さを伸縮させるので \(R^{\mathsf T}R\neq I\) です。群に属するのは級数の和全体だけです。',
 'Why does a skew-symmetric K give an orthogonal exponential?','なぜ反対称な K の指数関数は直交行列になるのですか？',
 r'Because \((e^{\theta K})^{\mathsf T}=e^{\theta K^{\mathsf T}}=e^{-\theta K}\), which is the inverse of \(e^{\theta K}\).',
 r'\((e^{\theta K})^{\mathsf T}=e^{\theta K^{\mathsf T}}=e^{-\theta K}\) が \(e^{\theta K}\) の逆行列だからです。',
 [p('theta','Rotation angle θ (degrees)','回転角 θ（度）',0,360,1,150),p('terms','Series terms N','級数の項数 N',1,16,1,3),p('tilt','Axis tilt from z (degrees)','z 軸からの軸の傾き（度）',0,90,1,35)]),
L('double-cover','2. The double cover: 720° to come home','2. 二重被覆：戻るのに 720°',
 r'Turn an object about a fixed axis. Its orientation returns after 360°, but the unit quaternion that produced it has only reached −1; it needs a second full turn to return to +1. The ribbon tied to the wall records the same fact. At 720°, drag Untwist: the double twist straightens while the block stays still. At 360° no such move exists.',
 r'物体を固定軸のまわりに回します。姿勢は 360° で元に戻りますが、それを生む単位四元数はまだ −1 にしか達していません。+1 に戻るにはもう一回転が必要です。壁に結んだリボンも同じことを記録します。720° で「ほどく」をドラッグすると、ブロックは静止したまま二重のねじれがまっすぐになります。360° ではそのような動かし方はありません。',
 r'q(\theta)=\cos\tfrac{\theta}{2}+\sin\tfrac{\theta}{2}\,(n_x\mathbf i+n_y\mathbf j+n_z\mathbf k),\qquad R_q(\mathbf v)=q\,\mathbf v\,\bar q',
 r'Both \(q\) and \(-q\) give the same rotation, so the map \(SU(2)\to SO(3)\) is two to one. At \(\theta=360^\circ\), \(q=-1\) yet \(R_q=I\).',
 r'\(q\) と \(-q\) は同じ回転を与えるので、写像 \(SU(2)\to SO(3)\) は二対一です。\(\theta=360^\circ\) で \(q=-1\) ですが \(R_q=I\) です。',
 r'The ribbon picture is a faithful statement about loops in \(SO(3)\), whose fundamental group is \(\mathbb Z/2\); it is not a claim that physical ribbons carry spin.',
 r'リボンの図は、基本群が \(\mathbb Z/2\) である \(SO(3)\) のループについての正確な主張です。現実のリボンがスピンを持つという主張ではありません。',
 'Which loop in SO(3) can be shrunk to a point?','SO(3) のどのループが一点に縮められますか？',
 r'The 720° loop. The 360° loop cannot, because its lift to \(SU(2)\) ends at \(-1\) instead of closing.',
 r'720° のループです。360° のループは縮められません。\(SU(2)\) への持ち上げが閉じずに \(-1\) で終わるためです。',
 [p('angle','Rotation angle (degrees)','回転角（度）',0,720,1,360)]),
L('commutator','3. The bracket measures failure to commute','3. 括弧積は非可換性を測る',
 r'Rotate by ε about x, then y, then undo x, then undo y. If rotations commuted you would return to the start. You do not: the loop leaves a gap, and the leftover rotation is a turn of about ε² about the z axis (clockwise seen from above). The log–log plot shows the gap shrinking with slope 2.',
 r'x 軸まわりに ε、次に y 軸まわりに ε 回し、それから x、y の順に戻します。回転が可換なら出発点に戻りますが、戻りません。ループには隙間が残り、残った回転は z 軸まわりのおよそ ε² の回転（上から見て時計回り）です。両対数グラフでは隙間が傾き 2 で縮みます。',
 r'e^{-\varepsilon Y}e^{-\varepsilon X}e^{\varepsilon Y}e^{\varepsilon X}=e^{\varepsilon^2[Y,X]+O(\varepsilon^3)},\qquad [Y,X]=YX-XY=-Z',
 r'For the rotation generators of \(\mathfrak{so}(3)\), \([X,Y]=Z\): the Lie algebra of rotations is \(\mathbb R^3\) with the cross product. The product is read right to left, so the first rotation is \(e^{\varepsilon X}\).',
 r'\(\mathfrak{so}(3)\) の回転生成子では \([X,Y]=Z\) です。回転のリー代数は外積を備えた \(\mathbb R^3\) です。積は右から左へ読むので、最初の回転は \(e^{\varepsilon X}\) です。',
 r'The \(\varepsilon^2\) law is asymptotic. At large \(\varepsilon\) the third-order terms tilt the leftover axis away from \(z\), which the readout shows.',
 r'\(\varepsilon^2\) の法則は漸近的なものです。\(\varepsilon\) が大きいと三次の項が残りの回転軸を \(z\) から傾けます。読み取り欄で確認できます。',
 'Why is the gap second order rather than first?','隙間が一次ではなく二次なのはなぜですか？',
 r'All first-order terms cancel because each step is undone; the first survivor is the commutator term \(\varepsilon^2[Y,X]\).',
 r'各手順が打ち消されるので一次の項はすべて消え、最初に残るのが交換子の項 \(\varepsilon^2[Y,X]\) だからです。',
 [p('eps','Step size ε (radians)','刻み ε（ラジアン）',0.05,1.2,0.01,0.5)])])

add_expansion('hamiltonian-mechanics','Hamiltonian mechanics: phase space and its geometry','ハミルトン力学：相空間とその幾何','Liouville’s theorem, symplectic integrators, and Noether’s link between symmetry and conservation.','リウヴィルの定理・シンプレクティック積分法・対称性と保存則を結ぶネーターの定理を扱います。','physics','Classical mechanics and calculus of variations','古典力学と変分法','David Tong · Classical Dynamics (Cambridge lecture notes)','https://www.damtp.cam.ac.uk/user/tong/dynamics.html',[
L('phase-flow','1. Liouville: the flow keeps area','1. リウヴィル：流れは面積を保つ',
 r'Each point of phase space is a complete state (angle, momentum) of a pendulum. Drag the disc of initial states anywhere and advance time. The disc shears into a thin filament because swings of different amplitude have different periods, but its area never changes.',
 r'相空間の各点は振り子の完全な状態（角度と運動量）です。初期状態の円板を好きな所へドラッグし、時間を進めてください。振幅によって周期が違うため円板は細い糸状に引き伸ばされますが、面積は変わりません。',
 r'\dot q=\frac{\partial H}{\partial p},\quad \dot p=-\frac{\partial H}{\partial q},\qquad H=\tfrac12p^2-\cos q,\qquad \nabla\!\cdot(\dot q,\dot p)=0',
 r'The velocity field \((\partial_pH,-\partial_qH)\) has zero divergence, so by the divergence theorem the enclosed area cannot grow or shrink.',
 r'速度場 \((\partial_pH,-\partial_qH)\) の発散は 0 なので、発散定理により囲まれた面積は増えも減りもしません。',
 r'Area is kept exactly by the true flow. The readout measures the polygon through 720 boundary points, so after long times a very thin filament is slightly under-resolved.',
 r'面積を厳密に保つのは真の流れです。読み取り欄は 720 個の境界点を結ぶ多角形で測るので、長時間後のごく細い糸では解像度がわずかに不足します。',
 'What does the thick curve through (±π, 0) separate?','(±π, 0) を通る太い曲線は何を分けていますか？',
 'The separatrix divides swinging motion (closed curves) from motion that goes over the top (open curves).',
 'セパラトリクスは、往復する振動（閉曲線）と頂点を越えて回り続ける運動（開いた曲線）を分けます。',
 [p('t','Time t','時間 t',0,16,0.1,9),p('radius','Disc radius','円板の半径',0.1,0.6,0.01,0.4),p('q0','Centre angle q','中心の角度 q',-3,3,0.05,1.5),p('p0','Centre momentum p','中心の運動量 p',-2.5,2.5,0.05,0.3)]),
L('symplectic','2. Integrators that respect the geometry','2. 幾何を尊重する積分法',
 r'Integrate a Kepler orbit with three methods at the same step size. Explicit Euler spirals outward and RK4 slowly loses energy. Leapfrog is only second order, yet its energy error stays bounded over very long runs, because each of its steps is itself an exact symplectic map.',
 r'同じ刻み幅で、ケプラー軌道を三つの方法で積分します。陽的オイラー法は外へ渦を巻き、RK4 はゆっくりエネルギーを失います。リープフロッグ法は二次精度にすぎませんが、エネルギー誤差は非常に長い時間にわたって有界です。一歩一歩がそれ自体シンプレクティック写像だからです。',
 r'p_{n+\frac12}=p_n-\tfrac h2\nabla V(q_n),\quad q_{n+1}=q_n+h\,p_{n+\frac12},\quad p_{n+1}=p_{n+\frac12}-\tfrac h2\nabla V(q_{n+1})',
 r'Leapfrog almost exactly conserves a modified energy \(\tilde H=H+O(h^2)\) for exponentially long times, so the true energy only oscillates. The orbit precesses instead of decaying.',
 r'リープフロッグ法は修正エネルギー \(\tilde H=H+O(h^2)\) を指数関数的に長い時間にわたってほぼ厳密に保存するので、本当のエネルギーは振動するだけです。軌道は減衰せず歳差運動をします。',
 r'Higher order is not always better over long times. RK4 is far more accurate per step, but its errors accumulate in one direction.',
 r'長時間では高次の方が良いとは限りません。RK4 は一歩あたりの精度ははるかに高いものの、誤差が一方向に蓄積します。',
 'Why does Euler’s energy grow rather than shrink?','オイラー法のエネルギーが減らずに増えるのはなぜですか？',
 r'In the simplest case, a harmonic oscillator, each Euler step moves along the tangent to the circle of constant energy and so lands outside it: the energy is multiplied by exactly \(1+h^2\) per step.',
 r'最も簡単な調和振動子の場合、オイラー法の一歩はエネルギー一定の円の接線に沿って進むので、円の外側に出ます。エネルギーは一歩ごとにちょうど \(1+h^2\) 倍になります。',
 [p('h','Time step h','時間刻み h',0.01,0.3,0.01,0.1),p('orbits','Orbits simulated','シミュレートする周回数',1,400,1,200),p('ecc','Eccentricity e','離心率 e',0,0.8,0.05,0.5)]),
L('noether','3. Noether: symmetry gives conservation','3. ネーター：対称性が保存則を与える',
 r'A particle moves in a planar potential. With no ripple the potential is rotationally symmetric and angular momentum is conserved: the orbit is a clean rosette. Add an n-fold ripple and rotational symmetry breaks; angular momentum now wanders, while energy, protected by time-translation symmetry, stays fixed.',
 r'粒子が平面上のポテンシャルの中を動きます。うねりがなければポテンシャルは回転対称で、角運動量は保存されます。軌道はきれいなロゼットです。n 回対称のうねりを加えると回転対称性が壊れ、角運動量はさまよいますが、時間並進対称性に守られたエネルギーは一定のままです。',
 r'V(r,\phi)=\tfrac14r^4\bigl(1+\varepsilon\cos n\phi\bigr),\qquad \frac{dL}{dt}=-\frac{\partial V}{\partial\phi}=\tfrac14\varepsilon n\,r^4\sin n\phi',
 r'At \(\varepsilon=0\), \(\partial V/\partial\phi=0\), so \(L=xp_y-yp_x\) is exactly constant.',
 r'\(\varepsilon=0\) では \(\partial V/\partial\phi=0\) なので、\(L=xp_y-yp_x\) は厳密に一定です。',
 r'A discrete symmetry (rotation by \(2\pi/n\)) does not give a conserved quantity. Noether’s theorem needs a continuous family of symmetries.',
 r'離散的な対称性（\(2\pi/n\) の回転）からは保存量は得られません。ネーターの定理には連続的な対称性の族が必要です。',
 'Which symmetry protects the energy here?','ここでエネルギーを守っている対称性はどれですか？',
 'Time translation: the potential does not depend on time.','時間並進です。ポテンシャルが時間に依存しないからです。',
 [p('eps','Ripple strength ε','うねりの強さ ε',0,0.5,0.01,0.15),p('n','Ripple symmetry n','うねりの対称性 n',1,6,1,3),p('time','Duration','継続時間',5,80,1,40)])])

add_expansion('stochastic-processes','Stochastic processes: Brownian motion and noise','確率過程：ブラウン運動とノイズ','Random walks rescaled into Brownian motion, quadratic variation, and densities that obey Fokker–Planck.','ランダムウォークからブラウン運動へのスケーリング・二次変分・フォッカー・プランク方程式に従う密度を扱います。','applications','Probability, measure theory, and Markov chains','確率・測度論・マルコフ連鎖','Gregory F. Lawler · Stochastic Calculus: An Introduction with Applications','https://www.math.uchicago.edu/~lawler/finbook.pdf',[
L('scaling','1. From random walk to Brownian motion','1. ランダムウォークからブラウン運動へ',
 r'Take n coin-flip steps, shrink time by n and space by √n. As n grows, the paths stop looking like staircases and start looking like one universal random curve. Zoom in: a quarter of the time and half of the space looks statistically the same as the whole.',
 r'コイン投げの歩みを n 回とり、時間を n 分の 1、空間を √n 分の 1 に縮めます。n を増やすと経路は階段に見えなくなり、一つの普遍的なランダム曲線に見え始めます。拡大してください。時間を 4 分の 1、空間を 2 分の 1 にした部分は、統計的に全体と同じに見えます。',
 r'W_n(t)=\frac{1}{\sqrt n}\sum_{i\le nt}\xi_i\ \xrightarrow{\ d\ }\ B(t),\qquad B(ct)\overset{d}{=}\sqrt c\,B(t)',
 r'At \(t=1\), the endpoint histogram approaches the standard normal density; the shaded bands are \(\pm\sqrt t\) and \(\pm2\sqrt t\).',
 r'\(t=1\) での終点のヒストグラムは標準正規密度に近づきます。影の帯は \(\pm\sqrt t\) と \(\pm2\sqrt t\) です。',
 r'Donsker’s theorem is convergence in distribution of whole paths. Any single simulated path is still a staircase at fine enough scale.',
 r'ドンスカーの定理は経路全体の分布収束です。シミュレーションした個々の経路は、十分細かく見ればやはり階段です。',
 'Why scale space by √n rather than n?','空間を n ではなく √n で縮めるのはなぜですか？',
 r'The variance of n independent ±1 steps is n, so dividing by \(\sqrt n\) is the only choice that keeps the endpoint variance at 1.',
 r'独立な ±1 の歩み n 回の分散は n なので、\(\sqrt n\) で割るのが終点の分散を 1 に保つ唯一の選び方だからです。',
 [p('k','Steps n = 2^k','歩数 n = 2^k',2,12,1,8),p('zoom','Zoom level','拡大段階',0,3,1,0),p('seed','Random seed','乱数の種',1,50,1,7)]),
L('quadratic-variation','2. Quadratic variation','2. 二次変分',
 r'Cut [0, 1] into 2^m pieces and add up the increments of a Brownian path two ways. The sum of absolute increments grows without bound, so the path has infinite length. The sum of squared increments settles at exactly t. That single fact, dB² = dt, is why stochastic calculus needs an extra term.',
 r'[0, 1] を 2^m 個に分け、ブラウン経路の増分を二通りに足し合わせます。増分の絶対値の和は際限なく増えるので、経路の長さは無限です。一方、増分の二乗の和はちょうど t に落ち着きます。この一つの事実 dB² = dt こそ、確率解析に追加の項が必要な理由です。',
 r'\sum_k\bigl(B_{t_{k+1}}-B_{t_k}\bigr)^2\longrightarrow t,\qquad \int_0^tB\,dB=\tfrac12B_t^2-\tfrac12t\ \ (\text{It\^o})',
 r'The left-point (Itô) sum of \(B\,\Delta B\) tends to \(\tfrac12(B_1^2-1)\); the midpoint (Stratonovich) sum tends to \(\tfrac12B_1^2\). The readout computes both.',
 r'\(B\,\Delta B\) の左端点（伊藤）和は \(\tfrac12(B_1^2-1)\) に、中点（ストラトノヴィッチ）和は \(\tfrac12B_1^2\) に近づきます。読み取り欄で両方を計算します。',
 r'The path is sampled at \(2^{14}\) points, so level \(m=14\) is the finest partition the data can show; beyond that the path is a straight-line interpolation.',
 r'経路は \(2^{14}\) 点で標本化されているので、\(m=14\) がデータで示せる最も細かい分割です。それより細かくは直線補間になります。',
 'For a smooth curve, what happens to the sum of squares?','滑らかな曲線では、二乗の和はどうなりますか？',
 r'It tends to zero, because each squared increment is \(O(\Delta t^2)\) and there are only \(1/\Delta t\) of them.',
 r'0 に近づきます。各増分の二乗は \(O(\Delta t^2)\) で、それが \(1/\Delta t\) 個しかないからです。',
 [p('m','Partition level m (2^m pieces)','分割段階 m（2^m 個）',1,14,1,6),p('seed','Random seed','乱数の種',1,50,1,3)]),
L('fokker-planck','3. Paths and their density','3. 経路とその密度',
 r'An Ornstein–Uhlenbeck particle is pulled toward zero and kicked by noise. Watch individual paths wander while the density they build obeys a deterministic equation. Drag the time slice: the histogram of the simulated paths matches the exact Gaussian solution.',
 r'オルンシュタイン・ウーレンベック過程の粒子は 0 へ引き戻されながらノイズに揺さぶられます。個々の経路がさまよう一方で、それらが作る密度は決定論的な方程式に従います。時刻の断面をドラッグしてください。シミュレーション経路のヒストグラムは厳密なガウス解と一致します。',
 r'dX=-\theta X\,dt+\sigma\,dW,\qquad \partial_tp=\partial_x(\theta xp)+\tfrac{\sigma^2}{2}\partial_x^2p',
 r'Starting from \(x_0\), \(X_t\sim\mathcal N\!\bigl(x_0e^{-\theta t},\ \tfrac{\sigma^2}{2\theta}(1-e^{-2\theta t})\bigr)\). At \(\theta=0\) this is Brownian motion with variance \(\sigma^2t\).',
 r'\(x_0\) から出発すると \(X_t\sim\mathcal N\!\bigl(x_0e^{-\theta t},\ \tfrac{\sigma^2}{2\theta}(1-e^{-2\theta t})\bigr)\) です。\(\theta=0\) では分散 \(\sigma^2t\) のブラウン運動になります。',
 r'The paths use the exact Gaussian transition over each small step, so there is no discretisation bias, only sampling noise from 600 paths.',
 r'経路は小さな各刻みで厳密なガウス遷移を使うので離散化の偏りはなく、600 本の経路による標本誤差だけがあります。',
 'What is the long-run variance?','長時間後の分散はいくらですか？',
 r'\(\sigma^2/(2\theta)\): the balance between noise pumping variance in and the drift pulling it out.',
 r'\(\sigma^2/(2\theta)\) です。ノイズが分散を注ぎ込む働きと、ドリフトが引き戻す働きの釣り合いです。',
 [p('theta','Mean reversion θ','平均回帰の強さ θ',0,3,0.05,1),p('sigma','Noise σ','ノイズ σ',0.2,2,0.05,1),p('x0','Start x₀','出発点 x₀',-2,2,0.05,1.5),p('t','Time slice t','時刻の断面 t',0.05,4,0.05,1)])])

add_expansion('solid-state-physics','Solid-state physics: waves in a crystal','固体物理：結晶の中の波','Tight-binding bands, band gaps from a periodic potential, and Brillouin zones.','強束縛近似のバンド・周期ポテンシャルが生むバンドギャップ・ブリルアンゾーンを扱います。','physics','Quantum mechanics and Fourier analysis','量子力学とフーリエ解析','David Tong · Solid State Physics (Cambridge lecture notes)','https://www.damtp.cam.ac.uk/user/tong/solidstate.html',[
L('tight-binding','1. Bands from hopping','1. 飛び移りから生まれるバンド',
 r'An electron hops along a chain whose bonds alternate between strengths t₁ and t₂. Each Bloch wavevector k gives two energies, so the levels form two bands. Make the bonds unequal and a gap opens at the zone edge. Drag the gold point along the band to see the wave on the chain.',
 r'電子が、結合の強さが t₁ と t₂ で交互に変わる鎖に沿って飛び移ります。各ブロッホ波数 k に二つのエネルギーがあるので、準位は二本のバンドになります。結合を不均等にすると、ゾーン端にギャップが開きます。金色の点をバンドに沿ってドラッグし、鎖の上の波を見てください。',
 r'E_\pm(k)=\pm\bigl|t_1+t_2e^{ika}\bigr|=\pm\sqrt{t_1^2+t_2^2+2t_1t_2\cos ka}',
 r'At \(ka=\pm\pi\), \(E_\pm=\pm|t_1-t_2|\), so the gap is \(2|t_1-t_2|\). With \(t_1=t_2\) the gap closes and the chain is a single cosine band folded in half.',
 r'\(ka=\pm\pi\) では \(E_\pm=\pm|t_1-t_2|\) なので、ギャップは \(2|t_1-t_2|\) です。\(t_1=t_2\) ならギャップは閉じ、鎖は半分に折り返した一本の余弦バンドになります。',
 r'The model keeps only nearest-neighbour hopping and one orbital per site. Real band structures need more orbitals and longer-range terms.',
 r'このモデルは最近接の飛び移りと、各サイト一つの軌道だけを残しています。実際のバンド構造にはもっと多くの軌道と長距離の項が必要です。',
 'What is the group velocity at the zone edge?','ゾーン端での群速度はいくらですか？',
 r'Zero whenever \(t_1\ne t_2\): the bands are flat there, and the wave is a standing wave.',
 r'\(t_1\ne t_2\) なら 0 です。そこでバンドは平らになり、波は定在波です。',
 [p('t1','Hopping t₁','飛び移り t₁',0,2,0.05,1),p('t2','Hopping t₂','飛び移り t₂',0,2,0.05,0.5),p('k','Wavevector ka/π','波数 ka/π',-1,1,0.01,0.35)]),
L('kronig-penney','2. Band gaps from a periodic potential','2. 周期ポテンシャルが生むバンドギャップ',
 r'A free electron can have any energy. Put it in a crystal of square barriers and whole intervals of energy become forbidden. The left view shows the allowed bands as strips over the potential; the right view shows the same bands as E(k). Raise the barriers and the bands narrow while the gaps widen.',
 r'自由電子はどんなエネルギーでもとれます。四角い障壁が並ぶ結晶に入れると、エネルギーの区間ごと禁止されるようになります。左はポテンシャルの上に許されたバンドを帯として、右は同じバンドを E(k) として示します。障壁を高くするとバンドは細くなり、ギャップは広がります。',
 r'\cos ka=\cos\alpha b\,\cosh\beta c+\frac{\beta^2-\alpha^2}{2\alpha\beta}\sin\alpha b\,\sinh\beta c,\quad \alpha=\sqrt E,\ \beta=\sqrt{V_0-E}',
 r'Units with \(\hbar^2/2m=1\) and lattice constant \(a=b+c=1\). An energy is allowed exactly when the right side lies in \([-1,1]\); above the barrier \(\beta\) becomes imaginary and \(\cosh,\sinh\) turn into \(\cos,\sin\).',
 r'\(\hbar^2/2m=1\)、格子定数 \(a=b+c=1\) の単位です。右辺が \([-1,1]\) に入るときに限りエネルギーは許されます。障壁より上では \(\beta\) が虚数になり、\(\cosh,\sinh\) は \(\cos,\sin\) に変わります。',
 r'Even above the barrier top, gaps persist: every periodic potential opens gaps at the zone boundaries, though high gaps become narrow.',
 r'障壁の頂上より上でもギャップは残ります。どんな周期ポテンシャルもゾーン境界でギャップを開きますが、高い所のギャップは狭くなります。',
 'Where in k do the gaps open?','ギャップは k のどこで開きますか？',
 r'At the zone boundary \(ka=\pm\pi\) (and at \(k=0\) for higher bands), where Bragg reflection mixes \(k\) with \(k-2\pi/a\).',
 r'ゾーン境界 \(ka=\pm\pi\)（高いバンドでは \(k=0\) も）です。そこではブラッグ反射が \(k\) と \(k-2\pi/a\) を混ぜます。',
 [p('v0','Barrier height V₀','障壁の高さ V₀',0,60,0.5,20),p('width','Barrier width c','障壁の幅 c',0.05,0.5,0.01,0.2),p('energy','Probe energy E','調べるエネルギー E',0.2,45,0.1,12)]),
L('brillouin','3. Reciprocal lattice and Brillouin zones','3. 逆格子とブリルアンゾーン',
 r'Drag the second lattice vector. The reciprocal lattice rotates and stretches with it, and the Brillouin zones are recomputed: the n-th zone is the set of wavevectors for which the origin is the n-th nearest reciprocal lattice point. The zones fragment into shards, yet every zone has exactly the same area.',
 r'二本目の格子ベクトルをドラッグしてください。逆格子もそれに合わせて回転・伸縮し、ブリルアンゾーンが計算し直されます。第 n ゾーンとは、原点が n 番目に近い逆格子点となる波数の集合です。ゾーンは破片に分かれますが、どのゾーンの面積もまったく同じです。',
 r'\mathbf a_i\cdot\mathbf b_j=2\pi\,\delta_{ij},\qquad |\mathrm{BZ}_n|=\frac{(2\pi)^2}{|\mathbf a_1\times\mathbf a_2|}',
 r'At a 60° angle with equal lengths the lattice is hexagonal and the first zone is a regular hexagon; at 90° it is a square.',
 r'長さが等しく角度が 60° なら格子は六方で、第一ゾーンは正六角形になります。90° なら正方形です。',
 r'Zone areas are computed by counting pixels in the plotted window, so high zones that leave the window are reported only approximately.',
 r'ゾーンの面積は描画範囲の画素を数えて計算するので、範囲からはみ出す高次のゾーンは近似的な値になります。',
 'Why do all zones have equal area?','なぜすべてのゾーンの面積が等しいのですか？',
 'Translating the pieces of any zone by reciprocal lattice vectors reassembles exactly one copy of the first zone.',
 'どのゾーンの破片も逆格子ベクトルで平行移動すれば、ちょうど一つの第一ゾーンに組み直せるからです。',
 [p('len','Length of a₂','a₂ の長さ',0.6,1.6,0.01,1),p('ang','Angle between a₁ and a₂ (degrees)','a₁ と a₂ のなす角（度）',40,140,1,60),p('zones','Zones shown','表示するゾーン数',1,8,1,6)])])

add_expansion('control-theory','Control theory: feedback, poles, and stability','制御理論：フィードバック・極・安定性','Pole locations and step responses, PID feedback, and Bode and Nyquist diagrams.','極の位置とステップ応答・PID フィードバック・ボード線図とナイキスト線図を扱います。','applications','Dynamical systems and complex analysis','力学系と複素解析','Åström and Murray · Feedback Systems (FBSwiki)','https://fbswiki.org/wiki/index.php/Feedback_Systems:_An_Introduction_for_Scientists_and_Engineers',[
L('poles','1. Poles decide the response','1. 極が応答を決める',
 r'A second-order system has a pair of poles in the complex s-plane. Drag the upper pole (its mirror follows). Moving it left makes the response settle faster; moving it up makes it oscillate faster; crossing into the right half-plane makes it blow up.',
 r'二次系は複素 s 平面に一対の極を持ちます。上の極をドラッグしてください（鏡像の極もついてきます）。左へ動かすと応答は速く落ち着き、上へ動かすと速く振動し、右半平面へ入ると発散します。',
 r'H(s)=\frac{\sigma^2+\omega^2}{(s-\sigma)^2+\omega^2},\qquad y(t)=1-e^{\sigma t}\Bigl(\cos\omega t-\frac{\sigma}{\omega}\sin\omega t\Bigr)',
 r'For \(\sigma<0\) the overshoot is \(e^{\pi\sigma/\omega}\), which depends only on the angle of the pole from the imaginary axis, and the envelope decays like \(e^{\sigma t}\).',
 r'\(\sigma<0\) ではオーバーシュートは \(e^{\pi\sigma/\omega}\) で、虚軸から見た極の角度だけで決まります。包絡線は \(e^{\sigma t}\) のように減衰します。',
 r'The steady-state gain is normalised to one. Real systems have zeros and more poles, which change the shape but not the rule that right-half-plane poles mean instability.',
 r'定常ゲインは 1 に正規化しています。実際の系には零点や他の極があり形は変わりますが、右半平面の極が不安定を意味するという規則は変わりません。',
 'Which pole positions give the same overshoot?','どの極の位置が同じオーバーシュートを与えますか？',
 r'Every pole on the same ray from the origin, since the overshoot depends only on \(\sigma/\omega\).',
 r'原点から出る同じ半直線上のすべての極です。オーバーシュートは \(\sigma/\omega\) だけで決まるからです。',
 [p('sigma','Real part σ','実部 σ',-3,1,0.05,-0.8),p('omega','Imaginary part ω','虚部 ω',0,6,0.05,2.5)]),
L('pid','2. PID feedback','2. PID フィードバック',
 r'A sluggish third-order plant must follow a step in its set-point, and at t = 15 a load disturbance hits it. Tune the proportional, integral and derivative gains. The small plot shows the four closed-loop poles, so you can see why a tuning rings or goes unstable.',
 r'鈍い三次のプラントが目標値のステップに追従しなければならず、t = 15 で負荷外乱が加わります。比例・積分・微分ゲインを調整してください。小さな図は閉ループの四つの極を示すので、ある調整がなぜ振動したり不安定になったりするのかが分かります。',
 r'u=K_pe+K_i\!\int e\,dt-K_d\dot y,\qquad G(s)=\frac1{(s+1)^3},\qquad s^4+3s^3+(3+K_d)s^2+(1+K_p)s+K_i=0',
 r'Without the integral term a constant disturbance leaves a permanent error; any \(K_i>0\) drives it to zero, as long as the loop stays stable.',
 r'積分項がなければ一定の外乱は恒久的な誤差を残します。ループが安定である限り、\(K_i>0\) ならその誤差は 0 になります。',
 r'The derivative acts on the measurement, not on the error, so a set-point step does not cause a derivative kick. Actuator limits are not modelled.',
 r'微分は誤差ではなく測定値にかけているので、目標値のステップで微分キックは起きません。アクチュエータの制限はモデル化していません。',
 'Why can too much gain destabilise a stable plant?','なぜゲインが大きすぎると安定なプラントが不安定になるのですか？',
 r'The plant lags by up to 270°; at the frequency where the lag reaches 180°, enough gain turns negative feedback into positive feedback.',
 r'プラントの位相遅れは最大 270° に達します。遅れが 180° になる周波数で十分なゲインがあると、負帰還が正帰還に変わります。',
 [p('kp','Proportional gain Kₚ','比例ゲイン Kₚ',0,6,0.05,1.5),p('ki','Integral gain Kᵢ','積分ゲイン Kᵢ',0,3,0.05,0.6),p('kd','Derivative gain K_d','微分ゲイン K_d',0,4,0.05,1)]),
L('bode-nyquist','3. Bode and Nyquist','3. ボード線図とナイキスト線図',
 r'The loop transfer function is traced two ways: as gain and phase against frequency, and as a single curve in the complex plane. Raise the gain or add delay; when the Nyquist curve wraps around −1 the closed loop is unstable, exactly when the Bode plot shows gain above 1 at a phase of −180°.',
 r'ループ伝達関数を二通りに描きます。周波数に対するゲインと位相として、そして複素平面上の一本の曲線としてです。ゲインを上げたり遅れを加えたりしてください。ナイキスト曲線が −1 を囲むと閉ループは不安定になります。これはボード線図で位相 −180° のときにゲインが 1 を超えるのとちょうど同じ時です。',
 r'L(i\omega)=\frac{K\,e^{-i\omega\tau}}{(1+i\omega)^3},\qquad \text{closed loop stable}\iff\text{the curve does not encircle }-1',
 r'With no delay the phase crosses \(-180^\circ\) at \(\omega=\sqrt3\), where \(|L|=K/8\): the gain margin is \(8/K\), so \(K=8\) is the edge of stability.',
 r'遅れがないとき位相は \(\omega=\sqrt3\) で \(-180^\circ\) を横切り、そこで \(|L|=K/8\) です。ゲイン余裕は \(8/K\) なので、\(K=8\) が安定の境界です。',
 r'This plant is itself stable, so the simple no-encirclement rule applies. An unstable plant needs the full Nyquist criterion with counted encirclements.',
 r'このプラント自体は安定なので、囲まないという簡単な規則が使えます。不安定なプラントには、囲む回数を数える完全なナイキスト判定が必要です。',
 'Why does delay spiral the Nyquist curve?','なぜ遅れはナイキスト曲線を渦巻きにするのですか？',
 r'Delay adds phase \(-\omega\tau\) without changing gain, so as \(\omega\) grows the curve keeps winding while its radius shrinks.',
 r'遅れはゲインを変えずに位相 \(-\omega\tau\) を加えるので、\(\omega\) が増えると曲線は半径を縮めながら回り続けます。',
 [p('gain','Loop gain K','ループゲイン K',0.5,12,0.1,4),p('delay','Delay τ','遅れ τ',0,2,0.02,0)])])

add_expansion('logic-computability','Logic and computability: what can be computed','論理と計算可能性：何が計算できるか','Turing machines, the diagonal argument behind the halting problem, and Gödel numbering.','チューリング機械・停止問題の背後にある対角線論法・ゲーデル数を扱います。','foundations','Set theory and discrete mathematics','集合論と離散数学','Stanford Encyclopedia of Philosophy · Turing Machines','https://plato.stanford.edu/entries/turing-machine/',[
L('turing','1. Stepping through a Turing machine','1. チューリング機械を一歩ずつ',
 r'A head reads one cell, consults a finite table, writes, moves one cell and changes state. That is all. Choose a machine and scrub through its run; the space-time diagram below stacks every tape, so the whole computation is visible at once.',
 r'ヘッドがマスを一つ読み、有限の表を参照し、書き込み、一マス動き、状態を変えます。それだけです。機械を選んで実行の過程をたどってください。下の時空図はすべての時刻のテープを積み重ねるので、計算全体を一度に見られます。',
 r'\delta:\ Q\times\Gamma\to Q\times\Gamma\times\{L,R\}',
 r'The four-state busy beaver starts on a blank tape, halts after 107 steps and leaves 13 ones, the most any halting four-state, two-symbol machine can leave.',
 r'4 状態のビジービーバーは空白のテープから始めて 107 ステップで停止し、13 個の 1 を残します。停止する 4 状態 2 記号の機械が残せる最大数です。',
 r'Each table here is fixed and finite. What makes the model universal is that one fixed machine can read another machine’s table from its tape and simulate it.',
 r'ここでの表はどれも固定された有限のものです。このモデルを万能にするのは、ある固定された機械が別の機械の表をテープから読み取って模倣できることです。',
 'Why can nobody compute the busy beaver function in general?','なぜ一般にはビジービーバー関数を計算できないのですか？',
 'A program that computed it would bound every halting run and so would decide the halting problem.',
 'それを計算するプログラムがあれば、停止するすべての実行の長さを抑えられ、停止問題を判定できてしまうからです。',
 [c('machine','Machine','機械',0,3,1,2,[['Binary increment','二進数に 1 を足す'],['Busy beaver, 2 states','ビジービーバー（2 状態）'],['Busy beaver, 4 states','ビジービーバー（4 状態）'],['Unary addition','一進数の足し算']]),p('step','Step','ステップ',0,110,1,110)]),
L('halting','2. The diagonal argument','2. 対角線論法',
 r'Suppose some program H could tell, for every program i and input j, whether i halts on j. Then build D: on input i, D does the opposite of what the table says program i does on i. D differs from every row on the diagonal, so D is not in the table, although the table was meant to list every program. Click cells to change the table: the contradiction survives every choice.',
 r'あるプログラム H が、すべてのプログラム i と入力 j について i が j で停止するかどうかを判定できると仮定します。そこで D を作ります。D は入力 i に対して、表が示すプログラム i の i での振る舞いと逆のことをします。D は対角線上ですべての行と異なるので表に含まれません。しかし表はすべてのプログラムを並べたはずでした。マスをクリックして表を変えてください。どう選んでも矛盾は残ります。',
 r'D(i)=\begin{cases}\text{loop}&\text{if }H(i,i)=\text{halts}\\\text{halt}&\text{if }H(i,i)=\text{loops}\end{cases}\qquad D(d)\ \text{halts}\iff D(d)\ \text{loops}',
 r'If \(D\) were program number \(d\), the entry \(H(d,d)\) would have to equal its own opposite.',
 r'\(D\) がプログラム番号 \(d\) なら、成分 \(H(d,d)\) は自分自身の逆と等しくなければなりません。',
 r'The table shown is hypothetical: its entries are chosen by you or by a seed, not computed. The argument is about any table, which is the point.',
 r'表示している表は仮想的なものです。成分は計算ではなく、あなたか乱数の種が決めています。論証はどんな表にも当てはまり、それこそが要点です。',
 'Which assumption does the contradiction refute?','この矛盾はどの仮定を否定しますか？',
 'That H exists as a program that always halts with the right answer.','H が常に停止して正しい答えを返すプログラムとして存在するという仮定です。',
 [p('size','Programs listed','並べるプログラム数',4,12,1,8),p('seed','Random seed','乱数の種',1,40,1,5)]),
L('godel','3. Gödel numbering','3. ゲーデル数',
 r'Give each symbol a code and turn a formula into one number: the k-th prime raised to the code of the k-th symbol. Unique factorisation means the number can be decoded, so statements about formulas become statements about numbers. Build your own formula from the palette.',
 r'各記号に番号を与え、式を一つの数に変えます。k 番目の素数を k 番目の記号の番号乗したものを掛け合わせるのです。素因数分解の一意性によりこの数は復号できるので、式についての命題が数についての命題になります。パレットから自分の式を作ってみてください。',
 r'\ulcorner s_1s_2\cdots s_k\urcorner=2^{c(s_1)}\,3^{c(s_2)}\,5^{c(s_3)}\cdots p_k^{\,c(s_k)}',
 r'With the codes shown, \(\ulcorner 0=0\urcorner=2^{6}\cdot3^{5}\cdot5^{6}=243{,}000{,}000\).',
 r'表の番号では \(\ulcorner 0=0\urcorner=2^{6}\cdot3^{5}\cdot5^{6}=243{,}000{,}000\) です。',
 r'The particular codes are a convention. What matters is that coding and decoding are mechanical, so provability becomes an arithmetical property.',
 r'個々の番号の付け方は約束事にすぎません。重要なのは符号化と復号が機械的に行えることで、それにより証明可能性が算術的な性質になります。',
 'Why use primes rather than just writing the codes side by side?','なぜ番号を並べて書くだけでなく素数を使うのですか？',
 'The product is a single natural number that arithmetic can talk about, and unique factorisation guarantees it decodes to exactly one sequence.',
 '積は算術が扱える一つの自然数であり、素因数分解の一意性がそれをただ一つの記号列に復号できることを保証するからです。',
 [c('formula','Formula','式',0,3,1,1,[['0 = 0','0 = 0'],['S0 + S0 = SS0','S0 + S0 = SS0'],['¬(0 = S0)','¬(0 = S0)'],['∀x (x = x)','∀x (x = x)']])])])

extra_sources.update({
 'halting':('Stanford Encyclopedia of Philosophy · Computability and Complexity','https://plato.stanford.edu/entries/computability/'),
 'godel':('Stanford Encyclopedia of Philosophy · Gödel’s Incompleteness Theorems','https://plato.stanford.edu/entries/goedel-incompleteness/'),
})
