from pathlib import Path
import json, html, importlib.util
ROOT=Path(__file__).resolve().parents[1]
D=[]
def topic(slug,en,ja,desc,jdesc,group,prereq,jpre,source,url):
 t=dict(slug=slug,title=[en,ja],description=[desc,jdesc],group=group,prerequisite=[prereq,jpre],source=source,url=url,labs=[]);D.append(t);return t

def lab(t,id,en,ja,body,jbody,formula,example,jexample,caution,jcaution,question,jquestion,answer,janswer,params):
 t['labs'].append(dict(id=id,title=[en,ja],body=[body,jbody],formula=formula,example=[example,jexample],caution=[caution,jcaution],question=[question,jquestion],answer=[answer,janswer],params=params))
def p(key,en,ja,lo,hi,step,value):return [key,en,ja,lo,hi,step,value]
t=topic('linear-algebra','Linear algebra: the geometry of transformations','線形代数：変換の幾何','Coordinates, area, eigenvectors, projection, and singular values.','座標・面積・固有ベクトル・射影・特異値を実験します。','foundations','Vectors and elementary algebra','ベクトルと初等代数','MIT OpenCourseWare · Linear Algebra','https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/')
lab(t,'basis','1. Basis and coordinates','1. 基底と座標','Drag the two circular basis handles or use the sliders. The highlighted physical vector stays at (1,1), while its coordinates in the new basis change. The columns of a matrix are the images of the standard basis.','円形のハンドルをドラッグするか、スライダーで基底を変えてください。強調したベクトル (1,1) は動きませんが、新しい基底での座標は変わります。行列の列は標準基底の像です。',r'B[v]_B=v,\qquad [v]_B=B^{-1}v','For B=diag(2,1), the coordinates of (1,1) are (1/2,1).','B=diag(2,1) なら (1,1) の座標は (1/2,1) です。','Dependent columns do not form a basis; an inverse does not exist.','列が一次従属なら基底ではなく、逆行列は存在しません。','What happens when the two columns coincide?','2つの列が一致するとどうなりますか？','The plane collapses to a line. Coordinates are no longer unique when a solution exists.','平面が直線に潰れます。解が存在しても座標は一意に定まりません。',[p('a','First basis x','第1基底 x',-2,2,.1,1),p('b','First basis y','第1基底 y',-2,2,.1,0),p('c','Second basis x','第2基底 x',-2,2,.1,.5),p('d','Second basis y','第2基底 y',-2,2,.1,1)])
lab(t,'det','2. Determinant and rank','2. 行列式と階数','The unit square becomes a parallelogram. Its area is the absolute determinant; the sign records orientation. Set one scale to zero to see rank fall.','単位正方形は平行四辺形になります。面積は行列式の絶対値で、符号は向きを表します。倍率を0にして階数の低下を観察します。',r'\det A=ad-bc,\qquad \operatorname{area}(A(S))=|\det A|\operatorname{area}(S)','For diag(-2,1), area doubles and orientation reverses.','diag(-2,1) は面積を2倍にし、向きを反転します。','A determinant of one preserves area, but need not preserve lengths or angles.','行列式が1でも、長さや角度を保つとは限りません。','Can a shear change shape without changing area?','せん断は面積を変えずに形を変えられますか？','Yes. The matrix with rows (1,s) and (0,1) has determinant one for every s.','はい。行が (1,s)、(0,1) の行列は、どの s でも行列式が1です。',[p('a','Horizontal scale','横方向の倍率',-2,2,.1,1),p('d','Vertical scale','縦方向の倍率',-2,2,.1,1),p('c','Shear','せん断',-2,2,.1,.7)])
lab(t,'eigen','3. Eigenvectors and iteration','3. 固有ベクトルと反復','Rotate the eigenbasis and change its two eigenvalues. Repeated application scales each eigenvector component separately. Dashed lines mark the invariant directions.','固有基底を回転させ、2つの固有値を変えます。反復で各固有ベクトル成分が別々に伸縮します。破線は不変な方向です。',r'A=Q\operatorname{diag}(\lambda_1,\lambda_2)Q^T,\quad A^nv=Q\operatorname{diag}(\lambda_1^n,\lambda_2^n)Q^Tv','With eigenvalues 1.2 and 0.5, one component grows while the other decays.','固有値が1.2と0.5なら、一方の成分は増大し、他方は減衰します。','This laboratory uses real symmetric matrices. A real rotation need not have a real eigenvector.','この実験は実対称行列に限定しています。実数の回転行列に実固有ベクトルがあるとは限りません。','If both eigenvalues have magnitude below one, where does every orbit go?','両方の固有値の絶対値が1未満なら、軌道はどこへ向かいますか？','To the origin, because both scalar powers tend to zero.','両方の固有値の累乗が0に近づくため、原点へ向かいます。',[p('l1','Eigenvalue 1','固有値1',-.9,1.4,.1,1.2),p('l2','Eigenvalue 2','固有値2',-.9,1.4,.1,.5),p('angle','Basis angle (degrees)','基底の角度（度）',0,180,5,30),p('n','Iterations','反復回数',0,8,1,3)])
lab(t,'projection','4. Least squares as projection','4. 射影としての最小二乗法','Rotate a line through the origin. The closest point on it to v=(2,1) is the orthogonal projection. The residual is perpendicular to the line.','原点を通る直線を回転させます。v=(2,1) に最も近い直線上の点は直交射影です。残差は直線に垂直です。',r'\hat v=u(u^Tv),\quad \|u\|=1,\qquad u^T(v-\hat v)=0','Projecting (2,1) onto the x-axis gives (2,0), with residual (0,1).','(2,1) の x 軸への射影は (2,0)、残差は (0,1) です。','A fitted projection minimizes squared error, not necessarily every other loss function.','射影が最小化するのは二乗誤差で、すべての損失関数ではありません。','When is the residual zero?','残差が0になるのはいつですか？','When the vector lies on the chosen line.','ベクトルが選んだ直線上にあるときです。',[p('angle','Line angle (degrees)','直線の角度（度）',0,180,1,20)])
lab(t,'svd','5. Singular values and rank','5. 特異値と階数','Rotate the input, stretch along two perpendicular axes, then rotate the output. The image of the unit circle is an ellipse. Removing the smaller stretch gives a rank-one approximation.','入力を回転し、直交する2方向に伸縮させ、出力を回転します。単位円の像は楕円です。小さい方の伸縮を除くと階数1の近似になります。',r'A=U\Sigma V^T,\quad A_1=\sigma_1u_1v_1^T,\quad \|A-A_1\|_2=\sigma_2','For diag(2,0.5), the best rank-one approximation is diag(2,0), with operator-norm error 0.5.','diag(2,0.5) の最良の階数1近似は diag(2,0) で、作用素ノルムの誤差は0.5です。','Singular values are nonnegative; they are not generally the eigenvalues of A.','特異値は非負ですが、一般には A の固有値とは異なります。','What happens when the second singular value is zero?','第2特異値が0だとどうなりますか？','The ellipse collapses to a segment and the rank is one.','楕円は線分に潰れ、階数は1になります。',[p('s1','First singular value','第1特異値',1,3,.1,2),p('s2','Second singular value','第2特異値',0,1,.05,.5),p('angle','Output rotation (degrees)','出力の回転（度）',0,180,5,30),p('input','Input rotation (degrees)','入力の回転（度）',0,180,5,20),p('rank','Retained rank','残す階数',1,2,1,2)])
t=topic('fourier-analysis','Fourier analysis: functions made of waves','フーリエ解析：波で関数を作る','Harmonics, convolution, and the limits of sampling.','調和波・畳み込み・標本化の限界を探ります。','analysis','Trigonometry and integration','三角関数と積分','Stanford · The Fourier Transform and its Applications','https://see.stanford.edu/Course/EE261')
lab(t,'harmonics','1. Reconstruct a square wave','1. 矩形波を再構成する','Add odd harmonics to a square wave. Smooth regions converge, but overshoot near each jump persists while becoming narrower. At a jump the series converges to the midpoint.','矩形波に奇数次の調和波を加えます。滑らかな部分は収束しますが、跳躍の近くの行き過ぎは幅を狭めながら残ります。跳躍点では左右の値の平均へ収束します。',r'S_N(x)=\frac4\pi\sum_{k=0}^{N-1}\frac{\sin((2k+1)x)}{2k+1}','The first approximation is 4 sin(x)/π. Its amplitude exceeds one.','最初の近似は 4 sin(x)/π で、振幅は1を超えます。','More terms do not remove the limiting Gibbs overshoot relative to the jump size.','項数を増やしても、跳躍幅に対するギブス現象の行き過ぎの比率は0になりません。','Does convergence have to be uniform?','必ず一様収束しますか？','No. Continuous partial sums cannot converge uniformly to a discontinuous function.','いいえ。連続な部分和が不連続な関数へ一様収束することはありません。',[p('n','Odd harmonics','奇数次の項数',1,30,1,5)])
lab(t,'convolution','2. Convolution as overlap','2. 重なりとしての畳み込み','Slide one unit-width rectangular pulse over another. Their convolution is the overlap length: a triangular function. The filled overlap and marked output are linked.','幅1の矩形パルスを別のパルスに重ねて動かします。畳み込みは重なりの長さとなり、三角形の関数になります。塗られた重なりと出力点が連動します。',r'(f*g)(t)=\int_{\mathbb R}f(\tau)g(t-\tau)\,d\tau=\max(0,1-|t|)','At displacement t=0.25 the overlap is 0.75.','ずれ t=0.25 で重なりは0.75です。','Convolution includes a reversal before shifting. The reversal is invisible for these symmetric pulses.','畳み込みでは移動の前に反転します。この対称なパルスでは反転が見えません。','Why is the output zero at displacement 1.2?','ずれが1.2なら出力が0になるのはなぜですか？','The two supports no longer overlap.','2つの台が重ならないためです。',[p('t','Displacement','ずれ',-1.5,1.5,.05,.25)])
lab(t,'sampling','3. Sampling and aliasing','3. 標本化とエイリアシング','Compare a continuous cosine with equally spaced samples. The dashed cosine is the folded frequency that gives the same samples. Raise the sampling rate to separate frequencies.','連続な余弦波と等間隔の標本を比較します。破線は同じ標本値を与える折り返し周波数の余弦波です。標本化周波数を上げて区別します。',r'x_n=\cos(2\pi f n/f_s),\qquad f_{\rm alias}=\left|((f+f_s/2)\bmod f_s)-f_s/2\right|','A 7 Hz cosine sampled at 10 Hz shares its samples with a 3 Hz cosine.','7 Hz の余弦波を10 Hzで標本化すると、3 Hz の余弦波と標本値が一致します。','The sampling theorem assumes a band-limited signal and ideal reconstruction. Finite samples do not uniquely identify arbitrary signals.','標本化定理は帯域制限と理想的な再構成を仮定します。有限個の標本だけで任意の信号は特定できません。','What sampling rate avoids aliasing for a signal band-limited to 7 Hz?','7 Hz以下に帯域制限された信号で折り返しを避ける標本化周波数は？','Choose a rate strictly greater than 14 Hz.','14 Hzより大きい周波数を選びます。',[p('f','Signal frequency (Hz)','信号周波数（Hz）',1,12,.5,7),p('fs','Sampling rate (Hz)','標本化周波数（Hz）',2,30,1,10)])
t=topic('dynamical-systems','Dynamical systems: stability and chaos','力学系：安定性とカオス','Phase portraits, changing equilibria, and sensitive dependence.','相図・平衡点の変化・初期値への鋭敏な依存を調べます。','analysis','Derivatives and elementary differential equations','微分と初歩的な微分方程式','MIT · Nonlinear Dynamics: Chaos','https://ocw.mit.edu/courses/12-006j-nonlinear-dynamics-chaos-fall-2022/')
lab(t,'phase','1. A spiral in phase space','1. 相空間のらせん','The arrows give the instantaneous direction of motion. Change the growth rate to turn a decaying spiral into a growing one. The trajectory is an exact solution, sampled for display.','矢印は瞬間的な運動の向きです。増大率を変えると、減衰するらせんが増大するらせんになります。軌道は厳密解を描画用に標本化しています。',r'\dot x=ax-y,\quad\dot y=x+ay,\quad z(t)=e^{(a+i)t}z(0)','At a=-0.2 the radius is multiplied by exp(-0.2t).','a=-0.2 では半径が exp(-0.2t) 倍になります。','A center at a=0 is stable but not asymptotically stable.','a=0 の中心は安定ですが、漸近安定ではありません。','What changes sign at the stability threshold?','安定性の境界で何の符号が変わりますか？','The real parts of the eigenvalues a±i.','固有値 a±i の実部です。',[p('a','Growth rate','増大率',-.5,.5,.05,-.2),p('x','Initial x','初期 x',-2,2,.1,1),p('y','Initial y','初期 y',-2,2,.1,0)])
lab(t,'bifurcation','2. A saddle-node bifurcation','2. サドルノード分岐','Move the parameter through zero. Two equilibria are born when the graph first touches and then crosses the horizontal axis. Arrows show the sign of the velocity.','パラメータを0の前後で動かします。グラフが横軸に接してから交差すると、2つの平衡点が生まれます。矢印は速度の符号を示します。',r'\dot x=\mu-x^2,\quad x_*=\pm\sqrt\mu\ (\mu\ge0),\quad f\prime(x_*)=-2x_*','For μ=1, x=1 is attracting and x=-1 is repelling.','μ=1 では x=1 が吸引的、x=-1 が反発的です。','At μ=0 the equilibrium attracts from only one side. A zero derivative alone does not classify stability.','μ=0 の平衡点は片側からのみ吸引します。微分が0というだけでは安定性は分類できません。','How many real equilibria exist when μ is negative?','μが負のとき実平衡点はいくつありますか？','None, because x² cannot equal a negative number.','0個です。x²は負の数と等しくなりません。',[p('mu','Parameter μ','パラメータ μ',-1,2,.05,1)])
lab(t,'chaos','3. The logistic map','3. ロジスティック写像','Compare two orbits whose starting values differ by one millionth. Parameter changes can produce convergence, cycles, or sensitive dependence. The lower panel samples long-run values across parameters.','初期値が100万分の1だけ違う2つの軌道を比較します。パラメータにより収束・周期・鋭敏な依存が現れます。下の図は各パラメータで過渡状態を除いた値です。',r'x_{n+1}=rx_n(1-x_n),\quad 0\le r\le4','For r=2, most interior initial values approach 1/2.','r=2 では区間内部の多くの初期値が1/2へ近づきます。','A finite orbit is not a proof of chaos. Periodic windows occur inside the complicated parameter region.','有限の軌道はカオスの証明ではありません。複雑なパラメータ領域にも周期窓があります。','Does r greater than 3 always imply chaos?','rが3より大きければ必ずカオスですか？','No. Stable periodic cycles also occur.','いいえ。安定な周期軌道も現れます。',[p('r','Parameter r','パラメータ r',2,4,.01,3.8),p('x','Initial value','初期値',.05,.9,.01,.2)])
t=topic('optimization','Optimization: the geometry of the best choice','最適化：最良の選択の幾何','Descent, conditioning, constraints, and shadow prices.','降下法・条件数・制約・影の価格を調べます。','applications','Derivatives, vectors, and matrices','微分・ベクトル・行列','Boyd and Vandenberghe · Convex Optimization','https://stanford.edu/~boyd/cvxbook/')
lab(t,'descent','1. Gradient descent and conditioning','1. 勾配降下法と条件数','Follow gradient steps across elliptical contours. Strongly unequal curvatures make steps zigzag. Newton’s exact step reaches this quadratic minimum in one iteration.','楕円の等高線を横切る勾配ステップを追います。曲率の差が大きいとジグザグになります。この二次関数ではニュートン法の厳密な1ステップで最小点に達します。',r'f(x,y)=\tfrac12(x^2+\kappa y^2),\quad x_{n+1}=(1-\eta)x_n,\quad y_{n+1}=(1-\eta\kappa)y_n','For κ=4, constant-step gradient descent converges when 0<η<0.5.','κ=4 のとき、一定刻みの勾配降下法は 0<η<0.5 で収束します。','Newton’s one-step result is special to an invertible quadratic Hessian. It is not a general guarantee.','1ステップで収束する性質は、可逆なヘッセ行列を持つ二次関数に特有です。一般には保証されません。','Why can increasing the step size make progress worse?','刻み幅を大きくすると悪化することがあるのはなぜですか？','An update multiplier can have magnitude above one, amplifying errors.','更新の倍率の絶対値が1を超え、誤差を増幅するためです。',[p('k','Condition number κ','条件数 κ',1,10,1,4),p('eta','Step size η','刻み幅 η',.02,.8,.02,.2)])
lab(t,'constraint','2. A moving constraint','2. 動く制約','Move the line x+y=b across concentric objective contours. The optimum is where the smallest reachable circle touches the line.','直線 x+y=b を目的関数の同心円に沿って動かします。到達できる最小の円が直線に接する点が最適点です。',r'\min_{x+y=b}(x^2+y^2),\qquad x_*=y_*=b/2,\quad f_*=b^2/2','For b=2, the best point is (1,1), with objective value 2.','b=2 の最適点は (1,1)、目的関数値は2です。','This is an equality constraint. Replacing it with an inequality changes the feasible region and sometimes the optimum.','これは等式制約です。不等式に変えると実行可能領域や最適点が変わることがあります。','Why must x and y be equal at the optimum?','最適点で x と y が等しくなるのはなぜですか？','Because x²+y²=b²/2+(x-y)²/2, minimized at x=y.','x²+y²=b²/2+(x-y)²/2 なので、x=y で最小になります。',[p('b','Constraint value b','制約値 b',-3,3,.1,2)])
lab(t,'duality','3. Multipliers and sensitivity','3. 乗数と感度','The optimal value curve tells us how costly a change in the constraint is. The tangent slope equals the multiplier when the Lagrangian uses λ(b-x-y).','最適値の曲線は制約変更の費用を表します。ラグランジアンを λ(b-x-y) と定義すると、接線の傾きが乗数に一致します。',r'L=x^2+y^2+\lambda(b-x-y),\quad g(\lambda)=\lambda b-\lambda^2/2,\quad \lambda_*=b=\frac{df_*}{db}','At b=2, increasing b by 0.01 raises the optimum by about 0.02.','b=2 で b を0.01増やすと、最適値は約0.02増えます。','Multiplier signs depend on the chosen constraint convention. Sensitivity is a local approximation.','乗数の符号は制約の書き方に依存します。感度は局所的な近似です。','What is the duality gap at λ=b?','λ=b の双対ギャップはいくつですか？','Zero: the primal minimum and dual maximum both equal b²/2.','0です。主問題の最小値も双対問題の最大値も b²/2 です。',[p('b','Constraint value b','制約値 b',-3,3,.1,1.5),p('lambda','Trial multiplier λ','試す乗数 λ',-4,4,.1,0)])
t=topic('probability-inference','Probability: learning from uncertainty','確率：不確実性から学ぶ','Bayesian updating, sums of random variables, and conditional probability.','ベイズ更新・確率変数の和・条件付き確率を学びます。','applications','Fractions, counting, and basic probability','分数・場合の数・初歩的な確率','Brown University · Seeing Theory','https://seeing-theory.brown.edu/bayesian-inference/index.html')
lab(t,'bayes','1. Update a belief','1. 信念を更新する','Choose a beta prior and counts of heads and tails. The updated density combines the prior with the likelihood. The dashed curve shows the prior for comparison.','ベータ事前分布と表・裏の回数を選びます。更新した密度は事前分布と尤度を組み合わせます。破線は比較用の事前分布です。',r'p\sim\operatorname{Beta}(\alpha,\beta),\quad p\mid h,t\sim\operatorname{Beta}(\alpha+h,\beta+t)','A uniform prior with 3 heads and 1 tail gives Beta(4,2), whose mean is 2/3.','一様な事前分布に表3回・裏1回なら Beta(4,2) となり、平均は2/3です。','The model assumes independent flips with a fixed unknown probability. A posterior is conditional on these assumptions.','各試行は独立で、未知の確率は一定と仮定しています。事後分布はこの仮定に依存します。','Why is the posterior mean not exactly the observed fraction?','事後平均が観測比率そのものにならないのはなぜですか？','The prior also contributes information; its relative influence decreases as observations accumulate.','事前分布も情報を持つためです。観測が増えるとその相対的影響は小さくなります。',[p('alpha','Prior α','事前 α',1,8,1,1),p('beta','Prior β','事前 β',1,8,1,1),p('h','Heads','表',0,30,1,3),p('t','Tails','裏',0,30,1,1)])
lab(t,'clt','2. Standardized sums','2. 標準化した和','Increase the number of independent Bernoulli trials. Bars show exact binomial mass divided by the standardized bin width; the curve is the standard normal density.','独立なベルヌーイ試行の回数を増やします。棒は厳密な二項確率を標準化した区間幅で割ったもの、曲線は標準正規密度です。',r'Z_n=\frac{S_n-np}{\sqrt{np(1-p)}}\ \xrightarrow{d}\ N(0,1),\quad 0<p<1','For n=20 and p=0.5, the sum has mean 10 and variance 5.','n=20、p=0.5 の和の平均は10、分散は5です。','The central limit theorem concerns distributional convergence. Small n or highly skewed trials can give poor approximations.','中心極限定理は分布の収束を述べます。nが小さい場合や偏りが大きい場合、近似は悪くなります。','Does the theorem say individual trials become normally distributed?','個々の試行が正規分布になるという意味ですか？','No. The standardized sum approaches a normal law; each trial remains Bernoulli.','いいえ。標準化した和が正規分布に近づき、各試行はベルヌーイ分布のままです。',[p('n','Trials','試行回数',2,60,1,20),p('p','Success probability','成功確率',.1,.9,.05,.5)])
lab(t,'conditional','3. Conditional probability','3. 条件付き確率','A unit square is the sample space. Event B is a vertical strip; the part of A inside and outside B can have different heights. Conditioning on B changes the denominator.','単位正方形を標本空間とします。Bは縦の帯で、Aの高さはBの内外で変えられます。Bで条件付けると分母が変わります。',r'P(A\mid B)=\frac{P(A\cap B)}{P(B)},\quad P(A)=P(A\mid B)P(B)+P(A\mid B^c)P(B^c)','If P(B)=0.4 and P(A|B)=0.75, then P(A∩B)=0.3.','P(B)=0.4、P(A|B)=0.75 なら P(A∩B)=0.3 です。','Conditional probability is not generally symmetric: P(A|B) and P(B|A) can differ.','条件付き確率は一般に対称ではなく、P(A|B) と P(B|A) は異なり得ます。','When are A and B independent here?','この図で A と B が独立になるのはいつですか？','When the two conditional heights are equal, so knowing B does not change the probability of A.','2つの条件付きの高さが等しく、Bを知ってもAの確率が変わらないときです。',[p('b','Probability of B','Bの確率',.1,.9,.05,.4),p('inside','A given B','Bの下でのA',0,1,.05,.75),p('outside','A given not B','B以外でのA',0,1,.05,.25)])
t=topic('group-theory','Group theory: symmetry as algebra','群論：対称性を代数にする','Compose symmetries, inspect group tables, and count orbits.','対称変換の合成・群の表・軌道の数え上げを学びます。','foundations','Functions and composition','関数と合成','Thomas Judson · Abstract Algebra: Theory and Applications','https://judsonbooks.org/aata-files/aata-20110810.pdf')
lab(t,'compose','1. Order matters','1. 順序が重要','Label a regular polygon, then compare a rotation after reflection with reflection after rotation. Labels let us distinguish transformations that leave the outline unchanged.','正多角形の頂点に番号を付け、反転後の回転と回転後の反転を比較します。輪郭が同じでも番号により変換を区別できます。',r'D_n=\langle r,s\mid r^n=e,\ s^2=e,\ srs=r^{-1}\rangle','For a square, a quarter-turn and a reflection do not commute.','正方形の90度回転と反転は交換しません。','An unchanged outline does not mean every vertex stayed fixed.','輪郭が同じでも各頂点が固定されているとは限りません。','When do the two displayed compositions agree?','表示した2つの合成が一致するのはいつですか？','When 2k is divisible by n, including zero rotation and a half-turn for even n.','2kがnで割り切れるときです。回転なし、またはnが偶数なら半回転が該当します。',[p('n','Polygon sides','辺の数',3,8,1,4),p('k','Rotation steps','回転ステップ',0,7,1,1)])
lab(t,'table','2. A multiplication table','2. 積の表','Explore the cyclic subgroup of rotations. A cell in row a and column b records a rotation by a+b steps modulo n. Highlight a pair and check its inverse.','回転からなる巡回部分群を調べます。行a・列bは、a+bをnで割った余りの回転です。組を選び、逆元を確かめます。',r'C_n=\mathbb Z/n\mathbb Z,\qquad a*b=(a+b)\bmod n','In C₅, 3+4=2 modulo 5, and the inverse of 3 is 2.','C₅では 3+4≡2、3の逆元は2です。','This rotation subgroup is commutative; the full dihedral group generally is not.','回転部分群は可換ですが、二面体群全体は一般に可換ではありません。','Why does each row contain every group element once?','各行にすべての元が1回ずつ現れるのはなぜですか？','Adding a fixed element is a bijection, with subtraction as its inverse.','固定した元を加える操作は全単射で、引き算が逆操作だからです。',[p('n','Group order','群の位数',3,8,1,5),p('a','Row a','行 a',0,7,1,3),p('b','Column b','列 b',0,7,1,4)])
lab(t,'orbit','3. Orbits, stabilizers, and cosets','3. 軌道・固定部分群・剰余類','Generate rotations by k steps and mark the vertices reachable from vertex zero. Other colors of position are avoided: reachable vertices are filled, others open. The subgroup cosets partition the vertices into equal orbits.','kステップの回転で生成される群を作り、頂点0から到達できる頂点を塗ります。その他は白抜きです。部分群の剰余類が頂点を同じ大きさの軌道に分けます。',r'|\langle k\rangle|=\frac n{\gcd(n,k)},\qquad |Gx|=\frac{|G|}{|G_x|}','For n=6 and k=2, the orbits are {0,2,4} and {1,3,5}.','n=6、k=2 の軌道は {0,2,4} と {1,3,5} です。','For the full dihedral action on vertices the stabilizer has two elements; for a rotation subgroup it is trivial.','頂点への二面体群全体の作用では固定部分群の位数は2ですが、回転部分群では1です。','How many cosets does the generated subgroup have?','生成された部分群の剰余類はいくつですか？','gcd(n,k), since each coset has n/gcd(n,k) elements.','gcd(n,k) 個です。各剰余類には n/gcd(n,k) 個の元があります。',[p('n','Vertices','頂点数',3,12,1,6),p('k','Generator steps','生成元のステップ',0,11,1,2)])
t=topic('algebraic-topology','Algebraic topology: detecting holes','代数的位相幾何：穴を見つける','Build complexes, distinguish cycles from holes, and vary scale.','複体を作り、閉路と穴を区別し、尺度を変えて調べます。','geometry','Sets, graphs, and elementary linear algebra','集合・グラフ・初歩的な線形代数','Allen Hatcher · Algebraic Topology, Chapter 2','https://pi.math.cornell.edu/~hatcher/AT/ATpage.html')
lab(t,'complex','1. Build a complex','1. 複体を作る','Add the edges of a triangle, then its filled face. The third edge creates a cycle; the face makes that cycle a boundary and removes the one-dimensional hole.','三角形の辺を加え、最後に面を埋めます。3本目の辺で閉路ができ、面を加えると閉路が境界となって1次元の穴が消えます。',r'\beta_0=V-\operatorname{rank}\partial_1,\quad\beta_1=E-\operatorname{rank}\partial_1-\operatorname{rank}\partial_2','Three vertices and three edges give β₀=1, β₁=1. Adding the face gives β₁=0.','頂点3・辺3なら β₀=1、β₁=1。面を加えると β₁=0 です。','A drawn loop is not necessarily a homological hole: it may bound a filled surface.','描かれた閉路が必ず穴を表すとは限りません。面の境界かもしれません。','Why does filling the face not change the number of components?','面を埋めても連結成分数が変わらないのはなぜですか？','Its boundary already belongs to one connected component.','その境界はすでに1つの連結成分に属しているためです。',[p('stage','Construction stage','構成段階',0,4,1,3)])
lab(t,'filtration','2. Holes across scales','2. 尺度を変えて穴を見る','Eight points lie on a circle. Connect pairs within the threshold and fill every triangle whose three edges are present. Compute homology over the two-element field using boundary-matrix ranks.','円周上に8点を置きます。閾値以内の点を結び、3辺がある三角形をすべて埋めます。2元体上の境界行列の階数からホモロジーを計算します。',r'H_1=\ker\partial_1/\operatorname{im}\partial_2,\qquad \partial_1\partial_2=0','At a threshold of 0.8, adjacent points form an octagonal loop with β₁=1.','閾値0.8では隣接点が八角形の閉路を作り、β₁=1です。','Only the two-skeleton is displayed. It suffices for H₀ and H₁, but not for higher-dimensional homology.','表示は2次元骨格のみです。H₀とH₁には十分ですが、高次のホモロジーには不十分です。','Why can a larger threshold destroy a hole?','閾値を大きくすると穴が消えるのはなぜですか？','New triangular faces can fill a previously unfilled cycle.','新しい三角形の面が、それまで埋まっていなかった閉路を埋めるためです。',[p('eps','Distance threshold','距離の閾値',.1,2.1,.05,.8)])
lab(t,'euler','3. Euler characteristic','3. オイラー標数','Choose a triangulated disk or the boundary of a tetrahedron. Count vertices, edges, and faces. The alternating sum agrees with the alternating sum of Betti numbers.','三角形の円板または四面体の境界を選びます。頂点・辺・面を数える交代和は、ベッチ数の交代和と一致します。',r'\chi=V-E+F=\beta_0-\beta_1+\beta_2','A tetrahedron boundary has 4−6+4=2, with β₀=1, β₁=0, β₂=1.','四面体の境界は 4−6+4=2 で、β₀=1、β₁=0、β₂=1 です。','The tetrahedron here is its surface, not the solid including its interior.','ここでの四面体は表面だけであり、内部を含む立体ではありません。','Why does a disk have Euler characteristic one?','円板のオイラー標数が1なのはなぜですか？','It has one component and no positive-dimensional homology.','連結成分が1つで、正の次元のホモロジーがないためです。',[p('solid','Disk (0) / tetrahedron surface (1)','円板 (0) ／四面体表面 (1)',0,1,1,1)])
t=topic('numerical-analysis','Numerical analysis: when computation misleads','数値解析：計算が誤解を招くとき','Time stepping, cancellation, and interpolation error.','時間刻み・桁落ち・補間誤差を調べます。','applications','Calculus and basic differential equations','微積分と初歩的な微分方程式','Jiří Lebl · Notes on Diffy Qs, Numerical Methods','https://www.jirka.org/diffyqs/html/numer_section.html')
lab(t,'ode','1. Accuracy and stability','1. 精度と安定性','Compare explicit Euler and fourth-order Runge–Kutta with exact exponential decay. Increase the step size until a numerical solution behaves unlike the true solution.','陽的オイラー法と4次ルンゲ・クッタ法を指数減衰の厳密解と比較します。刻み幅を増やし、数値解が真の解と異なる振る舞いをする点を探します。',r'y\prime=-5y,\ y(0)=1,\quad y(t)=e^{-5t},\quad y_{n+1}^{\rm Euler}=(1-5h)y_n','At h=0.5, Euler multiplies each step by −1.5 and diverges.','h=0.5 のオイラー法は毎回−1.5倍になり、発散します。','Higher order does not guarantee stability for every step size. Both methods here are explicit.','高次の方法でも任意の刻み幅で安定とは限りません。ここでは両方とも陽解法です。','What is Euler’s strict stability interval for this equation?','この方程式でオイラー法が厳密に安定となる刻み幅の区間は？','0<h<0.4, because |1−5h|<1.','|1−5h|<1 より 0<h<0.4 です。',[p('h','Step size h','刻み幅 h',.025,.6,.025,.1)])
lab(t,'cancellation','2. Subtracting almost equal numbers','2. 近い数を引くとき','Compare direct evaluation with an algebraically equivalent rationalized expression. As x shrinks, rounding can erase the small difference between the square root and one.','直接計算と有理化した等価な式を比較します。xが小さくなると丸め誤差で平方根と1の小さな差が失われます。',r'\frac{\sqrt{1+x}-1}{x}=\frac1{\sqrt{1+x}+1}\longrightarrow\frac12','At x=10⁻¹⁶, binary64 commonly rounds 1+x to 1, so the direct numerator becomes zero.','x=10⁻¹⁶ では通常の倍精度で 1+x が1に丸められ、直接計算の分子が0になります。','The plotted error uses the stable equivalent as a reference; it is not an arbitrary-precision certificate.','誤差は安定な等価式を基準にしています。任意精度計算による保証ではありません。','Does making x smaller always improve a numerical limit estimate?','xを小さくすれば数値的な極限の推定は必ず改善しますか？','No. Truncation error may shrink while roundoff error becomes dominant.','いいえ。打切り誤差が小さくなる一方、丸め誤差が支配的になることがあります。',[p('exponent','Decimal exponent: x = 10⁻ᵉ','指数：x = 10⁻ᵉ',1,17,1,12)])
lab(t,'interpolation','3. Where you sample matters','3. 標本点の置き方が重要','Interpolate the Runge function with a polynomial. Compare equally spaced nodes with Chebyshev–Lobatto nodes clustered near the ends. Dots mark the interpolation data.','ルンゲ関数を多項式で補間します。等間隔点と端点付近に集まるチェビシェフ・ロバット点を比較します。点は補間に使ったデータです。',r'f(x)=\frac1{1+25x^2},\quad x_j^{\rm Cheb}=\cos(j\pi/n),\quad j=0,\ldots,n','For degree 10, equally spaced interpolation oscillates strongly near the endpoints.','10次の等間隔補間は端点付近で大きく振動します。','The displayed maximum error is sampled, not a rigorous supremum bound. More nodes alone need not improve interpolation.','表示する最大誤差は標本上の値で、厳密な上限ではありません。点を増やすだけで改善するとは限りません。','Why can a perfect fit at all nodes still be misleading?','すべての点で完全に一致しても誤解を招くのはなぜですか？','Values between nodes can oscillate dramatically; fitting data and approximating a function are different requirements.','点の間で大きく振動し得るためです。データへの一致と関数全体の近似は別の要件です。',[p('n','Polynomial degree','多項式の次数',2,16,1,10),p('cheb','Equally spaced (0) / Chebyshev (1)','等間隔 (0) ／チェビシェフ (1)',0,1,1,0)])

# Expansion topics: compact, source-backed labs designed for the shared 2D renderer.
def add_expansion(slug,en,ja,desc,jdesc,group,pre,jpre,source,url,labs):
 t=topic(slug,en,ja,desc,jdesc,group,pre,jpre,source,url)
 for x in labs: lab(t,*x)
 return t

def L(i,en,ja,body,jbody,formula,ex,jex,ca,jca,q,jq,a,ja_,params):
 return (i,en,ja,body,jbody,formula,ex,jex,ca,jca,q,jq,a,ja_,params)

add_expansion('number-theory','Number theory: patterns in the integers','数論：整数のパターン','Congruences, primes, and public-key ideas.','合同式・素数・公開鍵の考え方を探ります。','foundations','Algebra and proof','代数と証明','MIT OpenCourseWare · Number Theory','https://ocw.mit.edu/courses/18-781-theory-of-numbers-spring-2012/',[
L('modular','1. Modular clocks','1. 合同式の時計','Move around a clock and compare repeated addition with multiplication modulo n.','時計の上を動き、nを法とする加法と乗法を比較します。',r'a\equiv b\pmod n\iff n\mid(a-b)','For n=12, 17 and 5 occupy the same residue class.','n=12では17と5は同じ剰余類です。','A congruence is an equivalence relation, not ordinary equality.','合同は通常の等号ではなく同値関係です。','Why does multiplication preserve congruence?','乗法が合同を保つのはなぜですか？','Because n dividing a-b also divides ca-cb.','nがa-bを割れば、ca-cbも割るためです。',[p('n','Modulus n','法 n',3,20,1,12),p('a','First integer','整数1',0,40,1,17),p('b','Second integer','整数2',0,40,1,5)]),
L('sieve','2. Sieve of Eratosthenes','2. エラトステネスの篩','Watch composite numbers fade as prime factors are crossed out.','素因数で合成数を消していく様子を見ます。',r'\pi(x)=\#\{p\le x:p\text{ prime}\}','At x=30 there are ten primes.','x=30以下には素数が10個あります。','The prime-counting function is not exactly x/log x at small x.','素数計数関数は小さいxではx/log xと一致しません。','Why can we stop crossing out at sqrt(x)?','√xまでで消去を止められるのはなぜですか？','A composite number has a factor no larger than its square root.','合成数には平方根以下の因子があるためです。',[p('limit','Upper limit','上限',20,120,1,60)]),
L('rsa','3. RSA key intuition','3. RSA鍵の直観','See modular exponentiation turn a message into a reversible residue when the keys are chosen from coprime factors.','互いに素な因子から鍵を選び、合同べき乗でメッセージを可逆な剰余に変換します。',r'c\equiv m^e\pmod N,\qquad m\equiv c^d\pmod N','For p=5, q=11, N=55 and e=3, the inverse d satisfies ed≡1 mod 40.','p=5,q=11ならN=55、e=3に対しed≡1 (mod 40)を満たすdを選びます。','Toy keys are not secure; real RSA uses much larger primes and padding.','小さな例は安全ではありません。実際のRSAは巨大な素数とパディングを使います。','What makes the decryption exponent special?','復号指数が特別なのはなぜですか？','It is an inverse of e modulo φ(N), under the coprime conditions.','互いに素の条件のもとでφ(N)を法とするeの逆元だからです。',[p('p','Prime p','素数 p',3,13,1,5),p('q','Prime q','素数 q',5,17,1,11),p('m','Message m','メッセージ m',2,40,1,7)])])

add_expansion('graph-theory','Graph theory: routes, trees, and networks','グラフ理論：経路・木・ネットワーク','Shortest paths, spanning trees, and centrality.','最短経路・全域木・中心性を可視化します。','foundations','Sets and elementary algorithms','集合と初歩的なアルゴリズム','Diestel · Graph Theory','https://diestel-graph-theory.com/',[
L('shortest','1. Shortest paths','1. 最短経路','Adjust edge weights and watch Dijkstra’s frontier expand from the source.','辺の重みを変え、始点からダイクストラ法の前線が広がる様子を見ます。',r'd(v)=\min_{(u,v)\in E}\{d(u)+w(u,v)\}','With nonnegative weights, the settled label is final.','非負の重みなら確定したラベルは最終値です。','Dijkstra fails with negative edge weights.','負の辺重みではダイクストラ法は使えません。','Why does the frontier stay optimal?','前線が最適であり続けるのはなぜですか？','Every alternative path must pass through a node with a no-smaller settled distance.','別経路は必ず、確定距離以上のノードを通るためです。',[p('shortcut','Diagonal shortcut','斜めの近道',0,1,1,1),p('traffic','Traffic weight','混雑重み',1,4,1,2)]),
L('spanning','2. Minimum spanning trees','2. 最小全域木','Compare a greedy tree with every network edge and reveal the cut property.','貪欲に選んだ木と全辺を比較し、カット性質を見ます。',r'|T|=|V|-1,\qquad w(T)=\min_{\text{spanning }S}w(S)','A tree on six vertices has five edges.','6頂点の木は5本の辺を持ちます。','A spanning tree connects all vertices without cycles; it need not preserve shortest routes.','全域木は全頂点を閉路なく結びますが、最短経路を保つとは限りません。','Why does the lightest crossing edge belong to some MST?','最軽量の横断辺がある最小木に属するのはなぜですか？','Exchange it with a heavier edge on the corresponding tree path.','木の経路上の重い辺と交換できるためです。',[p('cut','Cut position','カット位置',1,4,1,2),p('w','Candidate weight','候補の重み',1,9,1,3)]),
L('centrality','3. Centrality and influence','3. 中心性と影響力','Compare degree, closeness, and betweenness on a small network.','小さなネットワークで次数・近接・媒介中心性を比較します。',r'C_B(v)=\sum_{s\ne v\ne t}\frac{\sigma_{st}(v)}{\sigma_{st}}','A bridge node can have modest degree but high betweenness.','橋の頂点は次数が小さくても媒介中心性が高くなり得ます。','Centrality is a model choice, not a universal ranking.','中心性はモデルの選択であり、普遍的な順位ではありません。','Which measure rewards many direct neighbours?','多くの直接の隣人を評価する指標は？','Degree centrality counts immediate neighbours.','次数中心性は直接の隣人を数えます。',[p('hub','Hub strength','ハブの強さ',0,4,1,2),p('bridge','Bridge strength','橋の強さ',0,4,1,3)])])

add_expansion('partial-differential-equations','Partial differential equations: fields in motion','偏微分方程式：動く場','Heat, waves, and potential fields on a grid.','格子上の熱・波・ポテンシャル場を調べます。','analysis','Calculus and vectors','微積分とベクトル','MIT OpenCourseWare · Partial Differential Equations','https://ocw.mit.edu/courses/18-155-differential-analysis-fall-2013/',[
L('heat','1. Heat diffusion','1. 熱拡散','Scrub time as a hot spot spreads and smooths across a one-dimensional rod.','熱い点が棒の上で広がり滑らかになる様子を時間で追います。',r'\partial_tu=\kappa\partial_{xx}u','Diffusion reduces sharp gradients while conserving total heat under insulated boundaries.','断熱境界では拡散が急な勾配を減らし、総熱量を保ちます。','The finite difference step must obey a stability bound.','差分法の刻みは安定性の上限を守る必要があります。','Why does the peak fall?','ピークが下がるのはなぜですか？','Heat flows down the gradient into neighbouring cells.','熱は勾配を下る方向へ隣接セルに流れるためです。',[p('time','Time','時間',0,40,1,12),p('kappa','Diffusivity','拡散係数',.05,.5,.05,.2)]),
L('wave','2. Wave equation','2. 波動方程式','Change tension and watch a pulse reflect from fixed ends.','張力を変え、固定端でパルスが反射する様子を見ます。',r'\partial_{tt}u=c^2\partial_{xx}u','A fixed end reverses the sign of the reflected displacement.','固定端では反射変位の符号が反転します。','The string model ignores damping and transverse nonlinearities.','弦モデルは減衰と横方向の非線形性を無視します。','What controls wave speed?','波の速さを決めるものは？','The parameter c, set by tension and linear density.','張力と線密度で決まるパラメータcです。',[p('time','Time','時間',0,30,1,8),p('c','Wave speed','波速',.5,2,.1,1)]),
L('laplace','3. Potential fields','3. ポテンシャル場','Move two charged boundaries and inspect equipotential contours and field lines.','2つの帯電境界を動かし、等電位線と電場線を調べます。',r'\nabla^2V=0,\qquad \mathbf E=-\nabla V','Field lines cross equipotentials at right angles.','電場線は等電位線と直交します。','The plotted solution is a teaching model on a finite rectangular domain.','表示は有限の長方形領域上の教育用モデルです。','Where is the field strongest?','電場が最も強いのはどこですか？','Where equipotentials are packed most closely.','等電位線が最も密な場所です。',[p('left','Left potential','左の電位',-1,1,.1,-1),p('right','Right potential','右の電位',-1,1,.1,1)])])

add_expansion('information-theory','Information theory: uncertainty and codes','情報理論：不確実性と符号','Entropy, noisy channels, and information distance.','エントロピー・雑音のある通信路・情報距離を探ります。','applications','Probability and logarithms','確率と対数','Cover and Thomas · Elements of Information Theory','https://web.stanford.edu/~montanar/TEACHING/Stat316/Cover_Thomas.pdf',[
L('entropy','1. Entropy','1. エントロピー','Tune a binary source and see uncertainty peak at a fair coin.','二値情報源を動かし、公平なコインで不確実性が最大になることを見ます。',r'H(X)=-\sum_xp(x)\log_2p(x)','A fair binary source carries one bit per symbol.','公平な二値情報源は1記号あたり1ビットです。','Entropy measures uncertainty in a distribution, not the meaning of a message.','エントロピーはメッセージの意味ではなく分布の不確実性を測ります。','When is binary entropy maximal?','二値エントロピーが最大になるのは？','At p=1/2.','p=1/2のときです。',[p('p','Probability of one','1の確率',.01,.99,.01,.5)]),
L('channel','2. A noisy channel','2. 雑音のある通信路','Increase bit-flip noise and compare input and output uncertainty.','ビット反転雑音を増やし、入力と出力の不確実性を比較します。',r'I(X;Y)=H(Y)-H(Y\mid X)','A noiseless binary channel has one bit of capacity.','雑音のない二値通信路の容量は1ビットです。','Capacity is an asymptotic coding limit, not the success rate of one short message.','容量は漸近的な符号化限界で、短い一通の成功率ではありません。','What happens at a flip probability of one half?','反転確率が1/2だとどうなりますか？','The output is independent of the input and mutual information is zero.','出力は入力から独立し、相互情報量は0です。',[p('noise','Flip probability','反転確率',0,.5,.01,.1)]),
L('kl','3. Divergence','3. ダイバージェンス','Compare a model distribution with observations using Kullback–Leibler divergence.','モデル分布と観測分布をカルバック・ライブラー・ダイバージェンスで比較します。',r'D_{\mathrm{KL}}(P\|Q)=\sum_xP(x)\log\frac{P(x)}{Q(x)}','D_KL is zero only when the two distributions agree.','2つの分布が一致するときだけD_KLは0です。','It is not symmetric and is not a metric.','対称ではなく、距離関数でもありません。','Why can a tiny Q(x) be costly?','Q(x)が小さいとコストが大きいのはなぜですか？','Underestimating an event that occurs makes log(P/Q) large.','起こる事象を過小評価するとlog(P/Q)が大きくなるためです。',[p('p','Observed probability','観測確率',.05,.95,.05,.7),p('q','Model probability','モデル確率',.05,.95,.05,.5)])])

add_expansion('calculus-of-variations','Calculus of variations: paths and principles','変分法：経路と原理','Extremal paths, action, and geodesics.','極値経路・作用・測地線を可視化します。','geometry','Calculus and mechanics','微積分と力学','University of Cambridge · Calculus of Variations','https://www.damtp.cam.ac.uk/user/tong/variational.html',[
L('euler-lagrange','1. Euler–Lagrange','1. オイラー・ラグランジュ方程式','Vary a trial path and compare its action with the stationary path.','試行経路を変え、作用を停留させる経路と比較します。',r'\frac{d}{dt}\frac{\partial L}{\partial\dot q}-\frac{\partial L}{\partial q}=0','For L=½m q̇²−V(q), the equation is Newton’s law.','L=½m q̇²−V(q)なら方程式はニュートンの法則です。','Stationary does not always mean a global minimum.','停留は必ずしも大域的最小を意味しません。','What is being varied?','何を変分するのですか？','The whole path q(t), while endpoints are held fixed.','端点を固定したまま経路q(t)全体を変えます。',[p('bend','Trial bend','試行経路の曲がり',-1,1,.05,.3)]),
L('geodesic','2. Geodesics on a surface','2. 曲面上の測地線','Flatten a curved metric and compare coordinate lines with shortest paths.','曲がった計量を展開し、座標線と最短経路を比較します。',r'\delta\int ds=0,\qquad ds^2=g_{ij}dx^idx^j','Great circles are geodesics on a sphere.','球面上の大円は測地線です。','A coordinate straight line need not be geometrically straight.','座標上の直線が幾何学的に直線とは限りません。','Why do geodesics look curved in a map?','地図上で測地線が曲がって見えるのはなぜですか？','Projection distorts distances and angles.','投影が距離と角度を歪めるためです。',[p('latitude','Latitude','緯度',-80,80,5,30),p('arc','Arc length','弧長',.2,1.5,.05,1)]),
L('least-action','3. Least action','3. 最小作用の原理','Compare paths with the same endpoints and watch the classical path emerge as the stationary one.','同じ端点を持つ経路を比較し、古典経路が停留経路になることを見ます。',r'S[q]=\int_{t_0}^{t_1}L(q,\dot q,t)\,dt,\qquad\delta S=0','The classical path is a stationary-phase path in the semiclassical picture.','半古典的な描像では古典経路は位相が停留する経路です。','The phrase least action is shorthand; the action is stationary, not always least.','「最小作用」は略称で、作用は必ずしも最小ではなく停留します。','What stays fixed in the variation?','変分で固定するものは？','The endpoints and the time interval.','端点と時間区間です。',[p('amplitude','Path amplitude','経路振幅',0,1,.05,.35)])])

add_expansion('classical-mechanics','Classical mechanics: motion and forces','古典力学：運動と力','Projectiles, oscillators, and orbital motion.','投射・振動子・軌道運動を調べます。','physics','Vectors and calculus','ベクトルと微積分','OpenStax · University Physics, Volume 1','https://openstax.org/details/books/university-physics-volume-1',[
L('projectile','1. Projectile motion','1. 放物運動','Change launch angle and inspect the trajectory, range, and conserved horizontal velocity.','発射角を変え、軌道・飛距離・水平速度を調べます。',r'\mathbf r(t)=\mathbf r_0+\mathbf v_0t+\tfrac12\mathbf gt^2','At 45° without drag, range is maximal for fixed speed.','空気抵抗なしで速さ一定なら45°で飛距離が最大です。','The model neglects air resistance and Earth curvature.','モデルは空気抵抗と地球の曲率を無視します。','What remains constant?','何が一定ですか？','Horizontal velocity, while vertical velocity changes by gravity.','水平速度は一定で、鉛直速度は重力で変化します。',[p('angle','Launch angle (degrees)','発射角（度）',10,80,1,45),p('speed','Launch speed','初速',5,30,1,18)]),
L('oscillator','2. Harmonic oscillator','2. 調和振動子','Tune damping and stiffness to move between underdamped, critical, and overdamped motion.','減衰とばね定数を変え、減衰不足・臨界・過減衰を比べます。',r'm\ddot x+c\dot x+kx=0','Critical damping returns fastest without overshoot.','臨界減衰は行き過ぎなく最速で戻ります。','The spring is linear and the mass is point-like.','ばねは線形で、質点モデルです。','What sets the regime?','状態を決めるものは？','The discriminant c²−4mk.','判別式c²−4mkです。',[p('damping','Damping c','減衰 c',0,8,.1,1),p('stiffness','Stiffness k','剛性 k',1,9,.5,4)]),
L('mechanics-orbit','3. Orbital motion','3. 軌道運動','Change tangential speed and see circular, elliptical, or escaping paths in a teaching model.','接線速度を変え、円・楕円・脱出軌道を教育用モデルで見ます。',r'\ddot{\mathbf r}=-\mu\frac{\mathbf r}{\|\mathbf r\|^3}','At circular speed, radius and speed remain constant.','円軌道速度では半径と速さが一定です。','The two-body model omits perturbations and relativistic corrections.','二体モデルは摂動と相対論的補正を無視します。','What is conserved?','何が保存されますか？','In the ideal model, energy and angular momentum.','理想モデルではエネルギーと角運動量です。',[p('speed','Tangential speed','接線速度',.5,2,.05,1),p('mu','Gravity scale','重力尺度',.5,2,.05,1)])])

add_expansion('electromagnetism','Electromagnetism: fields and induction','電磁気学：場と誘導','Electric fields, magnetic forces, and changing flux.','電場・磁力・変化する磁束を可視化します。','physics','Vectors and calculus','ベクトルと微積分','MIT OpenCourseWare · Electricity and Magnetism','https://ocw.mit.edu/courses/8-02-physics-ii-electricity-and-magnetism-spring-2013/',[
L('electric-field','1. Electric field lines','1. 電場線','Move two charges and inspect the vector field and equipotential contours.','2つの電荷を動かし、ベクトル場と等電位線を調べます。',r'\mathbf E=\frac1{4\pi\varepsilon_0}\sum_iq_i\frac{\mathbf r-\mathbf r_i}{\|\mathbf r-\mathbf r_i\|^3}','Field lines leave positive charges and enter negative charges.','電場線は正電荷から出て負電荷に入ります。','The point-charge field diverges at the charge location.','点電荷の場は電荷位置で発散します。','How is direction encoded?','方向はどのように表されますか？','By arrows aligned with the local electric field vector.','局所電場ベクトルに沿う矢印です。',[p('q1','Charge 1','電荷1',-2,2,.1,1),p('q2','Charge 2','電荷2',-2,2,.1,-1)]),
L('lorentz','2. Lorentz force','2. ローレンツ力','Change velocity and magnetic field to see circular or helical motion.','速度と磁場を変え、円運動やらせん運動を見ます。',r'\mathbf F=q(\mathbf E+\mathbf v\times\mathbf B)','A velocity perpendicular to B bends continuously; parallel velocity is unchanged.','Bに垂直な速度は曲がり続け、平行成分は変わりません。','The nonrelativistic model assumes speeds well below c.','非相対論モデルで、速さは光速より十分小さいとします。','Which component does magnetic force not change?','磁力が変えない成分は？','The component of velocity parallel to the magnetic field.','磁場に平行な速度成分です。',[p('b','Magnetic field','磁場',.2,2,.1,1),p('vz','Parallel velocity','平行速度',-1,1,.1,.3)]),
L('induction','3. Faraday induction','3. ファラデー誘導','Sweep a magnet through a loop and track flux, induced emf, and current direction.','磁石をコイルの中で動かし、磁束・起電力・電流方向を追います。',r'\mathcal E=-\frac{d\Phi_B}{dt}','Faster flux change produces larger induced emf.','磁束の変化が速いほど起電力は大きくなります。','The loop is idealized with constant resistance and no self-inductance.','コイルは抵抗一定で自己インダクタンスなしと理想化します。','Why is there a minus sign?','マイナス符号はなぜですか？','Lenz’s law: the induced effect opposes the flux change.','レンツの法則で、誘導効果は磁束変化に逆らいます。',[p('position','Magnet position','磁石の位置',-2,2,.1,0),p('speed','Sweep speed','移動速度',.2,2,.1,1)])])

add_expansion('optics','Optics: rays, waves, and colour','光学：光線・波・色','Lenses, interference, and polarization.','レンズ・干渉・偏光を調べます。','physics','Waves and geometry','波と幾何','OpenStax · University Physics, Volume 3','https://openstax.org/details/books/university-physics-volume-3',[
L('lens','1. Thin lens','1. 薄レンズ','Move the object and watch the image switch from real to virtual.','物体を動かし、実像と虚像の切り替わりを見ます。',r'\frac1f=\frac1{d_o}+\frac1{d_i},\qquad m=-\frac{d_i}{d_o}','An object beyond 2f produces an inverted reduced image.','物体が2fより遠いと倒立した縮小像になります。','The thin-lens model ignores thickness and aberration.','薄レンズモデルは厚みと収差を無視します。','What happens at d_o=f?','d_o=fではどうなりますか？','The image distance diverges: rays leave parallel.','像距離が発散し、光線は平行になります。',[p('f','Focal length','焦点距離',1,5,.1,2),p('object','Object distance','物体距離',.5,10,.1,5)]),
L('interference','2. Double-slit interference','2. 二重スリット干渉','Change slit spacing and wavelength to move bright fringes across the screen.','スリット間隔と波長を変え、明線を動かします。',r'd\sin\theta=m\lambda','Bright fringes satisfy a path difference of mλ.','明線では光路差がmλです。','The small-angle screen approximation is used in the plot.','図では小角近似を使います。','What widens the fringe spacing?','縞の間隔を広げるものは？','A longer wavelength or smaller slit separation.','長い波長または小さいスリット間隔です。',[p('wavelength','Wavelength','波長',.4,1,.05,.6),p('spacing','Slit spacing','スリット間隔',.5,3,.1,1)]),
L('polarization','3. Polarization','3. 偏光','Rotate an analyser and compare transmitted intensity with Malus’s law.','検光子を回転し、透過強度をマリュスの法則と比べます。',r'I=I_0\cos^2\theta','Crossed polarisers transmit no ideal light.','直交した偏光子は理想的には光を通しません。','Real filters have finite extinction and wavelength dependence.','実際のフィルターには有限の消光比と波長依存性があります。','Why does intensity depend on angle twice?','強度が角度の二乗に依存するのはなぜですか？','The electric-field amplitude projects once, then intensity squares amplitude.','電場振幅を一度射影し、強度が振幅の二乗になるためです。',[p('angle','Analyser angle (degrees)','検光子角（度）',0,180,1,30),p('i0','Input intensity','入射強度',.2,1,.05,1)])])

add_expansion('thermodynamics','Thermodynamics: energy, work, and entropy','熱力学：エネルギー・仕事・エントロピー','PV paths, reversible limits, and entropy flow.','PV経路・可逆極限・エントロピーの流れを調べます。','physics','Algebra and energy','代数とエネルギー','MIT OpenCourseWare · Thermodynamics','https://ocw.mit.edu/courses/2-05-thermal-fluids-engineering-i-fall-2013/',[
L('pv','1. PV diagrams','1. PV図','Drag a piston path and see work as the signed area under the curve.','ピストン経路を動かし、曲線下の符号付き面積として仕事を見ます。',r'W=\int_{V_1}^{V_2}P\,dV','Expansion at positive pressure does work on the surroundings.','正圧での膨張は外界に仕事をします。','The path matters; work is not a state function.','仕事は状態関数ではなく経路に依存します。','Which quantity is path-dependent here?','ここで経路に依存する量は？','Work and heat, unlike internal energy.','内部エネルギーと違い、仕事と熱です。',[p('pressure','Pressure scale','圧力尺度',1,5,.1,2),p('volume','Final volume','終体積',1,5,.1,3)]),
L('thermo-entropy','2. Entropy and reversibility','2. エントロピーと可逆性','Compare a reversible ramp with an irreversible jump between two temperatures.','2つの温度間で可逆的な変化と不可逆な跳躍を比較します。',r'\Delta S=\int\frac{\delta Q_{\mathrm{rev}}}{T},\qquad\Delta S_{\mathrm{univ}}\ge0','Reversible exchange can approach zero entropy production.','可逆交換ではエントロピー生成を0に近づけられます。','A reversible process is an ideal limit, not a fast practical operation.','可逆過程は理想極限で、速い実用操作ではありません。','What direction is irreversible entropy production?','不可逆なエントロピー生成の向きは？','It is nonnegative for the universe.','宇宙全体では非負です。',[p('hot','Hot temperature','高温',300,800,10,600),p('cold','Cold temperature','低温',200,700,10,300)]),
L('equation-state','3. Equation of state','3. 状態方程式','Change amount, temperature, and volume for an ideal gas and read pressure.','物質量・温度・体積を変え、理想気体の圧力を読みます。',r'PV=nRT','Doubling temperature at fixed n and V doubles pressure.','nとVを固定して温度を2倍にすると圧力も2倍です。','Real gases deviate near phase transitions and high density.','実在気体は相転移や高密度でずれます。','Which variables are intensive?','示強変数はどれですか？','Temperature and pressure; n and V scale with system size.','温度と圧力です。nとVは系の大きさに比例します。',[p('n','Amount n','物質量 n',.5,3,.1,1),p('temperature','Temperature \\(T\\)','温度 \\(T\\)',200,800,10,300),p('volume','Volume V','体積 V',.5,5,.1,2)])])

add_expansion('quantum-mechanics','Quantum mechanics: amplitudes and spin','量子力学：振幅とスピン','Wavefunctions, uncertainty, and a rotatable Bloch sphere.','波動関数・不確定性・回転できるブロッホ球を探ります。','physics','Complex numbers and waves','複素数と波','MIT OpenCourseWare · Quantum Physics II','https://ocw.mit.edu/courses/8-05-quantum-physics-ii-fall-2013/',[
L('wavefunction','1. Wavefunction density','1. 波動関数の密度','Change the wave number and inspect nodes of a particle in a box.','波数を変え、箱の中の粒子の節を調べます。',r'\psi_n(x)=\sqrt{\frac2L}\sin\frac{n\pi x}{L},\qquad\rho=|\psi|^2','The density integrates to one after normalization.','規格化後の密度の積分は1です。','The plotted state is stationary; measurement collapse is not shown.','表示は定常状態で、測定収縮は扱いません。','Where is the particle least likely?','粒子が最も見つかりにくい場所は？','At nodes where the probability density is zero.','確率密度が0の節です。',[p('n','Quantum number n','量子数 n',1,6,1,2)]),
L('uncertainty','2. Uncertainty principle','2. 不確定性原理','Compare narrow and broad Gaussian packets in position and momentum.','位置と運動量で狭い・広いガウス波束を比較します。',r'\Delta x\,\Delta p\ge\frac\hbar2','A narrower packet has a broader momentum distribution.','狭い波束は広い運動量分布を持ちます。','The plotted widths are standard deviations of an ideal Gaussian.','表示する幅は理想ガウスの標準偏差です。','What trade-off is visible?','どんなトレードオフが見えますか？','Localizing x increases spread in p.','xを局在させるとpの広がりが増えます。',[p('width','Position width','位置の幅',.2,2,.05,.7)]),
L('bloch','3. Bloch sphere','3. ブロッホ球','Rotate a qubit state in a small 3D scene; the vector tip records the amplitudes and phase.','小さな3Dシーンで量子ビット状態を回転し、ベクトル先端で振幅と位相を示します。',r'|\psi\rangle=\cos\frac\theta2|0\rangle+e^{i\phi}\sin\frac\theta2|1\rangle','The poles are |0⟩ and |1⟩; the equator contains equal superpositions.','極は|0⟩と|1⟩で、赤道は等重ね合わせです。','The sphere is a state-space representation, not a particle orbit in real space.','球は状態空間の表現で、実空間の粒子軌道ではありません。','What does azimuth encode?','方位角は何を表しますか？','The relative phase between the basis amplitudes.','基底振幅の相対位相です。',[p('theta','Polar angle (degrees)','極角（度）',0,180,1,60),p('phi','Azimuth (degrees)','方位角（度）',-180,180,1,45)])])


add_expansion('complex-analysis','Complex analysis: maps, residues, and harmonic fields','複素解析：写像・留数・調和場','Conformal maps, residues, and harmonic functions.','等角写像・留数・調和関数を探ります。','analysis','Calculus and complex numbers','微積分と複素数','MIT OpenCourseWare · Complex Variables','https://ocw.mit.edu/courses/18-04-complex-variables-fall-2010/',[
L('conformal','1. Conformal maps','1. 等角写像','Transform a grid with z↦z² and see how angles are preserved locally away from critical points.','z↦z²で格子を変換し、臨界点以外で角度が局所的に保たれる様子を見ます。',r'f\text{ conformal where }f\prime(z)\ne0','The derivative multiplies by a local scale and rotation.','導関数は局所的な拡大と回転として働きます。','The map is not angle-preserving at z=0, where the derivative vanishes.','z=0では導関数が0になり、等角性が失われます。','What does the derivative control?','導関数は何を決めますか？','Its magnitude scales lengths and its argument rotates directions.','絶対値が長さを、偏角が方向の回転を決めます。',[p('power','Map power','写像のべき',1,4,1,2),p('angle','Input angle','入力角',0,360,5,45)]),
L('residue','2. Residues around a pole','2. 極のまわりの留数','Drag a contour around a pole and watch the integral jump when the pole enters.','極のまわりの経路を動かし、極が内部に入ると積分が変わる様子を見ます。',r'\oint_\gamma f(z)\,dz=2\pi i\sum\operatorname{Res}(f;z_k)','A contour enclosing one simple pole contributes 2πi times its residue.','単純極を1つ囲む経路は留数の2πi倍を与えます。','The contour must avoid poles and be positively oriented for this sign convention.','この符号規約では経路は極を避け、正の向きとします。','What changes when the pole crosses the contour?','極が経路を横切ると何が変わりますか？','The enclosed residue sum changes discontinuously.','内部の留数の和が不連続に変わります。',[p('radius','Contour radius','経路半径',.3,2,.05,1),p('pole','Pole offset','極のずれ',-.8,.8,.05,.4)]),
L('harmonic','3. Harmonic conjugates','3. 共役調和関数','Compare level curves of a harmonic function and its conjugate; they meet orthogonally.','調和関数と共役関数の等高線を比較し、直交して交わる様子を見ます。',r'f=u+iv\text{ holomorphic}\Longrightarrow\nabla u\perp\nabla v','The real and imaginary parts of z² are x²−y² and 2xy.','z²の実部と虚部はx²−y²と2xyです。','Orthogonality refers to regular level curves, away from critical points.','直交性は臨界点を除く正則な等高線についての性質です。','Why are the families orthogonal?','曲線族が直交するのはなぜですか？','The Cauchy–Riemann equations rotate one gradient into the other.','コーシー・リーマン方程式が一方の勾配を回転させるためです。',[p('phase','Phase angle (degrees)','位相角（度）',0,180,5,30)])])

add_expansion('fluid-dynamics','Fluid dynamics: flow, pressure, and vorticity','流体力学：流れ・圧力・渦度','Streamlines, Bernoulli pressure, and rotating flow.','流線・ベルヌーイ圧力・回転流を可視化します。','physics','Vectors and calculus','ベクトルと微積分','MIT OpenCourseWare · Fluid Dynamics','https://ocw.mit.edu/courses/2-25-advanced-fluid-mechanics-fall-2013/',[
L('streamlines','1. Streamlines','1. 流線','Change the source and sink strengths and inspect the instantaneous velocity field.','湧き出しと吸い込みの強さを変え、瞬間速度場を調べます。',r'\frac{d\mathbf x}{dt}=\mathbf u(\mathbf x,t)','A streamline is tangent to the velocity field at every point.','流線は各点で速度場に接します。','A streamline is not necessarily the path of one marked fluid parcel in unsteady flow.','非定常流では流線は特定の流体粒子の軌跡とは限りません。','What does an arrow encode?','矢印は何を表しますか？','The local velocity direction and relative speed.','局所速度の方向と相対的な速さです。',[p('source','Source strength','湧き出し強度',-2,2,.1,1),p('sink','Sink strength','吸い込み強度',-2,2,.1,-1)]),
L('bernoulli','2. Bernoulli along a streamline','2. 流線に沿うベルヌーイ','Narrow a channel and compare speed, pressure, and elevation along a streamline.','流路を狭め、流線に沿う速さ・圧力・高さを比較します。',r'P+\frac12\rho v^2+\rho gz=\text{constant}','At equal height, faster flow corresponds to lower static pressure.','同じ高さでは速い流れほど静圧が低くなります。','The ideal relation assumes steady, incompressible, inviscid flow along a streamline.','理想式は定常・非圧縮・非粘性の流れを仮定します。','Which term rises in a constriction?','狭窄部で増える項は？','The kinetic term ½ρv² as speed increases.','速さが増えるため運動エネルギー項½ρv²です。',[p('area','Area ratio','面積比',.3,2,.05,.6),p('speed','Inlet speed','入口速度',.5,4,.1,2)]),
L('vorticity','3. Vorticity and circulation','3. 渦度と循環','Rotate a local velocity field and compare vorticity with circulation around a small loop.','局所速度場を回転させ、小さなループの循環と渦度を比較します。',r'\boldsymbol\omega=\nabla\times\mathbf u,\qquad\Gamma=\oint_C\mathbf u\cdot d\mathbf l','Solid-body rotation has uniform vorticity twice the angular speed.','剛体回転の渦度は角速度の2倍で一様です。','A streamline pattern alone does not determine vorticity without velocity magnitudes.','流線の形だけでは速度の大きさがなく、渦度は決まりません。','What does circulation measure?','循環は何を測りますか？','The line integral of velocity around the closed loop.','閉曲線に沿った速度の線積分です。',[p('rotation','Angular speed','角速度',-2,2,.1,1),p('radius','Loop radius','ループ半径',.2,1,.05,.5)])])


add_expansion('statistics-inference','Statistics and inference: signals in data','統計と推測：データの中の信号','Sampling, confidence, and regression.','標本・信頼区間・回帰を探ります。','applications','Probability and algebra','確率と代数','OpenStax · Introductory Statistics','https://openstax.org/details/books/introductory-statistics-2e',[
L('mean','1. Sampling means','1. 標本平均','Draw repeated samples and watch their means cluster around the population mean.','標本を繰り返し取り、平均が母平均のまわりに集まる様子を見ます。',r'\operatorname{SE}(\bar X)=\frac{\sigma}{\sqrt n}','Larger samples reduce the standard error by a square-root law.','標本が大きいほど標準誤差は平方根則で減ります。','A small standard error does not remove bias from a bad sampling frame.','小さい標準誤差でも偏った標本枠のバイアスは消えません。','What changes when n quadruples?','nを4倍にすると何が変わりますか？','The standard error halves.','標準誤差が半分になります。',[p('n','Sample size n','標本サイズ n',4,100,1,25),p('sigma','Population spread','母標準偏差',.5,3,.1,1)]),
L('interval','2. Confidence intervals','2. 信頼区間','Move the confidence level and compare interval width with the standard error.','信頼水準を動かし、区間幅と標準誤差を比較します。',r'\bar x\pm z_{\alpha/2}\frac{\sigma}{\sqrt n}','Higher confidence requires a wider interval under the same data model.','同じデータモデルでは、信頼水準が高いほど区間は広くなります。','A 95% interval is a procedure with long-run coverage, not a 95% probability statement about this fixed parameter.','95%区間は長期的被覆率を持つ手続きで、固定したパラメータの確率文ではありません。','What narrows the interval?','区間を狭めるものは？','More observations or less variability.','観測数の増加または変動の減少です。',[p('n','Sample size n','標本サイズ n',4,100,1,25),p('level','Confidence level','信頼水準',.8,.99,.01,.95)]),
L('regression','3. Least-squares regression','3. 最小二乗回帰','Adjust slope and noise and inspect residuals around a fitted line.','傾きとノイズを変え、回帰直線まわりの残差を調べます。',r'\hat\beta=(X^TX)^{-1}X^Ty','The fitted line minimizes the sum of squared residuals.','回帰直線は残差平方和を最小にします。','Association in a fitted line does not establish causation.','回帰直線の関連だけでは因果は証明されません。','What does a residual measure?','残差は何を測りますか？','Observed response minus fitted response.','観測応答から予測応答を引いたものです。',[p('slope','Slope','傾き',-.5,2,.05,1),p('noise','Noise scale','ノイズ尺度',0,.8,.05,.2)])])

add_expansion('special-relativity','Special relativity: space, time, and light','特殊相対性理論：空間・時間・光','Lorentz diagrams, time dilation, and invariant intervals.','ローレンツ図・時間の遅れ・不変間隔を調べます。','physics','Algebra and geometry','代数と幾何','Einstein Online · Special Relativity','https://www.einstein-online.info/en/spotlight/special-relativity/',[
L('relativity-lorentz','1. Lorentz diagrams','1. ローレンツ図','Change relative speed and see how the coordinate grid tilts while light rays remain at 45°.','相対速度を変え、光線が45°のまま座標格子が傾く様子を見ます。',r'x\prime=\gamma(x-vt),\qquad t\prime=\gamma(t-vx/c^2)','The light cone is invariant under a Lorentz boost.','光円錐はローレンツ変換で不変です。','The diagram uses units with c=1.','図ではc=1の単位を使います。','What stays fixed for all inertial observers?','すべての慣性系で固定されるものは？','The speed of light and the spacetime interval.','光速と時空間隔です。',[p('v','Relative speed / c','相対速度 / c',-.8,.8,.05,.5)]),
L('spacetime','2. Proper time','2. 固有時','Compare a moving clock with the coordinate clock and inspect time dilation.','運動する時計と座標時計を比較し、時間の遅れを見ます。',r'\Delta\tau=\Delta t\sqrt{1-v^2/c^2}=\frac{\Delta t}{\gamma}','A moving clock accumulates less proper time between the same events.','同じ2事象の間で、運動する時計の固有時は短くなります。','The effect is reciprocal between inertial frames; acceleration changes the comparison setup.','慣性系同士では相互的で、加速度が比較設定を変えます。','What happens as v approaches c?','vがcに近づくとどうなりますか？','The proper-time factor approaches zero.','固有時の係数は0に近づきます。',[p('v','Speed / c','速さ / c',0,.99,.01,.6),p('time','Coordinate time','座標時間',1,10,.1,4)]),
L('twin','3. Relativistic momentum','3. 相対論的運動量','Increase speed and compare Newtonian momentum with the relativistic correction.','速さを増やし、ニュートン運動量と相対論的補正を比較します。',r'\mathbf p=\gamma m\mathbf v,\qquad E^2=(pc)^2+(mc^2)^2','At low speed γ≈1; near c the correction dominates.','低速ではγ≈1ですが、c付近で補正が支配的になります。','Mass-energy units and c=1 are used for the plot.','図では質量エネルギー単位とc=1を使います。','Why can a massive object not reach c?','質量を持つ物体がcに達しないのはなぜですか？','γ diverges, requiring unbounded energy.','γが発散し、無限大のエネルギーが必要になるためです。',[p('v','Speed / c','速さ / c',0,.99,.01,.8),p('mass','Rest mass','静止質量',.5,2,.1,1)])])

add_expansion('differential-geometry','Differential geometry: curvature and shape','微分幾何：曲率と形','Metrics, geodesics, and curvature on surfaces.','曲面上の計量・測地線・曲率を探ります。','geometry','Calculus and vectors','微積分とベクトル','MIT OpenCourseWare · Differential Geometry','https://ocw.mit.edu/courses/18-950-differential-geometry-fall-2008/',[
L('curvature','1. Curvature of a curve','1. 曲線の曲率','Change the bend of a planar curve and inspect its signed curvature.','平面曲線の曲がりを変え、符号付き曲率を調べます。',r'\kappa=\frac{|x\prime y\doubleprime-y\prime x\doubleprime|}{(x\prime^2+y\prime^2)^{3/2}}','A circle of radius \\(R\\) has constant curvature \\(1/R\\).','半径\\(R\\)の円は一定の曲率\\(1/R\\)を持ちます。','The visual uses a smooth teaching curve, not a measured path.','図は滑らかな教育用曲線で、実測経路ではありません。','Where is \\(\\kappa\\) largest?','\\(\\kappa\\)が最大なのはどこですか？','Where the tangent direction changes fastest with arc length.','弧長に対して接線方向が最も速く変わる場所です。',[p('bend','Bend amplitude','曲がりの振幅',0,1,.05,.45)]),
L('geodesic-surface','2. Geodesics on a surface','2. 曲面上の測地線','Compare a straight coordinate path with a shortest path drawn across a curved surface.','曲面上で座標線と最短経路を比較します。',r'\nabla_{\dot\gamma}\dot\gamma=0','Geodesics locally minimize distance when no conjugate point intervenes.','共役点が現れない局所範囲では測地線は距離を極小にします。','A map projection can make a geodesic look curved or straight.','地図投影は測地線を曲がって、または直線に見せます。','What does the connection correct?','接続は何を補正しますか？','It subtracts coordinate artefacts from ordinary acceleration.','通常の加速度から座標の見かけの効果を差し引きます。',[p('latitude','Starting latitude','出発緯度',-70,70,5,20),p('arc','Arc fraction','弧の割合',.2,1,.05,.7)]),
L('gaussian','3. Gaussian curvature','3. ガウス曲率','Morph between a bowl and a saddle and compare intrinsic curvature signs.','鉢型と鞍型を変形し、内在的な曲率の符号を比較します。',r'K=\frac{LN-M^2}{EG-F^2}','A sphere has positive Gaussian curvature \\(K>0\\); a saddle has negative curvature \\(K<0\\).','球面のガウス曲率は正\\(K>0\\)、鞍面では負\\(K<0\\)です。','The plotted surfaces are illustrative parameterized patches.','表示する曲面は教育用のパラメータ表示です。','Can bending without stretching change \\(K\\)?','伸縮なしの曲げで\\(K\\)は変わりますか？','For an isometric bend, intrinsic Gaussian curvature is preserved.','等長変形なら内在的なガウス曲率は保たれます。',[p('saddle','Saddle amount','鞍の量',-1,1,.05,.4)])])

add_expansion('statistical-mechanics','Statistical mechanics: microstates and temperature','統計力学：ミクロ状態と温度','Boltzmann weights, partition functions, and random walks.','ボルツマン重み・分配関数・ランダムウォークを探ります。','physics','Probability and energy','確率とエネルギー','OpenStax · University Physics, Volume 2','https://openstax.org/details/books/university-physics-volume-2',[
L('boltzmann','1. Boltzmann weights','1. ボルツマン重み','Raise \\(T\\) and watch high-energy states become more probable.','温度\\(T\\)を上げ、高エネルギー状態の確率が増える様子を見ます。',r'p_i=\frac{e^{-E_i/(k_BT)}}{Z}','The partition function \\(Z\\) normalizes all state weights.','分配関数\\(Z\\)はすべての状態の重みを規格化します。','The two-level model omits interactions and degeneracy.','二準位モデルは相互作用と縮退を無視します。','What happens as \\(T\\) approaches zero?','\\(T\\)が0に近づくとどうなりますか？','The lowest-energy state dominates.','最低エネルギー状態が支配的になります。',[p('temperature','Temperature \\(T\\)','温度 \\(T\\)',.2,5,.1,1),p('gap','Energy gap \\(\\Delta E\\)','エネルギー差 \\(\\Delta E\\)',.2,3,.1,1)]),
L('partition','2. Partition function','2. 分配関数','Compare free-energy changes as the number of accessible states grows.','利用可能な状態数を増やし、自由エネルギーの変化を比べます。',r'Z=\sum_i e^{-E_i/(k_BT)},\qquad F=-k_BT\ln Z','Adding accessible states lowers the free energy at fixed temperature.','固定温度で状態を増やすと自由エネルギーは下がります。','The state list is finite and chosen for visualization.','状態リストは有限で、可視化用に選ばれています。','Why does multiplicity matter?','多重度が重要なのはなぜですか？','More microstates contribute more terms to Z.','より多くのミクロ状態がZに項を加えるためです。',[p('states','Accessible states','利用可能な状態数',2,20,1,8),p('temperature','Temperature \\(T\\)','温度 \\(T\\)',.2,5,.1,1)]),
L('random-walk','3. Random walk and diffusion','3. ランダムウォークと拡散','Increase the number of steps \\(N\\) and inspect the spreading distribution.','歩数\\(N\\)を増やし、分布の広がりを調べます。',r'\langle x^2\rangle=Nt\,\ell^2\quad\text{(one-dimensional scaling)}','The root-mean-square displacement grows like \\(\\sqrt{N}\\).','二乗平均平方根変位は\\(\\sqrt{N}\\)に比例します。','One realization fluctuates around the ensemble scaling law.','1つの実現値は集団のスケーリング則のまわりで揺らぎます。','What grows linearly with \\(N\\)?','\\(N\\)に比例して増えるものは？','The mean-square displacement, not the displacement itself.','変位そのものではなく平均二乗変位です。',[p('steps','Step count \\(N\\)','歩数 \\(N\\)',10,200,1,80),p('bias','Step bias','歩行バイアス',-1,1,.05,0)])])

# Sources are paired with the experiment they support.
extra_sources={
 'cancellation':('David Goldberg · Floating-Point Arithmetic','https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html'),
 'interpolation':('Chebfun · Approximation Theory, §4.7','https://www.chebfun.org/docs/guide/guide04.html'),
 'clt':('Brown University · Probability Distributions','https://seeing-theory.brown.edu/probability-distributions/'),
 'conditional':('Brown University · Seeing Theory','https://seeing-theory.brown.edu/')}
for t in D:
 for l in t['labs']:
  l['source'],l['url']=extra_sources.get(l['id'],(t['source'],t['url']))
(ROOT/'math-labs/content.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
spec=importlib.util.spec_from_file_location('shell',ROOT/'tools/site-shell.py');shell=importlib.util.module_from_spec(spec);spec.loader.exec_module(shell)
for t in D:
 for lang in [0,1]:
  ja=lang==1; prefix='/ja' if ja else '';route=prefix+'/'+t['slug']+'/';alt=('' if ja else '/ja')+'/'+t['slug']+'/'
  esc=html.escape; nav,foot=None,None
  # Shared shell applied separately after generation.
  sections=[]
  for l in t['labs']:
   controls=''.join(f'<label>{esc(a[2 if ja else 1])} <output for="{l["id"]}-{a[0]}">{a[6]}</output><input id="{l["id"]}-{a[0]}" data-key="{a[0]}" type="range" min="{a[3]}" max="{a[4]}" step="{a[5]}" value="{a[6]}"></label>' for a in l['params'])
   sections.append(f'''<section class="experiment" id="{l['id']}" data-lab="{l['id']}"><div class="section-head"><h2>{esc(l['title'][lang])}</h2></div><p>{esc(l['body'][lang])}</p><div class="controls">{controls}</div><div class="plot" role="img" aria-label="{esc(l['title'][lang])}"></div><p class="readout" aria-live="polite"></p><div class="formula" data-tex="{esc(l['formula'],quote=True)}"></div><div class="notes"><p><strong>{'計算例' if ja else 'Worked example'}.</strong> {esc(l['example'][lang])}</p><p><strong>{'注意点' if ja else 'Watch out'}.</strong> {esc(l['caution'][lang])}</p><details><summary>{esc(l['question'][lang])}</summary><p>{esc(l['answer'][lang])}</p></details></div><a class="source" href="{l['url']}">{'参考文献' if ja else 'Reference'}: {esc(l['source'])}</a></section>''')
  links=''.join(f'<a href="#{l["id"]}">{esc(l["title"][lang])}</a>' for l in t['labs'])
  related=''.join(f'<a href="{prefix}/{u["slug"]}/">{esc(u["title"][lang])}</a>' for u in D if u!=t)
  page=f'''<!doctype html><html lang="{'ja' if ja else 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(t['title'][lang])} · Isegoria</title><meta name="description" content="{esc(t['description'][lang])}"><link rel="canonical" href="https://theisegoria.github.io{route}"><link rel="alternate" hreflang="{'en' if ja else 'ja'}" href="https://theisegoria.github.io{alt}"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/isegoria.css?v=20260915"><link rel="stylesheet" href="/analysis-atlas/vendor/katex.min.css"><link rel="stylesheet" href="/math-labs/labs.css"><script defer src="/analysis-atlas/vendor/katex.min.js"></script><script defer src="/math-labs/experience.js?v=20260919b"></script><script defer src="/assets/math-notation.js?v=20260919"></script><script defer src="/math-labs/app.js?v=20260920b"></script></head><body data-topic="{t['slug']}"><main class="math-wrap"><header class="lesson-intro"><p class="eyebrow">ISEGORIA / {'数学百科事典' if ja else 'MATH ENCYCLOPEDIA'}</p><h1>{esc(t['title'][lang])}</h1><p class="deck">{esc(t['description'][lang])}</p><p>{'前提知識' if ja else 'Before you begin'}: {esc(t['prerequisite'][lang])}</p>{'<p class="disclosure">英語原文からのAI翻訳。数式と計算モデルは両言語で共通です。</p>' if ja else ''}<nav class="lesson-nav" aria-label="{'実験' if ja else 'Experiments'}">{links}</nav><p class="method">{'予想してから操作し、計算例と問いで理解を確かめてください。グラフは数式の図示であり、証明ではありません。' if ja else 'Predict, manipulate, then check your reasoning against the example and question. Graphs illustrate the mathematics; they do not replace a proof.'}</p></header>{''.join(sections)}<section class="connections"><h2>{'次に読む' if ja else 'Continue exploring'}</h2><div class="lesson-nav">{related}</div><p><a href="{prefix}/math-encyclopedia/">{'数学百科事典に戻る' if ja else 'Back to the math encyclopedia'}</a></p></section></main><noscript>{'対話実験にはJavaScriptが必要です。本文と計算例はそのまま読めます。' if ja else 'Enable JavaScript for the experiments. Explanations and worked examples remain readable.'}</noscript></body></html>'''
  path=ROOT/route.strip('/')/'index.html';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(page)
print(f'Generated {len(D)*2} pages and {sum(len(t["labs"]) for t in D)} experiments')
