'use strict';
const $=id=>document.getElementById(id);
const fmt=n=>Number.isFinite(n)?(Math.abs(n)>=1e5||Math.abs(n)<1e-4?n.toExponential(6):Number(n.toPrecision(7)).toString()):'Outside numerical range';
function lgamma(z){const c=[676.5203681218851,-1259.1392167224028,771.3234287776531,-176.61502916214059,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-lgamma(1-z);z-=1;let x=.9999999999998099;c.forEach((v,i)=>x+=v/(z+i+1));let t=z+7.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
const gamma=s=>Math.exp(lgamma(s));const beta=(a,b)=>Math.exp(lgamma(a)+lgamma(b)-lgamma(a+b));
function tex(el,value,display=true){katex.render(value,typeof el==='string'?$(el):el,{displayMode:display,throwOnError:true})}
function typeset(el=document.body){renderMathInElement(el,{delimiters:[{left:'$$',right:'$$',display:true},{left:'\\(',right:'\\)',display:false}],throwOnError:true})}
let family='gamma', s=2, a=2, b=3;
function controls(){const params=family==='gamma'?[['s','Shape s',s]]:[['a','Left parameter a',a],['b','Right parameter b',b]];$('parameter-controls').innerHTML=params.map(([id,label,v])=>`<label for="param-${id}"><span class="control-head"><span>${label}</span><output id="value-${id}">${v.toFixed(2)}</output></span><input id="param-${id}" type="range" min="0.25" max="6" step="0.05" value="${v}"></label>`).join('');params.forEach(([id])=>$('param-'+id).addEventListener('input',e=>{const v=+e.target.value;if(id==='s')s=v;if(id==='a')a=v;if(id==='b')b=v;$('value-'+id).value=v.toFixed(2);draw()}));const presets=family==='gamma'?[['Half',.5],['Exponential',1],['Factorial',4]]:[['Uniform',1,1],['Symmetric',3,3],['Endpoint peaks',.5,.5]];$('presets').innerHTML=presets.map(([label],i)=>`<button type="button" data-preset="${i}">${label}</button>`).join('');$('presets').querySelectorAll('button').forEach((btn,i)=>btn.onclick=()=>{if(family==='gamma')s=presets[i][1];else[a,b]=presets[i].slice(1);controls();draw()})}
function draw(){const g=family==='gamma',value=g?gamma(s):beta(a,b);tex('kernel',g?String.raw`\Gamma(s)=\int_0^\infty t^{s-1}e^{-t}\,dt`:String.raw`B(a,b)=\int_0^1 t^{a-1}(1-t)^{b-1}\,dt`);$('area-value').textContent=fmt(value);tex('area-identity',g?`\\Gamma(${s.toFixed(2)})`:`B(${a.toFixed(2)},${b.toFixed(2)})`,false);$('shape-note').textContent=g?(s<1?'The curve rises without bound at zero, but its area stays finite because s > 0.':s===1?'At s = 1 the integrand is e⁻ᵗ. Its total area is 1.':`The integrand peaks at t = s − 1 = ${fmt(s-1)}. For positive integers, Γ(s) = (s − 1)!.`):'Parameter a controls the behavior near 0; b controls it near 1. Swapping a and b reflects the curve and preserves its area.';
const svg=$('area-plot'),W=svg.clientWidth,H=svg.clientHeight,m={l:58,r:16,t:24,b:44},xmax=g?Math.max(8,s+5*Math.sqrt(s)):1,fn=t=>g?Math.exp((s-1)*Math.log(t)-t):Math.exp((a-1)*Math.log(t)+(b-1)*Math.log1p(-t));let data=Array.from({length:701},(_,i)=>{let t=xmax*(.001+.998*i/700);return[t,fn(t)]});let ymax=Math.max(...data.map(d=>d[1]))*1.12;const X=x=>m.l+x/xmax*(W-m.l-m.r),Y=y=>H-m.b-y/ymax*(H-m.t-m.b),base=H-m.b;let line=data.map(([x,y],i)=>`${i?'L':'M'}${X(x).toFixed(2)},${Y(y).toFixed(2)}`).join(' '),area=`${line} L${X(data.at(-1)[0])},${base} L${X(data[0][0])},${base} Z`;let ticks='';for(let i=0;i<=4;i++){let yy=ymax*i/4;ticks+=`<line x1="${m.l}" x2="${W-m.r}" y1="${Y(yy)}" y2="${Y(yy)}" stroke="var(--line)"/><text x="${m.l-9}" y="${Y(yy)+4}" text-anchor="end">${Number(yy.toPrecision(2))}</text>`}for(let i=0;i<=4;i++){let xx=xmax*i/4;ticks+=`<text x="${X(xx)}" y="${base+22}" text-anchor="middle">${Number(xx.toPrecision(2))}</text>`}svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('aria-label',`${g?'Gamma':'Beta'} integrand with full area ${fmt(value)}. Plot excludes the endpoints${g?' and truncates the infinite tail':''}.`);svg.innerHTML=`<title>${g?'Gamma':'Beta'} integrand</title><desc>The shaded finite window illustrates the integral. The full value is calculated independently, including omitted endpoints and any tail.</desc>${ticks}<path d="${area}" fill="${g?'var(--blue)':'var(--purple)'}" opacity="0.13"/><path d="${line}" stroke="${g?'var(--blue)':'var(--purple)'}" fill="none" stroke-width="2.5"/><text x="${m.l}" y="14">integrand</text><text x="${W-m.r}" y="${H-4}" text-anchor="end">t</text>`;$('plot-note').textContent=g?`Plot window: 0.001T ≤ t ≤ 0.999T, T = ${xmax.toFixed(2)}. The displayed full integral includes both omitted ends and the infinite tail. Axes rescale.`:'Plot window: 0.001 ≤ t ≤ 0.999. Endpoint singularities are cropped; the displayed full integral includes them. Axes rescale.'}
['gamma','beta'].forEach(f=>$(f+'-tab').onclick=()=>{family=f;['gamma','beta'].forEach(t=>$(t+'-tab').setAttribute('aria-pressed',t===f));controls();draw()});controls();new ResizeObserver(draw).observe($('area-plot'));draw();

const specs={exp:[['p',4],['c',2],['r',1]],finite:[['a',1.5],['b',2.5],['L',2]],rational:[['p',3],['q',3],['c',1],['r',2]],trig:[['m',4],['n',2]]};
function setupTransform(){const kind=$('integral-family').value;$('integral-params').innerHTML=specs[kind].map(([k,v])=>`<label for="int-${k}">${k}<input type="number" step="0.25" id="int-${k}" value="${v}"></label>`).join('');$('integral-params').querySelectorAll('input').forEach(el=>el.oninput=transform);transform()}
function transform(){const kind=$('integral-family').value;let v={},missing=false;specs[kind].forEach(([k])=>{const el=$('int-'+k);v[k]=el.valueAsNumber;if(!Number.isFinite(v[k]))missing=true});let eq='',sub='',match='',reason='',value=NaN,valid=true;
if(missing){$('convergence').textContent='Enter a finite number in every field.';$('convergence').classList.add('invalid');['input-equation','substitution','matched-equation','calculated','transform-explanation'].forEach(id=>$(id).textContent='');return}
const {p,q,c,r,L,a,b,m,n}=v;
if(kind==='exp'){eq=String.raw`\int_0^\infty x^{${p-1}}e^{-${c}x^{${r}}}\,dx`;sub=String.raw`t=${c}x^{${r}},\qquad x^{p-1}dx=\frac{t^{p/r-1}}{r c^{p/r}}dt`;valid=p>0&&c>0&&r>0;reason=c<=0||r<=0?'Outside this template: c and r must be positive.':p<=0?'Diverges at zero: the power p − 1 must exceed −1.':'Converges: p > 0, c > 0, r > 0.';match=String.raw`\frac{\Gamma(p/r)}{r c^{p/r}}=\frac{\Gamma(${fmt(p/r)})}{${r}\cdot ${c}^{${fmt(p/r)}}}`;if(valid)value=Math.exp(lgamma(p/r)-Math.log(r)-p/r*Math.log(c));$('transform-explanation').textContent='The new Gamma argument is p/r. The exponential takes care of infinity; the power at zero supplies the restriction.'}
if(kind==='finite'){eq=String.raw`\int_0^{${L}}x^{${a-1}}(${L}-x)^{${b-1}}\,dx`;sub=String.raw`x=${L}t,\qquad dx=${L}\,dt`;valid=a>0&&b>0&&L>0;reason=L<=0?'Outside this template: L must be positive.':!valid?'Diverges at an endpoint: a and b must both be positive.':'Converges: a > 0, b > 0, L > 0.';match=String.raw`L^{a+b-1}B(a,b)=${L}^{${fmt(a+b-1)}}B(${a},${b})`;if(valid)value=Math.exp((a+b-1)*Math.log(L)+lgamma(a)+lgamma(b)-lgamma(a+b));$('transform-explanation').textContent='The two endpoint factors contribute Lᵃ⁻¹ and Lᵇ⁻¹; dx contributes one more L.'}
if(kind==='rational'){eq=String.raw`\int_0^\infty\frac{x^{${p-1}}}{(1+${c}x^{${r}})^{${q}}}\,dx`;sub=String.raw`t=${c}x^{${r}}`;valid=c>0&&r>0&&p>0&&p<r*q;reason=c<=0||r<=0?'Outside this template: c and r must be positive.':p<=0?'Diverges at zero: p must be positive.':p>=r*q?'Diverges at infinity: p must be smaller than r × q.':`Converges: 0 < p < rq (${fmt(r*q)}).`;match=String.raw`\frac{B(p/r,q-p/r)}{r c^{p/r}}=\frac{B(${fmt(p/r)},${fmt(q-p/r)})}{${r}\cdot${c}^{${fmt(p/r)}}}`;if(valid)value=Math.exp(lgamma(p/r)+lgamma(q-p/r)-lgamma(q)-Math.log(r)-p/r*Math.log(c));$('transform-explanation').textContent='The Beta arguments must add up to the denominator power q. At infinity, the original power is p − 1 − rq.'}
if(kind==='trig'){eq=String.raw`\int_0^{\pi/2}\sin^{${m}}\theta\cos^{${n}}\theta\,d\theta`;sub=String.raw`t=\sin^2\theta,\qquad d\theta=\frac{dt}{2\sqrt{t(1-t)}}`;valid=m>-1&&n>-1;reason=valid?'Converges: m > −1 and n > −1.':'Diverges at an endpoint: both m and n must exceed −1.';match=String.raw`\frac12 B\!\left(\frac{m+1}2,\frac{n+1}2\right)=\frac12 B(${fmt((m+1)/2)},${fmt((n+1)/2)})`;if(valid)value=.5*beta((m+1)/2,(n+1)/2);$('transform-explanation').textContent='The differential contributes a factor 1/2 and subtracts 1/2 from each transformed exponent.'}
tex('input-equation',eq);tex('substitution',sub);$('convergence').textContent=reason;$('convergence').classList.toggle('invalid',!valid);$('match-title').textContent=valid?'The match':'Check the domain first';if(valid){tex('matched-equation',match);$('calculated').textContent=Number.isFinite(value)&&value>0?'≈ '+fmt(value):'Outside the numerical range';}else{$('matched-equation').textContent='The Gamma/Beta evaluation is not valid for these parameters.';$('calculated').textContent=''}
}
$('integral-family').onchange=setupTransform;setupTransform();
let selectedExample=0,selectedStep=0;
$('example-list').innerHTML=EXAMPLES.map((e,i)=>`<button type="button" data-example="${i}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')} · ${e.title}</button>`).join('');
function showExample(){const e=EXAMPLES[selectedExample],step=e.steps[selectedStep];$('example-tag').textContent=e.tag;tex('example-integral',e.integral);$('example-condition').textContent=e.condition;$('step-title').textContent=step[0];tex('step-equation',step[1]);$('step-text').textContent=step[2];$('step-counter').textContent=`Step ${selectedStep+1} of ${e.steps.length}`;$('previous-step').disabled=selectedStep===0;$('next-step').disabled=selectedStep===e.steps.length-1;$('example-list').querySelectorAll('button').forEach((btn,i)=>btn.setAttribute('aria-pressed',i===selectedExample))}
$('example-list').querySelectorAll('button').forEach((btn,i)=>btn.onclick=()=>{selectedExample=i;selectedStep=0;showExample()});$('previous-step').onclick=()=>{if(selectedStep>0)selectedStep--;showExample()};$('next-step').onclick=()=>{if(selectedStep<EXAMPLES[selectedExample].steps.length-1)selectedStep++;showExample()};showExample();
$('practice-items').innerHTML=PRACTICE.map(([problem,hint,answer],i)=>`<div><h3>${String(i+1).padStart(2,'0')}</h3><div class="equation" data-practice-problem="${i}"></div><details><summary>Hint</summary><div class="equation" data-practice-hint="${i}"></div></details><details><summary>Solution</summary><div class="equation" data-practice-answer="${i}"></div></details></div>`).join('');PRACTICE.forEach(([p,h,a],i)=>{tex(document.querySelector(`[data-practice-problem="${i}"]`),p);tex(document.querySelector(`[data-practice-hint="${i}"]`),h,false);tex(document.querySelector(`[data-practice-answer="${i}"]`),a)});typeset();
